### ISSUE TITLE
[Remoto] Dev Mobile Pleno | Abacomm

### ISSUE THREAD

**Issue by DougFischer** [CocoaHeadsBrasil/vagas#1]
## Descrição da vaga

Vaga para compor a equipe de Mobile (iOS e Android) da Abacomm, em projetos de diversas naturezas, porém normalmente mais voltado ao mercado Corporativo (em especial empresas de Telecom e Saúde). 

Não existe um nível técnico totalmente definido para essa vaga, procuramos pessoas interessadas em crescer, que sejam capazes de tocar ao menos projetos menores por conta própria.

## Local

Na Abacomm incentivamos o trabalho remoto. Você pode atuar de qualquer lugar do planeta. Se você realmente prefere trabalhar no escritório, nossa sede é no Rio de Janeiro, na Barra. 

## Benefícios

- Vale refeição/alimentação.
- Plano de saúde.
- Horário flexível.

## Requisitos

Obrigatórios
- Ao menos 1 ano de experiência com Android (preferencialmente profissional).
- Ao menos 1 ano de experiência com iOS (pelo menos como hobby).
- Confortável com os principais padrões de desenvolvimento de software (Ex: MVC).
- Noções básicas de Scrum.
- GIT.

Desejáveis
- Objective-C.
- Experiência anterior com trabalho remoto.
- Testes unitários.
- Testes de interface, automatizados.
- Integração Contínua. 

## Contratação

Muito preferencialmente CLT. Outros modelos a negociar.

## Nossa empresa

A Abacomm é uma empresa focada em desenvolvimento mobile para o mercado corporativo, em especial Telecom e Saúde, com mais de 12 anos de atuação. Nossa equipe de desenvolvimento é 100% remota e por aqui você vai poder trabalhar em apps usados por algumas das principais empresas do Brasil. Não deixe de conhecer nosso site: www.abacomm.com.br

## Como se candidatar

Email para contato@abacomm.com.br com CV, github, portfólio e pretensão salarial. Colocar no assunto: Vaga Mobile Github.

**Comment by DougFischer** [comment]
Fechando a vaga pois a posição atual já foi preenchida, porém uma vaga com perfil similar será aberta nos próximos meses. Interessados podem continuar enviando CV's para um banco de talentos, porém sem compromisso imediato. Obrigado as mais de 50 pessoas que se candidataram.

**Comment by marcelofabri** [comment]
@DougFischer por curiosidade: esse número é de pessoas que chegaram através daqui ou no total?
