### ISSUE TITLE
[São Paulo - Pinheiros] Zazcar - Desenvolvedor iOS Sênior

### ISSUE THREAD

**Issue by viniciusalbino** [CocoaHeadsBrasil/vagas#10]
## Descrição da vaga

Estamos buscando um(a) desenvolvedor(a) iOS experiente para participar do projeto de uma solução inovadora de mobilidade urbana que irá transformar o modelo de negócio da Zazcar e envolve integração com HW embarcado em nossos carros.

## Local

R. Cônego Eugênio Leite, 623, Pinheiros - São Paulo, SP

## Benefícios

 Vale refeição
 Plano de saúde
 Ótimo ambiente de trabalho
 Uso de Zazcar
 Projeto desafiador

## Requisitos

Obrigatórios
- Experiência com Swift
- Controle de versão distribuído (git e/ou hg)
- Cocoapods para gerenciamento de dependências do projeto
- Sólido conhecimento em Objc, orientação a objeto e design patterns
- Integração com APIs RESTful e/ou webservices
- Familiaridade com o Xcode
- Familiaridade com componentes de User Interface do iOS
- Familiaridade com storyboards, xibs, autolayout
- Adaptação de layouts entre iPhone/iPad
- Conhecimento das guidelines de design e de desenvolvimento da Apple
- Conhecimento de metodologias ágeis (Scrum e XP)
- Fluência em inglês (leitura técnica)

Desejáveis
- Experiência em programação Ágil
- Ensino superior em áreas correlatas

## Contratação

CLT

### Zazcar
A Zazcar é uma empresa pioneira na exploração da atividade de compartilhamento de veículos (car sharing) no Brasil e estamos num momento de transformação intenso: estamos criando a nossa própria plataforma tecnológica (hardware, Apps e plataforma de gestão). Esse projeto visa habilitar o crescimento de 10x da frota planejado para os próximos 2 anos, com a expansão para as principais cidades do Brasil e Cone Sul.

Mobilidade do futuro será resultado do triunfo do acesso sobre a posse. O desenvolvimento de novas tecnologias, a democratização do acesso à internet e o aumento das velocidades de conexão, permitirão que as pessoas escolham a melhor forma de se locomover de acordo com o local onde estão, o objetivo e o custo. As opções de mobilidade serão feitas à medida da necessidade dos indivíduos, que poderão escolher a partir de um cardápio de opções interconectadas por tecnologias de acesso, banco de dados e sistemas de gestão inteligentes. Nesse cenário, empresas de mobilidade funcionarão como grandes plataformas integradoras, tal qual as operadoras de telefonia móvel de hoje. Elas oferecerão às pessoas mobilidade fácil e conveniente, libertando-as de todas as formas de transporte ineficientes e onerosas.

## Como se candidatar

Por favor envie um email para bernardom@zazcar.com.br com seu CV anexado - enviar no assunto: Vaga iOS

**Comment by barbosa** [comment]
Olá @viniciusalbino, tudo bem?

A vaga ainda está aberta? Só para saber se fechamos a issue ou mantemos aberta.

Obrigado!

**Comment by Viniciuscarvalho** [comment]
Opa @viniciusalbino a vaga ainda está aberta? Se já tiver sido preenchida poderia fechar a issue? 👍

**Comment by bernardonmazzini** [comment]
Caros,

Essa vaga não está mais aberta. 

Muito obrigado.
