### ISSUE TITLE
[Remoto] Arena - Desenvolvedor iOS Senior

### ISSUE THREAD

**Issue by rodrigoreis22** [CocoaHeadsBrasil/vagas#100]
## Empresa
Arena is a platform for sports fans to chat with one another during live events. Working with sports like UFC, Arena gives fans a place to connect that's not as cluttered as Twitter or Facebook, and that's focused just on the live event. Arena boasts some impressive audience numbers, it has more than 700,000 monthly active users and had over 100,000 uniques on a single UFC event. The startup is building widgets to allow websites and blogs to host Arena chats directly on their site. A part of Techstars Chicago 2016 class, we recently raised our seed round from strategic sports investors and we are growing very quickly.
Check out our demo day pitch: https://techstars.wistia.com/medias/j33uigdvk9 

## Descrição da vaga
As our first full-time Mobile iOS Engineer you’ll own and lead all parts of the iOS mobile pipeline. You will get to wear multiple hats as you work on APIs and UI, build systems, architecture and new features.

We believe in a strong, friendly engineering culture. Our team of hackers and thinkers is small, lean, and empathetic. We're looking for self motivated people who are excited about what we're working on and want to be a part of this project.

## Posição
Senior iOS Engineer

## Tipo de contratação
Remote. We're based in Silicon Valley and are building our engineering team in Brazil. You must be ok with occasional travel to San Francisco, all expenses paid.

###### Obrigatórios
5+ years of experience building iOS Apps 
B.S. in Computer Science or equivalent 
Expert at Objective-C, Cocoa, Swift, and iOS SDK 
Experience developing complex, custom iOS apps that talk to a server 
Proven ability to build, launch and iterate on mobile apps 
Eager to work in fast-paced startup environment and a desire to disrupt the sports industry

###### Diferenciais
Previous startup experience
Remote work experience

## Benefícios
Opportunity for stock options
Impact-first work environment (no politics, no pandering, no BS) 
Huge company vision (build the future, not just maintain the status quo) 
Contribute to open source projects

## Como aplicar
Apply through AngelList: https://angel.co/arena-7/jobs/198732-senior-ios-engineer

## Contato
Rodrigo - CTO
rodrigo@arena.im

**Comment by brunogama** [comment]
Essa vaga ainda está aberta?

**Comment by reprotector** [comment]
@rodrigoreis22 A vaga ainda está aberta? Podemos fechar a issue?

**Comment by rodrigoreis22** [comment]
@reprotector podemos fechar a vaga. Obrigado!
