### ISSUE TITLE
[REMOTO] Conductor - Desenvolvedor iOS Sênior e Especialista 

### ISSUE THREAD

**Issue by denisoliveira** [CocoaHeadsBrasil/vagas#1007]
## Empresa
A Conductor é a plataforma líder na América Latina em meios de pagamento e banking as a service. Por meio de nossa infraestrutura de APIs aberta e nativa em nuvem, atendemos às principais fintechs, bancos, varejistas e diferentes empresas do continente, permitindo que ofereçam soluções de pagamento inovadoras a seus clientes finais.

A Conductor atualmente atende mais de 85 milhões de contas e processa mais de R$100 bilhões em volume de pagamentos na América Latina. 

## Descrição da vaga
Você trabalhará no desenvolvimento do App Merci, um produto Whitelabel que forncecemos para diversos clientes nossos, SDK que enbarca diversas funcionalidades de pagamento, disitribuição de bibliotecas com XCFramework e componentes de código aberto com SPM.

## Posição
SÊNIOR E ESPECIALISTA

## Tipo de contratação
100% Remoto fulltime
Contratação CLT

###### Obrigatórios
* Domínio Objective-C / Swift
* Conhecimento em Swift: operadores, optionals, codables, functional operators
* Conhecimento em UIKit e seu padrões como DataSouece, Delegate, ChildView
* Storyboard: push, present, unwind, container view, detach view, storyboard objects
* AutoLayout: Constraints, Stackview
* Notification Center
* GCD
* CocoaPods
* Familiaridade com RESTFul APIs
* Estar atualizado com as novidades da plataforma
* Experiência com o Git
* Facilidade de trabalhar com equipes remotas

###### Desejáveis
* AVFoundation
* CoreImage
* CommonCrypto
* LocalAuthentication
* Alamofire
* SOLID
* Construção de frameworks
* Operação com múltiplos targets
* Test
* UI Test

###### Diferenciais
* Ter trabalhado com projetos whitelabels e modular
* Ter trabalhado com mult-frameworks
* Ter trabalhado com distribuição (CocoaPods, Carthage, SPM, XCFramework, Frameworks)
* Ter contribuido com alguma biblioteca de iOS

## Benefícios
* TotalPass
* Assitência Médica (Bradesco)
* Assistência Odontológica (Odontoprev)
* Vale Refeição/Alimentação (BEN VISA VALE)
* Previdência Privada (Bradesco Previdência)
* Seguro de Vida (Icatu Seguros)
* Parcerias
    * MACKENZIE
        * Pós-graduação
        * Educação Infantil, Ensino Fundamental I, II, Médio e Cursos de Línguas Estrangeiras (este último apenas São Paulo)
    * FIAP
        * Graduação
        * SHIFT
        * MBA
* Gympass
* Clube de Marcas

## Com quem você vai trabalhar
| ![](https://github.com/lgcassab.png?size=117) | ![](https://github.com/denisoliveira.png?size=117) | ![](https://github.com/issuran.png?size=117) |
| --- | --- | --- |
|[lgcassab](https://github.com/lgcassab) |[denisoliveira](https://github.com/denisoliveira) |[issuran](https://github.com/issuran) |

## Como aplicar
Encaminhar e-mail: katteryn.mendonca@conductor.com.br
Assunto: Especialista IOS

**Comment by issuran** [comment]
👍
