### ISSUE TITLE
[São Paulo/SP - Zona Sul] - DogHero - Arquiteto IOS

### ISSUE THREAD

**Issue by gabimollo** [CocoaHeadsBrasil/vagas#101]
**_Recruto para Startup com produto fantástico. São empresa do portfolio da Kaszek,Monashees+  e acabaram de ser selecionados pelo Google para programa global de aceleração._**

**Responsibilities**
Develop and maintain our native mobile apps (IOS)
Consume RESTful APIs to implement new functionalities that enhance the quality of our product
Bring pixel perfect UI/UX into life

**Requirements**
Senior experience coding in relevant startups and/or personal projects
Relevant Startup experience
Advanced knowledge of IOS 

**Local de trabalho:**
Vila Mariana

**Contratação:**
CLT Full

**Benefícios:**
Salário competitivo
Oportunidade de ganhar Stock Options
Assistência médica
Gym Pass
Bonus para upgrade deconfiguração de notebook
Cozinha com chefe de cozinha
Ambiente fun

Interessados enviar cv para `gaby_mollo@hotmail.com`

**Comment by reprotector** [comment]
@gabimollo Essa vaga já existe https://github.com/CocoaHeadsBrasil/vagas/issues/91, favor não duplicar as vagas pois gera confusão
