### ISSUE TITLE
[Rio de Janeiro] Mongeral Aegon - Desenvolvedor iOS

### ISSUE THREAD

**Issue by raphamzn** [CocoaHeadsBrasil/vagas#102]
## Empresa
MONGERAL AEGON
Estamos presentes no futuro das pessoas há quase 200 anos. Somos reconhecidos pelo Governo Federal como pioneiros em previdência no Brasil e, ao longo da nossa história, atuamos sempre focados em soluções em seguros de vida e previdência para três dos riscos sociais aos quais todos estamos expostos:
- Viver por mais tempo do que os recursos financeiros que acumulamos para manter o padrão de vida na aposentadoria.
- Perder temporária ou permanentemente da capacidade de gerar renda (invalidez).
- Morrer prematuramente, deixando dependentes.

## Descrição da vaga
Integrará a equipe de desenvolvimento e manutenção do app iOS no ramo de seguros, consumindo e alimentando dados a partir de uma api REST, utilizando CoreData. 

## Posição
Junior/Pleno/Senior

## Tipo de contratação
CLT

###### Obrigatórios
Experiência de no mínimo 1 ano em desenvolvimento e manutenção de aplicativos mobile nativos iOS (Objective-C / Swift)
SQLite/ Core Data
Experiência no uso de Web Services(REST, JSON).
Storyboard autolayout
Conhecimentos de UX.
Core Animation.
Design Patterns .
Cocoa pods.
Conhecimento em testes integrados.

###### Diferenciais
Experiência com apple watch
Links com código no github e ou apps publicadas
Integração contínua

## Como aplicar
Envie um email para cardoso.rcc@gmail.com, com seu CV anexado - enviar no assunto: Oportunidade iOS Mongeral
Faça o teste descrito no link: https://github.com/MongeralAegonDigital/ios-trabalhe-na-mad

## Contato
cardoso.rcc@gmail.com

**Comment by reprotector** [comment]
@raphamzn Conseguiram fechar a vaga? Posso fechar a issue?
