### ISSUE TITLE
[Remoto ou RJ] Desenvolvedor iOS JR ou PL na Globo.com 

### ISSUE THREAD

**Issue by MarcosiOSdev** [CocoaHeadsBrasil/vagas#1024]
## Empresa

A Globo é o maior grupo de mídia da América Latina. Nossas marcas digitais estão entre as maiores do Brasil, reconhecidas pela qualidade e liderança de audiência em seus segmentos. G1, Globoesporte.com, Gshow, Cartola, Globoplay, Globosatplay, são exemplos de um portfólio diverso presente na vida de milhões de pessoas que buscam informação, diversão e cultura.

Com foco no desenvolvimento de produtos, visando a melhor experiência de consumo, interação e relacionamento com os nossos usuários, contamos com um time de referência no mercado de Tecnologia. Possuímos uma das mais modernas infraestruturas de distribuição de conteúdo do Brasil.

Todas as nossas opiniões, decisões e ações se sustentam em nossos valores. Nossa Essência é composta por: Paixão por Comunicação | Brasilidade | Atitude Otimista | Talento e Liderança | Respeito à Diversidade | Qualidade e Inovação | Estética | Crescer Juntos

Aqui ideias, competência e inovação fazem toda a diferença. Valorizamos a diversidade e o desenvolvimento pessoal e profissional. Junte-se a nós e traga o seu talento!

## Descrição da vaga

Estamos com uma posição de Desenvolvedor iOS para construir features e inovar a plataforma de NativeSDK.
NativeSDK é uma plataforma que provê as principais features para produtos da Globo:
- Feed.
- Conteúdos dos Feeds.
- Menu  
- LGPD.
 
O Desenvolvedor tem a total autonomia no projeto e muito poder de opinião para melhoria do produto. 

Trabalhar aqui é super prazeroso, e o time é sensacional.

O que usamos :
- Cocoapods para fazer nossos modulos (PS: futuramente SPM) 
- Cocoapods para subir nossos modulos , exemplo: `pod 'NativeSDK', '3.3.0'`
- MVVM-C , MVP, VIPER e MVC ( depende do modulo ou submodulo ).
- Swift 5.0
- CI/CD c/ GitLab + Fastlane 
- Git
- Gitflow
- SwiftLint

## Posição
Junior ou Pleno.

## Tipo de contratação
* CLT
* Nós consideramos a possibilidade de trabalhar remotamente.

###### Obrigatórios

- Conhecimento com Swift
- Conhecimento com ViewCode
- Cocoapods
- Git / Gitflow
- CleanCode
- Possuir conhecimentos de integração utilizando API RESTful;
- Ser apaixonado por desenvolvimento e tecnologia;

###### Desejáveis
- Test Unitario
- Experiência com metodologias ágeis, como Kanban Scrum;
- Conhecimento profundo dos SDKs do iOS;
- Fortes habilidades na análise de logs e debug do sistema;
- Conhecimento em desenvolvimento de telas para iOS (ViewCode);
- Conhecimento dos padrões de design e guidelines de interface da Apple;
- Ter experiência com ferramentas como Firebase, Google Analytics, Crashlytics e Fastlane;
- Ter conhecimento de práticas de XP (TDD, pair programming, refactoring, continuous integration, etc);
- Experiência com push notifications / APNS.

###### Diferenciais
- Ter experiencia em trabalho com SDK (podspec)
- Contribuir em projetos open-source;
- Experiência com Objective-C;
- Experiência com ferramentas de CI;

## Outras informações

https://www.linkedin.com/company/rede-globo
https://www.instagram.com/vempraglobo/
https://www.facebook.com/VemPraGlobo/

## Como aplicar

https://talentos.globo.com

**Comment by munizin** [comment]
Haveria um email para que possamos enviar o CV? é que o site https://talentos.globo.com/ está apresentando problemas de DNS

**Comment by MarSYs1** [comment]
O site tem problemas

**Comment by MarSYs1** [comment]
O que posso fazer para mim candidatar ??
