### ISSUE TITLE
[Florianópolis - SC] Involves - Desenvolvedor iOS

### ISSUE THREAD

**Issue by nadocoelho** [CocoaHeadsBrasil/vagas#103]
## Empresa
A Involves foi a vencedora do prêmio Melhores Empresas para Trabalhar 2016 da GPTW
- Melhor empresa de T.I do Brasil (até 99 colaboradores)
- Melhor empresa de SC de todos os ramos de atuação (até 99 colaboradores)

No final de 2016 nos mudamos para uma nova sede e nossa estrutura está incrível!
Estamos com mais de 40 vagas em aberto e sempre buscando gente muito boa para fortalecer nosso time!

![2](https://cloud.githubusercontent.com/assets/17482386/21590112/ef759a44-d0df-11e6-84b0-314ae3cca807.jpg)
![4](https://cloud.githubusercontent.com/assets/17482386/21590109/ef7504d0-d0df-11e6-81d7-3f76754c48a0.jpg)
![5](https://cloud.githubusercontent.com/assets/17482386/21590110/ef757aaa-d0df-11e6-820c-0862e378223d.jpg)
![6](https://cloud.githubusercontent.com/assets/17482386/21590111/ef759918-d0df-11e6-8488-e4cfe5f7099f.jpg)
![7](https://cloud.githubusercontent.com/assets/17482386/21590114/ef9164a4-d0df-11e6-9753-1e65d5af4465.jpg)
![9](https://cloud.githubusercontent.com/assets/17482386/21590117/ef929c48-d0df-11e6-938d-2c9c6e142c44.jpg)
![10](https://cloud.githubusercontent.com/assets/17482386/21590119/ef934c88-d0df-11e6-8ca2-5b86a075eff1.jpg)
![11](https://cloud.githubusercontent.com/assets/17482386/21590118/ef92d3b6-d0df-11e6-93c7-75623fcc1de1.jpg)
![12](https://cloud.githubusercontent.com/assets/17482386/21590116/ef91df42-d0df-11e6-8e23-6d554e168116.jpg)
![15](https://cloud.githubusercontent.com/assets/17482386/21590122/efaef0fa-d0df-11e6-8324-ceb413f239fe.jpg)
![16](https://cloud.githubusercontent.com/assets/17482386/21590123/efaf68c8-d0df-11e6-8194-ba30bc13cfee.jpg)
![17](https://cloud.githubusercontent.com/assets/17482386/21590124/efb4f8b0-d0df-11e6-82da-93f01e15a8be.jpg)

## Descrição da vaga
Conceber e desenvolver aplicações iOS tendo compreensão completa das ferramentas nativas e ser proativo no uso das tendências tecnológicas da plataforma. Além disso, o especialista iOS tem de ter a iniciativa de ser full-stack, trabalhando e contribuindo tanto com especialistas UX e de produto na evolução das funcionalidades, quanto com especialistas back-end na performance e qualidade do sistema em geral.

###### Principais Atividades

- Apoia a melhoria da qualidade do software corrigindo eventuais defeitos que forem identificados
- Projeta e desenvolver novas funcionalidades que agreguem valor e sejam escaláveis
- Garanti a execução do processo de integração contínua dos módulos desenvolvidos
- Implanta e acompanha o comportamento do software em ambiente de produção, garantindo que esteja suportando a carga para a qual foi projetado
- Atualiza os módulos desenvolvidos em produção
- Promove o desenvolvimento profissional dos desenvolvedores nível júnior e pleno buscando sempre a criação de códigos com baixo acoplamento e alta coesão

## Posição
Sênior

## Tipo de contratação
Presencial / CLT

###### Obrigatórios

- Domínio de padrões de projeto
- Conhecimentos avançados em SQLite
- Conhecimentos em ao menos uma arquitetura de projeto (MVVM, VIPER, etc.)
- Domínio de Objective-C e Swift

###### Desejáveis

- Autolayout
- Fastlane
- Realm, NoSQL
- RxSwift
- TDD/BDD
- Git e Github

## Benefícios
- Horário semi-flexível
- Vale Refeição
- Vale Transporte
- PLR (distribuição dos lucros da empresa)
- Involvimento: são atividades pagas pela empresa para aumentar a interação entre os colaboradores. Dentro dos planos nós temos: Academia, Massagem, Yoga, Kart, Paintball, Futebol, Rafting...

## Como aplicar
Interessados devem entrar no link: [http://www.involves.com.br/pt/faca-parte-da-equipe](http://www.involves.com.br/pt/faca-parte-da-equipe), preencher os dados e selecionar a opção "Desejo me candidatar para uma das vagas em aberto". Selecionar a vaga de "DESENVOLVEDOR IOS III" e anexar o currículo.

## Contato
Dúvidas, entrar em contato pelo email: contato@involves.com.br

**Comment by reprotector** [comment]
@nadocoelho Conseguiram fechar a vaga? Posso fechar a issue?

**Comment by nadocoelho** [comment]
Fala @reprotector ainda não fechamos. Favor deixar aberto. Obrigado

**Comment by nadocoelho** [comment]
@reprotector vaga fechada. Pode fechar a issue, por favor.

**Comment by marcelofabri** [comment]
@nadocoelho Lembrando que quem cria issue também pode fechar 😉

**Comment by nadocoelho** [comment]
perfeito @marcelofabri, lembrarei na próxima! Obrigado por fechar!
Abraço

**Comment by nadocoelho** [comment]
@marcelofabri e @reprotector estamos abrindo mais uma vaga na nossa equipe. O que fica melhor: reabrir a issue ou criar uma nova?

**Comment by marcelofabri** [comment]
Acho que pode criar uma nova :)

**Comment by nadocoelho** [comment]
Beleza! Valeu @marcelofabri
