### ISSUE TITLE
[SP - Consolação] QuintoAndar - Desenvolvedor iOS Júnior/Sênior

### ISSUE THREAD

**Issue by rsacchi** [CocoaHeadsBrasil/vagas#105]
## Empresa
O QuintoAndar é uma empresa de tecnologia que facilita o processo de aluguel de imóveis do início ao fim. Usamos tecnologia e design para redesenhar o processo de locação e proporcionar o tipo de experiência que gostaríamos para nós mesmos. Estamos criando um novo modelo de negócios que é único no mundo inteiro e que vai revolucionar o setor imobiliário. Contamos com o suporte de alguns dos melhores investidores do mundo: Kaszek Ventures, Graph Ventures, e Kevin Efrusy from Accel Partners.

## Descrição da vaga
Trabalhar na versão iOS dos produtos do QuintoAndar. Todos os nossos apps são feitos em Swift.

## Posição
Júnior/Sênior

## Tipo de contratação
Presencial CLT

###### Obrigatórios
- Ser graduado em Ciência da Computação, Engenharia da Computação ou equivalente
- Ter conhecimento de Objective-C e Swift
- Inglês fluente
- Aprender muito rápido e ter alta capacidade analítica

###### Desejáveis
- Ter publicado algum app na App Store
- Já ter trabalhado com times de UX e produto
- Git
- CocoaPods

###### Diferenciais
- Ter experiência com desenvolvimento de apps para Android 

## Benefícios
- VA e VR
- VT
- Plano de saúde
- 40 dias de férias por ano
- Free beer às sextas-feiras
- Subsídio a academia de ginástica
- Ambiente típico de startup (informal, divertido, pode trabalhar de bermuda e chinelo, etc)

## Como aplicar
Aqui <a href="https://quintoandar.workable.com/jobs/403423" target="_blank">neste link</a>.

## Contato
Qualquer dúvida, pode me mandar um email: rafael.sacchi@quintoandar.com.br

**Comment by faganello60** [comment]
A Vaga está aberta?
Mandei um email e não tive retorno.
Obrigado.

**Comment by rsacchi** [comment]
@reprotector a vaga está aberta ainda.

**Comment by araujoraphael** [comment]
@rsacchi não rola esse remoto não?

**Comment by rsacchi** [comment]
@araujoraphael não :(

**Comment by Viniciuscarvalho** [comment]
A vaga continua aberta @rsacchi ?

**Comment by rsacchi** [comment]
@Viniciuscarvalho não, pode fechar!
