### ISSUE TITLE
[Remoto] Desenvolvedor Mobile Jr/Sr @ Nuage IT.

### ISSUE THREAD

**Issue by techrecruiterbsb** [CocoaHeadsBrasil/vagas#1059]
## Posição
Júnior e Sênior.

## Tipo de contratação
Remoto
CLT ou PJ

###### Obrigatórios
- Superior completo na área de TI;
- Experiência no desenvolvimento de aplicações híbridas para iOS e Android;
- Conhecimento em React Native;
- Docker;
- SQL;
- APIs Rest.

## Como aplicar
Se interessou pela vaga e preenche os requisitos? Envie o seu currículo para: techrecruiterbsb@gmail.com

**Comment by unnamedd** [comment]
Vagas postadas aqui devem ser exclusivamente relacionadas as plataformas Apple de desenvolvimento. Por favor, leia o README.
