### ISSUE TITLE
[SP - Alto de Pinheiros] - Desenvolvedores iOS Pleno/Senior - com Swift | BURN IT

### ISSUE THREAD

**Issue by herlanijunior** [CocoaHeadsBrasil/vagas#106]
## Empresa
A essência da Burn It é inflamar o seu projeto ou idéia e acelerar o seu potencial. 
Somos uma aceleradora de idéias e uma boutique de desenvolvimento em TI que cria e apoia projetos inovadores de nossos parceiros e clientes. 
Temos um olhar diferente do mercado, nosso dreamteam de tecnologia, projetos e design analisa cada projeto de acordo com sua fase e caraterística para entregar os melhores resultados.

## Descrição da vaga
Estamos procurando desenvolvedores(as) Apple iOS para INÍCIO IMEDIATO.

## Posição
Conosco seu trabalho será:

- Definir, criar, implementar e testar os Apps utilizando desenvolvimento nativo iOS (Swift).
Atenção: neste momento somente entrevistaremos pessoas com conhecimento em Swift (2 ou 3) e que trabalhem com código nativo (pessoas que desenvolvem somente com ferramentas do tipo Xamarin, PhoneGap, etc não são o perfil que procuramos no momento ).

- As Apps serão integrados com os serviços RESTful no backend, por isso é pré-requisito integração de sistemas via qualquer tipo de webservices além de conhecimentos básicos de SQL (ANSI).

- Você utilizará metodologia ágil com Kanban, integração continua, Amazon WebServices, Git, Jira, Slack, etc…. mas nada disto é mandatório, mas conhecer te coloca em destaque aos outros candidatos.

**Nosso processo de entrevista é composto de 5 fases:**

- Analise de CV ou portifólio de Apps
- Teste online de coding (acreditamos que bons engenheiros de código se adaptam a qualquer plataforma e/ou linguagem de programação) – máximo de 80 min
- Pré-entrevista on-line (skype) – 15 min
- Entrevista em nosso escritório local e teste prático de trabalho – 90 min
- Entrevista final com sócios para oferta de trabalho e acordo de remuneração. Se você aceitar já sai com seu contrato de trabalho assinado. – 30 min
**_- Todos os testes e entrevistas podem ser feitos nos dias e horários que você escolher_**

## Tipo de contratação
Presencial, horário flexível, CLT, PJ ou Freelancer. 
Remuneração é negociável, inclusive oferecemos bônus por performance (baseados nos prazos e qualidade das entregas).

## Benefícios
- você poderá escolher seu equipamento e configuração ( Windows, Linux ou Apple), todos com 2 monitores
- escritório moderno e com cadeiras de qualidade
- free snacks todos os dias
- projetos desafiadores e oportunidade de crescimento profissional
- tecnologia de ponta
- flexibilidade de horário ( nosso foco é a entrega )
- local de trabalho com fácil acesso ao transporte público (próximo a estação CPTM Cidade Universitária/ Praça Panamericana)

## Como aplicar
Interessado(a) ? Mande um email agora para: **_TALENTS@BURNIT.TECH_**

## Contato
http://www.burnit.tech/jobs-ios-developer/

**Comment by reprotector** [comment]
@herlanijunior Conseguiram fechar a vaga? Posso fechar a issue?
