### ISSUE TITLE
[REMOTO ou Campinas/SP] Desenvolvedor(a) Android na Projeto22

### ISSUE THREAD

**Issue by mayksalles** [CocoaHeadsBrasil/vagas#1062]
## Empresa
 Projeto22  -  prestadora de serviços em desenvolvimento de sistemas e Recursos Humanos (hunting e alocação)

## Descrição da vaga
Implementar novas funcionalidades, melhorias e correção de defeitos no serviço de indexação
e busca embarcado em aparelhos Android;
Contribuir com o sistema de integração continua e testes automatizados (unit test e
instrumentation test);
Transformar ideias em provas de conceito tais como novos algoritmos de busca, sistema de
análise e coleta de dados em tempo real, algoritmos de predição utilizando IA;
Interagir tecnicamente com equipes internas e externas (outros países);
## Posição
Pleno ou Júnior

## Tipo de contratação
CLT (Remoto ou presencial). 

###### Obrigatórios
Experiência com desenvolvimento Android
Experiência nas linguagens de programação Java e Python
Inglês intermediário

###### Desejáveis
Conhecimentos em NLP
Experiência com ferramentas Git, Jira, Jenkings
Conhecimentos de SQL, NoSQL, Elasticsearch ou SOLR
Conceitos básicos de Data Science

###### Diferenciais
Inglês avançado

## Benefícios
Plano Médico e Odontológico (gratuito para funcionário e dependentes) VA e/ou VR (em torno de 850,00) Fretado e/ou Estacionamento Gratuito Quick Massage Gympass para desconto em academias Auxílio educação continuada (MBA, pós, doutorado...) Auxílio idiomas Auxílio creche Bonificação anual de 2 salários Entre outros...

## Como aplicar
Enviar CV para : maycon.sales@projeto22.com.br

## Contato
maycon.sales@projeto22.com.br

**Comment by ezefranca** [comment]
@mayksalles esse forum é dedicado a vagas iOS e ecossistema Apple. 

Para Android recomendo: https://github.com/androiddevbr/vagas/issues
