### ISSUE TITLE
[Remoto] Mobile Hybrid App Developer na DevGrid

### ISSUE THREAD

**Issue by gabrielhws** [CocoaHeadsBrasil/vagas#1064]
## Descrição da vaga: 
 <p>We are seeking a detailed oriented individual to join our world-class team in going above and beyond. You are going to join a team of talented engineers building the next-generation IoT system.</p>
<p>We pride ourselves on engaging in innovative and challenging projects the world has never seen before. Thus, understanding the business logic involved in the product and teamwork are key to succeed in this role;</p>
<p>If you are confident you are the one - Apply now and let the future begin!</p>

## DevGrid: 
 <p>DevGrid is a Full Stack software development company based in the United Kingdom with two delivery hubs in Brazil. We enable innovation and digital transformation by bringing together our strong company culture and our bright engineers with your innovative business vision.</p>
</p>

 ## Habilidades: 
 - HTML 5 
- Javascript 
- PhoneGap 
- CSS 3 
- Sass/Less 
- RESTful 
- JSON
## Local: 
 100% Remoto
## Requisitos: 
 - Experience with Angular 1 or related technologies. 
- Experience with Cordova/Phonegap. 
- Experience with build pipeline tools such as NPM, Bower, Grunt, Gulp, SASS. 
- Extensive experience with Javascript, HTML5, CSS3, RESTful services. 
- Experience with JSON over REST APIs.  
- Experience building, maintaining and extending Single Page Applications.

## Como se candidatar:
Candidate-se em: [Mobile Hybrid App Developer na DevGrid](https://coodesh.com/vagas/mobile-hybrid-app-developer-134948?origin=github&modal=open)
## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [montin@devgrid.co.uk](mailto:montin@devgrid.co.uk)
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Pleno
#### Categoria
Mobile

**Comment by unnamedd** [comment]
Vaga em não conformidade com a regras do repositório.
