### ISSUE TITLE
[SP - Pinheiros] Banco Neon - Desenvolvedor Android Sr.

### ISSUE THREAD

**Issue by CamilaNeon** [CocoaHeadsBrasil/vagas#107]
## Banco Neon
O Neon é um banco, só que totalmente diferente.
Ele nasceu do desejo de transformar uma área que quase não se reinventa. E também nasce do cansaço de pagar uma fortuna em taxas e não receber um atendimento de qualidade. 
Nosso aplicativo foi construído para facilitar a vida financeira e valorizar a experiência dos clientes. Tudo sem enrolação, sem blá blá blá. 

## Descrição da vaga
O profissional trabalhará na equipe responsável pelo desenvolvimento e manutenção do app Android. A expectativa é que o profissional seja capaz de entregar um produto com requintes avançados de UX utilizando animações e navegação fluída.

## Posição
Desenvolvedor Android Sr.

## Tipo de contratação
Presencial, CLT

## Requisitos
Experiência de no mínimo 04 anos em desenvolvimento de aplicativos nativos Android.
Conhecimentos avançados em Java.
Conhecimentos avançados em animações.
Experiência no uso de Web Services(REST, JSON/XML).
Ter preocupação com a parte visual dos aplicativos.
Adaptação de layouts para diferentes tamanhos de telas.
Testes integrados.
Elaborar modelagem de dados.
Design Patterns.

###### Diferenciais
Experiência com desenvolvimento para smartwatch
Links com código no github e ou apps publicadas
Ter trabalhado com jogos.

## Benefícios
Horário Flexível
No dress code
Happy Hour semanal por conta da empresa
Sala de descanso/ videogame
Subsidio para academia (Gym Pass)
Subsidio Plano de Saúde
Estacionamento ou Vale Transporte (sem desconto no salário)
Vale Cultura
Vale Refeição

## Como aplicar
Envie o currículo para seja@banconeon.com.br

## Contato
www.banconeon.com.br

**Comment by talesp** [comment]
A Vaga é mesmo para Android? Por organização, por favor, cadastrar no https://github.com/androiddevbr/vagas e fechar a vaga, o foco aqui é iOS :)

**Comment by CamilaNeon** [comment]
Opsss... ok! Obrigada!
