### ISSUE TITLE
[REMOTO] Flutter Developer na Conquest One

### ISSUE THREAD

**Issue by lucasherodoto** [CocoaHeadsBrasil/vagas#1071]
## Empresa
A Conquest One é uma empresa especializada em Staffing de TI, sendo eleita 9 vezes como uma GPTW e agora está em busca de uma pessoa apaixonada por tecnologia e inovação para uma oportunidade incrível!

## Descrição da vaga

Foco em desenvolvimento, mas espera-se que a partir das reuniões o profissional consiga levantar alguns requisitos técnicos; Atuará em um projeto que já está em andamento e podem surgir demandas novas

## Posição
Sênior

## Tipo de contratação
PJ

###### Obrigatórios

iOS 
Android 
Flutter

###### Desejáveis

Scrum 

## Como aplicar

Por favor envie um email para lucas.martins@cq1.com.br com seu CV anexado e pretensão salarial
Enviar no assunto: Desenvolvedor Flutter

**Comment by unnamedd** [comment]
Esse repositório é apenas voltado para technologias Apple.
