### ISSUE TITLE
[São Paulo - Av. Paulista] Senior iOS Engineer (Swift) | Farfetch

### ISSUE THREAD

**Issue by rdgborges** [CocoaHeadsBrasil/vagas#1079]
## Descrição da vaga

You will contribute to the end-to-end development of iOS applications driving the long-term mobile strategy planned for Farfetch. You'll write top-notch Swift code and resort to battle-hardened design patterns. You'll also have the chance to work with a modular App architecture, Unit Tests, UI Automation, Snapshot Testing and automated build pipelines while reporting to the Engineering Lead.

### What you'll do

- You will guide feature development and help improve end-to-end product quality
- You will contribute for cross-team development of common libraries
- You will help establish best practices on iOS development and contribute for a learning environment
- You will be committed to Continuous Integration and Continuous Deployment
- You will work with other Product Development teams to improve consistency and timing of releases
- You will create prototypes of new ideas and explore new technologies on the forefront of mobile technology
- You will contribute with architectural solutions to deal with complex apps
- You will contribute with technical solutions to solve out of the ordinary performance challenges

## Local

Remoto. Modelo híbrido com foco em home-office no pós-pandemia. 

## Benefícios

- FARFETCH Equity plan and annual discretionary bonus
- Life insurance, health insurance and dental
- Gym membership, meal allowance and transportation vouchers
- Nursery reimbursement
- Special discounts at farfetch.com and brownsfashion.com

### Who you are

- You are experienced in iOS development with at least one released app (solo or as a team member)
- You are experienced in working with Swift
- You are experienced with the set up of automated Continuous Integration and Continuous Deployment systems
- Knowledgeable about REST API architecture
- Understanding of client-side development and the API backend stack
- Eager to get nerdy about memory management, UI layout/rendering and UI/network performance
- Proficient in written English

## Contratação

CLT

## FARFETCH

FARFETCH exists for the love of fashion. Our mission is to be the global platform for luxury fashion, connecting creators, curators and consumers.

We're a positive platform for good, bringing together an incredible creative community made up by our people, our partners and our customers. This community is at the heart of our business success. We welcome differences, empower individuality and celebrate diverse skills and perspectives, creating an inclusive environment for everyone. We are FARFETCH for All.

https://aboutfarfetch.com
https://farfetchcareers.com

### Technology

We're on a mission to build the technology that powers the global platform for luxury fashion. We operate a modular end-to-end technology platform purpose-built to connect the luxury fashion ecosystem worldwide, addressing complex challenges and enjoying it. We're empowered to break traditions and revolutionize, with the freedom and autonomy to make a difference for our customers all over the world.

### São Paulo

Our São Paulo office is located in the heart of the city, a region full of cultural spaces and history. The office houses several different teams, from Operations to Technology. We have an auditorium where we can host presentations, lectures and fun activities!

### Equal opportunities statement

FARFETCH is an equal opportunities employer ensuring that you are treated equally and fairly throughout our recruitment process. We are determined that no applicant experiences discrimination on the basis of sex, race, ethnicity, religion or belief, disability, age, gender identity, ancestry, sexual orientation, veteran status, marriage and civil partnership, pregnancy and maternity, or any other basis prohibited by applicable law. We continue to build our consciously inclusive culture as part of our Positively FARFETCH strategy throughout our business, partnerships and communities.

## Como se candidatar

https://farfetchcareers.com/job/5419/ios-software-engineer

**Comment by erickyamato** [comment]
@rdgborges, não encontro no site aonde aplicar. Pode me ajudar?
