### ISSUE TITLE
[EUA/RJ] eShares - Desenvolvedores iOS/Android Pleno/Senior

### ISSUE THREAD

**Issue by victorlandeira** [CocoaHeadsBrasil/vagas#108]
## Empresa
 A [eShares](https://esharesinc.com) é um fintech americana que lida com ações do mercado privado. Há 4 anos no mercado, a eShares tem como objetivo revolucionar a forma em que os certificados de ações de empresas privadas são gerados e geridos. Além de facilitar a gerencia de acionistas (Cap Table), Valuations e Vesting schedules.

## Descrição da vaga
  Estamos procurando desenvolvedores iOS/Android com inglês fluente. A vaga é pra trabalhar na Califórnia e isso inclui o processo de treinamento, passagens, hospedagem e visto. Até a aprovação do visto de trabalho, trabalhamos do Rio de Janeiro com regime CLT.

Diploma na área é um diferencial, mas não é obrigatório! Um Github bem movimentado, participações em palestras e eventos, e experiência profissional valem muito mais pontos.

Fora isso, a única coisa necessária é disponibilidade de viajar para os Estados Unidos esse ano ainda, em abril, para período de treinamento de três meses. O nosso processo de seleção e entrevistas é bem rápido, e você pode participar novamente mesmo que já tenhamos nos falado antes!

A eShares tem uma cultura bem forte de trabalho em equipe, colaboração e aprendizado. Trabalhar aqui é uma oportunidade de ter um impacto significativo sobre o produto, aprender bastante, e estar no lugar onde muita coisa da nossa área acontece.

<img width="625" alt="mobile engineers" src="https://cloud.githubusercontent.com/assets/5169408/23215458/38ebdfe2-f8f1-11e6-9c41-3c81cea7ac9e.png">

## Posição
 Pleno ou Sênior com experiência em Swift (iOS)
 Pleno ou Sênior com experiência em Java (Android)

## Tipo de contratação
 Presencial CLT

## Requisitos
 Experiência com Swift/Java
 Inglês fluente
 Visto de Visitante ou Negócio aos EUA 

### Brasil:
* Plano de Saúde
* Plano Odontológico
* Vale Refeição
* Vale Alimentação
* Vale transporte
* Auxilio Academia (50% da mensalidade)
* Snacks e geladeira abastecidos
### Palo Alto (Treinamento)
* Passagem
* Estadia
* Ajuda de custo em USD
* Auxilio Academia (50% da mensalidade)

## Como aplicar
Curriculo em inglês para victor.landeira@esharesinc.com

### Contato Slack
@victorlandeira - Victor Landeira
@bbheck - Bruno Hecktheuer

**Comment by reprotector** [comment]
@victorlandeira Conseguiram fechar a vaga? Posso fechar a issue?

**Comment by victorlandeira** [comment]
está aberto ainda!
comento em alguns dias quando fecharmos o recebimento de curriculos

**Comment by walterfernandes** [comment]
@victorlandeira existe possibilidade de trabalho remoto?

**Comment by victorlandeira** [comment]
infelizmente não @walterfernandes 
estar presente com a equipe faz bastante parte da cultura da empresa

**Comment by reprotector** [comment]
@victorlandeira Esse canal é apenas para vagas iOS/macOS. Vagas de Android podem ser postadas  no grupo AndroidDevBR: https://github.com/androiddevbr/vagas

**Comment by reprotector** [comment]
@victorlandeira Favor retirar Android da vaga. Fechando enquanto isso.
