### ISSUE TITLE
[Marialva-PR] Routerbox - Desenvolvedor Mobile Trainee

### ISSUE THREAD

**Issue by JFSene** [CocoaHeadsBrasil/vagas#110]
## Empresa
 Routerbox - Empresa voltada para o desenvolvimento de software de gerenciamento de provedor de internet.

## Descrição da vaga
Migrar para nativo os Apps ja desenvolvidos, dar suporte a versões anteriores.
## Posição
Trainee

## Tipo de contratação
Presencial - CLT

## Benefícios
Segue mais informações no flayer.

## Como aplicar
Segue mais informações no flayer.

## Contato
Segue mais informações no flayer.
![vaga-android-v2](https://cloud.githubusercontent.com/assets/17616463/22025021/3da7d84c-dcb3-11e6-9646-ad8d80e7edb2.jpg)

**Comment by unnamedd** [comment]
@JFSene, essa é uma oportunidade voltada para desenvolvedores Android. 

Por favor, publique no Vagas do AndroidDevBR.
https://github.com/androiddevbr/vagas

**Comment by fpg1503** [comment]
Além dissso é legal transcrever as informações da imagem para auxiliar os deficientes visuais, usuários de leitores de tela e a indexação da sua vaga na busca.

**Comment by JFSene** [comment]
Valeu pelas dicas ai galera. Vou arrumar isso aqui quando me enviarem a imagem correta e reabrir a Issue!!!
