### ISSUE TITLE
[São Paulo - SP] AgileThought Desenvolvedor IOS

### ISSUE THREAD

**Issue by vagastech** [CocoaHeadsBrasil/vagas#1106]
Vaga: Desenvolvedor Mobile (IOS e Android) sênior, para trabalhar em uma empresa de tecnologia em SP, zona sul.

Experiencia com desenvolvimento mobile para as plataformas Android e IOS.

 *IOS: conhecimentos em SWIFT, design patterns e integrações REST MVVM e MVVM-C
Distribuição na Apple Store
 
*Android: Proficiência em desenvolvimento para plataformas móveis. 
Experiência em desenvolvimento Kotlin e Android Studio
Integracoes API REST
Distribuição na Play Store

Benefícios: Vale Alimentação, vale refeição e vale combustível. + Assistência Médica + Assistência Odontológica + Seguro de Vida + Gympass
 Regime de trabalho : Presencial
Modelo: CLT 

Envie o currículo atualizado com pretensão salarial para o e-mail: Belen.ramirez.tech@gmail.com

**Comment by RecrutamentoDocketBrasil** [comment]
Belen.ramirez.tech@gmail.com
