### ISSUE TITLE
[Rio de Janeiro, RJ] Mobicare - Desenvolvedor iOS Jr/Pleno

### ISSUE THREAD

**Issue by burnermanx** [CocoaHeadsBrasil/vagas#111]
## Empresa: Mobicare
 Empresa do segmento de tecnologia especializada em solução de auto- atendimento móvel e wifi Carrier Grade.
 
## Descrição da vaga:
 
Participar de todo o ciclo de desenvolvimento de aplicativos, desde a fase de análise da solução até a entrega e manutenção do projeto.
 
Trabalhar com outros desenvolvedores de alto desempenho em um ambiente colaborativo.
 
## Posição
Desenvolvedor iOS Júnior/Pleno
 
## Tipo de contratação
CLT – Local: Botafogo, RJ.
 
###### Obrigatórios
- Forte conhecimento de Objective-c e Swift
- Experiência com os frameworks do iOS
- Conhecimento em desenvolvimento de telas para iOS (Storyboard, Auto Layout, componentes nativos, Views, criação de componentes customizados);
- Entendimento dos padrões de design e guidelines de interface da Apple
- Experiência com armazenamento off-line, threading e melhora de performance
- Conhecimento das libs open-source mais utilizadas para iOS
- Conhecimento de Cocoapods
- Familiaridade com RESTful webservices
- Familiaridade com ferramentas de versionamento (Git/SVN)
- Inglês técnico
 
###### Diferenciais:
- Experiência com push notifications / APNS
- Testes automatizados
- Testes de UI
- Contribuição em projetos open source
- Ter ao menos um aplicativo desenvolvido (não necessariamente publicado App Store)
- API’s do Google Services (maps, analytics, GTM, etc)
- Conhecimento de metodologias ágeis
 
## Benefícios
- Salário compatível com o mercado;
- Pacote de benefícios completo;
- Horário flexível de 40h semanais;
- Escritório com: Frutas, Sorvete, Pipoqueira, Frigobar, Vídeo – game e muito mais surpresas!
 
## Como aplicar 
Através do site www.mobicare.com.br ou pelo vagas@mobicare.com.br com o assunto: #Desenvolvedor iOS
 
## Contato 
21 3032-5165

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @burnermanx ?
