### ISSUE TITLE
[Remoto ou Londrina - PR] Desenvolvedor(a) iOS - Lapaza Empreendimentos

### ISSUE THREAD

**Issue by danielsanfr** [CocoaHeadsBrasil/vagas#1127]
## Empresa

Empresa responsável pelo desenvolvimento e manutenção do Sistema Integrado de Estacionamento Rotativo [Vago!](https://www.vagoonline.com.br), atuamos em várias cidades do sul e sudeste do Brasil. Contamos com sistemas web tanto para administração quanto para o uso dos usuários finais. Temos aplicativos Android e iOS desenvolvidos de forma nativa. E também temos parquímetros desenvolvidos com sistemas embarcados.

## Descrição da vaga

Você ajudará a dar manutenção e desenvolver novas funcionalidades em nosso aplicativo iOS.
Caso tenha interesse, também poderá conhecer como desenvolvemos as outras partes da nossa plataforma, assim como desenvolvemos e fabricamos nossos sistemas embarcados que equipam os nossos parquímetros.

## Posição

Junior, Pleno ou Sênior.

## Tipo de contratação

 CLT ou PJ a combinar.

### Obrigatórios

- 1+ anos de experiência com iOS (Swift);
- Confortável com padrão MVP, MVC, MVVM e derivados;

### Desejáveis

- Experiência com testes unitários;
- Experiência com testes de UI e integração;
- Experiência com RxSwift;
- Git (Git-flow);

### Diferenciais

- Projetos open source;
- Aplicativo publicado;
- Conhecimento em Android;

## Benefícios

- Plano de saúde;
- Vale refeição;

## Como aplicar

Por favor envie um email para danielsan@vago.online com seu CV anexado, link para LinkedIn e ou Github. Enviar no assunto: Vaga iOS.

## Contato

danielsan@vago.online

**Comment by danielsanfr** [comment]
Acabei de notar que na vaga não coloquei que a ela seria presencial (depois da pandemia) ou **remoto forever**.
Eu se eu editar a issue vocês recebem a notificação no Slack ou eu teria que criar outra issue?

**Comment by danielsanfr** [comment]
@unnamedd desculpa se estiver lhe incomodando ao lhe marcar, mas saberia me dizer se eu posso fechar essa vaga e criar outra, visto que deu a entender que a vaga era apenas presencial?

**Comment by unnamedd** [comment]
@danielsanfr só edita o conteúdo dela e eu coloco as labels que você julgar justa para essa vaga. Só me dizer aqui nos comentários. Não precisa criar outra não, até porque, depois fica mais complicado pra você mesmo gerenciar.

**Comment by danielsanfr** [comment]
Obrigado por responder tão rápido. Acho que só a label de remoto já deve ajudar, obrigado mais um vez 👍🏻 .

**Comment by unnamedd** [comment]
Se precisar de alguma coisa, por favor, me avisa!
