### ISSUE TITLE
[São Paulo, SP] Desenvolver mobile app

### ISSUE THREAD

**Issue by tripletech-it** [CocoaHeadsBrasil/vagas#114]
## Empresa
Tripletech, empresa especializada em soluções de TI

## Descrição da vaga
Analista programador mobile para apps híbridas e experiência de no mínimo 1 ano.
Desenvolvimento de apps usando Cordova e Ionic 2
## Posição
JR

## Tipo de contratação
 presencial podendo ser CLT ou PJ  

###### Obrigatórios
Requisitos Mandatórios:

Cordova
Javascript: Jquery e Angular
HTML 5
CSS 3
###### Desejáveis
-link com portfólio de trabalhos
-Inglês Intermediário
###### Diferenciais
Conhecimento em Ionic
Noções de design
Conhecimento básico em PHP ou Node
## Benefícios
•Plano de Saúde Amil
•Vl Refeição - R$20,00
•Vl Transporte ou Vl Combustível - R$10,00 dia (não à desconto de benefício)
•Seguro de Vida Coletivo
•Plano de Carreira e PLR
• Ambiente descontraído
•Café da manhã
•Horário Flexível
•Day off

## Contato
Por favor envie um email para rh@tripletech.com.br com seu CV anexado e informando preferencia de contratação CLT ou PJ - enviar no assunto: DevMobileApp

**Comment by reprotector** [comment]
@tripletech-it Qual a cidade da vaga? Por favor, coloque a cidade no título da vaga como as demais. Obrigado!

**Comment by tripletech-it** [comment]
Olá São Paulo - Capital
