### ISSUE TITLE
[São José dos Campos, SP] Desenvolvedor iOS Sênior

### ISSUE THREAD

**Issue by cassianomonteiro** [CocoaHeadsBrasil/vagas#115]
## Empresa
Guichê Virtual
www.guichevirtual.com.br
https://www.linkedin.com/company/guiche-virtual
Start-up criada a partir do desenvolvimento de uma plataforma integrada de venda de passagens de ônibus online. Temos 4 anos de vida, e no início de 2016 recebemos uma rodada de investimentos para fazer ramp-up, pulando de 12 para ~60 pessoas. Em 2017 estamos em uma nova fase de ramp-up para dobrar o tamanho da empresa.

### O que a gente procura:
Experiência em desenvolvimento de apps para iOS, tendo já desenvolvido/publicado apps. Conhecimentos em estrutura de dados, algoritmos, arquitetura de software, design patterns e TDD.

### O que seria legal:
- Experiência com desenvolvimento Agile/SCRUM;
- Conhecimento em UX, especialmente mobile.

### O que a gente espera:
- Pró-atividade em puxar problemas para si e buscar soluções;
- Comprometimento com o time;
- Compromisso com qualidade;
- Autodidata.

### O que você fará:
- Desenvolvimento do nosso app para iOS, direcionando arquitetura, manutenção e evolução do app;
- Levantamento dos requisitos/necessidades e propostas de solução, através de prototipa'ão e testes de usabilidade;
- Planejamento, priorização e estimativa das atividades a serem realizadas durante o ciclo de vida do app;
- Compartilhamento de conhecimento com o time.

## Posição
Sênior

## Tipo de contratação
CLT, presencial.

## Benefícios
- Plano de saúde com co-participação
- Vale refeição
- Vale transporte
- Horário flexível
- Ambiente informal (trabalhar de bermuda, etc.)
- Ainda estamos estruturando outros benefícios ao longo deste ano

## Com quem você vai trabalhar
Eu! =)
E mais um monte de gente legal, dá uma olhada no nosso linkedin!

## Como aplicar
Através da vaga no linkedin: https://www.linkedin.com/jobs/cap/view/316147051
Ou enviar email para recrutamento@guichevirtual.com.br

## Dúvidas
Pode me contactar no slack iOSDevBR: @cassianomonteiro ! =)

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @cassianomonteiro ?

**Comment by cassianomonteiro** [comment]
Foi fechada.
