### ISSUE TITLE
[MG - Uberlândia] Zup IT - Desenvolvedor iOS 

### ISSUE THREAD

**Issue by deboracardoso** [CocoaHeadsBrasil/vagas#116]
## Empresa
Fundada em 2011, a zup tem como foco ajudar empresas a lidar com toda complexidade de integração de sistemas e externalização de serviços, apoiando grandes clientes de vários segmentos da economia.
A ZUP possui plataforma e ferramentas completas para viabilizar técnica e financeiramente suas estratégias digitais. Sua tecnologia começou a ser desenvolvida em 2007 e busca solucionar desafios de ambientes completos para TI.
A companhia tem sua sede em Uberlândia (MG), onde está instalada a área de pesquisa e desenvolvimento, escritórios técnicos em São José do Rio Preto e escritório comercial em São Paulo.
Site: http://www.zup.com.br

## Descrição da vaga
Realizar a programação de sistemas em iOS, codificar e testar sistemas. Executar a manutenção dos sistemas, fazendo eventuais correções necessárias, visando atender às necessidades dos usuários. Desenvolver trabalhos de montagem, depuração e testes de programas, executando serviços de manutenção nos programas já desenvolvidos.

## Posição
Jr, Pl e Sr

## Tipo de contratação
CLT

###### Obrigatórios
 Experiência na função e conhecimento em Objetive-C e/ou Swift 

###### Diferenciais
Experiência em arquitetura de Software.

## Benefícios
Convênio médico, odontológico, vale alimentação, PLR, verba individual anual para treinamento, plano telefônico, programa de indicação. 

## Como aplicar
Interessados enviar currículo para vagas@zup.com.br

## Contato
vagas@zup.com.br

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @deboracardoso ?
