### ISSUE TITLE
[SP - Consolação] QuintoAndar - Desenvolvedor iOS Sênior

### ISSUE THREAD

**Issue by rsacchi** [CocoaHeadsBrasil/vagas#117]
## Empresa
O QuintoAndar é uma empresa de tecnologia que facilita o processo de aluguel de imóveis do início ao fim. Usamos tecnologia e design para redesenhar o processo de locação e proporcionar o tipo de experiência que gostaríamos para nós mesmos. Estamos criando um novo modelo de negócios que é único no mundo inteiro e que vai revolucionar o setor imobiliário. Contamos com o suporte de alguns dos melhores investidores do mundo: Kaszek Ventures, Graph Ventures, e Kevin Efrusy from Accel Partners.

## Descrição da vaga
Trabalhar na versão iOS dos produtos do QuintoAndar. Todos os nossos apps são feitos em Swift.

## Posição
Sênior

## Tipo de contratação
Presencial CLT

###### Obrigatórios
- Ser graduado em Ciência da Computação, Engenharia da Computação ou equivalente
- Profundo conhecimento de Objective-C e Swift
- Inglês fluente
- Aprender muito rápido e ter alta capacidade analítica
- Já desenvolveu aplicativos importantes
- Tem alguma experiência com banco de dados relacional
- Já escreveu alguma API RESTful para ser consumida por apps

###### Desejáveis
- Ter desenvolvido algum app para Android
- Ter trabalhado com times de UX e produto
- Git
- CocoaPods

###### Diferenciais
- Ter experiência com desenvolvimento de apps para Android 

## Benefícios
- VA e VR
- VT
- Plano de saúde
- 40 dias de férias por ano
- Free beer às sextas-feiras
- Subsídio a academia de ginástica
- Ambiente típico de startup (informal, divertido, pode trabalhar de bermuda e chinelo, etc)

## Como aplicar
Aqui <a href="https://quintoandar.workable.com/jobs/261960" target="_blank">neste link</a>.

## Contato
Qualquer dúvida, pode me mandar um email: rafael.sacchi@quintoandar.com.br

**Comment by reprotector** [comment]
@rsacchi Pode colocar atualizar a posição da vaga #105? Ambas as vagas tem o mesmo texto. Assim mantemos a visualização igual pra todo mundo :)

**Comment by rsacchi** [comment]
@reprotector como assim, adicionar label de Sr na 105 e fazer essa aqui apontar pra ela?
