### ISSUE TITLE
[Rio de Janeiro, RJ] Hotel Urbano - Desenvolvedor(a) iOS Pleno ou Sênior

### ISSUE THREAD

**Issue by thiagocortat** [CocoaHeadsBrasil/vagas#118]
## Empresa
Uma das maiores agências de turismo online do mundo precisa do seu talento. Estamos procurando um desenvolvedor iOS para nosso aplicativo!
A visão do Hotel Urbano é realizar o match dos nossos usuários com a viagem dos sonhos.
Números do HU:
mais de 180.000 hotéis ao redor do mundo;
18 milhões de viajantes cadastrados;
1 diária vendida a cada 8 segundos;
20 milhões de pessoas buscando viagens todo mês;
12 milhões de fans no facebook;

## Descrição da vaga
Faça parte do time HU.
Procuramos pessoas inteligentes e ágeis como você para nos ajudar a resolver os nossos desafios.
Você vai trabalhar, no seu dia-a-dia, buscando a alta disponibilidade e qualidade, atuando dentro de um time multidisciplinar.

## Tipo de contratação
CLT - Pleno, Sênior ou PJ a combinar.  Local: Barra da Tijuca, RJ.

###### Obrigatórios
Forte conhecimento de Objective-c e Swift
Experiência com os frameworks do iOS
Conhecimento em desenvolvimento de telas para iOS (Storyboard, Auto Layout, componentes nativos, Views, criação de componentes customizados);
Entendimento dos padrões de design e guidelines de interface da Apple
Conhecimento de Cocoapods
Ter facilidade para trabalhar dentro de times multi-disciplinares
Saber escrever código limpo e legível
Possuir conhecimentos de integração utilizando API RESTful
Ter conhecimento de práticas de XP (TDD, pair programming, refactoring, continuous integration, etc)
Familiaridade com Git
Experiência com push notifications / APNS

###### Diferenciais
Testes automatizados
Testes de UI
Contribuição em projetos open source
Conhecimentos de desenvolvimento WEB (HTML, CSS, Javascript, jQuery, etc);
Ter experiência com React Native;

## Benefícios
Assistência Médica,
Assistência Odontológica,
Tíquete-refeição
Horário Flexível
Seguro de vida
Auxílio Creche

## Como aplicar
Por favor envie um email para mobile@hotelurbano.com.br com seu CV anexado, mencionando apps publicados desenvolvidos por você. Enviar no assunto: Vaga Dev iOS.

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @thiagocortat ?

**Comment by thiagocortat** [comment]
Olá @Viniciuscarvalho. Sim já foi preenchida.
