### ISSUE TITLE
[SP - Vila Olímpia] B2W Digital - Desenvolvedor iOS Junior/Pleno

### ISSUE THREAD

**Issue by AndreasLS** [CocoaHeadsBrasil/vagas#119]
###### O que buscamos?

- Pessoas pró-ativas para resolução de problemas e que trabalhem bem em equipe;
- Experiência em desenvolvimento e manutenção de apps iOS
- Conhecimento em publicação e gerenciamento de aplicativos nas lojas;
- Conhecimento em Swift, OOP e API Rest (Twitter, Facebook e APIs Externas);

###### Responsabilidades:

- Concepção, desenvolvimento e implementação de prova de conceito e funcionalidades para produção.
- Projetar e implementar funcionalidades voltados para usuários em aplicativos mobile
- Desenvolvimento com foco em principios de design de UX para tablets e smartphones
- Analisar e otimizar para eficiência dos recursos e desempenho
- Trabalhar com estreita relação com as equipes de produto e design

## Posição
 Júnior / Pleno.

## Tipo de contratação
 Presencial CLT.

###### Obrigatórios
- Experiência no desenvolvimento de aplicações móveis nativas em Swift
- Otimizar aplicações móveis na plataforma iOS 
- Conhecimento da ferramenta XCode
- Compreensão de todo o ciclo de vida de desenvolvimento móvel
- Experiência em publicação de aplicativos na App Store
- Integração com APIs Restful / JSON e outras APIs de back-end
- Conhecimento de conceitos de OOP
- Controle de versão de software (GIT)
- Conhecimento de UI e UX (iOS Human Interface Guidelines)
- Conhecimento em animação

###### Desejáveis
- Experiência em utilização de serviços de bugtracker como Crashlytics.
- Conhecimento em desenvolvimento Android utilizando Frameworks ORM.
- Experiência em Testes Automatizados e metodologias ágeis
- Conhecimento em Integração Contínua

###### Diferenciais
- Experiência no desenvolvimento de aplicações em Objective-C

## Como aplicar
Interessados enviar currículo para Patricia Oliveira  [patricia.soliveira@b2wdigital.com](url)

## Contato
Para dúvidas ou maiores informações sobre a vaga, entrar em contato com  Patricia Oliveira  [patricia.soliveira@b2wdigital.com](url)

**Comment by richardfrk** [comment]
Olá, Tudo bem? Mandei um e-mail há mais de 10 dias e não obtive qualquer retorno... Gostaria de um feedback. Muito obrigado.
