### ISSUE TITLE
[Santa Catarina - Joinville] Desenvolvedor iOS - Camerite

### ISSUE THREAD

**Issue by ppamorim** [CocoaHeadsBrasil/vagas#12]
## Descrição da vaga

Precisamos de um desenvolvedor iOS para tocar o aplicativo atual. Feito em Swift e utilizando AutoLayout(PureLayout), Realm e Bolts.
## Local

Escritório Joinville - Santo Antônio
## Benefícios
- 1.5 horas de almoço;
- Horário flexível (de verdade);
- Vale alimentação;
- Vale transporte;
- Plano hospitalar;
- Estacionamento gratuito(a combinar);
- Maquina de café com 8 sabores;
- Sala de descanso grande;
- Ambiente com várias empresas, legal para networking;
- Restaurante/Padaria do lado da empresa.
## Requisitos

Obrigatórios
- Ser fera em Swift ou Objective-C. Ter pelo menos um projeto;
- Ter conhecimento em AutoLayout, Realm, Camera.

Desejáveis
- Leitura técnica / fluência em inglês.

Diferenciais
- Conhecimentos em desenvolvimento Android;
- Projetos OpenSource contam pontos;
- Conhecimento de linguagens funcionais também.
## Contratação

A combinar
## Nossa empresa

https://camerite.com/about
## Como se candidatar

Update: Por indicação de nosso supervisor, a vaga está disponível somente para profissionais de Joinville-SC ou regiões próximas.
Por favor envie um email para cristian@camerite.com e pedro@camerite.com com seu CV anexado - enviar no assunto: Vaga iOS - Camerite

**Comment by Viniciuscarvalho** [comment]
@ppamorim beleza? A vaga já foi preenchida? Se sim, poderia fechar a issue 👍

**Comment by Viniciuscarvalho** [comment]
@ppamorim A vaga já foi preenchida? Se sim, poderia fechar a issue? 👍
