### ISSUE TITLE
[SP - Alphaville] Cielo - Desenvolvedor iOS Sênior

### ISSUE THREAD

**Issue by mariliafranguelli** [CocoaHeadsBrasil/vagas#121]
**Descrição da vaga**
- Análise e desenvolvimento de soluções na plataforma iOS;
- Proposição de melhorias tecnológicas e processuais;
- Realização de pesquisas, acompanhando as evoluções e tendências tecnológicas;
- Suportar fábrica externa no desenvolvimento de sistemas.

**Posição**
Pleno/ Sênior

**Tipo de contratação**
Presencial, CLT full.

**Requisitos**
- Experiência em diferentes técnicas e ferramentas para acompanhamento dos projetos (JIRA);
- Experiência em desenvolvimento ágil, usando técnicas como Behaviour Driven Development (BDD) e Test Driven Development (TDD);
- Experiência, igual ou maior a 3 anos, no desenvolvimento, teste e debug de aplicativos nativos em iOS (Objective-C ou Swift);
- Experiência com frameworks iOS (ex: Core Data, Core Animation, etc);
- Experiência com Xcode, Cocoa Pods, AFNetworking, Autenticação por Oauth2, Interface Builder, Autolayout, Xib, Storyboards;
- Experiência em integração de apps mobile com webservices e APIs (HTTP based, XML-RPC, JSON ou outros serviços);
- Experiência nas guidelines de design e interface da Apple;
- Experiência nos protocolos de segurança referentes a mobile;
- Experiência em front-end (HTML5, JavaScript, CSS, entre outras tecnologias);
- Fundamentos sólidos no desenvolvimento de software (algoritmos, estruturas de dados, etc)
- Familiaridade com tendências de desenvolvimento de iOS emergentes e Design Patterns;
- Familiaridade com Customer Centric Design;

**Benefícios**
Assistência Médica, Assistência Odontológica, Plano de Previdência Privada, Seguro de Vida, Estacionamento/ Fretado, Auxílio Refeição (R$ 726,00 por mês), Auxílio Creche e PLR de até 3,3 salários por ano

**Como aplicar**
Interessados enviar currículo para Marília Franguelli (marilia.gabriela@2xs.com.br)

**Contato**
Para dúvidas ou maiores informações sobre a vaga, entrar em contato Marília Franguelli (marilia.gabriela@2xs.com.br)

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @mariliafranguelli ?

**Comment by mariliafranguelli** [comment]
Não Vinícius!

Pode cancelar...

Obrigada!

 

Marília Franguelli 
2XS Search and Success | São Paulo

Av. Nove de Julho, 3452 - 10° andar – Jardim Paulista
Tel: (+55 11) 2371-0000 – (11) 98918-9277

 

De: Vinicius Carvalho Marques [mailto:notifications@github.com] 
Enviada em: quinta-feira, 24 de agosto de 2017 13:49
Para: CocoaHeadsBrasil/vagas <vagas@noreply.github.com>
Cc: mariliafranguelli <marilia.gabriela@2xs.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [CocoaHeadsBrasil/vagas] [SP - Alphaville] Cielo - Desenvolvedor iOS Sênior (#121)

 

A vaga ainda está aberta @mariliafranguelli <https://github.com/mariliafranguelli>  ?
