### ISSUE TITLE
[SP - Alphaville] Cielo - Desenvolvedor Android Sênior

### ISSUE THREAD

**Issue by mariliafranguelli** [CocoaHeadsBrasil/vagas#122]
**Descrição da vaga**
- Análise e desenvolvimento de soluções na plataforma Android;
- Proposição de melhorias tecnológicas e processuais;
- Realização de pesquisas, acompanhando as evoluções e tendências tecnológicas;
- Suportar fábrica externa no desenvolvimento de sistemas.

**Posição**
Pleno/ Sênior

**Tipo de contratação**
Presencial, CLT full.

**Requisitos**
Ampla Experiência em diferentes frameworks de metodologias ágeis (Scrum, Kanban e Lean Thinking);
- Experiência em diferentes técnicas e ferramentas para acompanhamento dos projetos (JIRA);
- Experiência em desenvolvimento ágil, usando técnicas como Behaviour Driven Development (BDD) e Test Driven Development (TDD);
- Experiência, igual ou maior a 5 anos, no desenvolvimento, teste e debug de aplicativos nativos em Android;
- Experiência em integração de apps mobile com webservices e APIs (HTTP based, XML-RPC, JSON ou outros serviços);
- Experiência com Android Studio, Android SDK, gerenciamento de memória, background services, UI layouts e renderização.
- Experiência com o Android Development Guidelines e Android Style Guidelines;
- Experiência nos sistemas Android open-source e as bibliotecas disponíveis;
- Experiência nos protocolos de segurança referentes a mobile;
- Experiência em front-end (HTML5, JavaScript, CSS, entre outras tecnologias);
- Fundamentos sólidos no desenvolvimento de software (algoritmos, estruturas de dados, etc)
- Familiaridade com tendências de desenvolvimento de Android emergentes e Design Patterns;
- Familiaridade com Customer Centric Design;

**Como aplicar**
Interessados enviar currículo para Marília Franguelli (marilia.gabriela@2xs.com.br)

**Contato**
Para dúvidas ou maiores informações sobre a vaga, entrar em contato Marília Franguelli (marilia.gabriela@2xs.com.br)

**Comment by marcelofabri** [comment]
Esse espaço é somente para vagas para iOS.

**Comment by fpg1503** [comment]
Você pode publicar essa vaga no [repositório de vagas Android](https://github.com/androiddevbr/vagas).
