### ISSUE TITLE
Desenvolvedor IOS

### ISSUE THREAD

**Issue by ingridamr** [CocoaHeadsBrasil/vagas#123]
SP - Metrô Conceição

BRQ IT Services

Profissional atuará com o desenvolvimento de aplicativos mobile utilizando IOS.

Desenvolvedor IOS Pleno ou Sênior

CLT Full + Benefícios 

Superior completo ou cursando

Experiência com desenvolvimento de aplicativos IOS.

Temos Assistência Médica, Assistência Odontológica, Vale Refeição, Vale Alimentação, Seguro de Vida e Previdência Privada.

Etapas do Processo: Envio de cv, entrevista de RH e entrevista técnica.

Enviar o cv para iribeiro@brq.com

**Comment by marcelofabri** [comment]
@ingridamr Por favor, formate a vaga conforme nosso template.
