### ISSUE TITLE
Desenvolvedor Android

### ISSUE THREAD

**Issue by ingridamr** [CocoaHeadsBrasil/vagas#124]
SP - Metrô Conceição

BRQ IT Services

Profissional atuará com o desenvolvimento de aplicativos mobile utilizando Android.

Desenvolvedor Android Pleno ou Sênior

CLT Full + Benefícios 

Superior completo ou cursando

Experiência com desenvolvimento de aplicativos Android.

Temos Assistência Médica, Assistência Odontológica, Vale Refeição, Vale Alimentação, Seguro de Vida e Previdência Privada.

Etapas do Processo: Envio de cv, entrevista de RH e entrevista técnica.

Enviar o cv para iribeiro@brq.com

**Comment by marcelofabri** [comment]
Esse repositório não é para vagas Android.

**Comment by Viniciuscarvalho** [comment]
@ingridamr você pode colocar a vaga de Android no devido repositório - https://github.com/androiddevbr/vagas
