### ISSUE TITLE
Desenvolvedor Pleno ou Sênior Android

### ISSUE THREAD

**Issue by ingridamr** [CocoaHeadsBrasil/vagas#125]
SP - Metrô Conceição

BRQ IT Services

Profissional atuará com o desenvolvimento de aplicativos mobile utilizando Android.

Desenvolvedor Android Pleno ou Sênior

CLT Full + Benefícios 

Superior completo ou cursando

Experiência com desenvolvimento de aplicativos Android.

Temos Assistência Médica, Assistência Odontológica, Vale Refeição, Vale Alimentação, Seguro de Vida e Previdência Privada.

Etapas do Processo: Envio de cv, entrevista de RH e entrevista técnica.

Enviar o cv para iribeiro@brq.com

**Comment by fpg1503** [comment]
Esse espaço é somente para vagas iOS. Você pode publicar essa vaga no [repositório de vagas Android](https://github.com/androiddevbr/vagas).
