### ISSUE TITLE
[REMOTO] iOS Developer @brMalls

### ISSUE THREAD

**Issue by atracaoeselecaobrmalls** [CocoaHeadsBrasil/vagas#1250]
## Empresa

 A brMalls é a maior empresa integrada de shoppings do Brasil, com participação em 31 shopping centers, atendendo aos consumidores das diferentes classes sociais no país.

Além de deter participações, somos especializados na administração e comercialização de espaços em nossos shopping centers. Possuímos experiência na gestão de empreendimentos comerciais, e uma rede de relacionamentos com as principais redes varejistas do país, facilitando a comercialização de seus espaços.

Além de movimentar a economia das regiões onde estamos presentes, nós também somos uma rede transformadora capaz de promover, todos os dias, um espaço de convivência, felicidade e oportunidades.

Nossos valores traduzem o nosso jeito de ser:

- Time Excelente: Valorizamos a excelência e a dedicação, reconhecendo via meritocracia a importância de cada um na construção de nosso sucesso.
- Dono: Somos um time apaixonado pelo nosso negócio e trabalhamos com autonomia, simplicidade e espírito empreendedor.
- Colaboração: Somos abertos a ouvir e entender nossos clientes, colaboradores e parceiros, estimulando a integração e a confiança entre todos.
- Cliente: Temos compromisso de servir todos nossos clientes com empatia e integridade.
- Resultados Hoje e Sempre: Trabalhamos pelo presente e pelo longo prazo do nosso negócio, obstinados por resultados sustentáveis que constroem nosso legado.

## Descrição da vaga

- Desenvolver e suportar aplicações para atender às necessidades do negócio;
- Construir um código com qualidade e testável;
- Apoiar na manutenção e evolução da arquitetura dos sistemas;
- Atuar em time ágil e com práticas de engenharia ágil.

## Posição
 Pleno e Sênior (2 vagas)

## Tipo de contratação
CLT

## Requisitos

- Experiência com Swift;
- Conhecimento na composição de apps iOS em estrutura, APIs e performance;
- Conhecimento do ciclo de vida de aplicações e componentes iOS;
- Bom entendimento sobre arquitetura de sistema;
- Experiência com métodos ágeis e práticas de engenharia ágil, como TDD;
- Conhecimento em sistemas de versionamento, preferencialmente o GIT (Git-Flow);
- Conhecimento dos principais frameworks adotados pela comunidade iOS;
- Experiência com testes: importância, propósito e prática;
- Capacidade de produzir código limpo e de fácil manutenção.

Diferenciais:

- Experiência com produtos digitais ou apps de larga escala;
- Experiência com view code;
- Conhecimento em CI/CD/Fastlane.

## Benefícios
- Gympass
- PLR anual
- Assist. Médica
- Assist. Odontológica
- Estacionamento
- Poss. Horário Flexível
- Seguro de Vida
- Vale-Alimentação
- Vale-Refeição
- Vale-Transporte
- Auxílio Farmácia
- Um dia de folga no mês do aniversário
- Parceria com plataforma Psicologia Viva

## Como aplicar
Por favor envie um email para andressa.fonseca@brmalls.com.br com seu CV anexado ou link do perfil no LinkedIn (enviar no assunto: Vaga iOS).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias úteis após cada processo.
E-mail para contato em caso de não haver resposta: atracao.selecao@brmalls.com.br.

**Comment by tozzetti** [comment]
A vaga ainda está aberta ;)
