### ISSUE TITLE
[SP - Vila Madalena] Quanta Brasil- Desenvolvedor iOS Pleno)

### ISSUE THREAD

**Issue by Natassiaperez** [CocoaHeadsBrasil/vagas#127]
## Empresa
Empresa Multinacional Americana, com 40 anos de mercado.
São 14 escritórios divididos entre Estados Unidos, Europa, América do Sul e Asia, 1800 funcionários no mundo. 
Uma Agência full service, que atua na intercessão de tecnologia, design e marketing.

## Descrição da vaga
Desenvolvimento de Software

## Posição
 Pleno e/ou Sênior

## Tipo de contratação
Presencial PJ

## Requisitos
Procuramos devs com conhecimento em Swift (já utilizamos a versão 3), incluindo algumas libs:
- RxSwift
- Realm
- Padrão de desenvolvimento MVVM
É necessário um cuidado/atenção com a questão visual (aparência) no desenvolvimento de softwares.
Os projetos que trabalhamos costumam ser complexos, o cuidado com o produto final (usabilidade, performance, aparência, funcionalidade) é fundamental.

## Como aplicar
Encaminhar currículo/Portfólio para nperez@quanta.com

## Contato
nperez@quanta.com / 11 9 7690 6966

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @Natassiaperez ?
