### ISSUE TITLE
[SP - Vila Guilherme] LuizaLabs - Magazine Luiza - Desenvolvedor iOS todos os níveis

### ISSUE THREAD

**Issue by yuriferretti-luizalabs** [CocoaHeadsBrasil/vagas#128]
## Empresa
Iniciado no núcleo de Pesquisa e Desenvolvimento do Magazine Luiza, o Luizalabs é um laboratório de Tecnologia e Inovação que tem como objetivo criar produtos e serviços com foco no varejo, oferecendo aos clientes mais benefícios e uma melhor experiência de compra.

## Descrição da vaga

Buscamos desenvolvedores iOS que queiram fazer parte do nosso time no escritório de São Paulo e que sejam apaixonados por Mobile e aplicações de alta performance; que estejam dispostos a fazer experimentações em larga escala e utilizar a nossa grande base de clientes para testar e amplificar o impacto de nossas ações.

Temos grande autonomia e responsabilidade, somos multidisciplinares, autogerenciáveis e com pouca burocracia no nosso cotidiano, lutando para sempre romper barreiras que diminua nossa capacidade de agregar valor ao negócio. Fazemos entregas frequentes e agimos rapidamente ao encontrar problemas; nosso ritmo é acelerado mas temos tranquilidade para planejar e executar nossas tarefas com qualidade.

Estamos localizados na zona norte de São Paulo na Vila Guilherme e temos um time com grande engajamento, com muita vontade de melhorar a experiência de nossos consumidores e com muito bom humor para encarar as adversidades que existem no caminho.

Experiência com Desenvolvimento iOS é o que buscamos mas para nós é igualmente (ou mais) importante que você seja apaixonado pelo que faz e goste de compartilhar o que conhece; que tenha uma cabeça de aprendiz pois aqui sempre temos algo a aprender uns com os outros, não importa o nível de maturidade ou experiência. Se você se identificou com esse perfil, inscreva-se e nós entraremos em contato! Seja bem vindo!

## Posição
Todos os níveis

## Tipo de contratação
CLT presencial

##### Obrigatórios

* Swift, Objective-C, Restful APIs

* Versionamento (GIT preferencialmente)

* Gerenciamento de dependências com Cocoapods

##### Desejáveis

* Metodologias Ágeis
* Testes Automatizados (XCTest ou Quick)

##### Diferenciais

* Programação reativa

* Testes de UI usando XCUITests ou KIF

* Experiência com Continuos Integration (Travis-CI)

* Conhecimento em outros modelos de arquitetura (por ex: MVVM, VIPER, RIBLET, VIP)

* Automação de CI/CD usando fastlane

* Fabric

## Benefícios
* Vale alimentação ou refeição;

* Plano de saúde (Unimed ou Allianz);

* Plano odontológico;

* Academia;

* Estacionamento;

* Bolsa de Estudos;

* Bônus Anual (PLR);

* Ambiente informal.

## Como aplicar 

[![button](https://d3uepj124s5rcx.cloudfront.net/items/411L1F1h3U26260n1g3V/apply-icon.png?v=c3d7c9e7)](https://luizalabs.workable.com/jobs/429030/candidates/new)

## Contato

camila.silva@luizalabs.com

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @yuriferretti-luizalabs ?

**Comment by yuriferretti-luizalabs** [comment]
Está sim @Viniciuscarvalho !!!

**Comment by martinitorquato** [comment]
Vaga aberta? Oo, somente presencial ? @yuriferretti-luizalabs

**Comment by yuriferretti-luizalabs** [comment]
está aberta sim e é presencial @martinitorquato
