### ISSUE TITLE
[SÃO PAULO/REMOTO] Desenvolvedor(a) iOS @ Itaú 

### ISSUE THREAD

**Issue by beabelli** [CocoaHeadsBrasil/vagas#1280]
## Vem ser Itaú! #feitocomvc
Estamos buscando pessoas que queiram se desenvolver e aprender constantemente, compartilhando, colaborando, inovando e entregando valor para todos os nossos clientes.

Para que isso aconteça, temos um time de peso que busca as **melhores tecnologias** e garante que os processos sejam os **mais eficientes**. Quer fazer parte da transformação? Venha conhecer essa e outras oportunidades!

**E a área de Tecnologia?**
Somos uma área que busca ser cada vez mais digital nas soluções, humana na experiência e no contato com as pessoas. Queremos as pessoas inconformadas, as inquietas, as indignadas e apaixonadas por tecnologia. Não queremos você apenas por achar que você tem a nossa cara. Queremos ter um pouco da sua também!

## Descrição da vaga
- Atuar em times ágeis e multidisciplinares;
- Desenvolvimento e ecossistema de mobile para plataformas iOS 
- Atuar na evolução das plataformas considerando reuso e performance dos sistemas;
- Propor soluções técnicas para as necessidades dos time de negócios;
- Acompanhamento de todo o ciclo de desenvolvimento de software (solução, desenvolvimento, implantação);

## Posição
Temos oportunidades para nível **Pleno** e **Senior** ;-)

## Tipo de contratação
Contratação CLT, podendo ser no modelo híbrido (SP) ou full remote.

###### Obrigatórios
- Conhecimentos consolidados em Swift 
- Conhecimento do fluxo de integração contínua e deploy contínuo.
- Conhecimento em execução de code-reviews
- Conhecimento qualidade e testes (Ex: Teste unitários, testes integrados, testes funcionais e testes automatizados);
- Conhecimento em arquitetura de aplicativos mobile (MVC, MVP, MVVM);
- Conhecimento com Git e funcionamento Git Flow;

###### Desejáveis
- Construção de esteiras de CI/CD (Ex: Jenkins, Sonar, Fortify, Puppet ).
- Vivência em ambiente Ágil e DevOps;
- Visão de arquitetura de software e melhores práticas de mercado;

###### Diferenciais
- Conhecimento em Cloud
- Conhecimento em SRE
- Microserviços e API

## Benefícios

- Vale Transporte 
- Vale Refeição (Restaurantes) / Vale Alimentação (Supermercados)
- Convênio médico e odontológico
- Seguro de Vida
- PLR (Mediante resultados do banco)
- Previdência privada
- Descontos exclusivos em nossos produtos financeiros
- Licença maternidade estendida
- Auxílio Creche / Babá (para papais e mamães)
-  Incentivo a estudos
-  Gym Pass (Mas se preferir temos Bio Ritmo em alguns polos)
-  Acesso aos Clubes Itaú (Guarapiranga / Itanhaém e São Sebastião)
+ Algumas vantagens que você pode conhecer durante o processo 😊

## Como aplicar
Caso tenha interesse, você pode se candidatar em nossas vagas via Linkedin ou em nosso banco de talentos da 99jobs!
- Itaú e Redecard: https://www.linkedin.com/jobs/view/2597302741/?capColoOverride=true
- Iti (conta digital do Itaú): https://www.linkedin.com/jobs/view/2669315748/?capColoOverride=true

- Candidatura via 99jobs: https://99jobs.com/itau-unibanco/jobs/148729-banco-de-talentos-frontend-mobile-qa-e-projetos?preview=true

## Contato
Recruiters:
Bea | beatriz.bellinetti@mailer.com.br
Gi Leo | giovana.guimaraes@itau-unibanco.com.br

**Comment by manomano157** [comment]
Op
