### ISSUE TITLE
Vaga removida

### ISSUE THREAD

**Issue by alelealmeida** [CocoaHeadsBrasil/vagas#129]
Vaga removida por ferir regras de uso

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @alelealmeida ?

**Comment by alelealmeida** [comment]
Olá Vinícius,

 

                Sim, ainda estamos aguardando.

 

 

Atenciosamente,

 


  <http://www.faap.br/msexch/assin_diretoria_70m.jpg> 

Alexandre Almeida
Informática - Sistemas 

 <mailto:aalmeida@faap.br> aalmeida@faap.br 
Tel.: +55 11 3662.7185

As informações da mensagem e anexos são confidenciais, de uso exclusivo das partes e contêm assuntos privados. É ilegal sua utilização por pessoas não autorizadas. Desconsidere e apague se não for o destinatário. 
This e-mail and any files transmitted with it contain confidential information. It is solely for use by the individual for whom it is intended. Its use is illegal for unauthorized persons. If you received this e-mail in error, please, delete it from your system.

 

De: Vinicius Carvalho Marques [mailto:notifications@github.com] 
Enviada em: sexta-feira, 25 de agosto de 2017 09:49
Para: CocoaHeadsBrasil/vagas
Cc: alelealmeida; Mention
Assunto: Re: [CocoaHeadsBrasil/vagas] [SP - Pacaembu] - FAAP - Desenvolvedor Mobile IOS (#129)

 

A vaga ainda está aberta @alelealmeida <https://github.com/alelealmeida>  ?

**Comment by reprotector** [comment]
Vaga removida por ferir regras de uso - #226
