### ISSUE TITLE
[São Paulo] - Desenvolvedor iOS Sênior - Concrete Solutions

### ISSUE THREAD

**Issue by talesp** [CocoaHeadsBrasil/vagas#13]
## Descrição da vaga

Participar de equipe mobile com desenvolvimento na plataforma iOS.
## Local

Escritório São Paulo - Próximo a Berrini
## Requisitos

É necessário apresentar os seguintes conhecimentos:
- Controle de versão distribuído (git e/ou hg)
- Cocoapods para gerenciamento de dependências do projeto
- Sólido conhecimento em Objc, orientação a objeto e design patterns
- Integração com APIs RESTful e/ou Webservices
- Familiaridade com o Xcode
- Familiaridade com componentes de User Interface do iOS
- Familiaridade com storyboards, xibs, autolayout
- Adaptação de layouts entre iPhone/iPad
- Conhecimento das guidelines de design e de desenvolvimento da Apple
- Conhecimento de metodologias ágeis (Scrum e XP)
- Experiência com testes em iOS
- Fluência em inglês (leitura técnica)
## Pontos extras:
- Frameworks de teste kiwi , Expecta , specta , etc
- Continous Integration Bots , jenkins , etc
- Swift
- Criptografia e segurança
## Escolaridade:

Ter cursado ou estar cursando nível superior na área tecnológica.
## Como se candidatar

Por favor envie um email para recrutamento@concretesolutions.com.br

**Comment by Viniciuscarvalho** [comment]
Opa @talesp a vaga ainda está aberta? Se for o caso de já ter sido preenchida, poderia fechar a issue 👍

**Comment by talesp** [comment]
Opa, desculpa, só vi agora. Vaga ainda aberta (ta difícil contratar 😭)

**Comment by talesp** [comment]
Atualizando algumas infos e adicionada a opção de pleno - temos vagas nos dois níveis

**Comment by reprotector** [comment]
@talesp Já fecharam as vagas? Pode fechar a issue?

**Comment by talesp** [comment]
Já contratamos, mas ainda temos vaga aberta. Na verdade temos para nesses níveis agora também em BH, e no RJ tem vaga pra JR/PL/Sr

**Comment by talesp** [comment]
dando um up porque ainda estamos precisando, senior pra SP, PL e SR pra RJ, e todos os níveis pra BH :D

**Comment by talesp** [comment]
Continuamos com vagas abertas, agora também em Recife :D
