### ISSUE TITLE
[SP - Centro] KickSIM - Desenvolvedor iOS Júnior

### ISSUE THREAD

**Issue by jaqueventurim** [CocoaHeadsBrasil/vagas#132]
## Empresa
KickSIM - startup de roaming celular grátis. Nós encaminhamos as suas ligações para o número internacional sem o custo de roaming.
Nossa sede é no Vale do Silício e a equipe do Brasil trabalha em SP/São Paulo.

## Descrição da vaga
Nós da KickSIM estamos procurando uma(um) desenvolvedora(desenvolvedor) pra fazer parte do nosso time em crescimento. Queremos alguém apaixonado pelo o que faz, motivado a resolver problemas e um bom comunicador com os colegas de trabalho.
Você vai ser responsável pelo nosso app da loja da Apple e vai ter o espaço de crescimento como profissional para testar e falhar rápido. Nós trabalhamos com Lean Startup onde falhar é um ótimo aprendizado!
Nosso trabalho consiste em entregas semanais e você será cobrado por isso e não pelos dias trabalhados na semana. Nós encorajamos o trabalho remoto e temos a preferência de quem mora na cidade de São Paulo.
Habilidades requeridas

## Posição
Júnior :)

## Tipo de contratação
A combinar

###### Obrigatórios
Conhecimento de swift
Publicado ao menos um app na App Store
Experiência com linguagens web
Conhecimento de metodologias ágeis

## Benefícios

- R$ 2.500 após o período de experiência. Durante a experiência (90 dias) ajuda de custo de R$ 1.200,00.
- Aprendizado 
- Ótimo ambiente de trabalho
- Contato direto com o CEO da empresa
- Chance de crescimento

## Como aplicar
Entre nesse link (http://www.kicksim.com.br/jobs/) e faça o cadastro :)

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @jaqueventurim ?
