### ISSUE TITLE
[REMOTO] Desenvolvedor iOS [Junior] | STANT

### ISSUE THREAD

**Issue by RosannePlech** [CocoaHeadsBrasil/vagas#1329]
> ### Requisitos:

Formação superior em andamento em Sistema de Informação, Análise de Sistemas, Ciências da Computação ou áreas afins;
Inglês básico;
Conhecimento básico em programação e desenvolvimento de sistemas;
Conhecimento intermediário em Swift;
Conhecimentos básicos no framework IOS;
Experiência com GIT;
Experiência no consumo de API's REST;
Noções de TDD (Desenvolvimento guiado por testes).
Desejável: Conhecimento básico em Metodologia Ágil (SCRUM). 

> ### Benefícios

🥗VR ou VA (Cajú Benefícios)
🚗VT ou Vale Mobilidade (Caso escolha modalidade Presencial)
🕐 Flexibilidade de horário
🎈Day off de aniversário
😃Time colaborativo
✅Ótimo ambiente para trabalhar
📱Modelo de trabalho remoto ou presencial (Maceió-AL)

> ### Contratação
PJ.

> ### O Stant
Somos o Stant, uma plataforma SaaS (Software como Serviço) nas versões Web e Mobile de gerenciamento de obras que está revolucionando o mercado da Construção Civil.
Nosso time é formado por profissionais experientes em diferentes áreas, verdadeiros amantes da tecnologia e engenharia, apaixonados por superar expectativas. 
Contamos com a inovação e velocidade de uma startup para oferecer aos nossos clientes uma experiência diferenciada para acompanhamento e gestão de obras.

Vamos juntos? 🤝🚀🧡

> ### Como se candidatar 
Para se candidatar e / ou saber mais sobre a vaga, acesse: https://jobs.solides.com/stant/vaga/95991

**Comment by diegoiosdev** [comment]
Boa tarde , ainda esta avaliando os candidatos para esta vaga ?
