### ISSUE TITLE
Vaga   Desenvolvedor IOS (remoto)

### ISSUE THREAD

**Issue by cimerio** [CocoaHeadsBrasil/vagas#1338]
Desenvolvedor IOS- PJ- Remoto
Valor PJ 95 a 120 a  hora- CV para recrutamento@iventis.com.br
Sólidos conhecimentos em Swift , arquiteturas MVVM / VIP / Clean
CocoaPods, Carthage e SPM ,Clean Architecture, SOLID e boas práticas de desenvolvimento ,programação reativa (RxSwift, RxCocoa, Reactive Swift)
Ter trabalhado com pelo menos um app que tenha sido publicado na AppStore

**Comment by diegoiosdev** [comment]
Boa tarde , ainda esta avaliando os candidatos para esta vaga ?
