### ISSUE TITLE
[SP - Água Branca] AMARO - Mobile Lead Developer

### ISSUE THREAD

**Issue by icefall** [CocoaHeadsBrasil/vagas#134]
## Empresa
AMARO is an online women's fashion brand based in São Paulo. We monthly launch new collections with the latest international trends at disruptive prices, delivered speedily and in style. Through technology, vertical integration and omni-channel distribution, AMARO is changing the way Brazilians consume fashion. www.amaro.com

## Descrição da vaga
AMARO is looking for a talented iOS Mobile Lead to manage and develop our iOS and Android apps, leveraging our e-commerce platform's JSON API. The ideal candidate has solid experience in iOS development.

This is a highly analytical role that requires a driven, self-reliant and generalist hacker.

## Posição
Lead

## Tipo de contratação
CLT

###### Obrigatórios
- Professional or academic experience in software development
- Management and leadership experience
- Knowledge in software engineering best practices and trends
- Extensive knowledge in iOS and Android software development
- Advanced level of English

###### Responsabilidades
- Manage the software development of AMARO's Android and iOS apps
- Lead the mobile team
- Hands-on manager, doing programming work in either iOS, Android or both
- Manage product roadmap for both apps

###### Personalidade
- Highly analytical and focused
- Passion for technology, e-commerce and startups
- Entrepreneurial, driven and proactive
- Excellent technical communication skills

## Benefícios
Meal Allowance or Dinning Hall
Transportation allowance or parking lot
Health Insurance Amil
GymPass
Discount on Amaro products
More stuff...

## Como aplicar e contato
Email: carl.brusell@amaro.com

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @icefall ?

**Comment by icefall** [comment]
@Viniciuscarvalho está sim. Só mandar o currículo pro email. :)
