### ISSUE TITLE
[Remoto] Desenvolvedor (a) iOS

### ISSUE THREAD

**Issue by Grupo-Dream-Work** [CocoaHeadsBrasil/vagas#1344]
## Pré-requisitos para candidatura:

- Relevante experiência hands-on com Swift 5+ e desenvolvimento iOS;
- Conhecimento de Design Patterns, Orientação a Objetos, Clean Code e boas práticas de programação;
- Conhecimento de versionamento utilizando GitFlow;
- Testes unitários;
- Integração com Apis REST.

## Desejável, mas não eliminatório:

- Conhecimento de Auto-Layout, utilizando XIB, ViewCode, Storyboard;
- Modularização de componentes e código;
- Conhecimento de testes instrumentados;
- Conhecimento em SOLID;
- Utilização de Cocoapods.

## Diferencial:

- Automação com CI/CD;
- Banco de dados local (CoreData, Realm, Keychain…);
- Automação de testes em Appium;
- Gerenciamento de memória.

## Contratação

**PJ** 

## Como se candidatar

**Por favor envie um email informando sua pretensão salarial para leandro.lemos@grupodreamwork.com.br com seu CV anexado - enviar no assunto: [Remoto] Desenvolvedor (a) iOS**

**Ou candidatar-se através do link: https://jobs.recrutei.com.br/grupo-dream-work/vacancy/15802-dw1218-desenvolvedor-a-ios**

**Comment by diegoiosdev** [comment]
Boa tarde a vaga ainda em disponível ?
