### ISSUE TITLE
[REMOTO] Popcode Mobile - Dev iOS Júnior/Pleno

### ISSUE THREAD

**Issue by lisandrabarreto** [CocoaHeadsBrasil/vagas#1345]
## Nossa empresa 🌈

A Popcode é uma startup brasileira criada para explorar um novo e eficaz canal de comunicação e espaço de mídia, através da criação de aplicativos personalizados para dispositivos iOS (iPhone, iPad e iPod Touch) e Android (smartphones e tablets).

Criamos aplicativos sob medida, moldando-o de acordo com suas necessidades e usando todos os recursos necessários do aparelho. Focados no desenvolvimento de aplicativos, com mais de 1 milhão de usuários ativos e com clientes do ramo financeiro. Fornecemos aplicativos para bancos, fintechs e empresas de cartão de crédito. Em 2019 crescemos cerca de 40% e em 2020 dobramos de tamanho.

## Descrição da vaga ✍️

Nessa posição você será responsável por toda a arquitetura, desenvolvimento, manutenção e planejamento da vida útil dos projetos iOS. Poderá definir metodologias e tecnologias que desejar, entretanto deve garantir a operação e evolução constante dos projetos desenvolvidos.

## Posição 🚀
 
- Dev. iOS Júnior ou Pleno

## Tipo de contratação 📌
 
- Remoto, CLT ou PJ

###### Obrigatórios

- Experiência em Desenvolvimento de Apps Nativos com Swift (IOS)
- Experiência com integração com APIs REST
- Experiência com MVVM
- Controle de Versão com Git
- Boas práticas de UI/UX
- Ter trabalhado em algum aplicativo publicado em alguma loja.

###### Desejáveis

- Conhecimento com tecnologias Nativas (Android ou iOS).
- Ter participado de projetos com metodologia Ágil;

## Benefícios  🌴

**CLT:**

- Plano de saúde e dental após 3 meses;
- Day Off no mês do aniversário;
- Reembolso de certificações e treinamentos;
- Participação do programa de Gamificação para prêmios;
- Vale alimentação;
- Auxílio home-office;

**PJ:**

- Férias remuneradas;
- Day Off no mês do aniversário
- Reembolso de certificações, além de acessos em plataformas de treinamentos;
- Participação do programa de Gamificação para prêmios;
- Auxílio home-office

## Como aplicar 🤗

Topa um novo desafio? Você pode enviar o seu currículo para o nosso e-mail queroser@popcode.com.br, não esquece de indicar a área de interesse no assunto, fechado? Sempre bom enviar o seu Portfólio e/ou Github junto.

## Contato 📩

E-mail para contato em caso de não haver resposta: lisandra.barreto@popcode.com.br

**Comment by diegoiosdev** [comment]
Boa tarde a vaga ainda esta disponível ?

**Comment by MarSYs1** [comment]
Bom dia !!
A vaga ainda esta aberta ?
