### ISSUE TITLE
(Remoto) Desenvolvedor(a) IOS JR  na Iventis

### ISSUE THREAD

**Issue by cimerio** [CocoaHeadsBrasil/vagas#1348]
Desenvolvedor (a) Ios Jr - PJ
CV para recrutamento@iventis.com.br

Estudando desenvolvimento de sistemas, ciência da computação, engenharia da computação, áreas afins; 
Conhecimento em lógica de programação e em Orientação Objeto
Conhecimento Básico de Autolayout ,Swift , git
Se já tiver alguns conhecimento em iOS....melhor ainda

**Comment by diegoiosdev** [comment]
Boa tarde , a vaga ainda esta disponível ?

**Comment by MarSYs1** [comment]
Bom dia , a vaga ainda esta disponível ?
