### ISSUE TITLE
[SP - Bosque Saúde] LittleBoat - Desenvolvedor iOS e Android

### ISSUE THREAD

**Issue by tolitola** [CocoaHeadsBrasil/vagas#136]
## Descrição da empresa
 A LittleBoat é uma empresa de desenvolvimento de soluções utilizando tecnologia de ponta. Temos expertise em desenvolvimento de apps, games, VR, AR, beacons, kinect, etc.

## Descrição da vaga
Estamos em busca de um novo talento em desenvolvimento de Games e Aplicativos
Requisitos:
 - Formação superior em Ciência da Computação ou similares, ou experiência de trabalho equivalente
 - 4+ anos de experiência trabalhando com desenvolvimento de Aplicativos iOS ou Android ou utilizando ferramenta Unity3D
 - Sólidos conhecimentos em orientação a objetos, engenharia de sistemas, estrutura de dados e algoritmos
 - Desejável conhecimento na plataforma Xamarin ou Unity3d

## Posição
 Desenvolvedor pleno ou senior

## Tipo de contratação
Contratação inicial PJ
Trabalho no local (SP - bosque da saúde)

## Benefícios
 - Possível home office 1 ou 2 vezes por semana
 - Vale transporte e refeição
 - Férias remuneradas

## Contato
Para maiores informações ou envio de currículo, entrar em contato no email: 
contato@littleboat.com.br

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @tolitola ?

**Comment by tolitola** [comment]
Olá @Viniciuscarvalho , a vaga já foi preenchida. 
Grande Abs!
