### ISSUE TITLE
[São Paulo, SP] React-Native Developer (with Native iOS Expertise)

### ISSUE THREAD

**Issue by nic** [CocoaHeadsBrasil/vagas#138]
## Empresa
ABOUT QUANTO

Our small businesses are moving faster than banks and governments, which hold back our economic engine. Quanto turns delay into growth to move our economy forward.

We’re reinventing the banking experience for those who venture, innovate and flourish, by bringing design, technology and transparency to the companies and entrepreneurs we admire.

Our first step is the ContaQuanto, a current account solution that modernizes the SME’s day-to-day finance. Quanto is the first “fintech” in Brazil with a full-stack partnership with one of Brazil’s premier banks to deliver business banking services, providing Quanto with unique access to the financial system while maintaining the agility and culture of a start-up.

At Quanto you will get to deploy your code into products that are relevant from day one as part of a team that is impact-driven and committed to building a modern, just and accessible financial system.

## Descrição da vaga
Our challenge is to build a full-featured business banking system with a reliable, scalable core that serves applications that are beautiful and intuitive. We want our entrepreneurs to spend less time managing, and more time growing.

This is where you come in.

You’ll work with our design team implement mobile applications using React Native. You’ll collaborate closely with our back-end team, using GraphQL and Relay. We are passionate for elegant interfaces and totally obsessed for simplicity in user experience.

We value above all your intellectual curiosity, resilience in the face of unexpected challenges and your ability to perform or coordinate with several different roles within our team (Dev, Design, UI, UX).

## Posição
Pleno or Senior

## Tipo de contratação
Presencial
CLT or PJ (negotiable)

###### Obrigatórios
Experience and excellence at:
- Javascript (ES6)
- Native framework (React Native)
- Data-drive framework (Relay)
- Query language API (GraphQL)
- Responsive interface (Flexbox)
- Cross-device compatibility testing

###### Desejáveis
- Modern UX tools (Sketch, Envision)
- UI concepts and standards (Material)
- Test-driven development (Jest)
- Internal tools (Git, Slack, Raygun, Loggly, CircleCI)

###### Diferenciais
- Native iOS (Swift, Objective-C)
- Native Android (Kotlin, Java)

## Benefícios
- Standard benefits such as health insurance and meal-tickets.
- “Build your own rig”
- Flexible working hours, focused on deliverables
- Internal workshops and subsidies for external workshops and conferences
- Modern working environment in Pinheiros, with shower/bike rack and within walking distance to the subway

## Como aplicar
Please apply in https://quanto.workable.com/jobs/448526

**Comment by joelwallis** [comment]
Eu vi ES8 ali? ES8???

**Comment by lucasferreira** [comment]
O cara viajou no tempo, para o futuro, adquiriu experiência em ES8 e voltou de volta ao passado para se candidatar a esta vaga.

**Comment by joelwallis** [comment]
3-5 anos de experiência em React e React Native 😆 

Cara, a primeira versão estável do React não tem nem um ano (ver [v15.0.0](https://github.com/facebook/react/releases/tag/v15.0.0)) e o [lançamento do projeto foi em Maio de 2013](https://github.com/facebook/react/releases/tag/v0.3.0). Como que uma pessoa teria cinco anos de experiência em tecnologias recém-lançadas?

PS: [React Native ainda não tem stable releases](https://github.com/facebook/react-native/releases) e [o primeiríssimo lançamento foi em Fevereiro de 2016](https://github.com/facebook/react-native/releases/tag/v0.20.0-rc).

**Comment by joelwallis** [comment]
Caramba, alguém está apagando os comentários! 😆  Genial! Mas lembro que todos que deram Watch no repositório recebem notificações de novos comentários.

@nic reveja seu anúncio de vaga de emprego. Se isso foi um erro de redação, corrija-o. Informe os responsáveis que o texto da vaga não faz sentido.

**Comment by marcelofabri** [comment]
@joelwallis Seu comentário aparece aqui ainda 😅

**Comment by marcelofabri** [comment]
Foi mal, vi agora no Slack que tiveram mais dois comentários. Não sei o que aconteceu.

**Comment by nic** [comment]
@joelwallis Sorry. Fixed!

**Comment by nic** [comment]
@marcelofabri Que doidera, aqui só aparece dois comentário do @joelwallis 
Tiveram outros?

**Comment by marcelofabri** [comment]
<img width="757" alt="captura de tela 2017-03-14 as 21 50 19" src="https://cloud.githubusercontent.com/assets/833072/23921810/41274812-0900-11e7-8921-659deb154082.png">

**Comment by joelwallis** [comment]
Obrigado @marcelofabri!

**Comment by nic** [comment]
Conseguimos o cara!! Valew @marcelofabri @joelwallis ;)
