### ISSUE TITLE
Freelancers

### ISSUE THREAD

**Issue by marceloreis13** [CocoaHeadsBrasil/vagas#14]
## Descrição da vaga

Estou montando uma agencia que será especializada em mobiles, onde meus parceiros serao 100% especializados em suas areas, por isso vou trabalhar com fornecedores remotos.
Sempre que houver projetos em mesa, irei passar o escopo para os parceiros/fornecedores, entao vou fazer uma analise de custo/prazo/qualidade para escollher qual parceiro irei repassar o projeto.

## Local

Remotamente

## Requisitos

Obrigatorio
 - Email 
 - Telefone

Desejaveis
 - Perfil Github
 - Portifolio

Desejáveis
- Desenvolvimento em Swift 2.0

## Contratação

PJ a combinar

## Nossa empresa

http://migre.mobi

## Como se candidatar

Por favor envie um email para contato@migre.mobi com o titulo: Dev iOS e com os dados solicitados em ##Requisitos

**Comment by ronanrodrigo** [comment]
@marcelloreis tentei enviar um e-mail pra contato@migre.mobi mas ele retornou

**Comment by lgcassab** [comment]
Seu email <contato@migre.mobi> não está operacional.

**Comment by Viniciuscarvalho** [comment]
@marcelloreis esse trabalho já foi preenchido? Caso sim, poderia fechar a issue 👍

**Comment by klevison** [comment]
Creio que essa vaga já era. E-mail voltando.
