### ISSUE TITLE
Programador IOS Pleno

### ISSUE THREAD

**Issue by imangegali** [CocoaHeadsBrasil/vagas#140]
[SP - Metrô Conceição] Empresa BRQ IT Services - Programador IOS Pleno
BRQ - Consultoria de TI de grande porte - www.brq.com 
Posição: Pleno
Tipo de contratação: CLT 
Requisitos: Superior completo ou cursando na área de T.I desenvolvimento e experiêcia com Programação IOS Objetive C.
Obrigatórios: IOS
Desejáveis: não possui.
Diferenciais: ter atuado em instituições financeiras.
Benefícios: AM, AO, VR, VA, SV e PP (Previdência privada)
Com quem você vai trabalhar: Trabalhará com a equipe de programadores da BRQ.
Como aplicar: Entrevista de RH e uma entrevista técnica.
Contato: iribeiro@brq.com
Informe aqui os contatos para mais informações: 2526-0582

**Comment by reprotector** [comment]
Segundo aviso: Por favor, siga nosso template. Estou fechando a issue até ela for editada.

**Comment by imangegali** [comment]
Renan,


Boa tarde!


Mas eu segui, como devo colocar as informações? No que estou errando?


Pode me ajudar?


[BRQ - Paixão por transformar tecnologia em eficiência e inovação]

Ingrid A. M. Ribeiro
BRQ – Recrutamento & Seleção
Tel.: (11) 2526-0582

Nossos Valores:
Paixão – Aprendizado – Entrega – Autonomia – Ética – Perenidade

Conheça nossa empresa: Vídeo BRQ<http://www.brq.com/video> e www.brq.com<http://www.brq.com/>




________________________________
De: Renan Protector <notifications@github.com>
Enviado: quarta-feira, 15 de março de 2017 16:09:08
Para: CocoaHeadsBrasil/vagas
Cc: Ingrid Aparecida Mangegali Ribeiro; Author
Assunto: Re: [CocoaHeadsBrasil/vagas] Programador IOS Pleno (#140)


Segundo aviso: Por favor, siga nosso template. Estou fechando a issue até ela for editada.
