### ISSUE TITLE
[Remoto] Estágio iOS Developer

### ISSUE THREAD

**Issue by TacianySouza** [CocoaHeadsBrasil/vagas#1400]
Estamos buscando alguém para trabalhar com desenvolvimento SwiftUI que tenha paixão por novos desafios, com disposição de descobrir e aprender todos os dias; que contribua com o time; que atue com autonomia, usando a liberdade para opinar em processos e questões relacionadas ao cliente quando for preciso.

**Nós te oferecemos:**
- Convênio Médico (sem descontos) 🩺
- Vale Refeição/Ajuda de custo🍽
- Descanso Remunerado 🏝
- Bônus Anual 💸
- Horário flexível 😎
- 40h semanais 😍
- E claro, home office 🧡

Aqui você vivenciará uma cultura de desenvolvimento, dinâmico, colaborativo, gestão horizontal e com um ótimo relacionamento entre colegas e clientes.

Link para inscrição: https://forms.office.com/Pages/ResponsePage.aspx?id=xhswl7-qE0KxQOlXRIjyUtWHnATkYhRFqpMUj0vZZr5UNlpUUEhWME5GT0FDQzBEUElDVFgwQThJWC4u

**Comment by Vivianemelos** [comment]
Ola, boa noite. Voces oferecem o computador?

**Comment by diegoiosdev** [comment]
Bom dia a vaga foi preenchida ?
