### ISSUE TITLE
[BRASIL - Remoto] Picpay - Desenvolvedor Sênior/Especialista iOS 

### ISSUE THREAD

**Issue by bananajobs** [CocoaHeadsBrasil/vagas#1402]
O time da Picpay Store tem o propósito de criar uma plataforma de integração, gestão e crescimento para grandes marcas dentro do ecossistema do PicPay. Trabalhando para construir as tecnologias do futuro, esse time tem como objetivo construir um novo conceito de compra, venda e consumo de serviços. 

Requisitos e qualificações: 
Atuação com as seguintes ferramentas:
Swift;
Experiência com Objective-C
REST APIs;
Autolayout com xib, storyboard e/ou ViewCode;
Noções de arquitetura (MVVM, Viper, e etc);
Testes automatizados;
Ferramentas de controle de versão (Git);
Gerenciamento de dependências.

Responsabilidades e atribuições: 
Desenvolver soluções escaláveis e que irão ser utilizadas por milhões de usuários;
Apresentar melhorias nos fluxos atuais do produto e garantir qualidade nas entregas;
Autonomia no desenvolvimento e manutenção dos sistemas.

Se você acredita que se encaixa no perfil desejado, por favor aplique :) 
https://jobs.lever.co/bananajobs/eb7a0e83-8584-4f96-a3ef-c460860cafed?lever-origin=applied&lever-source%5B%5D=GitHub

**Comment by Viniciuscarvalho** [comment]
Por favor, descrever a vaga de acordo com o modelo, faltam informações se é remoto, CLT...
