### ISSUE TITLE
[Amsterdã] Siilo - iOS Engineer

### ISSUE THREAD

**Issue by peagasilva** [CocoaHeadsBrasil/vagas#1403]
## Empresa
[Siilo](https://www.siilo.com) is a secure medical communication app designed for healthcare professionals. Every day, almost 400,000 healthcare professionals use Siilo to discuss and coordinate patient care with colleagues both within and beyond their organisational walls. Today, Siilo is the largest medical network in Europe. 

At Siilo, we believe that by connecting modern healthcare professionals, simplifying their workflows, and democratising access to expertise and experience, we can improve their quality of life and, ultimately, patient care worldwide.

## Descrição da vaga
We're seeking an iOS Engineer to support our secure messenger and knowledge-sharing platform. As a member of our iOS team, you'll be leveraging the latest tools to maintain and develop our industry-leading app, which thousands of healthcare professionals rely on every day. Along with contributing code, you'll also have the opportunity to evaluate and shape our constantly-evolving work processes alongside the rest of our small but talented engineering team.

## Posição
This role is for a medior or senior engineer.

## Tipo de contratação
Apesar de estarmos trabalhando de forma remota desde o início da pandemia, a vaga é híbrida assim que a situação permitir. A Siilo é Visa Sponsor, mas é necessário realocar pra Amsterdã.

###### Obrigatórios
- 3+ years of experience with iOS development; fluency in Swift and comfort using UIKit, SwiftUI, RxSwift, and Combine
- You're passionate about writing clean, tested, and well-documented code
- You are willing to always discuss new ideas and approaches to solve problems. You understand that the technologies surrounding iOS development are always evolving and you are eager to learn, code, and share new solutions with your colleagues
- You love to work collaboratively. You understand that the whole is greater than the sum of the parts
- You're comfortable with using 3rd-party libraries and dependency managers (we use CocoaPods and SPM)
- Fluent in English; Dutch is not necessary

###### Desejáveis
- Reactive programming (we use RxSwift and are moving our project to Combine)
- Cryptography
- Secure storage of data (keychain, encrypted database, data protection)
- Delivering universal apps
- Contributing to open-source projects
- Modularized projects
- Circle CI and/or fastlane tools

## Benefícios
- The freedom to work how you work best - we have a relaxed but very ambitious company culture
- Flexible working hours - we believe in having a great work/life balance
- A great office in the middle of the Amsterdam canals
- Learning & development budget + flexible time to learn - if you’re not learning, we’re not developing as a company, so choose what you want to learn and share as a team!
- 24 days of annual leave per year (and the ability to accrue more days on your Siilo anniversary!)
- 4 weeks to work remotely from wherever you want
- Annual mental health + physical health allowance
- Summer hours
- Team creativity budget for bonding with your amazing colleagues

## Com quem você vai trabalhar
A small, but very talented (and friendly!) team

## Como aplicar
Você pode se aplicar [aqui](https://jobs.lever.co/siilo/66baa1ea-f2e5-432e-bde2-85b6faf2f282).

## Contato
[Aqui no site da vaga](https://jobs.lever.co/siilo/66baa1ea-f2e5-432e-bde2-85b6faf2f282) ou pode entrar em contato a Samantha: srao [at] siilo [dot] com

**Comment by marceloreis13** [comment]
Is this position active? 'Coz the link for apply is broken

**Comment by peagasilva** [comment]
Hi @marceloreis13, thanks for the heads up. The opening is now closed. Cheers!
