### ISSUE TITLE
iOS Developer

### ISSUE THREAD

**Issue by renatasaranz** [CocoaHeadsBrasil/vagas#1427]
## Empresa
 Tech For TI
Consultoria de Tecnologia da Informação, há 13 anos no mercado e especializada em soluções inteligentes e referência na entrega de serviços de alta qualidade.

## Descrição da vaga
Oportunidade para Desenvolvedor (a) iOS
100% home office.
Requisitos imprescindíveis: - Mandatório Swif e ter domínio de SOLID/Object Oriented Programming, Clean Code, Clean Architecture; - Familiaridade com Jira, Bitbucket e Confluence.

## Posição
 Posição Pl. ou Sr. (Serão considerados ambos).

## Tipo de contratação
 Remoto Full, PJ - Contrato prazo indeterminado.

## Requisitos
Mandatório Swif e ter domínio de SOLID/Object Oriented Programming, Clean Code, Clean Architecture;
Familiaridade com Jira, Bitbucket e Confluence.

## Benefícios
Informe os benefícios que a empresa oferece

## Com quem você vai trabalhar
Se desejar insira uma lista dos futuros colegas de trabalho. Você pode gerar uma com os usuários do GitHub dos funcionários em http://fpg1503.com/GithubProfileTableGenerator/

## Como aplicar
Enviar CV via email ou whatsapp

## Contato
[rsaranz@techforti.com.br](mailto:rsaranz@techforti.com.br)
📱WhatsApp: (11) 97105-1194

**Comment by Viniciuscarvalho** [comment]
@renatasaranz por favor se possível trazer mais informação sobre a empresa e também sobre os detalhes técnicas para a vaga.

**Comment by renatasaranz** [comment]
OK Vinicius, vou complementar sim. Obrigada.
