### ISSUE TITLE
[GO - Rio Verde] ON GO - Desenvolvedor iOS Swift

### ISSUE THREAD

**Issue by fykos** [CocoaHeadsBrasil/vagas#143]
## Empresa
 O ON GO é um aplicativo de mobilidade urbana, com táxi, mototáxi e motofrete.

## Descrição da vaga
 Desenvolver um aplicativo em Swift baseado no aplicativo já existente em Objective-C.
 Caso conheça alguém, também precisamos de programador Android e Analista/Desenvolvedor WEB PHP/MySQL.

## Posição
 Pleno

## Tipo de contratação
 Presencial, CLT, PJ. 

## Requisitos
 Desenvolvedor de aplicativo nativo em Swift utilizando Xcode última versão.

###### Obrigatórios
 Já possuir um aplicativo em nativo em Swift já publicado na AppStore ou em fase de testes em iPhone.

## Com quem você vai trabalhar
| ![](https://github.com/fykos.png?size=117) | ![](https://github.com/waister.png?size=117) |
| --- | --- |
|[Elis](https://github.com/fykos) |[Waister](https://github.com/waister) |
|Desenvolvedor iOS|Desenvolvedor Android|

## Como aplicar
 Envie um e-mail para ongo-github@elisnunes.com.br

## Contato
 WhatsApp: (64) 99299-4416
 E-mail: ongo-github@elisnunes.com.br

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @fykos ?
