### ISSUE TITLE
[Remoto] Nomo - operadora de celular

### ISSUE THREAD

**Issue by victormendes5** [CocoaHeadsBrasil/vagas#1430]
## Empresa

A Nomo nasceu de uma verdade: com as operadoras de sempre não dá mais. 

Assim nasceu uma operadora sem letras miúdas, simples e digital (como tudo que você gosta). 

A Nomo é diferente porque não temos medo de dizer não ao mercado e o seu modus operandi (operadora) de ser.

Nós oferecemos uma melhor experiência porque procuramos resolver os erros que as operadoras cometem: atendimento demorado (e ineficiente), cobranças indevidas, planos que ficam mais caros ao longo do tempo, aprovações de crédito misteriosas que não dão certo e todo tipo de problema que existe na relação entre as operadoras e seus clientes. 

Como fazemos isso?

Atendimento humano

O atendimento da Nomo é feito diretamente pelo aplicativo, não tem musiquinha, robôs ou nada do tipo. Toda conversa é iniciada com uma pessoa e finalizada com uma pessoa. Atendemos assim porque sabemos que a experiência de esperar e não ter o seu problema resolvido é extremamente frustrante. 

Planos inteligentes

Os planos da Nomo foram criados para que você consiga sempre estar na melhor oferta possível para o seu tipo de consumo. Se você gastou menos do que contratou, indicamos um plano mais barato, se você gastou mais do que contratou e precisou contratar pacotes extras, também vamos te indicar um plano que seja mais adequado para você. Queremos que você só utilize aquilo que é necessário.

Controle de tudo pelo aplicativo da Nomo

No app da Nomo você pode mudar, cancelar ou pausar o seu plano quando quiser, não precisa falar com um atendente ou ligar para uma central de atendimento, basta clicar no seu plano e mudar. Te oferecemos autonomia para que você possa sempre escolher o que é melhor para você. 

Cobertura nacional

A cobertura da Nomo funciona de norte a sul, por isso você não precisa ter medo de ficar sem o seu sinal. Nós alugamos a infraestrutura da Vivo para te proporcionar velocidade e alcance onde for necessário, mas esse é o único vínculo que temos com eles. 

A Nomo está em fase Beta, por isso ao baixar o aplicativo, preencha os dados para entrar na lista de interesse. Caso você seja um cliente selecionado para o Beta, com o chip da Nomo em mãos, você já pode experimentar uma operadora de celular que te coloca nos planos. Mais do mesmo nunca mais: vem pra Nomo!

## Descrição da vaga

Ajudar na construção e no desenvolvimento de um aplicativo incrível, que vai auxiliar nossos clientes no dia a dia a terem uma experiência descomplicada e simples, nunca antes vista no mercado de telecom.

## Posição

Junior/Pleno

## Tipo de contratação

CLT ou PJ

###### Obrigatórios

- Utilizar Swift;
- Versionamento de código em alguma plataforma; 
- Utilizar minimamente alguma arquitetura de mercado (MVVM, MVP e etc);
- UIKit/SwiftUI.

###### Desejáveis

- Testes automatizados de qualquer tipo;
- Conhecimento sobre CI/CD;

## Como aplicar

Podem vir falar comigo no slack mesmo @victormendes

**Comment by diegoiosdev** [comment]
Bom dia, a oportunidade  ainda está aberta ?

**Comment by victormendes5** [comment]
Oi @diegoiosdev, bom dia! Ta aberta sim. Me manda um email para a gente conversar, `victor.mendes@nomo.com.br`.

**Comment by diegoiosdev** [comment]
ok , email enviado.
