### ISSUE TITLE
[Rio de Janeiro, RJ] Mongeral Aegon - Desenvolvedor iOS Sênior

### ISSUE THREAD

**Issue by kspedro** [CocoaHeadsBrasil/vagas#145]
## Empresa

![lv1439997712111730](https://cloud.githubusercontent.com/assets/26658870/24308820/467bd67a-10a8-11e7-93e6-7aa89aa9a285.png)

A Mongeral Aegon é uma multinacional que está presente no futuro das pessoas há quase 200 anos, atuando no mercado de Seguro de Vida e Previdência. 

Em 2016, entramos para a lista das 10 Melhores Empresas para se Trabalhar do Rio de Janeiro, pela Great Place to Work. 
Se você está em busca de desafios profissionais, venha fazer parte do nosso time!

## Descrição da vaga
Estamos procurando um desenvolvedor experiente para compor nosso time de iOS, no desenvolvimento de um projeto inovador para o mercado de seguros.
## Posição
 Desenvolvedor iOS (Sênior)

## Tipo de contratação
 CLT

## Requisitos
Experiência em projetos mobile iOS;
Conhecimentos básicos em front-end (HTML, CSS e Javascript);
Conhecimentos de SOA, baseado em REST;
Conhecer e ter experiência com testes unitários, de aceitação, mocks, etc;
Saber escrever um código limpo e legível;
Ter conhecimento de práticas de XP (TDD, pair programming, refactoring, continuous integration, etc);
Experiência com métodos ágeis (Scrum, Kanban, Lean, etc);
Saber trabalhar com ferramentas de controle de versão (Git);
Conhecimentos de design de interface e experiência do usuário;
Experiência em mentoring/coaching de pares e team members menos experientes;
Motivação para aprender e pró-atividade.

###### Diferenciais
Conhecimentos em Android, React-Native, Xamarin;
Conhecimentos de automação de publicação de aplicações (Fastlane, etc);
Versionamento utilizando Git Flow;
Conhecimento em alguma linguagem de desenvolvimento Web server-side (PHP, Ruby, Python, JAVA, .NET, Swift);
Conhecimento de ambientes Linux (instalação, configuração, etc);

## Benefícios
Salário compatível com o mercado;
Plano de Saúde;
Plano Odontológico;
Vale-refeição;
Vale Alimentação;
Vale-transporte;
Auxílio Creche ou babá;
**PLR**;
Previdência Privada;
13º;
Academia;
Café da Manhã;

## Com quem você vai trabalhar
Dentro do Marketing Digital da Mongeral Aegon, junto com o time de Front e Backend, UI e UX.

Estamos no Centro do Rio, pertinho das estações de metrô Uruguaiana e Presidente Vargas.

## Como aplicar
Entrevista com RH e entrevista com a equipe da área.

## Contato
Envie um e-mail com o assunto "Desenvolvedor iOS Sênior" para kpedro@mongeralaegon.com.br

(21) 3722-2635
Karolina Pedro

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @kspedro ?

**Comment by kspedro** [comment]
Olá Vinivius.

Está aberta sim.

Atenciosamente,

Karolina Pedro
Gestão e Performance
+55 21 3722-2635
mongeralaegon.com.br<http://mongeralaegon.com.br/>
facebook.com/mongeralaegon<http://facebook.com/mongeralaegon>

[cid:_1_1A4428901A442070006640758325808F]

De: Vinicius Carvalho Marques [mailto:notifications@github.com]
Enviada em: sexta-feira, 25 de agosto de 2017 09:55
Para: CocoaHeadsBrasil/vagas <vagas@noreply.github.com>
Cc: Karolina Santos Pedro <KPedro@mongeralaegon.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [CocoaHeadsBrasil/vagas] [Rio de Janeiro, RJ] Mongeral Aegon - Desenvolvedor iOS Sênior (#145)


A vaga ainda está aberta @kspedro<https://github.com/kspedro> ?
