### ISSUE TITLE
[Remoto] iOS Developer Sr CLT @ Rightpoint

### ISSUE THREAD

**Issue by larissazz** [CocoaHeadsBrasil/vagas#1462]
## Empresa

Rightpoint, a Genpact company (NYSE: G) is a global experience leader. Over 700 employees across 12 offices work with clients end-to-end, from defining and enabling vision, to ensuring ongoing market relevance. Our diverse teams lead with empathy, data and creativity—always in service of the experience. From whiteboard to roll-out, we help our clients embed experience across their operations from front to back office to accelerate digital transformation through a human-centric lens. Rightpoint has been recognized among the top customer experience consultancies in The Forrester Wave™: Customer Experience Strategy Consulting Practices, Q4 2020.

Are you someone who wants to inspire change in the way business is done? Do you want to work with encouraged and like-minded intrapreneurs? Us too! We take our work very seriously, but we have fun doing it. And we’re searching for passionate, talented people to join the Rightpoint team.

## Descrição da vaga

Rightpoint’s Product Development practice implements custom, dynamic, experience-led applications. We’re looking for iOS developers with strong product mindsets who care about building software that meaningfully connects with people. We value engineering excellence alongside a commitment to helping other team members succeed.
When you join us, you’ll be exposed to a broad variety of exciting technologies and industries (healthcare, mobile, security, Internet of Things, accessibility, and more). We are also passionate about giving back to the community through open-source contributions, hosting events, contributing to conferences, and more.
RightPoint: https://www.youtube.com/watch?v=fnowVfy257k
This role requires you to be able to communicate in English (Verbal and Written). ONLY resumes in English will be considered.

Responsabilidades
-Develop native iOS applications and frameworks using Swift.
-Lead development of world class apps.
-Define and implement robust app architectures and complex user interfaces.
-Apply expert knowledge of iOS system frameworks to solve novel problems.
-Collaborate with designers, engineers, and product managers to build great experiences.

## Posição

Sênior.

## Tipo de contratação

CLT. 

## Requisitos

O que você precisa conhecer
-Develop native iOS applications and frameworks using Swift.
-Lead development of world class apps.
-Define and implement robust app architectures and complex user interfaces.
-Apply expert knowledge of iOS system frameworks to solve novel problems.
-Collaborate with designers, engineers, and product managers to build great experiences.

Pra ter aquela vantagem extra
-Work with BLE, beacons, and connected devices.

## Benefícios

-Medical insurance paid 100% to employees and direct dependents;
-Dental insurance paid 50% to employees and direct dependents;
-Life insurance;
-Meal voucher (1 per business day R$25,00);
-Bus transportation to band 5s who earn up to R$4500,00
-Annual bonus to band 4+ (~11% of annual salary). For band 3 it´s 15%. It´s must be eligible according to the guidelines.
-Monthly variable income compensation (VIC) for band 5s based on the eligibility according to the policy.
-3 PBD or personal business days per year on top of vacations.

## Como aplicar

Saiba mais sobre essa grande oportunidade e se candidate no site (basta fazer login e inserir seus contatos): https://vagas.hunterco.com.br/job/62acca4c143e6b001f3dc776?r=srch&c=4740

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias úteis após cada processo. Depois da candidatura no site, entraremos em contato para alinhamento e marcar entrevista.

**Comment by larissabazzo** [comment]
Vaga aberta ainda!
