### ISSUE TITLE
[REMOTO] Head de Engenharia de Software

### ISSUE THREAD

**Issue by giumandri** [CocoaHeadsBrasil/vagas#1464]
## Empresa

Startup israelense, recém chegada ao Brasil, num momento scale-up muito intenso!

## Posição
 Head of Software Engineering

## Tipo de contratação
Remoto, CLT

###### Obrigatórios
Conhecimento em gestão de equipe;
Conhecimento em AWS;
Sólida experiência com JAVA

###### Diferenciais
Experiência como Tribe Lead

## Benefícios
Pacote de benefícios completo + Bônus anual

## Como aplicar
Caso tenha interesse em conhecer um pouco mais da proposta, por favor, entre em contato comigo através do e-mail giuliamandri@pageexecutive.com :)

**Comment by thiagodelmotte** [comment]
@giumandri o e-mail está retornando
