### ISSUE TITLE
[São Paulo] PSMCompany - Desenvolvedor Mobile iOS

### ISSUE THREAD

**Issue by fwfreitas** [CocoaHeadsBrasil/vagas#147]
## Empresa
A PSM Company é uma empresa líder em serviços integrados de Recrutamento e Seleção em TI e Telecom, resultado de mais de 25 anos de experiência profissional. O alicerce de sua sólida história de sucesso está nos diferenciais competitivos como inovação, postura consultiva e excelência operacional.
Presente nos diversos segmentos do mercado, a PSM Company oferece seus serviços nas seguintes áreas de negócios: Professional Services, Hunting, Mapeamento Comportamental de Profissionais e Equipes e o Portal online, daRHwin, com soluções únicas em Gestão de Recursos Humanos.

## Descrição da vaga
Estamos em busca de um Desenvolvedor IOS para atuação em uma empresa multinacional Italiana de meios de pagamentos.

## Posição
Desenvolvedor IOS Pleno

## Tipo de contratação
Contratação CLT Full mais benefícios

## Requisitos
Experiência com desenvolvimento de aplicativos nativos para IOS
Experiência com Objective C ou Swift
Conhecimento em banco de dados

###### Diferenciais
Diferencial conhecer frameworks híbridos ou android

## Benefícios
Vale Refeição
Assistência Médica
Seguro de Vida
Convenio Odontológico
Convênio Farmácia
Vale transporte
Cartão GoodCard
Parcerias com universidades e escolas de idiomas
PLR

## Como aplicar
Interessados encaminhar currículo com pretensão salarial para francisco.freitas@psmcompany.com.br

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @fwfreitas ?

**Comment by fwfreitas** [comment]
Olá Vinicius, desculpa a demora!

 

A vaga foi cancelada, vou cancelar no sistema.

 

Qualquer dúvida, à disposição.

 

Atenciosamente,

 

Descrição: Francisco Freitas (2)

 

De: Vinicius Carvalho Marques [mailto:notifications@github.com] 
Enviada em: sexta-feira, 25 de agosto de 2017 10:00
Para: CocoaHeadsBrasil/vagas
Cc: fwfreitas; Mention
Assunto: Re: [CocoaHeadsBrasil/vagas] [São Paulo] PSMCompany - Desenvolvedor Mobile iOS (#147)

 

A vaga ainda está aberta @fwfreitas <https://github.com/fwfreitas>  ?
