### ISSUE TITLE
[Campinas - SP] iFood - Desenvolvedor iOS 

### ISSUE THREAD

**Issue by xdoug7** [CocoaHeadsBrasil/vagas#148]
## Empresa
![09-ifood](https://cloud.githubusercontent.com/assets/1906178/24522859/52b72462-1567-11e7-8e14-92c18765d065.png)

O iFood, líder em delivery on-line de comida na América Latina, oferece o serviço via site e aplicativo nos sistemas operacionais iOS, Android e Windows Phone.

- Movimenta mais de R$ 1 bilhão, por ano, entre os parceiros; 
- Em 5 anos registra mais de 3 milhões de pedidos feitos por mês; 
- Presente em mais de 100 cidades do Brasil, com mais de 15 mil restaurantes cadastrados; 
- Expansão no México, na Colômbia e na Argentina; 
- Participação de um dos maiores players do mercado de aplicativos do mundo (Movile); 
- Participação do maior grupo de pedidos on-line do mundo (Just Eat).

Conheça mais sobre nós:
[ifood.delivery](https://ifood.delivery/br/sobre)
[Lovemonday](https://www.lovemondays.com.br/trabalhar-na-ifood/perfil)
[Linkedin](https://www.linkedin.com/company-beta/247645/life/)

## O que você irá entregar
 
- Novas funcionalidades que brilhem os olhos dos nossos usuários, utilizando tecnologias como CocoaPods, Fastlane, push noticiations, etc;
- Propor melhorias de processo e desenvolvimento e distribuição de nossos produtos;
- Colaborar com a área de produto, design e com os desenvolvedores das outras plataformas com o objetivo de ter um produto final com uma visão unificada;
- Executar e acompanhar resolução de bugs e exceptions reportados;
- Medir e otimizar a performance e uso de dados.

## Posição

Estamos com 1 vaga aberta Sênior.

## Tipo de contratação

CLT.

## O que você precisa ter

- Excelente conhecimento nas linguagens Swift e/ou Objective-C;
- Experiência com o processo de distribuição da App Store;
- Estar confortável com a aplicação dos Guidelines usando Auto Layout, Storyboard, @IBDesignables e @IBInspectables;
- Conhecimentos nas arquiteturas MVC, MVVM e VIPER;
- Gosto por modelos mais enxutos de projetos e experimentação contínua;
- Gostar de comer;
- Querer definir o jeito como as pessoas pedem e consomem delivery.

## O que nós vamos te entregar

- As ferramentas necessárias para cuidar do produto que realmente afeta a vida de milhões de usuários em um mercado com oportunidades gigantes de crescimento no Brasil e no exterior;
- Lugar em uma empresa que cresce 300% ao ano e que ainda mantém a cultura e dia a dia de uma Startup;
- Ambiente altamente colaborativo, com grande autonomia e baixa burocracia;
- Contratação CLT com benefícios;
- Bônus anual;
- Autonomia pra definir processo de trabalho e seu próprio ritmo;
- Ambiente de alto crescimento individual e da empresa como um todo.

## Como aplicar

Mande suas infos [aqui](https://ifood.delivery/br/vagas/Tecnologia%20e%20Produto/b68a3fea-7f98-4c46-ab1a-6a83f73651c0).

## Contato

Qualquer dúvida ou se quiser trocar ideia de como é trabalhar no iFood, pode me procurar no Slack do iOSDevBR ou mandar um e-mail para douglas.ferreira@ifood.com.br

**Comment by xdoug7** [comment]
@Viniciuscarvalho A vaga de Júnior/Pleno foi preenchida estamos só com a posição de Sênior. Pode remover as tags?

**Comment by Viniciuscarvalho** [comment]
Alterei @xdoug7 👍

**Comment by reprotector** [comment]
Olá @xdoug7 A vaga ainda está aberta?

**Comment by xdoug7** [comment]
Sim @reprotector, agora mais que nunca. A Vaga de Sênior ainda está aberta.
