### ISSUE TITLE
[São Paulo] Dev iOS Junior

### ISSUE THREAD

**Issue by fnazarios** [CocoaHeadsBrasil/vagas#15]
## Descrição da vaga

Desenvolvimento e manutenção dos apps e frameworks do Moip

## Local

Escritório São Paulo - Av Faria Lima

## Benefícios

- Assistência Médica e Odontológica
- VT com desconto de apenas 2%.
- Flex Car (combustível).
- Seguro de Vida Itaú.
- Frutas.
- Auxilio Incentivo a Idiomas.
- Convênio com Academia.
- Convênio Sesc.

## Requisitos

Obrigatórios
- Experiência com Swift ou Objective-C
- Conhecimento / experiência em alguma linguagem de programação orientada a objetos (Java, Ruby, Python, NodeJS);
- Noções em APIs Restful;
- Familiaridade com o processo de distribuição da App Store;
- Noções em UIKit, Auto Layout, Cocoa Touch, XCTest, MapKit, SafariServices;
- Noções com a automatização de testes unidade, integração e funcional;
- Noções TDD / BDD;

Desejáveis
- Reactive Programming

Diferenciais
- projetos opensource

## Contratação

CLT

## Nossa empresa

O Moip é a empresa de pagamentos mais inovadora do Brasil. Ajudamos todos os meses mais de 100k empreendedores e PMEs a receberem pagamentos online (e offline). Acreditamos que a inovação e o empreendedorismo devam ser o motor de crescimento do país e por isso estamos redefinindo a forma com que pequenos negócios lidam com a sua vida financeira.

## Como se candidatar

https://moip.workable.com/jobs/241914

**Comment by mbrufatto** [comment]
A vaga pode ser para trabalho remoto?

**Comment by VitorFerraz** [comment]
Vaga ainda aberta?

**Comment by Viniciuscarvalho** [comment]
Vaga já foi preenchida @fnazarios ? Se sim, pode fechar a issue? 👍
