### ISSUE TITLE
[São Paulo - SP] Iterative - Desenvolvedor iOS

### ISSUE THREAD

**Issue by rafaelnicolett** [CocoaHeadsBrasil/vagas#150]
## Iterative
A ITERATIVE é uma empresa de TI, inovadora, dinâmica e moderna, em plena ascensão e expansão, com seus serviços e produtos. 

Nosso time é composto por profissionais que gostam de tecnologia, comprometidos com prazos, responsáveis, engajados, criativos, dinâmicos e com bom senso de humor, criando um ambiente descontraído e uma equipe altamente eficaz e responsável. 

Nosso escritório fica na Vila Leopoldina, temos algumas Vans que circulam de 15 em 15 minutos nas estações: Imperatriz Leopoldina e Ceasa. 
Horário de trabalho flexível e não batemos ponto.

## Posição
Pleno e Sênior

## Tipo de contratação
Forma de Contratação PJ (aceitamos empresas simples) 

###### Obrigatórios
•	Swift
•	Orientação a objetos e boas práticas de programação
•	Consumo de APIs REST
•	Objective - C

###### Desejáveis
•	Experiência com testes automatizados;
•	Ter aplicativos publicados;
•	Conhecimento Server/Web;
•	Android/Java;

## Benefícios
Descanso Remunerado após 12 meses de contrato
Participação de Lucros Trimestral 

## Como aplicar
Enviar currículos atualizados para: camila.wolf@iterative.com.br 

## Contato
Se tiver alguma dúvida sobre a empresa, produto ou o time, sinta-se à vontade de entrar em contato no e-mail ou telefone: 11 3094-6868 / Camila Wolf

**Comment by faganello60** [comment]
Contratação PJ mas eu tenho que trabalhar 8 horas por dia na empresa?

**Comment by rafaelnicolett** [comment]
@faganello60 Então isso é bem comum aqui em SP e na area de TI com desenvolvimento. Eu mesmo atuo nesta forma a 3 anos. E tenho diversos conhecidos que tem atuam dessa forma. Seria um problema pra vc? A empresa é bacana da uma olhada aqui http://www.iterative.com.br 

Valeu man,

**Comment by reprotector** [comment]
Olá @rafaelnicolett A vaga ainda está aberta?
