### ISSUE TITLE
[Remoto] Exactaworks - Tech Lead Mobile

### ISSUE THREAD

**Issue by fegoulart** [CocoaHeadsBrasil/vagas#1509]
## Empresa
A Exactaworks é uma empresa de consultoria e desenvolvimento ágil que nasceu trazendo consigo o expertise de profissionais com mais de 10 anos de experiência na elaboração de projetos e gestão de times de tecnologia para renomadas empresas brasileiras em diferentes setores da economia.
Nosso objetivo é criar oportunidades de mudança, crescimento e inovação para nossos clientes, utilizando a tecnologia para transformar o cotidiano e melhorar a interação entre pessoas e empresas. Buscamos de forma incansável gerar valor comercial para nossos clientes em cada projeto.

## Descrição da vaga
O Tech Lead Mobile será o responsável técnico pela integração de uma instituição financeira com a Apple Pay e o Google Pay.
Atividades:

* Definição de arquitetura.
* Acompanhamento do desenvolvimento (backend, infra, iOS e Android)
* FU com stakeholders e executivos.
* Interface com Apple e Google (ingles fluente necessário) 

## Posição
Tech Lead

## Tipo de contratação
Remoto  CLT  PJ

###### Obrigatórios
* Experiência prévia com definição de arquitetura em projetos de integração de sistemas.
* Conhecimento das especificidades do ciclo de vida de desenvolvimento mobile.
* Experiência prévia em reports executivos.
* Experiência prévia em liderança técnica de equipes
* Experiência em cloud pública
* Inglês fluente

###### Desejáveis
* Experiência em desenvolvimento nativo (Android e/ou iOS)
* Experiência em desenvolvimento backend

###### Diferenciais
Conhecimento de Java Spring

## Benefícios
Benefícios de mercado

## Como aplicar
Enviar mensagem para [Maite](https://www.linkedin.com/in/maite-scache-costa-2a563b152/) ou [Tamires](https://www.linkedin.com/in/tamiresmiguel/).
Ou preencher formulário no [site](https://jobs.exactaworks.com.br/jobs/tech-lead-2871245a-8089-4f59-a7c3-3bbdff816aaa).

## Contato
[Maite](https://www.linkedin.com/in/maite-scache-costa-2a563b152/) ou [Tamires](https://www.linkedin.com/in/tamiresmiguel/)

**Comment by DouglasiOSDeveloper** [comment]
Estou interessado! Podemos conversar sobre?
