### ISSUE TITLE
[São Carlos - SP] Monitora - Desenvolvedor iOS

### ISSUE THREAD

**Issue by Wheelerruis** [CocoaHeadsBrasil/vagas#151]
## Empresa
Fundada há 5 anos, a Monitora está localizada na cidade de São Carlos - SP, a 238 Km de São Paulo e é uma fábrica de software voltada ao desenvolvimento de soluções corporativas para o mercado interno e externo atendendo empresas como a TAM e empresas em outros países como Londres e Malta. 

## Descrição da vaga
![vaga](https://cloud.githubusercontent.com/assets/26803873/24622485/9baf87ce-187b-11e7-95de-b8b069d37505.png)

## Posição
Desenvolvedor IOS Pleno

## Tipo de contratação
CLT com a possibilidade de fazer home uma vez por semana

###### Obrigatórios
•	Orientação a objetos e boas práticas de programação
•	Consumo de APIs REST
•	Objective - C
•	Inglês

###### Desejáveis
•	Swift

###### Diferenciais
A nossa empresa oferece:
a) um ótimo ambiente de trabalho
 i) oferecemos frutas no escritório da empresa
 ii) doces
 iii) e uma vez por mês algum evento especial para integrar a galera
b) horário flexível (a ser combinado com o líder),
c) código de vestimenta informal
d) treinamentos constantes por meio da "Monitora University" (finalizamos curso de SCRUM, requisitos, automação de teste e vários workshops em conjunto com o OpenSanca dos quais sempre temos algumas vagas reservadas)
e) Subsídio para Inglês
f) Aula de inglês in company
g) Subsídio de estacionamento para colaboradores próximo ao local de trabalho.
h) Home office 1 vez por semana (a ser combinado com o líder da equipe)
i) Seguro de vida e funeral.

## Benefícios
Home 
VA	
VR	
Unimed (Convênio total sem nenhum desconto)
Subisídio Bolsa de estudos
Curso de inglês in company 
Bônus de até 10% (atualmente concedido a cada 3 meses
Bônus/PLR referente a aproximadamente até um 14º salário pago parte em janeiro e parte em fevereiro

## Como aplicar
http://monitoratec.com.br/pt#trabalhe-conosco

## Contato
Elisa Cardinalli - elisa.cardinalli@monitoratec.com.br
Wheeler Ruis   - wheeler.silva@monitoratec.com.br

**Comment by Wheelerruis** [comment]
CLT

**Comment by reprotector** [comment]
Olá @Wheelerruis A vaga ainda está aberta?
