### ISSUE TITLE
(Remoto/Híbrido) Desenvolvedor IOs Jr/Pl

### ISSUE THREAD

**Issue by 1nChurch** [CocoaHeadsBrasil/vagas#1517]
Empresa
Olá, muito prazer, nós somos a inChurch!
A única plataforma no Brasil de desenvolvimento apps, sites, totens nativos para as igrejas.
Somos muito mais que tecnologia e inovação: somos pessoas movidas por desafios e vamos transformar a InChurch na melhor e maior empresa global de Tecnologia e Inovação para o 3º setor.
A gente sonha grande e buscamos por pessoas que tenham brilho nos olhos, paixão pelo que faz e queiram compartilhar uma trajetória de crescimento conosco.
Se você é DEV IOS e deseja, assim como nós ajudar igrejas a atrair, cuidar e capacitar pessoas através da tecnologia, vem com a gente!

Descrição da vaga
**O que você vai fazer?**
Desenvolver funcionalidades e dar manutenção no nosso aplicativo IOs;
Criar variantes do layout original de uma aplicação whitelabel;
Migrar aplicação do Objective-C para o Swift.

Dar suporte na gestão da equipe de IOS.

**O que esperamos de você?**
Domínio da linguagem Swift e conhecimento de Objective-C;
Conhecimento da Guideline de Design e Desenvolvimento Apple;
Familiaridade com integração APIs REST;
Experiência em versionamento de projetos com Git;
Prática com storyboards, xibs e auto layout.

**Posição**
Jr/Pl

**Tipo de contratação**
CLT

Labels
iOS
Híbrido
Remoto
Jr
Pl

Se esta vaga tem tudo a ver com você se candidate pelo link 
https://inchurch.solides.jobs/vacancies/168438?

**Comment by MarSYs1** [comment]
O link não tem acesso !!

**Comment by MarSYs1** [comment]
Está quebrado
