### ISSUE TITLE
[Remoto] nexmuv - Desenvolvedor IOS SR

### ISSUE THREAD

**Issue by HelenNexmuv** [CocoaHeadsBrasil/vagas#1524]
## Nexmuv
Somos uma empresa de tecnologia que aplica inovação em tudo aquilo que entrega. 

## Descrição da vaga
Desenvolvimento web e Mobile 

## Posição
 Sênior 

## Tipo de contratação
Remoto  - PJ  

## Requisitos
- Experiência avançada com desenvolvimento mobile IOS;
- Boa experiência com desenvolvimento em Flutter; 
- Git, Design Patterns, MVVM e Clean Architecture; 
- Guidelines (Material Design); 
- Json, Rest; 

###### Obrigatórios
IOS 
Flutter 

## Contato
Interessados, por favor, encaminhar CV para Helen.matos@nexmuv.com.br

**Comment by raphaeltorquat0** [comment]
A vaga ainda está aberta?
