### ISSUE TITLE
[ES - Vitória] Mobile Saúde - Desenvolvedor iOS

### ISSUE THREAD

**Issue by lucasromanomr** [CocoaHeadsBrasil/vagas#153]
## Empresa
Somos a Mobile Saúde, uma desenvolvedora de soluções inovadoras na área da saúde. Nosso escritório é em Vitória-ES, e nossa carteira de clientes abrange operadoras de saúde de todo o Brasil.
Estamos em fase de expansão e à procura de um desenvolvedor iOS para se juntar à equipe. O profissional irá atuar no levantamento, definição, especificação e desenvolvimento de aplicativos e sistemas para iOS.

https://www.mobilesaude.com.br

## Descrição da vaga
Programador iOS com conhecimento em Objective-C e Swift

## Posição
 Desenvolvedor iOS (Pleno)

## Tipo de contratação
 Presencial

###### Obrigatórios
- Ensino superior completo ou em fase de conclusão;
- Experiência em linguagens Objetive-c e iOS SDK;
- Web services, especialmente APIs REST;
- Familiaridade com HTTP, HTML, XML e jSon;
- Orientação a objetos e MVC;
- Banco de dados MySql e CoreData;
- Familiaride com repositorio Git.
- Inglês intermediário;

###### Diferenciais
- Conhecimento em AWS;
- Conhecimento em Swift;
- Inglês avançado;
- Experiência com processo de publicação na app store.

## Benefícios
• Refeição;
• Transporte;
• Plano de saúde Unimed;

## Como aplicar
Envie um email para oportunidades@mobilesaude.com.br com seu CV anexado. Assunto: Vaga Desenvolvedor iOS

## Contato
E-mail: oportunidades@mobilesaude.com.br

**Comment by lucasromanomr** [comment]
Vaga já preenchida

**Comment by reprotector** [comment]
Foi alguém daqui, @lucasromanomr ?

**Comment by lucasromanomr** [comment]
@reprotector daqui do GitHub? Não.
Do ES? sim.

Vaga também foi divulgada pelas redes sociais, quem entrou ficou conhecendo pelo facebook
