### ISSUE TITLE
iOS | Sênior - REMOTO - PJ

### ISSUE THREAD

**Issue by Teachrecruiter** [CocoaHeadsBrasil/vagas#1536]
## Pessoa Desenvolvedora iOS | Sênior (Projeto Internacional)  REMOTO - PJ

Suas principais responsabilidades serão:

**-Auxiliar no desenvolvimento de aplicativos iOS, com ênfase em vídeo e animação;**
**-Implementar modelos de IA em dispositivos;**
-Criar provas de conceito, demonstrações e enviar produtos finais.

 REMOTO - PJ

Você vai precisar de:

-Projetos que demonstrem proficiência em **iOS**;
-BS/MS em Ciências da Computação ou disciplina relacionada;
-Experiência com o **UIKit**;
-Experiência com programação **multithreading**;
-Experiência em escrever **testes unitários e código testável**;
-Experiência na criação de APIs;
-Conhecimento profundo de padrões de design e boas práticas de engenharia;
-Experiência em usar APIs de terceiros;
-Habilidades independentes, analíticas e de resolução de problemas.

## Benefícios
Plano de Saúde e Odontológico Bradesco
-Gympass
-Seguro de Vida
-Férias remuneradas 
-Equipamento

## Como aplicar
https://kobe.gupy.io/jobs/5365701?jobBoardSource=gupy_public_page ou e-mail: eduarda.damiani@kobe.io

**Comment by bmarcall** [comment]
Ja preencheram essa vaga?
