### ISSUE TITLE
[Remoto] iOS Developer na Torc

### ISSUE THREAD

**Issue by coderReview** [CocoaHeadsBrasil/vagas#1537]
Nesta função, você gastará um certo tempo desenvolvendo código iOS, especialmente casos de uso complexos. Além disso, você fará parceria com Produto, UX e Engenheiros para iterar os recursos e melhorar nosso Produto. Você também orientará/orientará os membros da equipe regularmente. Nesta função, o escopo do desenvolvimento não se limita apenas ao trabalho de recursos, mas também envolverá melhorias básicas na arquitetura.

## Local

Remoto - Empresa nos EUA.

## Responsabilidades

- Melhorar e manter a infraestrutura e os pipelines de CI e CD de nossos aplicativos móveis. Fornecer suporte de ferramentas de alto nível aos engenheiros da equipe.
- Colabore para impulsionar soluções que reduzam custos e tempo de lançamento no mercado.
- Ser responsável pela entrega de aplicativos ponta a ponta, incluindo a coordenação com as equipes necessárias para implantação de produção.
- Monitorando continuamente a integridade e os KPIs do aplicativo, apoiando a triagem de quaisquer problemas de produção como e quando necessário.
- Colabore na solução de problemas complexos de dados, recursos, serviços e plataformas e execute análises de causa raiz para resolver proativamente problemas operacionais e de produto.
- Seja um defensor das melhores práticas de segurança, defenda e apoie a importância da segurança na engenharia.
- Fornecer orientação técnica e mentoria aos colegas engenheiros em atividades de design e desenvolvimento de software.
- As funções do trabalho podem mudar a qualquer momento devido às necessidades do negócio.

## Qualificações

**QUALIFICAÇÕES REQUERIDAS**:

- Inglês fluente
- Mais de 6 anos de experiência em desenvolvimento de software com pelo menos 6+ anos em design/desenvolvimento de aplicativos iOS Mobile.
- Mais de 5 anos de experiência com estruturas modernas de desenvolvimento iOS, como SwiftUI.
- Mais de 5 anos de experiência trabalhando com equipes multifuncionais, como equipes de design, produto e dados, para oferecer ótimas experiências ao usuário.
- Mais de 2 anos de experiência influenciando grandes organizações nas melhores práticas de desenvolvimento para iOS móvel.
- Mais de 2 anos de experiência em acessibilidade. Experiência em telemetria e observabilidade além do Firebase.
- Mais de 2 anos demonstrando desejo de construir testes desde o início com experiência em desenvolvimento de TDD. Entrega contínua em mobile, revisão de código, análise estática, integração contínua, automação e testes funcionais (usando XCUI).

**QUALIFICAÇÕES PREFERENCIAIS**:

- Experiência em lidar com múltiplas prioridades concorrentes em um ambiente de ritmo acelerado.
- BFF (Backend para FrontEnd) e GraphQL.
- Expertise em ferramentas iOS, frameworks e Programação Reativa e construção de bibliotecas de Design Systems.
- Integração com estruturas, ferramentas e SDKs de terceiros.
- Experiência com sessão autenticada usando OAuth e tokens autenticados.
- Experiência com construção de sistemas em aplicativos altamente modularizados (XCode Cloud, CircleCI).
- Analisadores estáticos e dinâmicos (lint, regras personalizadas).
- Contribuições significativas de aplicativos voltados para o cliente lançados na loja da Apple.

## Como se candidatar

Use o link abaixo para se cadastrar:

https://platform.torc.dev/#/r/xhblcov/cp

Link da vaga em inglês:

https://lp.torc.dev/jobs/ios-developer-2

**Comment by coderReview** [comment]
@Lucca-C

**Comment by coderReview** [comment]
Vaga relacionada para Android - https://github.com/androiddevbr/vagas/issues/2188

**Comment by unnamedd** [comment]
Por favor, poste aqui vagas somente para plataformas Apple.
