### ISSUE TITLE
[Remoto/Campinas] Dextra - Desenvolvedor iOS

### ISSUE THREAD

**Issue by tamiresmgomes** [CocoaHeadsBrasil/vagas#155]
## Empresa
 Desde 1995 no mercado de tecnologia, enxergamos a inovação como chave para nosso diferencial no mercado.
A Dextra é especialista no desenvolvimento de software sob medida para negócios digitais. Usamos processos de inovação, tecnologia e conhecimento do negócio para a criação de produtos digitais que colocam nossos clientes em um novo patamar de mercado.
Este ano fomos eleitos a 5ª MELHOR empresa brasileira de TI para se trabalhar no ranking do Great Place to Work de Tecnologia da Informação e em quarto lugar do ranking da América Latina!

## Descrição da vaga
Se você é ávido por tecnologias de ponta e gosta de novos desafios...Aqui é o seu lugar!
Na Dextra os desenvolvedores são responsáveis pela expertise e conhecimento das tecnologias e propõem as melhores soluções técnicas durante todo o processo de desenvolvimento garantindo o sucesso da entrega para o cliente.

## Posição
Desenvolvedor iOS Pleno / Sênior

## Tipo de contratação
Contratação CLT para atuação de 40h semanais, com alocação na sede em Campinas ou Remoto

## Requisitos
O que você precisa saber para ocupar esta vaga?
Programar.. Mas com paixão!  Ser fera no desenvolvimento de aplicativos na plataforma iOS usando Objective-C e principalmente Swift; Desenvolver novas funcionalidades para os produtos digitais de nossos clientes  e ter conhecimento em desenvolvimento de telas para iOS (Storyboard, Auto Layout, componentes nativos, Views, criação de componentes customizados)

## Benefícios
Além dos benefícios tradicionais possuímos: Horário flexível; Casual Day everyday; Sala PS3/ Espaço Relax; Planos de Carreira; Treinamentos internos; Mentoria e muito mais.

## Como aplicar
Envie seu cv para recrutamento@dextra-sw.com ou se aplique em nosso [site](http://dextra.com.br/carreiras/)

## Contato
Tamires Gomes - tamires.gomes@dextra-sw.com

**Comment by araujoraphael** [comment]
Essa possiblidade de Home Office seria 100% remoto(outra cidade) ?

**Comment by tamiresmgomes** [comment]
A possibilidade de home office é par time  ;)

**Comment by MinervaAplicativos** [comment]
Olá, vocês já pensaram em fazer outsourcing? Sai o mesmo preço de um funcionário, mas você tem uma equipe à disposição e com um contrato de prestação de serviços.

**Comment by araujoraphael** [comment]
Como assim? Seria part-time home office + part-time e o restante presencial ou se for fazer home office, o trabalho fica só part-time?

**Comment by tamiresmgomes** [comment]
Na Dextra valorizamos muito a interação entre equipe e a presença de todos os membros no dia a dia da empresa. Essa vaga é para contratação CLT com atuação de 40 horas semanais para atuação em nossa base em Campinas, contudo, caso haja interesse, trabalhamos com horários flexíveis e possibilidade de atuar em home office em alguns dias da semana. Espero ter sido mais clara ;) Abs

**Comment by araujoraphael** [comment]
Ah, obrigado. Minha dúvida era mais essa. Se havia possibilidade de remoto. Obrigado
