### ISSUE TITLE
[Remoto] enjoei.com - iOS Senior

### ISSUE THREAD

**Issue by paulosigales** [CocoaHeadsBrasil/vagas#156]
## enjoei.com
startup brasileira. marketplace que vem dobrando de tamanho todo ano. hoje somos mais de 100 funcionários distribuídos entre operações no brasil e na argentina.
 
empresa investida pelos fundos monashees+ e bessemer venture partners.
 
resumidamente: só tem fera nessa empresa.

## Descrição da vaga
- trabalhar no app para iPhone do enjoei (desenvolvido em swift 3, auto layout e suporte a iOS 9+
- trabalhar em apps de novos produtos e marcas do grupo
- implementação de novas features no roadmap, melhorias, e correções em todas as áreas do aplicativo
- interações frequentes com as equipes de produto, backend e design
- fazer testes e code reviews, focando na atenção a detalhes e senso de ownership do produto

## Posição
Desenvolvedor iOS Senior

## Tipo de contratação
CLT - Remoto

###### Obrigatórios
- ótimo conhecimento do iOS frameworks 
- domínio do swift 3 e o básico de objective-c
- storyboards e xibs
- autolayout
- bons conceitos de usabilidade mobile
- código limpo e estruturado
- git/gitHub
- consumo de APIs REST
- uso de bibliotecas / cocoapods
- ter familiaridade com o Sketch
- conhecer o processo de certificados e publicação Apple
- experiência mínima de 3 anos

###### Desejáveis
- testes unitários usando XCTestCase
- testes de UI automatizados usando XCTestCase
- integração Contínua (CI) no iOS
- conhecimento sobre automatização de testes e geração de builds (ex.: fastlane, xctool, etc)
- contato com a comunidade de desenvolvedores iOS
- experiência em outras linguagens (não para trabalhar aqui, apenas como experiência)

## Benefícios
VR ou VA, Plano de saúde e dental, seguro de vida e reembolso de internet

## Com quem você vai trabalhar
https://www.linkedin.com/search/results/people/?facetCurrentCompany=%5B%222733924%22%5D

## Como aplicar
https://jobs.lever.co/enjoei/3e5fe530-e3d7-4b99-ab56-35ab6fd9666e

## Contato
Paulo Sigales - iOS Tech Lead
paulo@enjoei.com.br

**Comment by brunogama** [comment]
Url para aplicar está retornando 404

**Comment by paulosigales** [comment]
Obrigado @brunogama, a url foi ajustada.
