### ISSUE TITLE
[SP - Vila Olímpia] - GTORH - Desenvolvedor iOS Sênior

### ISSUE THREAD

**Issue by Brunarhti** [CocoaHeadsBrasil/vagas#158]
## Empresa
Empresa multinacional espanhola, de grande porte, excelente oportunidade de desenvolvimento, contrata profissionais no seguinte perfil :

Sólida experiência em desenvolvimento de aplicações nativas para iOS;
Imprescindível conhecimento de Swift;
Bons conhecimentos em SOLID, importante saber aplicá-los;
Conhecimentos em Clean Architecture (VIPER);
Experiência em desenvolvimento de testes unitários;
Necessário ter atuado com Git e Git-Flow;
Conhecimentos em Clean Code, Scrum, Jira e Integração contínua, será considerado um diferencial;
Idiomas: Espanhol e/ou Inglês em nível intermediário; 
Contratação por tempo indeterminado.

## Posição
Sênior

## Tipo de contratação
PJ

 Informe se é remoto/presencial, CLT, PJ ou Freelancer. 
Presencial 

## Benefícios
Informe os benefícios que a empresa oferece

## Com quem você vai trabalhar
Se desejar insira uma lista dos futuros colegas de trabalho. Você pode gerar uma com os usuários do GitHub dos funcionários em http://fpg1503.com/GithubProfileTableGenerator/

## Como aplicar
Informe como é feito o processo para aplicar a vaga

## Contato
Os interessados, favor encaminhar currículo, informando valor pretendido e disponibilidade para: brunarhti@gmail.com

**Comment by unnamedd** [comment]
@Brunarhti 

Regras de Uso
**Todas as vagas** devem conter o nome da empresa que está contratando

**Comment by Brunarhti** [comment]
Thiago, no caso dessa oportunidade, não posso abrir o nome do cliente, ele
pediu confidencialidade. Como podemos fazer?

2017-04-13 16:02 GMT-03:00 Thiago Holanda <notifications@github.com>:

**Comment by unnamedd** [comment]
Não podemos abrir exceções. 
Faz parte das regras de uso do repositório.

**Comment by Arlen2014** [comment]
Aproveitando a oportunidade, alguem poderia me dizer o que seria esta tal de SOLID?

**Comment by unnamedd** [comment]
@Arlen2014 

https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)
https://scotch.io/bar-talk/s-o-l-i-d-the-first-five-principles-of-object-oriented-design
