### ISSUE TITLE
[São Paulo] - Desenvolvedor iOS Sênior/Pleno - 99

### ISSUE THREAD

**Issue by philipesteiff** [CocoaHeadsBrasil/vagas#16]
**Descrição da vaga**

Aqui na 99 estamos constantemente evoluindo nossa cultura de desenvolvimento. Abordamos o desenvolvimento mobile com precisão e rigor de engenharia, trabalhamos com testes e ferramentas que garantem a qualidade e o impacto positivo nos nossos usuários.

Pequenos detalhes são vitais, focamos na experiência do usuário. Se você é um dev focado em produto, que não hesita em lutar por aquilo que acredita, e se nos seus aplicativos você emprega valores como usabilidade e velocidade, nós adoraríamos lhe conhecer.

**Aqui você irá:**

- Garantir o envio de software com qualidade, através de integração contínua, automação de testes e profundos code-reviews.
 
- Construir plataformas sustentáveis e estáveis para novas ideias de produto.
 
- Trabalhar com time multidisciplinar.
 
- Encontrar soluções simples e elegantes para problemas difíceis.
 

**Você possui:**

- Graduação na área de computação ou experiência prática equivalente.

- Experiência com GIT.

- Capacidade de priorizar tarefas efetivamente.

- Experiência com as melhores práticas de engenharia de software (testes, code-review, continous integration …).

- Conhecimento e vivência com RESTFul

- Vários anos de experiência em Objective-C e desenvolvimento iOS.

- Conhecimentos avançados nos frameworks Cocoa Touch(Foundation, UIKIT, MapKit).

- Familiaridade com o processo de distribuição da App Store.

- Experiência com MVVM

- Experiência com Reactive Cocoa

- Experiência Viper

**O que os devs amam na 99? \o/**

- os patinetes
- café
- bolo na sexta
- cerveja na sexta
- game night na quinta
- bermuda e chinelo
- badminton
- basquete
- violão

[>> Candidatar <<](http://goo.gl/forms/d9i7tK399E)

**Comment by marcelofabri** [comment]
Duplicado da #9?

**Comment by philipesteiff** [comment]
Fato! Sry
