### ISSUE TITLE
[SP - Vl.Olímpia] Oportunidade: Desenvolvedor iOS - Sênior {02 vagas}

### ISSUE THREAD

**Issue by Brunarhti** [CocoaHeadsBrasil/vagas#160]
## Empresa
Empresa multinacional espanhola contrata profissionais no seguinte perfil:

## Descrição da vaga
Desenvolvedor IOS - Sênior - 02 vagas
Sólida experiência em desenvolvimento de aplicações nativas para iOS;
Imprescindível conhecimento de Swift;
Bons conhecimentos em SOLID, importante saber aplicá-los;
Conhecimentos em Clean Architecture (VIPER);
Experiência em desenvolvimento de testes unitários;
Necessário ter atuado com Git e Git-Flow;
Conhecimentos em Clean Code, Scrum, Jira e Integração contínua, será considerado um diferencial;
Idiomas: Espanhol e/ou Inglês em nível intermediário; 
Contratação por tempo indeterminado.

## Posição
 Sênior

## Tipo de contratação
PJ

## Benefícios
Informe os benefícios que a empresa oferece

## Com quem você vai trabalhar
Se desejar insira uma lista dos futuros colegas de trabalho. Você pode gerar uma com os usuários do GitHub dos funcionários em http://fpg1503.com/GithubProfileTableGenerator/

## Como aplicar
Informe como é feito o processo para aplicar a vaga

## Contato
Os interessados deverão encaminhar currículo, informando pretensão e disponibilidade p/ brunarhti@gmail.com.

Bruna Santos
Headhunter
(11) 98116-8396

**Comment by reprotector** [comment]
@Brunarhti, devido a insistência em não seguir as regras do canal, estamos retirando as vagas e bloqueando seu perfil de criar novas vagas por aqui. Obrigado pela compreensão.
