### ISSUE TITLE
[Curitiba-PR] Desenvolvedor iOS Pleno

### ISSUE THREAD

**Issue by fernandoamorim** [CocoaHeadsBrasil/vagas#162]
## Empresa
Mobiletouch Produtora, 6 anos de mercado no desenvolvimento de Aplicativos e Sistemas.

## Posição
Desenvolvedor Pleno

## Tipo de contratação
PJ 

###### Obrigatórios
Swift, Objective-C

###### Desejáveis
RXSwift, Real Database (Firebase), Testes automatizados

###### Diferenciais
Android

## Benefícios
VR+VT

## Como aplicar
Envie um email para fernando.amorim@mobiletouch.com.br com o assunto [DEViOS]

## Contato
fernando.amorim@mobiletouch.com.br

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @fernandoamorim ?
