### ISSUE TITLE
[SP - São José do Rio Preto] Zup IT - Desenvolvedor iOS

### ISSUE THREAD

**Issue by richardfrk** [CocoaHeadsBrasil/vagas#164]
## Empresa

![](http://www.itforum.com.br/wp-content/uploads/2016/11/logo-ZUP.png)

Fundada em 2011, a ZUP tem como foco ajudar empresas a lidar com toda complexidade de integração de sistemas e externalização de serviços, apoiando grandes clientes de vários segmentos da economia. A ZUP possui plataforma e ferramentas completas para viabilizar técnica e financeiramente suas estratégias digitais. Sua tecnologia começou a ser desenvolvida em 2007 e busca solucionar desafios de ambientes completos para TI. A companhia tem sua sede em Uberlândia (MG), onde está instalada a área de pesquisa e desenvolvimento, escritórios técnicos em São José do Rio Preto e escritório comercial em São Paulo.
Site: http://www.zup.com.br

## Descrição da vaga
Realizar o desenvolvimento de aplicativos iOS. Executar a manutenção de aplicativos, fazendo eventuais correções necessárias, visando atender às necessidades dos nossos clientes.

## Posição
Júnior, Pleno e Sênior.

## Tipo de contratação
CLT

###### Obrigatórios
Experiência com Swift e/ou Objective-C, Cocoa Touch, Xcode, RESTful APIs.

###### Desejáveis
Experiência com construção de telas: Storyboards, Auto Layout, Size Class.
Experiência com CocoaPods, Git, Scrum.

## Benefícios
Além dos benefícios como: Convênio Médico, Convênio Odontológico, Vale Alimentação, PLR, Verba individual anual para treinamento, Plano Telefônico e Programa de Indicação. Possuímos um novo ambiente, muito bem aconchegante com: video game, sinuca, café da manhã e além é claro, da nossa ótima localização aqui em Rio Preto.

## Como aplicar
Aos interessados, devem enviar um currículo para [richard.cocco@zup.com.br](mailto:richard.cocco@zup.com.br)

## Contato
Para mais detalhes entre em contato comigo pelo Slack, meu nickname é "richardfrk" ou me mande um e-mail [richard.cocco@zup.com.br](mailto:richard.cocco@zup.com.br)

**Comment by reprotector** [comment]
Olá @richardfrk , essa outra vaga ainda está aberta? #116

**Comment by richardfrk** [comment]
E ai @reprotector tudo bem? Acredito que sim,mas essa que postei agora é unicamente para a unidade de SJRP. Mas posso entrar em contato com a matriz para verificar para você se a #116 esta aberta ainda.
