### ISSUE TITLE
[SP - Centro] 7COMm - Desenvolvedor(a) Backoffice

### ISSUE THREAD

**Issue by marciosm** [CocoaHeadsBrasil/vagas#165]
## 7COMm
Há 30 anos no mercado, a 7COMm é reconhecida como referência na prestação de serviços e soluções em TI com foco em desenvolvimento de softwares e sistemas.
Cultivamos parcerias sólidas que permitem maturidade e posicionamento estratégico nos serviços prestados. Simplicidade, ética e comprometimento, relacionamento e atendimento, criatividade e inovação, capital humano e sustentabilidade fazem parte de nossos valores.
Fazer parte da equipe 7COMm envolve contribuir para o nosso crescimento como profissional, mantendo-se sempre atualizado com as principais tendências do mercado e plataformas de desenvolvimento. Nosso reconhecimento no mercado e princípios são mantidos através de nossos profissionais altamente qualificados.

## Posição
Pleno ou Sênior

## Contratação
Forma de Contratação: PJ (aceitamos empresas simples, desde que com sócio e ligadas a TI) 

###### Obrigatórios
Desenvolvimento Mobile Nativo e Mobile com Xamarim;
Desenvolvimento híbrido (Ionic 2/3 ou React Native);
Conhecimento em Angular 2 ou 4, Typescript, HTML5, CSS 3;
Conhecimento em integração utilizando API Restfull.

###### Desejáveis
PHP, C#, Ruby.
Atuar com práticas ágeis.

## Benefícios
A 7COMm oferece uma série de ações internas que estimulam o bem estar e qualidade de vida de nossos colaboradores.

## Contato
Currículos para: thais.carvalho@7comm.com.br
Informar pretensão salarial.

**Comment by araujoraphael** [comment]
Aceita MEI?

**Comment by marciosm** [comment]
MEI não aceita infelizmente :(

Em 25 de abr de 2017 20:05, "Raphael Alves" <notifications@github.com>
escreveu:

**Comment by reprotector** [comment]
Olá @marciosm . A vaga ainda está aberta?

**Comment by marciosm** [comment]
Oi Renan. Sim. Ainda aberta.

Em 25 de out de 2017 12:12, "Renan Protector" <notifications@github.com>
escreveu:
