### ISSUE TITLE
[SP - Vila Madalena] Fullbar - Desenvolvedor iOS Pleno/Senior

### ISSUE THREAD

**Issue by laismasini** [CocoaHeadsBrasil/vagas#166]
## Empresa
Criada em 2012, a Fullbar é uma agência digital com mais estratégias que denominações.
Nossa busca incansável por novas ideias e tecnologias nos dão prazer em trabalhar. Afinal, passamos o dia na frente do computador porque criamos ambientes online que, de certa forma, são parecidos com um bar: cheio de boas experiências aos clientes.
Costumamos dizer que, na Fullbar, exercemos a Criatividade com uma generosa dose de tecnologia. Sem ressaca.

## Descrição da vaga
O desenvolvedor irá integrar um time de desenvolvimento, trabalhando no desenvolvimento de aplicações nativas, principalmente em Swift. Deve ser capaz de liderar os projetos trabalhando de forma autônoma quanto integrado em uma equipe com várias pessoas (criação e gerentes de projetos).

## Posição
Desenvolvedor IOS Pleno/Sênior

## Tipo de contratação
Presencial PJ

## Requisitos
- Domínio técnico e experiência em linguagem nativa iOS (Swift e Objective-C);
- Integração com webservices RESTFul e SOAP;
- Conhecimento de Analytics;
- Saber escrever código limpo e legível (Clean Architecture e Clean Code);
- Saber trabalhar com ferramentas de controle de versão;

###### Obrigatórios
- Domínio técnico e experiência em linguagem nativa iOS (Swift e Objective-C);
- Integração com webservices RESTFul e SOAP;

###### Desejáveis
- Desenvolvimento em Android: Java, Android, SDK (Android);
- Desenvolvimento em Xamarin;

###### Diferenciais
- Experiência com realidade aumentada e virtual;
- MVC, orientação a objetos;
- Conhecimentos de design de interface e experiência do usuário;
- Conhecimento em desenvolvimento para a plataforma Apple IOS utilizando Storyboard e XIB;
- Ter trabalhado em agências de publicidade e/ou produtoras web;

## Benefícios
- Almoço na faixa;
- 13º salário;
- Férias remuneradas.

## Com quem você vai trabalhar
www.fullbar.com.br

## Como aplicar
- Enviar e-mail com o CV para: lucas.muniz@fullbar.com.br e fabio@fullbar.com.br;
- Enviar portfólio com aplicativos desenvolvidos para iOS (com propriedade ou coparticipação) que possamos avaliar (não é necessário estar publicado nas lojas);
- Enviar pretensão salarial.

## Contato
lucas.muniz@fullbar.com.br e fabio@fullbar.com.br

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @laismasini ?
