### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Sênior de iOS - Cliente Confidencial

### ISSUE THREAD

**Issue by mariliafranguelli** [CocoaHeadsBrasil/vagas#167]
**Descrição da vaga**
Estamos procurando por um profissional com larga experiência em desenvolvimento de aplicativos nativos iOS e com habilidades no design de UI/UX.

**Local** 
Escritório São Paulo

**Benefícios**
Benefícios de mercado + bônus de até 3 salários por ano

**Descritivo da vaga**

- 3 anos de experiência com análise e desenvolvimento de soluções na plataforma iOS.
- Desenvolver sistemas baseados em testes que vise garantir a qualidade e a funcionalidade do software
- Proposição de melhorias tecnológicas e processuais
- Realização de pesquisas, acompanhando as evoluções e tendências tecnológicas
- Trabalhar em conjunto com o designer de UI/UX para converter os designs criado em aplicações funcionais e intuitivas
- Identificar oportunidades e demandas de desenvolvimento, definindo sua priorização e integração com as demais áreas
- Gerenciar os recursos tais como: mapeamento de escopo, estimativa, esforço, prazos para concepção do projeto, até a entrega final dos projetos garantindo o escopo e prazos acordados.

 **Contratação**
CLT

 **Nossa empresa**
Fintech que será pioneira no seu segmento. 

**Como se candidatar**
Por favor, envie um e-mail para marilia.gabriela@2xs.com.br com o título da vaga.

**Comment by reprotector** [comment]
@mariliafranguelli Por favor leia as regras do canal. Não aceitamos vagas sem o nome da empresa que está contratando.

"Todas as vagas devem conter o nome da empresa que está contratando

Se você é um recrutador, você deve identificar o nome da empresa em que o candidato irá trabalhar"

https://github.com/CocoaHeadsBrasil/vagas

**Comment by mariliafranguelli** [comment]
Olá, Renan! Tudo bem?

Obrigada pelo feedback.

Essa é uma vaga confidencial, o cliente é uma Fintech (startup), mas ainda não posso divulgar o nome.

Não posso colocar a vaga no canal então?

 

Abraços,

 

Marília Franguelli 
2XS Search and Success | São Paulo

Av. Nove de Julho, 3452 - 10° andar – Jardim Paulista
Tel: (+55 11) 2371-0000 – (11) 98918-9277

 

De: Renan Protector [mailto:notifications@github.com] 
Enviada em: quinta-feira, 4 de maio de 2017 11:38
Para: CocoaHeadsBrasil/vagas <vagas@noreply.github.com>
Cc: mariliafranguelli <marilia.gabriela@2xs.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [CocoaHeadsBrasil/vagas] [São Paulo, SP] Desenvolvedor Sênior de iOS - Cliente Confidencial (#167)

 

@mariliafranguelli <https://github.com/mariliafranguelli>  Por favor leia as regras do canal. Não aceitamos vagas sem o nome da empresa que está contratando.

"Todas as vagas devem conter o nome da empresa que está contratando

Se você é um recrutador, você deve identificar o nome da empresa em que o candidato irá trabalhar"

https://github.com/CocoaHeadsBrasil/vagas

**Comment by reprotector** [comment]
@mariliafranguelli Infelizmente não podemos abrir exceções. Quando puder divulgar o nome da startup é só criar uma nova vaga :)

**Comment by mariliafranguelli** [comment]
Claro, eu entendo!

Muito obrigada!

 

Abraços,

 

Marília Franguelli 
2XS Search and Success | São Paulo

Av. Nove de Julho, 3452 - 10° andar – Jardim Paulista
Tel: (+55 11) 2371-0000 – (11) 98918-9277

 

De: Renan Protector [mailto:notifications@github.com] 
Enviada em: quinta-feira, 4 de maio de 2017 11:45
Para: CocoaHeadsBrasil/vagas <vagas@noreply.github.com>
Cc: mariliafranguelli <marilia.gabriela@2xs.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [CocoaHeadsBrasil/vagas] [São Paulo, SP] Desenvolvedor Sênior de iOS - Cliente Confidencial (#167)

 

@mariliafranguelli <https://github.com/mariliafranguelli>  Infelizmente não podemos abrir exceções. Quando puder divulgar o nome da startup é só criar uma nova vaga :)
