### ISSUE TITLE
[São Paulo] Dev iOS Senior - Moip Pagamentos

### ISSUE THREAD

**Issue by fnazarios** [CocoaHeadsBrasil/vagas#17]
## Descrição da vaga

Desenvolvimento dos aplicativos e SDK para pagamento e gestão financeira dos clientes do Moip.
## Local

Av Faria Lima com rua Amauri 
## Benefícios
- Assistência Médica e Odontológica.
- VT com desconto de apenas 2%.
- Flex Car (combustível).
- Seguro de Vida Itaú.
- Frutas.
- Auxilio Incentivo a Idiomas.
- Convênio com Academia.
- Convênio Sesc.
## Requisitos

Obrigatórios
- Experiência com Objective-C e Swift
- Experiência em alguma linguagem de programação orientada a objetos (Java, Ruby, Python, NodeJS);
- Experiência com APIs Restful;
- Experiência com o processo de distribuição da App Store;
- Auto Layout, Storyboard, @IBDesignables e @IBInspectables;
- Experiência com a automatização de testes unidade, integração e funcional;
- Experiência com TDD / BDD;
- Conhecimento de metodologias ágeis (Scrum);
- Capacidade de priorizar tarefas efetivamente.

Desejáveis
- Experiência com MVVM
- Experiência com RxSwift
- Experiência VIP (View-Interactor-Presenter)
## Contratação

CLT
## Nossa empresa

O Moip é a empresa de pagamentos mais inovadora do Brasil. Ajudamos todos os meses mais de 100k empreendedores e PMEs a receberem pagamentos online (e offline). Acreditamos que a inovação e o empreendedorismo devam ser o motor de crescimento do país e por isso estamos redefinindo a forma com que pequenos negócios lidam com a sua vida financeira.
## Como se candidatar

https://moip.workable.com/jobs/246361

**Comment by reprotector** [comment]
@fnazarios A vaga já foi preenchida? Podemos fechar a issue? :)
