### ISSUE TITLE
[SP-Paulista] Senior iOS Engineer - Evino

### ISSUE THREAD

**Issue by leticiaevino** [CocoaHeadsBrasil/vagas#170]
Evino Senior iOS Engineer São Paulo - Paulista
   
## EVINO

In less than 4 years of existence ( evino ) has become one of the biggest Brazilian e-commerces and fastest growing wine platform. We're now counting with 200+ people, an outstanding revenue growth and break-even, all of that while also enjoying pretty cool wine labels. Besides wine, the preparation for a new business scale and managing people / growth are the foundations of our success.

## Descrição da vaga
We offer a flexible environment where you'll be able to make a difference. In the Tech / Product verticals we believe that nothing brings more value to our users than constantly shipping features in production. To accomplish that we have been creating an open and collaborative environment that makes sure no good idea is thrown in the drawer and that purpose drives our everyday work. If you're a wine lover, or at least wants to learn more about it, we offer a wine tasting with specialists every Friday in our office :)

Responsibilities
Architect, code and maintain our iOS application
Adapt the code to use our new service API
Deliver a well tested, maintainable, clean mobile application
Integrate with third party analytical tools (appsee, fabric, google analytics) for proper instrumentation
Work with the Product team towards understanding requirements and implementing amazing features
Help manage app deployments, fixes, continuous integration, monitoring tools

## Posição
Senior iOS Engineer 

## Tipo de contratação
CLT

###### BA/BS Degree (preferably in Computer Science, Math, Engineering) or equivalent experience
 iOS tools software development (Swift and Objective-C)
Solid understanding of data structures (lists, queues, arrays, maps, graphs) and when to apply them
Experienced with Core Animation, Core Data, and various Cocoa frameworks
Coding experience with modern concurrent / parallel mechanisms such as reactive architectures, multithreading, asynchronous programming
Significant experience using Web Services (REST, SOAP)
Well acquainted with modern development best practices, such as Design Patterns, Microservices, TDD, DevOps, Continuous Integration/Deployment/Delivery, Cloud Computing
Familiar with at least one Agile framework (Scrum, Kanban, XP)

###### Desejáveis
Solid understanding of distributed systems, event driven and reactive programming
Experience with public clouds (AWS, Azure, Google Cloud Platform)
Previous experience with retail / e-commerce

## Benefícios
VT,VR,Am,AO,Seg Vida.

## Como aplicar
E-mail com cv´s para: leticia.santinelli@evino.com.br

## Contato
Leticia  leticia.santinelli@evino.com.br

**Comment by marcelofabri** [comment]
@leticiaevino por favor coloque o local da vaga no título :)

**Comment by leticiaevino** [comment]
@marcelofabri  Opa obrigada pela observação Marcelo :) Colocado
