### ISSUE TITLE
[Bauru - SP] SOMOS Educação - Desenvolvedor iOS [2 vagas]

### ISSUE THREAD

**Issue by alborghette** [CocoaHeadsBrasil/vagas#171]
## Empresa
A SOMOS Educação é o maior grupo de educação básica do Brasil e um dos maiores grupos de educação do mundo.

Nossas escolas, sistemas de ensino, editoras, produtos e serviços para gestão e formação complementar impactam o dia a dia e transformam a vida de milhares de educadores e de milhões de alunos, juntamente com suas famílias, por todo o país.

Com portfólio completo de soluções, organizado em um ecossistema de negócios integrado, potencializamos os resultados da educação brasileira, aumentando também a rentabilidade das escolas que o utilizam.

As marcas do grupo SOMOS Educação são referências de qualidade. Oferecemos uma formação completa que prepara nossos alunos para as provas do ENEM, dos melhores vestibulares do país e também da vida.

Por trás de tudo isso, existe um time de profissionais inquietos, que compartilha o compromisso de formar gerações de brasileiros cada vez melhores.

## Descrição da vaga
A SOMOS Educação está com uma vaga aberta de iOS Developer para a unidade em Bauru-SP. Você será responsável por cuidar do nosso app principal junto com a equipe, corrigindo bugs e criando funcionalidades que estejam no roadmap. 

## Posição
Junior | Pleno | Sênior

## Tipo de contratação
CLT - Presencial 

## Requisitos
- Swift
- Realm
- Publicação iTunes Connect
- Storyboard
- Firebase CrashReport
- CocoaPods

## Benefícios
- Vale refeição/alimentação
- Plano médico/odontológico
- Horário (na medida do possível das 8h/dia) flexível
- Ajuda de custo para participação em eventos. 

## Como aplicar
Enviar um email para rafael.teixeira@somoseducacao.com.br com o título VAGA DEV iOS com seu CV ou perfil do Linkedin. Fique à vontade para enviar junto também uma apresentação sobre você, trabalhos já realizados, apps publicados ou perfil no Github.

## Contato
Qualquer dúvida, pode entrar em contato pelo email rafael.teixeira@somoseducacao.com.br.

**Comment by alborghette** [comment]
Adicionamos novas vagas para nível Sênior também.

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @alborghette ?

**Comment by alborghette** [comment]
Oi @Viniciuscarvalho, desculpe a demora. A vaga foi preenchida sim, tivemos bastante inscrições do pessoal da comunidade.
Podemos fechar a issue, valeu.
