### ISSUE TITLE
[Moema e Vila Olimpia -São Paulo - SP] One Choice - Desenvolvedor IOS

### ISSUE THREAD

**Issue by GabrielaVaccari** [CocoaHeadsBrasil/vagas#173]
## Empresa
 One Choice é uma empresa com foco em inovação na área de recrutamento e seleção de profissionais de TI.
## Descrição da vaga
Desenvolvedor IOS
## Posição
 Sênior
## Tipo de contratação
Presencial 
CLT ( 10 a 16 mil)
## Requisitos
3+ anos de experiência com desenvolvimento iOS (Objective C, Swift),
Familiaridade com metodologias ágeis (Scrum, Kanban,XP, BDD, Lean)
###### Obrigatórios
 Desenvolvimento iOS (Objective C, Swift),
###### Desejáveis
Ter alguma experiência com mercado financeiro, seguradora ou com fraude é um diferencial.
Domínio sobre principais metodologias ágeis (Scrum, XP, BDD, Lean) 
## Benefícios
Beneficos a combinar
## Contato
CV para talentos@onechoice.com.br e gabrielavaccari@onechoice.com.br
Desenvolvedor IOS SR

**Comment by reprotector** [comment]
Olá, @GabrielaVaccari. A vaga é para trabalhar na OneChoice ou em outra empresa que contratou a OneChoice?

**Comment by GabrielaVaccari** [comment]
temos 2 vagas de alocação num cliente e uma vaga clt direto do cliente


2017-05-24 14:01 GMT-03:00 Renan Protector <notifications@github.com>:

**Comment by reprotector** [comment]
@GabrielaVaccari Estou fechando a divulgação da vaga aqui pois ela está ferindo as regras do canal: 

Todas as vagas devem conter o nome da empresa que está contratando
Se você é um recrutador, você deve identificar o nome da empresa em que o candidato irá trabalhar

As regras do canal se encontram aqui: https://github.com/CocoaHeadsBrasil/vagas

**Comment by GabrielaVaccari** [comment]
Renan , é a one choice que esta contratando nao estou entendendo


2017-05-24 14:05 GMT-03:00 Renan Protector <notifications@github.com>:

**Comment by GabrielaVaccari** [comment]
é uma pena  que nao posso divulgar uma vaga que eu estou trabalhando,
entrevistando e fazendo todo o processo
 que paga 16 mil reais clt ate ..
mas blz quem perde sao os desenvolvedores


2017-05-25 8:18 GMT-03:00 Gabriela | One Choice Consulting <
gabrielavaccari@onechoice.com.br>:

**Comment by reprotector** [comment]
@GabrielaVaccari Para as 2 vagas na OneChoise, onde a empresa contratante será a OneChoice você pode divulgar sem problemas. Basta abrir uma nova vaga com ela. Já para a vaga em que o CNPJ contratante é o cliente, não será possível divulgar a vaga aqui sem a identificação do cliente. O desenvolvedor precisa saber a empresa em que ele irá trabalhar.
