### ISSUE TITLE
[SP - Morumbi] PSM Company - Desenvolvedor Mobile Pleno

### ISSUE THREAD

**Issue by fwfreitas** [CocoaHeadsBrasil/vagas#175]

**Comment by reprotector** [comment]
Olá, @fwfreitas . A vaga é para trabalhar na PSM ou em outra empresa que contratou a PSM para recrutar?

**Comment by fwfreitas** [comment]
Olá Renan,

 

Essa vaga é para trabalhar em outra empresa, mas não podemos mencionar o cliente.

 

Fomos contratados para recrutar.

 

Atenciosamente,

 

Descrição: Assinatura

 

De: Renan Protector [mailto:notifications@github.com] 
Enviada em: quarta-feira, 24 de maio de 2017 20:16
Para: CocoaHeadsBrasil/vagas
Cc: fwfreitas; Mention
Assunto: Re: [CocoaHeadsBrasil/vagas] [SP - Morumbi] PSM Company - Desenvolvedor Mobile Pleno (#175)

 

Olá, @fwfreitas <https://github.com/fwfreitas>  . A vaga é para trabalhar na PSM ou em outra empresa que contratou a PSM para recrutar?
