### ISSUE TITLE
[SP - São Bernardo do Campo] AppFactory - Desenvolvedor iOS Pleno

### ISSUE THREAD

**Issue by maiconpeixinho** [CocoaHeadsBrasil/vagas#176]
## Empresa
Fabrica de aplicativos estabelecida em São Bernardo do Campo - SP

## Descrição da vaga
Atuará com o desenvolvimento de aplicativos mobile, plataforma iOS, análise e avaliação de sistemas, elaboração de documentação técnica e demais atividades.
Necessário experiência em desenvolvimento na plataforma iOS Objective-C. Desejável conhecimento em Swift, API e JSON, e APPs publicados na App Store.

## Posição
Pleno

## Tipo de contratação
Contratação PJ. 

###### Obrigatórios

- Ser graduado em Ciência da Computação, Engenharia da Computação ou equivalente
- Conhecimento intermediario em Objective-C
- Inglês
- Aprender muito rápido e ter alta capacidade analítica
- Ter aplicativos publicados na App Store
- Ter alguma experiência com banco de dados relacional

###### Desejáveis

- Ter desenvolvido algum app para Android
- Ter noções de UX
- Git
- CocoaPods
- Swift

###### Diferenciais

- Desenvolver também para Android
- Processo de publicação na App Store
- Provisions e Certificates

## Como aplicar
Envie o currículo para jobs@appfactory.com.br com pretenção salarial

## Contato
www.appfactory.com.br

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @maiconpeixinho ?
