### ISSUE TITLE
EclipseSpaceWifi - Desenvolvedor iOS Pleno

### ISSUE THREAD

**Issue by diegodaminelli** [CocoaHeadsBrasil/vagas#177]
## Empresa
 www.eclipsespacewifi.com.br 

## Descrição da vaga

Desenvolvedor Junior ou Pleno Nativo de IOs

## Posição
Pleno

## Tipo de contratação

Remoto ou Presencial no Rio de Janeiro,  PJ  - Fulltime

###### Obrigatórios
Conhecimento pleno em IOS Nativo

###### Diferenciais
Estar no Rio de Janeiro

## Benefícios
PL + Bônus por Meta 

## Como aplicar
Entrar em contato por email

## Contato
diego@eclipsewifi.com.br

**Comment by unnamedd** [comment]
@diegodaminelli por favor, adicione o local para onde é a vaga no título da issue, seguindo o padrão das outras issues.

**Comment by Viniciuscarvalho** [comment]
A vaga já foi preenchida @diegodaminelli ?
