### ISSUE TITLE
[MG - Belo Horizonte] Samba Tech - Desenvolvimento Mobile 

### ISSUE THREAD

**Issue by thafreireec** [CocoaHeadsBrasil/vagas#178]
## Empresa
Na Samba, colaborador é Rei!

Reconhecida pelo Instituto Great Place to Work® como uma das 40 melhores empresas para se trabalhar no Brasil na categoria TI & Telecom em 2015 e eleita pela FastCompany como uma das companhias mais inovadoras da América Latina em 2014, a Samba Tech ajuda centenas de empresas a se comunicarem melhor com sua audiência através dos seus vídeos online.

## Descrição da vaga
Estamos procurando um desenvolvedor de aplicativos IOS ou ANDROID para integrar nosso time de desenvolvimento e ter a oportunidade de trabalhar na construção de aplicativos que irão revolucionar a forma como as empresas se comunicam usando vídeos.

Fazer parte da Equipe de Talentos da Samba Tech dará a você uma oportunidade única de participar de uma empresa em crescimento rápido e de desempenhar um papel importante na construção de produtos e serviços que prometem transformar a indústria de vídeos online e revolucionar a experiência digital!

## Posição
Júnior/ Pleno

## Tipo de contratação
CLT

## Requisitos
- Nível superior completo em Ciência da Computação, Engenharia da Computação ou áreas afins; 
- Experiência mínima de 1 ano em cargos similares.    

###### Obrigatórios
- Experiência em Objective-C ou Swift e Java, bons conhecimentos em algoritmos, análise de algoritmos e estrutura de dados;
- Conhecimento de Android Studio /XCode, SDK IOS ou SDK Android. 

###### Diferenciais
- Aplicativo publicado nas lojas;
- Experiência em Continuous Integration.

## Benefícios
- Vale Refeição;  
- Vale Transporte;
- Plano de Saúde;  
- Previdência Privada;  
- Seguro de Vida;
- GymPass;
- Horario Flexível.
  
## Como aplicar
Os interessados deverão cadastrar o curriculo no link:
http://jobs.kenoby.com/sambatech/job/analista-de-desenvolvimento-mobile/5903455bfbb33f6af3d35617

## Contato
thabata.costa@sambatech.com.br

**Comment by reprotector** [comment]
@thafreireec Diferenciais e Obrigatórios estão com o mesmo texto

**Comment by thafreireec** [comment]
Obrigada. Fiz as alterações!!!

**Comment by reprotector** [comment]
Olá @thafreireec A vaga ainda está aberta?
