### ISSUE TITLE
[SP - São Paulo] WebGados - Desenvolvedor iOS Pleno

### ISSUE THREAD

**Issue by workstein** [CocoaHeadsBrasil/vagas#179]
## Empresa
WebGados: A primeira e única plataforma online integrada para vender e comprar o melhor em gado de corte e leite, equídeos, ovinos, caprinos, maquinários agrícolas, caminhões, propriedades rurais, produtos e serviços através do seu computador ou smartphone.

Site: https://webgados.com.br

## Descrição da vaga
Desenvolvimento e Manutenção do aplicativo WebGados

## Posição
Pleno

## Tipo de contratação
Contratação PJ

## Requisitos
Nível superior cursando/completo em Ciência da Computação, Engenharia da Computação ou áreas afins;
Experiência mínima de 1 ano em cargos similares.

###### Obrigatórios
Ser apaixonada(o) por desenvolvimento de software e tecnologia
Ter experiência com Objective C e/ou Swift;

###### Desejáveis
Git
Experiência com armazenamento de dados (modo offline)
Experiência com desenvolvimento de testes unitários
Experiência com Storyboard, Auto Layout, Size Classes e Multitasking

###### Diferenciais
Aplicativo publicado nas lojas;
Conhecimento em Node.JS e Mongo.DB

## Benefícios
Mesa de Ping Pong
Emenda de Feriados

## Como aplicar
Enviar e-mail com o currículo e possível portfólio para: gabriel.stein@webgados.com.br

**Comment by Viniciuscarvalho** [comment]
A vaga já foi preenchida @workstein ?
