### ISSUE TITLE
[São Paulo - Vergueiro] Netshoes - Desenvolvedor iOS Sênior

### ISSUE THREAD

**Issue by viniciusalbinonetshoes** [CocoaHeadsBrasil/vagas#18]
## Descrição da vaga

Buscamos desenvolvedores com experiência de no mínimo 2 anos com desenvolvimento de  apps iOS e experiência em Swift. Trabalho presencial em horário comercial.
## Local

Escritório em São Paulo - próximo ao metrô Vergueiro
## Benefícios
- Use Mac + Monitor
- Equipe dinâmica e motivada
- Voz ativa e participação nas decisões de negócio
- VR, VA, VT, Assistência Médica + Assistência Odontológica, Benefício Farmácia, Seguro de Vida, Plano de Previdência de Privada, Bolsa de estudos, PLR
## Requisitos

Obrigatórios
- Controle de versão distribuído usando git
- Ciclo de vida do UIViewController
- Boas práticas em Objective-C e Swift, orientação a objeto e design patterns
- Integração com APIs RESTful
- Familiaridade com componentes de UIKit
- Adaptação de layouts usando Class Size e Autolayout
- Conhecimento das guidelines de design da Apple Store e de desenvolvimento

Desejáveis
- Conhecimento de metodologias ágeis ( Scrum )
- Fluência em inglês ( leitura técnica )
- Conhecimento sobre integração contínua ( build, test, relatórios )

Diferenciais
- Portfólio de aplicativos na Apple Store
- Conhecimento em e-commerce
- Conhecimento em Otimização de Performance e Segurança
## Contratação

CLT Full - 44h Semanais
## Nossa empresa

Somos nós que construímos cada história de sucesso, cada inovação que leva à melhor experiência de compra para nossos clientes.
Estamos constantemente quebrando recordes e ampliando a nossa atuação. Não somos mais apenas esporte. Somos moda. Somos estilo de vida. E seremos muito mais.
E é dessa incansável vontade de fazer mais e melhor que pautamos nossos novos valores, missão e visão para continuarmos sempre à frente.
Somos Netshoes. Somos Zattini. Somos o Grupo Netshoes! 
## Como se candidatar

Por favor envie um email para marcelo.paparelli@netshoes.com - enviar no assunto: Vaga iOS

**Comment by Viniciuscarvalho** [comment]
@viniciusalbinonetshoes esta vaga já foi preenchida? Se caso já tenha sido preenchida, poderia fechar a issue 👍

**Comment by viniciusalbinonetshoes** [comment]
@Viniciuscarvalho a vaga continua em aberto, assim que for preenchida eu já fecho aqui!  👍

**Comment by Viniciuscarvalho** [comment]
👍  @viniciusalbinonetshoes
