### ISSUE TITLE
[RJ - Barra da Tijuca] Fulllab - Desenvolvedor iOS Junior/Pleno/Senior

### ISSUE THREAD

**Issue by EduardoTT** [CocoaHeadsBrasil/vagas#180]
![vaga-ios](https://user-images.githubusercontent.com/10534997/26989728-7da935de-4d2a-11e7-85cf-3ce233cf3b86.png)

## Fulllab
Empresa criada para atender o varejo. Combinando dados de consumo, mídia contextualizada e produtos omnichannel, online, mobile e para lojas físicas, oferecemos as soluções mais modernas e eficientes para o aumento da conversão.
www.fulllab.com.br

## Descrição da vaga
O colaborador fará parte do time do Mobfiq, um app de ecommerce com mais de 250K downloads.
www.mobfiq.com.br

## Posição
Junior, Pleno ou Senior.

## Tipo de contratação
Presencial, CLT ou PJ. 

###### Obrigatórios
Forte conhecimento de Swift;
Trabalhar com Auto Layout usando XIBs;
Bom conhecimento do UIKit e de outras frameworks nativas.

###### Desejáveis
Conhecimento de ferramentas de automatização (fastlane, jenkings, xcode server);
Experiencia em publicar apps para a App Store

## Contato
juliana@fulllab.com.br

**Comment by Viniciuscarvalho** [comment]
A vaga já foi preenchida? @EduardoTT

**Comment by EduardoTT** [comment]
Esta especificamente, sim. Mas a Fulllab ainda precisa de desenvolvedores iOS. Eu fecho a issue?

**Comment by Viniciuscarvalho** [comment]
Só altera então pro caso que você precisar! 👍

**Comment by EduardoTT** [comment]
Ok, ainda são os mesmo requisitos.

**Comment by EduardoTT** [comment]
Reabrindo a Issue, pois estamos contratando novamente :)

**Comment by EduardoTT** [comment]
Vaga aberta novamente!

**Comment by victorvieiraveiga** [comment]
Vaga para JR?
