### ISSUE TITLE
[SP - São Carlos] Ringa - Desenvolvedor iOS

### ISSUE THREAD

**Issue by BruhhGarcia** [CocoaHeadsBrasil/vagas#181]
![cartaz_ringa-01](https://user-images.githubusercontent.com/1772293/27298357-ac76b41e-54fe-11e7-8d93-f3bbdf205149.png)

## Empresa
A Ringa é um empresa jovem (temos menos de 3 anos), com ambiente descontraído e com um time extremamente motivado. Trabalhamos com projetos nacionais e internacionais e focamos sempre em trabalhar com novas tecnologias.
http://ringa.com.br

## Descrição da vaga
Estamos a procura de um desenvolvedor iOS para atuar em um projeto internacional.

## Posição
Junior

## Tipo de contratação
 Presencial PJ

###### Obrigatórios
- Bom conhecimento em lógica de programação
- Conhecimentos de arquitetura de software e padrões de projeto
- Conhecimentos de UI/UX
- Disponibilidade de 40 horas semanais para trabalho presencial em São Carlos
- Bom conhecimento em POO
- Objective-C
- Git

###### Diferenciais
- Experiência em Swift

## Como aplicar
Envie seu currículo para ninjas@ringa.com.br

## Contato
bruna@ringa.com.br

**Comment by Viniciuscarvalho** [comment]
A vaga já foi preenchida @BruhhGarcia ?

**Comment by BruhhGarcia** [comment]
Já sim @Viniciuscarvalho
