### ISSUE TITLE
[SP - São Paulo] Gold 360 - Desenvolvedor iOS Pleno

### ISSUE THREAD

**Issue by diegoromualdo** [CocoaHeadsBrasil/vagas#182]
## Empresa
A Gold 360 nasceu em 2012, com ambiente descontraído e com um time extremamente motivado. Trabalhamos com projetos multiplataformas e focamos sempre em trabalhar com novas tecnologias.

## Descrição da vaga
Desenvolvimento e Manutenção dos aplicativos (+ de 20 APPs)

## Posição
Desenvolvedor iOS Pleno

## Tipo de contratação
CLT Full

###### Obrigatórios
Experiência trabalhando com desenvolvimento nativo;
Conhecimentos em Swift, Storyboards, Auto Layout, Consumo de API's REST;
Conhecimentos de Objective-C;
Conhecimentos de design de interface e experiência do usuário;
Experiência com o processo de distribuição da App Store;
Conhecimentos na utilização de gerenciadores de dependências (cocoapods, carthage, etc);

###### Desejáveis
Saber trabalhar com ferramentas de controle de versão (Git);
Conhecimentos nas arquiteturas MVC, MVVM;
Conhecimentos de automação de publicação de aplicações (fabric, fastlane, etc);
Saber utilizar RxSwift;
Criar testes automatizados;
Conhecer TDD/BDD;

## Benefícios
Plano de Saúde Bradesco, Seguro de Vida, VR (35,00/dia), PLR
Ambiente descontraído, churrasco na "laje", geladeira com cervejas, refrigerantes e sucos, sala com PS4

## Com quem você vai trabalhar
| ![](https://github.com/kosicki123.png?size=117) |
| --- |
|[kosicki123](https://github.com/kosicki123) |

## Processo de contratação
1ª Etapa - Teste prático
2ª Etapa - Entrevista técnica
3ª Etapa - Entrevista RH

## Contato
diego.silva@gold360.com.br

**Comment by Viniciuscarvalho** [comment]
A vaga já foi preenchida @diegoromualdo ?
