### ISSUE TITLE
[RJ - Rio de Janeiro] Six Creative - Desenvolvedor iOS Pleno

### ISSUE THREAD

**Issue by victorhugorch** [CocoaHeadsBrasil/vagas#183]
## Empresa
A SIX CREATIVE é uma empresa de criação e produção de idéias em comunicação, integrando mídias e medindo resultados.
Fazemos isso utilizando tecnologia e criatividade para contar para as pessoas as idéias de sua marca, e monitoramos as reações destas pessoas, transformando isso em informação.

## Posição
Pleno

## Tipo de contratação
 Presencial, PJ

###### Obrigatórios
- 1 ano de experiência com Desenvolvimento iOS (ou ter algum projeto bacana pra mostrar);
- Trabalhar com REST API;
- Conhecimentos sólidos Objective-C ou Swift 3;
- Conhecimentos na plataforma XCode;
- Programação Orientada a Objetos- Respeitar UI, UX e Guidelines de design;
- Versionamento de código utilizando Git;
- Sólidos Conhecimentos em SQL;

###### Diferenciais
- Conhecimentos de Design Patterns;
- Conhecimento em Testes Funcionais;
- Projetos Open-Source

## Contato
Quem tiver dentro do perfil deve mandar o CV pra: victor@sixcreative.com.br com o assunto: Vaga Desenvolvedor iOS

**Comment by Viniciuscarvalho** [comment]
A vaga já foi preenchida @victorhugorch ?
