### ISSUE TITLE
 [SP - Alphaville] E-Deploy- Desenvolvedor iOS (Pleno e Sênior)

### ISSUE THREAD

**Issue by vcmoraesedeploy** [CocoaHeadsBrasil/vagas#184]
## Empresa
A e-Deploy está preparada para o desenvolvimento nas principais plataformas de mercado, entre elas iOS e Android.
Já participamos de grandes projetos e ajudamos empresas como Boehringer Ingelheim e Atlas Schindler a criar soluções móveis que hoje são essenciais para o bom desempenho
de suas equipes de campo.

## Descrição da vaga
Atuar no desenvolvimento de vários projetos novos, e em andamento. 

## Posição
Pleno e Sênior

## Tipo de contratação
Presencial, e somente PJ.

## Requisitos
Sólida experiência no desenvolvimento de aplicações mobile na plataforma iOS (iPhone e iPad) que envolvam integrações com serviços web internos, de clientes e/ou terceiros (APIs RESTful e SOAP).
Sólidos conhecimentos em controle de versão no Git (SVN, Jira e/ou TFS), gerenciamento de dependências do projeto, como por exemplo Cocoapods e publicação de versões na loja Apple Store.
Ter familiaridade com componentes de User Interface do iOS e com storyboards, xibs e autolayout.
Experiência em adaptações de layouts entre iPhone e iPad, além de conhecimento das guidelines de design e de desenvolvimento da Apple.
Ter conhecimentos em testes automatizados e inglês técnico (leitura).
Apoiar a área de desenvolvimento provendo informações para os desenvolvedores da equipe e participar da resolução de problemas encontrados no dia-a-dia de trabalho dos desenvolvedores iOS (iPhone e iPad) Junior, Pleno e Testers.

###### Obrigatórios
-Objective C
-Swift, 
-CocoaPods
-Auto Layout
-Git
-JSON
-MVC
-MVP 
-Arquitetura de Software.

###### Desejáveis
-Testes Unitários 
-VIPER
-Xamarin

###### Diferenciais
-Programação Reativa.
-MVVM

## Contato
victor.moraes@e-deploy.com.br

**Comment by vcmoraesedeploy** [comment]
@marcelofabri por favor atualizar para somente PJ, obrigado!

**Comment by Viniciuscarvalho** [comment]
A vaga já foi preenchida @vcmoraesedeploy ?
