### ISSUE TITLE
[Campinas - SP] Instituto Eldorado - Desenvolvedor iOS

### ISSUE THREAD

**Issue by serralvo** [CocoaHeadsBrasil/vagas#185]
## Instituto de Pesquisas Eldorado
O Instituto de Pesquisas Eldorado está em operação desde março de 1999 e dedica-se à Pesquisa e Desenvolvimento de novas tecnologias com foco em TI&Telecom, caracterizando-se como um provedor de soluções tecnológicas. Presente em três localidades, o Eldorado tem um ambiente que se destaca pela promoção da qualidade de vida, inovação, flexibilidade e processos bem estruturados, sendo classificado como uma das Melhores Empresas para Trabalhar em rankings como Você S/A e GPTW, mais recentemente estando presente na lista das Melhores Empresas para Começar a Carreira.
 
Como alguns os diferenciais do Instituto Eldorado, podemos citar: Proximidade com a Universidade/meio acadêmico; projetos desafiantes e em contato com tendências na área de tecnologia; Plano de desenvolvimento bem estruturado e Programas de apoio a capacitação.

[Saiba mais sobre o Instituto Eldorado](http://www.eldorado.org.br/)

## Descrição da vaga
Atuação em projeto desenvolvido em parceria com grandes empresas nacionais e multinacionais, para implementação de soluções na área de saúde (back-end e aplicativos iOS).

## Posição
Júnior, Pleno.

## Tipo de contratação
CLT

###### Obrigatórios
* Formação superior em Engenharia/Ciência da Computação, Sistemas de Informação ou similar;
* Experiência com o desenvolvimento de aplicações nativas para iOS;
* Experiência em desenvolvimento com Objective-C/Swift e Xcode;

###### Desejáveis
* Desejável experiência com consumo de webservice e jsons em aplicativos móveis;

###### Diferenciais
* Experiência em AWS e aplicativos publicados na App Store serão diferenciais;

## Como aplicar
Enviar currículo para curriculo@eldorado.org.br – Código: CPS_iOS

## Contato
Enviar currículo para curriculo@eldorado.org.br – Código: CPS_iOS ou http://www.eldorado.org.br/oportunidade/analistaengenheiro-de-desenvolvimento-ios/

**Comment by Viniciuscarvalho** [comment]
A vaga já foi preenchida @serralvo ?
