### ISSUE TITLE
[SP - Faria Lima] Desenvolvedor iOS

### ISSUE THREAD

**Issue by joaofranco** [CocoaHeadsBrasil/vagas#186]
## Easy
Easy é uma das maiores empresa de mobilidade da América Latina. Fundada em 2011 no Rio de Janeiro como Easy Taxi. 

Atualmente a Easy e Cabify anunciaram uma aliança que irá proporcionar novos desafios. 

## Posição
Senior

## Tipo de contratação
Presencial, CLT

###### Obrigatórios
-Swift ou Objective C com vontade de aprender Swift
-GIT
-JSON
-Testes unitários

###### Desejáveis
-MVC, MVVM, MVP ou Viper
-Arquitetura de Software
- Conhecimentos de Design Patterns;
- Migração de Objc para Swift
- Criação de pods
- Continuous Integration / Fastlane

###### Diferenciais
- Resolver problemas de mobilidade
- Criativo e Inovador
- Pró-atividade

## Benefícios
- Mesa de pebolim
- Vale Refeição;
- Plano de Saúde;
- Horário Flexível;
- Ambiente de trabalho;

## Contato
joao.franco@easytaxi.com.br

**Comment by Viniciuscarvalho** [comment]
A vaga já foi preenchida @joaofranco ?

**Comment by joaofranco** [comment]
Existia 1 vaga para pleno e 1 para senior. 
Preenchemos a de Pleno. Ainda precisamos de 1 senior.

O que faço ?
- Edito Issue? Crio novo ?

**Comment by Viniciuscarvalho** [comment]
Só edita a issue @joaofranco

**Comment by reprotector** [comment]
Olá @joaofranco A vaga ainda está aberta?
