### ISSUE TITLE
DESENVOLVEDOR iOS SÊNIOR – HOME OFFICE

### ISSUE THREAD

**Issue by RADARProfissional** [CocoaHeadsBrasil/vagas#188]
A Radar Profissional, Consultoria de Recrutamento & Seleção e Terceirização de mão de obra, busca profissionais para atuar em um dos nossos clientes. 

Requisitos:
•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Conhecimento de conceitos orientados a objetos, integrações contínuas e Git;
•	Paixão por Desenvolvimento de Software e forte interação e senso de design;
•	Experiência com Multi-Threading e gerenciamento de memória específicos para dispositivos móveis;
•	Inglês Avançado; 
•	Será considerado como diferencial, profissionais que tenham:
- Experiência com Apple Store e Processo de Distribuição;
- Aplicação aprovada na Apple Store; 
- Conhecimento SQL e / ou vontade de aprender;
- Experiência em trabalho com teste A / B;
- Conhecimento Firebase, ferramentas de teste automatizadas e Swift 3.
Responsabilidades:
•	Certificar que o aplicativo seja testado de acordo com as diretrizes da empresa; 
•	Publicar o aplicativo; 
•	Acompanhar as ferramentas de análise / crashlytics para aprimoramento contínuo de aplicativos;
•	Trabalhar juntamente com o UX e outros desenvolvedores visando oferecer a melhor experiência ao usuário.

Contratação: PJ
Local: ***Home Office***
Interessados: Enviar currículo para cristiane@radarprofissional.com.br 
Visite nosso site: www.radarprofissional.com.br 

Por gentileza, INDIQUE e COMPARTILHE. 

#RADAR Profissional# VAGAS# INDIQUE# COMPARTILHE#

**Comment by Uragawa** [comment]
Quem é o cliente? De acordo com as <a href="https://github.com/CocoaHeadsBrasil/vagas/blob/master/README.md">regras</a> do canal/repositório, precisa constar essa informação.

**Comment by marcelofabri** [comment]
Fechando por não seguir as regras da comunidade.
