### ISSUE TITLE
[Remoto] Desenvolvedor iOS Pleno ou Sênior ( Objective-C)

### ISSUE THREAD

**Issue by DanielBAmorim** [CocoaHeadsBrasil/vagas#189]
## Descrição da vaga
Projeto de aproximadamente 2 meses para desenvolver aplicativos utilizando Objective-C

## Posição
Pleno ou Sênior

## Tipo de contratação
Remoto, PJ. 

###### Obrigatórios
- 3 anos de experiência em Objective-C
- GIT

## Benefícios
- Flexibilidade de Horário.

## Como aplicar
Enviar email para daniel.amorim@mobrj.com.br com o CV e valor por hora pretendido.
Colocar no assunto : Vaga desenvolvedor iOS - Objective-C

## Contato
daniel.amorim@mobrj.com.br

**Comment by Viniciuscarvalho** [comment]
A vaga já foi preenchida @DanielBAmorim ?
