### ISSUE TITLE
[São Paulo - Berrini] Desenvolvedor iOS Pleno e Sênior

### ISSUE THREAD

**Issue by Vivianematos** [CocoaHeadsBrasil/vagas#19]
Descrição da vaga

Local

Zona Sul - Berrini

Benefícios

frigobar sempre cheio :P
sala de jogos
Requisitos

Obrigatórios

Experiência em programação iOS.
Vivência na utilização de Git.
Ser pró ativo e gostar de trabalhar como time.
Gostar de participar de discussões estratégicas e não somente técnica.
Possuir e enviar portfólio com apps desenvolvidos para iPhone e/ou iPad.

Desejáveis
Experiência com projetos utilizando Scrum.
Ter trabalhado com TDD.
Conhecimento em programação Swift.
Contratação

PJ 

Nossa empresa

Aqui na GingaOne somos um grupo de profissionais extremamente qualificados, dedicados e apaixonados pelo que fazem, que acreditam no poder transformador da tecnologia e que querem deixar sua marca neste admirável mundo novo.

Como se candidatar

Por favor envie um email para viviane.matos@gingaone.com com seu CV anexado e Pretensão PJ. - enviar no assunto: Vaga iOS

**Comment by mbrufatto** [comment]
Aceitam trabalhadores remotos?

**Comment by Vivianematos** [comment]
Olá,

Podemos avaliar tb.

*Viviane Matos Bonifacio*
Recursos Humanos

+ 55 11 5505 2923
+ 55 11 97653-6975

Skype: viviane.bonifacio2
www.gingaone.com


2016-05-12 22:54 GMT-03:00 mbrufatto <notifications@github.com>:

**Comment by Viniciuscarvalho** [comment]
@Vivianematos a vaga ainda está aberta? Se já estiver sido preenchida, poderia fechar a issue? 👍
