### ISSUE TITLE
[SP - Campinas] inGaia - Desenvolvedor iOS 

### ISSUE THREAD

**Issue by inGaia-Fernanda** [CocoaHeadsBrasil/vagas#190]
A[ inGaia ](http://www.ingaia.com.br/) é o único marketplace do mercado imobiliário brasileiro, com uma plataforma de negócios completa para imobiliárias e corretores de imóveis.

Desenvolve ferramentas inteligentes e reúne a maior comunidade imobiliária do país, com mais de 30.000 corretores, 5.000 imobiliárias e 44 redes, conectando-os a uma dinâmica rede de informações, serviços e parceiros. 

**Sobre a Vaga:**

Cargo: Desenvolvedor iOS
Vaga para atuar em Campinas (presencial) - contratação CLT.
Horário de trabalho: Segunda a sexta-feira das 09h00 às 18h00 (com 1 hora para refeição);
Remuneração: à combinar;
Vale refeição: R$484,00 (cartão mensal);
Vale transporte;
Assistência médica (Unimed);
Assistência odontológica (Uniodonto);

Você irá trabalhar com uma equipe que respira tecnologia, pois ela está presente no nosso dia a dia como a razão e o meio para seguirmos inovando.

O desenvolvedor é a pessoa que transforma nossas idéias em realidade, aqui você participará do desenvolvimento, aplicando todo seu conhecimento e será apoiado por nossa equipe de especialistas.

O conhecimento técnico e a experiência são importantes, mas valorizamos as pessoas empreendedoras, criativas, comunicativas, sonhadoras e que realmente queiram fazer a diferença.

**Requisitos:**
- Estar cursando ou concluído a graduação na área de T.I.
- Experiência mínima de 2 anos com desenvolvimento mobile;
- Experiência em:
. Swift;
. REST;
. Git;
. Push Notifications;
. Noções de usabilidade;
. Publicação de aplicativos;
. Testes automatizados;

**Desejável:**
- Fabric;
- Google Analitycs;
- RxSwift;
- Android;

Se você se identificou com a inGaia, venha fazer parte desse time inovador!

**_Se candidate através: http://www.ingaia.com.br/vagas/   ou  cv@ingaia.com.br_**

**Comment by Viniciuscarvalho** [comment]
A vaga já foi preenchida @inGaia-Fernanda ?
