### ISSUE TITLE
[Blumenau] Desenvolver iOS - Sparta Labs

### ISSUE THREAD

**Issue by gugacorrea** [CocoaHeadsBrasil/vagas#191]
## Empresa
 A Sparta Labs está a 5 anos no mercado de desenvolvimento mobile e estamos procurando desenvolvedores com experiência em iOS, no desenvolvimento nativo.
O ambiente da empresa é bastante descontraído, buscamos sempre um ambiente harmonioso entre os membros do time e com liberdade de espaço e tempo. 

## Descrição da vaga
O desenvolvedor trabalhará em nosso escritório, que fica na região central de Blumenau, no edifício Ibiza. 

## Posição
Pleno, trabalhará em contato direto com os diretores da empresa.

## Tipo de contratação
Contratação por CLT.

## Requisitos
Conhecimento em desenvolvimento em Obj-C/Swift. 
Conhecimento com PS e Sketch. 

## Benefícios
Plano de saúde, VR e VT.

## Com quem você vai trabalhar
Diretamente com os diretores da empresa, em projeto de clientes de médio e grande porte.

## Como aplicar
As informações devem ser enviada para o e-mail abaixo. Após analise entraremos em contato para agendarmos uma conversa. 

## Contato
Entre em contato pelo e-mail: gustavo.correa@spartalabs.com.br

**Comment by Viniciuscarvalho** [comment]
A vaga já foi preenchida @gugacorrea ?

**Comment by gugacorrea** [comment]
Boa tarde Vicente,

Ainda não.

Atenciosamente,

Gustavo Corrêa
+55 47 9656-6785 | spartalabs.com.br

Em 24 de agosto de 2017 às 13:40:36, Vinicius Carvalho Marques (
notifications@github.com) escreveu:

A vaga já foi preenchida @gugacorrea <https://github.com/gugacorrea> ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CocoaHeadsBrasil/vagas/issues/191#issuecomment-324690248>,
or mute the thread

**Comment by reprotector** [comment]
Olá @gugacorrea A vaga ainda está aberta?

**Comment by gugacorrea** [comment]
Boa tarde @reprotector, tudo bem?

Sim, ainda estamos procurando desenvolvedores para nossa equipe.

**Comment by araujoraphael** [comment]
@gugacorrea, abriram possibilidade para trabalhar remotamente ?

**Comment by gugacorrea** [comment]
Boa tarde @araujoraphael, tudo bem? Estamos dando prioridade para desenvolvedores locais. Mas envie suas informações para nós, não estamos limitados a isso.
