### ISSUE TITLE
[SC - Joinville] TOTVS - Desenvolvedor iOS

### ISSUE THREAD

**Issue by carlosjunior** [CocoaHeadsBrasil/vagas#192]
## Empresa
A TOTVS é uma empresa brasileira de tecnologia, especialista no desenvolvimento de soluções de negócios para players de todos os portes. 

Nossas ferramentas são integradas e atendem tanto o core business quanto o back office dos nossos clientes, permeando toda a sua cadeia de valor, de ponta a ponta. Tudo para tornar o empreendedor mais competitivo em sua especialidade de atuação.

Para oferecer produtos que de fato tenham valor para o cliente, precisamos entender do segmento tão bem quanto ele. Por isso contamos com times especialistas em cada um de nossos nichos de atuação, responsáveis por entender o mercado em profundidade para propor soluções cada vez mais aderentes. 

Nos desafiamos também a sempre estar um passo à frente de suas necessidades e ir sempre além do que já foi feito em termos de inovação e soluções disruptivas.

## Descrição da vaga
Procuramos por desenvolvedores que tenham inovação no seu DNA e sejam loucos o suficiente para pensar em soluções “fora da caixa”.

## Posição
Pleno-sênior

## Tipo de contratação
Presencial, CLT

## Procuramos profissionais que

- Que goste de codar em Swift J e nem tanto em Objetive C L;
- Queira viver em um ambiente dinâmico e que constantemente vai te desafiar com a evolução e superação;
- Assume o risco de forma responsável e "se atire";
- Que goste de TDD e não se sinta bem de liberar releases sem testes automatizados;
- Que pense sempre na melhor solução, pois o nosso sucesso é o sucesso dos nossos clientes;
- Quando acertar, acelera! Mas se errar, admite, corrige rápido, aprende e evolui;
- Entenda que seu trabalho é fundamental para o êxito da equipe;
- Que goste de autonomia e ambiente de trabalho flexível;
- Saiba ler e escrever em inglês, quem sabe até conversar :)

## Tecnologias que trabalhamos:

- Swift;
- Autenticação OAuth 1.0/2.0;
- Consumo de serviços API REST JSON;
- Desenvolvimento de Testes Automatizados aplicando TDD;
- Armazenamento em banco de dados (SQL Lite, Realm, etc).

## O que seria muito legal se você conhecesse

- Ter desenvolvido ou participado da concepção de framework ou SDKs.
- Nossa a lista é grande, mas se você se identifica com a maioria e não tem medo de apreender as demais , venha fazer parte deste desafio que temos uma grande missão pela frente.

## Formação acadêmica

- Superior em andamento ou concluído na área de TI

## Como aplicar

Se candidatar através do link:
https://www.linkedin.com/jobs/view/407872100/

**Comment by reprotector** [comment]
Olá @carlosjunior A vaga ainda está aberta?
