### ISSUE TITLE
[RJ - Barra da Tijuca] **Gazeus Games**- Desenvolvedor iOS Sênior 

### ISSUE THREAD

**Issue by AlinePian** [CocoaHeadsBrasil/vagas#193]
## Empresa
Gazeus Games é a mais poderosa liga de super heróis digitais, disfarçada de desenvolvedora e publicadora brasileira de jogos mobile, na luta em prol da diversão!

**## Descrição da vaga**
Desenvolvimento e manutenção de aplicativos para iPhone, iPad e iPod.

**## Posição**
Sênior

**## Tipo de contratação**
 Presencial, CLT

**## Requisitos**
- Conhecimentos sólidos de estruturas de dados, algoritmos e arquitetura de sistemas;

- Capacidade de aprender rapidamente diferentes linguagens e tecnologias;

- Conhecimento da língua inglesa.

**###### Obrigatórios**
- Objective-C

- Xcode

- iOS SDK / API Cocoa Touch em geral

- Familiaridade com componentes de UI do iOS

- Familiaridade com Autolayout e adaptação de layout entre diferentes tamanhos de tela

- Conhecimentos das melhores práticas e guidelines de desenvolvimento da Apple

- Sólidos conhecimentos de Orientação a Objetos

- Experiência de uso de sistemas de versionamento

**###### Desejáveis**
- Experiência com Git

- Familiaridade com o processo de aprovação e submissão de Apps para a App Store

- Swift

- Familiaridade com construção de Frameworks

**###### Diferenciais**
- Sólidos conhecimentos em C e/ou C++

- Ter Apps publicados na App Store

- Noções de Gradle

- Noções de Android SDK, Android NDK, Unity3D, Android Studio

- Experiência com desenvolvimento Android;

**## Benefícios**
- Plano de Saúde e Odontológico Bradesco
- VR (33,66)
- VT

**Outros benefícios:**
- Shiatsu
- Snacks oferecidos pela empresa
- Horário flexível
- Day off no dia do aniversário

## Com quem você vai trabalhar
No time de desenvolvimento Mobile

## Como aplicar
https://gazeus.workable.com/j/1F7866C3D0

## Contato
aferrer@gazeus.com

**Comment by reprotector** [comment]
Olá @AlinePian A vaga ainda está aberta?

**Comment by AlinePian** [comment]
@reprotector No momento não está aberta, mas se tivermos candidatos potenciais pode ter chances de contratar independente da vaga estar aberta ou não.
