### ISSUE TITLE
[SP - Valinhos] - KERIX - Desenvolvedor iOs Pleno ou Sênior

### ISSUE THREAD

**Issue by Fernandolinokerix** [CocoaHeadsBrasil/vagas#194]
A KERIX é uma empresa consolidada no desenvolvimento de softwares para grandes empresas, e está em pleno desenvolvimento da área de mobile, já com o lançamento em parceria com um instituto de pesquisa e desenvolvimento de um aplicativo revolucionário para um nicho de mercado.

## Descrição da vaga
Desenvolvedor iOs

## Posição
Pleno ou Sênior

## Tipo de contratação
Contratação PJ. 

## Requisitos
Desenvolvimento de aplicativos iOS nativo, participação em projetos, testes etc.
Ter experiência em Swift / Objective-C, Xcode, CocoaPods, Google Firebase, publicação App Store, padrões de projeto, lógica e afins. 

## Benefícios
Equipe de trabalho diferenciada, oportunidade de crescimento e clima organizacional diferenciado

## Como aplicar
enviar currículo com pretensão valor/hora como PJ e disponibilidade para contato@kerix.com.br

## Contato
Fernando Lino 19 38491662 - contato@kerix.com.br

**Comment by reprotector** [comment]
Olá @Fernandolinokerix .  A vaga ainda está aberta?
