### ISSUE TITLE
[São Paulo] Desenvolvedor IOS

### ISSUE THREAD

**Issue by MiraEduc** [CocoaHeadsBrasil/vagas#195]
## Empresa
A Mira é uma Startup que busca solucionar uma questão básica em todo o mundo: educação. Desenvolvemos ferramentas com o objetivo de facilitar a vida de professores e gestores, envolvendo os responsáveis e garantindo uma melhora no processo educativo dos alunos de modo escalável e com baixo custo.
Somos uma empresa engajada por um propósito maior, fazer a diferença na educação pública do Brasil. Somos inconformados com o presente e queremos construir um futuro diferente.
Se você quer que seu trabalho cause impacto na sociedade e você sinta orgulho disso, seu lugar é aqui.
Queremos inspirar outras pessoas, contribuir positivamente para o futuro de nosso país. Para isso contamos com colaboradores engajados, apaixonados pela nossa causa e motivados pelo impacto social.

UM POUCO SOBRE A NOSSA CULTURA:
•	Somos orientados pela experiência de nosso usuário. O problema do nosso usuário é o nosso problema;
•	Nosso foco é resultado, contamos com uma equipe altamente capaz e disposta para atingi-lo;
•	Estamos sempre em busca de melhorias;
•	Estimulamos o “pensar fora da caixa” e valorizamos as boas ideias;
•	Nossa equipe é colaborativa e prestativa;
•	Valorizamos as singularidades e respeitamos as diferenças;
•	Damos a todos autonomia e liberdade para colocar suas ideias em prática;
•	Nossos Miranautas se sentem donos do projeto e realizados a cada entrega;
•	Reconhecemos nossos erros, e mais do que isso, estamos sempre abertos a mudança.
•	Aqui tudo é compartilhado, nossos resultados, ideias, dúvidas, gostamos de ouvir a opinião de nosso time, independente da posição que ocupe.
Se você gosta de desafios, quer trabalhar com as melhores tecnologias e participar da construção do nosso projeto, veja abaixo detalhes do job:

## Descrição da vaga
Atividades: 
Desenvolvimento de software na plataforma XCode utilizando a linguagem Swift.

## Posição
 Junior/Pleno

## Tipo de contratação
 Presencial e CLT.

###### Obrigatórios
Bom conhecimento no desenvolvimento iOS em swift;
Amor pelo desenvolvimento de software;
Preocupação em não só encontrar uma solução para o problema, mas a melhor;
Vontade de aprender; 

###### Desejáveis
Conhecimentos em testes unitários e instrumentais;
Conhecimentos em arquiteturas baseadas em negócio, como a Clean Architecture;
Conhecimento em Realm;
Arquitetura MVVM
Conceitos de Solid;
Ter um app publicado;

## Benefícios

•	Vale Refeição, Vale Transporte e Auxílio Creche;
•	Assistência Médica – 100% custeada pela empresa;
•	PLR – Atrelado a metais gerais;
•	Ambiente divertido e casual;
•	Dresscode Informal;
•	Bem-estar e diversão: Happy Hour toda sexta, Snacks à vontade, sala de descanso, video game, ginástica laboral e quick massage;
•	Desconto com escola de idiomas;
•	Ótima Localização – Ao lado metrô Santa Cruz;

## Como aplicar
Interessados enviar cv atualizado, com nome da vaga no assunto para larissa.rocha@mira.vc

## Contato
larissa.rocha@mira.vc

**Comment by MiraEduc** [comment]
N/A

**Comment by reprotector** [comment]
Olá @MiraEduc. A vaga ainda está aberta?

**Comment by MiraEduc** [comment]
Olá Boa Tarde,

A vaga já foi finalizada.

Atte.

Larissa Rocha
Analista de RH

[image: Imagem inline 2]


2017-10-25 12:14 GMT-02:00 Renan Protector <notifications@github.com>:
