### ISSUE TITLE
[SP - Vila Olímpia] Moobie - Desenvolvedor iOS Pleno/Sênior

### ISSUE THREAD

**Issue by fpg1503** [CocoaHeadsBrasil/vagas#196]
## Empresa
Moobie - startup de plataforma de compartilhamento de carro de pessoa para pessoa. Estamos em uma fase única early stage com possibilidade de influenciar o rumo do produto e da experiência dos usuários interagindo com todo o time (10 pessoas hoje).

## Descrição da vaga
Desenvolvedor irá ser responsável junto a mais um desenvolvedor pelo desenvolvimento de todas as novas features no nosso aplicativo iOS recém lançado e manutenção do mesmo.
Participará de todas as reuniões de planejamento das sprints e contribuirá com recomendações das melhores soluções a serem implementadas e definição das estimativas.

## Posição
Desenvolvedor iOS Pleno/Sênior

## Tipo de contratação
CLT - 44hs semanais

###### Obrigatórios
- Conhecimentos de lógica de programação e orientação a objetos
- Experiência com Swift
- Experiência com UIKit
- Estar disposto a aprender sempre
- Raciocínio analítico extremamente desenvolvido
- Conhecimento sobre sistema de controle de versão (Git)

###### Desejáveis
- Experiência trabalhando com metodologias de desenvolvimento ágil (Scrum, uso de PRs, Code Review)
- Conhecimentos básicos sobre programação funcional
- Capacidade de se comunicar em inglês (interações com o time da Apple Store etc)
- Conhecimentos sobre programação reativa (i.e. Rx, ReactiveCocoa)
- Experiência com escrita de layouts programaticamente (i.e. Cartography, PureLayout, ReLayout)

###### Diferenciais
- Não gostar de storyboard é um plus
- Experiência com Fastlane
- Testes (i.e. XCTest, Quick, Nimble)

## Benefícios
- Vale Refeição
- Plano de saúde (com contribuição mínima)
- Flexibilidade de horário
- Ambiente startup (mesa de ping pong, bolo da tia Marisa, happy hours, etc)

## Com quem você vai trabalhar
| ![](https://github.com/fpg1503.png?size=100) | ![](https://github.com/leonardo2204.png?size=100) | ![](https://github.com/danmalafaia.png?size=100) | ![](https://github.com/caiohcarleto.png?size=100) | ![](https://github.com/eserete.png?size=100) | ![](https://media.licdn.com/mpr/mpr/shrinknp_100_100/AAEAAQAAAAAAAAfyAAAAJGI1MjFhMjUzLWIzZDAtNDUyYi1iYjM5LTljMTI4YjJhMmNjNQ.jpg) |
| --- | --- | --- | --- | --- | --- |
|[fpg1503](https://github.com/fpg1503) |[leonardo2204](https://github.com/leonardo2204) |[danmalafaia](https://github.com/danmalafaia) |[caiohcarleto](https://github.com/caiohcarleto) |[eserete](https://github.com/eserete) |[tamylin](https://www.linkedin.com/in/tamy-lin-28730b/) |

| ![](https://media.licdn.com/mpr/mpr/shrinknp_100_100/p/4/000/16f/1a8/108b05a.jpg) |
| --- |
|[uribeteofilo](https://www.linkedin.com/in/uribeteofilo/) |

## Como aplicar
- Entre em contato conosco (informações abaixo) e passe seu CV
- Analisaremos seu CV e enviaremos um desafio caso seu perfil esteja alinhado com o que estamos procurando
- Você deverá fazer um [pequeno desafio](https://github.com/moobie/desafio-app) para que conheçamos mais sobre seu jeito de codificar e suas habilidades
- Conversa com o time

## Contato
Para mais informações sobre a vaga mande um email para francesco@moobie.com.br ou fale comigo pelo [Slack do iOS Dev BR](http://iosdevbr.herokuapp.com) (@fpg1503)

**Comment by reprotector** [comment]
Olá @fpg1503 A vaga ainda está aberta?

**Comment by fpg1503** [comment]
@reprotector está sim!
