### ISSUE TITLE
[BA - Salvador] MTM Tecnologia - Desenvolvedor iOS Pleno/Sênior

### ISSUE THREAD

**Issue by ramilton** [CocoaHeadsBrasil/vagas#197]
## Empresa
A MTM Tecnologia desenvolve e licencia soluções inovadoras de m-health para grandes instituições de saúde nacionais e internacionais. As nossas soluções permitem que essas instituições possam incorporar tecnologias móveis aos seus processos hospitalares visando apoiar médicos, pacientes e funcionários.

## Descrição da vaga
Desenvolvimento de software nativo utilizando a linguagem Swift.

## Posição
Pleno/sênior

## Tipo de contratação
Presencial com possibilidade de remoto.
CLT

###### Obrigatórios
Desenvolvimento iOS em swift;

###### Desejáveis
Git
Metodologias de desenvolvimento ágil

## Benefícios
Vale Refeição
Vale Transporte
Plano de saúde
Flexibilidade de horário

## Como aplicar
Interessados enviar cv atualizado para curriculos@mtmtecnologia.com.br

## Contato
Ramilton Silva
ramilton.silva@mtmtecnologia.com.br

**Comment by reprotector** [comment]
Olá @ramilton A vaga ainda está aberta?
