### ISSUE TITLE
[RJ - Centro] Montreal Informática - Desenvolvedor iOS Pleno

### ISSUE THREAD

**Issue by viniciusromeiro** [CocoaHeadsBrasil/vagas#199]
## Montreal Informática:
A Montreal foi fundada em 1987 e desde então vem trazendo ao mercado a sua marca de criatividade. Hoje posicionada entre as 15 maiores empresas de tecnologia do Brasil, como integradora, a Montreal sempre se destacou pela inovação.

## Posição:
Pleno

## Tipo de contratação:
Presencial, CLT.

###### Obrigatórios
Necessários mais de 3 anos de experiência comprovada no desenvolvimento de aplicativos iOS nativos utilizando Objective C ou Swift.

###### Desejáveis
Padrões de Projeto (Design Patterns) MVC e MVVM, Json/XML, APIs RESTfull e SOAP, Conhecimento básico de SQL, software de controle de versão (SVN, GIT). Adaptação de layouts para iPhone e iPad, Push Notification, testes unitários (TDD) e automatizados (UI). 

###### Diferenciais
Geração de certificados iOS, publicação (TestFlight e AppStore) e Xamarin.

## Benefícios
Plano de saúde, Plano odontológico, Vale Refeição e Vale transporte.

## Como aplicar
Enviar e-mail para: vinicius.romeiro@montreal.com.br

## Contato
Para mais informações acesse o site: www.montreal.com.br

**Comment by Viniciuscarvalho** [comment]
Por favor @viniciusromeiro depois colocar a descrição da vaga nos moldes do temos no nosso template, sem apagar os '#'. Obrigado 👍

**Comment by reprotector** [comment]
Olá @viniciusromeiro A vaga ainda está aberta?

**Comment by viniciusromeiro** [comment]
Está sim @reprotector
