### ISSUE TITLE
[Remoto] Desenvolvedor iOS Pleno/Senior | Onyo

### ISSUE THREAD

**Issue by ppgsalomao** [CocoaHeadsBrasil/vagas#2]
## Descrição da vaga

Customers’ experiences at food courts will never be the same. That's the reason we’re looking for an iOS Developer to join the team that will put in our customers’ hands the absolute power of choice of what and when to eat in a crowded food court. You’ll design, architect and ship, on a global basis, an amazing App entirely focused on our customers' experience.

## Local

Remoto

## Benefícios

- Todos os previstos em lei (13º, Férias, Vale Transporte)
- Vale Refeição
- Plano de Saúde e Odontológico
- E mais ... venha conhecer =)

## Requisitos

What you'll do:
* Contribute with the whole product conception and development, from design to delivering the experience to our customers.
* Contribute and implement new features from scratch, along with improving already existing code.
* Have ownership over the product, and fight for it's improvement and success.
* Interact with all teams, from Backend to Customer Success, to help create the best App ever.
* Write clean, maintainable and testable code while continually iterating and shipping.
* Solve technical debits, even when they were not created by you.

What we’re looking for:
* Experience with iOS development with Swift.
* Strong understanding of iOS Platform, frameworks and user experience.
* Desire to create products that are as beautifully built as they are designed.
* Open Source friendly. Contributions to open source projects is a plus.
* Previous remote experience is a plus.

## Contratação

CLT

## Nossa empresa

About us:
* We have a strong culture enforced by our values. Wanna know all 8? Come talk to us! For now, let us tell you 3 of them: 
  * “We are learning machines”.
  * “We work as a team, valuing all individual contributions”.
  * “We are transparent in our dealings”.
* We give a high value to the power of choice in all matters, from the code design to life choices like where do you want to work from.
* We work remotely, from any place, anywhere.
* We love challenges, and we have them daily for lunch or dinner.
* We really care about our quality of life.
* We believe we have the best team ever, and you could be part of it.

## Como se candidatar

Por favor envie um email para pedro@onyo.com com seu CV anexado e Link para o LinkedIn.

**Comment by barbosa** [comment]
Fala @ppgsalomao, tudo certo?

A vaga ainda está aberta? Só para saber se fechamos a issue ou mantemos aberta.

Obrigado!

**Comment by ppgsalomao** [comment]
Gugão,

Ta aberta sim!

Abraços,

**Comment by thssolution** [comment]
Fala @ppgsalomao, tudo certo?
Seria CLT?

**Comment by ppgsalomao** [comment]
@thssolution É CLT sim.

**Comment by Viniciuscarvalho** [comment]
@ppgsalomao beleza? A vaga ainda está aberta? Se for o caso de já ter sido preenchida, pode fechar a issue 👍
