### ISSUE TITLE
[São Paulo - Vila Hamburguesa] Desenvolvedor iOS | Easy Taxi

### ISSUE THREAD

**Issue by alexkawaharada** [CocoaHeadsBrasil/vagas#20]
## Descrição da vaga

Buscamos um Desenvolvedor ou Desenvolvedora iOS para trabalhar no time de mobile da Easy Taxi. Que sejam comprometidos com o trabalho e humildes para trabalhar em um time extremamente horizontal.
Somos uma startup. Então não precisa se preocupar com dress code a menos que esteja pensando em vir trabalhar nú.

## Local

Matriz Easy Taxi.

Avenida Queiroz Filho, 1700 - Vila Hamburguesa, Próximo a estação Villa Lobos / Jaguaré

## Benefícios

- VR ( R$ 18,00 ) + VT+ Plano de Saúde Amil 100% Coberto pela empresa + PO + Seguro de vida
- Ambiente informal ( Tênis, camiseta, bermuda, chinelo )

## Requisitos

Conhecimento em:

- GIT
- Objective-C
- Rest

Desejáveis
- Ferramentas de integração contínua
- Alguma linguagem para escrever scripts de automatização
- Swift (Não precisa ter vasta experiência, até porque isso é um pouco impossível)

Diferenciais
- Inglês

## Contratação

CLT Full  a combinar

## Nossa empresa

A Easy Taxi é o maior aplicativo de chamada de táxi da América Latina. Criada no Brasil em junho de 2011, a empresa nasceu com o objetivo de transformar o mercado de táxis. Nosso aplicativo permite que passageiros e taxistas possam ser conectados de uma forma rápida e prática. Não trabalhamos para atingir metas, trabalhamos por um propósito.

## Como se candidatar

Por favor envie um email para alex.kawaharada@easytaxi.com.br com o título Dev.iOS

**Comment by Viniciuscarvalho** [comment]
@alexkawaharada a vaga já foi preenchida? Se sim, pode fechar a issue? 👍

**Comment by alexkawaharada** [comment]
Sim Vinicius, vou fechar a vaga, obrigado
Em 12 de jul de 2016 19:58, "Vinicius Carvalho Marques" <
notifications@github.com> escreveu:
