### ISSUE TITLE
[Porto Alegre, RS] Superplayer - iOS Developer

### ISSUE THREAD

**Issue by robsondealmeida** [CocoaHeadsBrasil/vagas#200]
O [Superplayer](https://www.superplayer.fm/) é um serviço de streaming de música com a missão de tornar cada momento da vida das pessoas mais especial através da trilha sonora perfeita. Hoje temos mais de 1,5 milhões de usuários e 4 milhões de downloads em nossos aplicativos para as plataformas iOS e Android. Fomos acelerados globalmente pelo Google e fazemos parte da Movile, a maior empresa de serviços móveis da América Latina (iFood, PlayKids, Apontador, entre outros).
<br/><br/>

## Descrição da vaga

Buscamos um iOS Developer capaz de arquitetar e construir interfaces que proporcionem a melhor experiência em aplicativos de música da plataforma iOS, que seja apaixonado por aprender e codificar (em Swift e Objective-C) e que goste de pensar no produto além das linhas de código.

Ela/ele será responsável por pensar, contribuir no planejamento e desenvolver novas funcionalidades no Superplayer para plataforma iOS, trabalhar junto com nosso time de engenheiros na arquitetura e definição de soluções de alta escala e alta disponibilidade e utilizar as melhores práticas e tecnologias para escrever código que se orgulhará de ler amanhã. :)
<br/>

## Tipo de contratação
Presencial, CLT.
<br/>

## Responsabilidades

- Pensar, contribuir no planejamento e desenvolver novas funcionalidades no Superplayer para iOS.
- Garantir, junto com nosso time de designers, a melhor experiência em aplicativos de música da plataforma.
- Utilizar as melhores práticas e tecnologias para escrever código em Swift e Objective-C.
- Trabalhar junto com nosso time de engenheiros na arquitetura e definição de soluções de alta escala e alta disponibilidade.
- Resolver problemas e defeitos no Superplayer para iOS e cuidar para que eles nunca cheguem em ambiente de produção.
- Ajudar seus colegas nerds a resolver problemas complexos.
- Definir, junto com todo o time do Superplayer, os caminhos de nossos produtos e nosso processo de desenvolvimento.
<br/>

## Requisitos

- Paixão em escrever código e pela plataforma iOS.
- Graduado(a) ou graduando(a) em alguma faculdade de informática: engenharia de software, ciências da computação, sistemas de informação, processamento de dados, análise de sistemas ou qualquer outra que ensine que 1 + 1 não é 2.
- Vivência com desenvolvimento de aplicativos para plataforma iOS.
- Domínio de conceitos de OOP e conhecimento em conceitos de Functional Programming.
- Conhecimento sobre os guidelines de desenvolvimento e usabilidade da plataforma iOS.
- ♡ Git.
- Habilidade de desenvolver aplicativos do seu início ao fim (desde Create a new Xcode project até fazer o upload do IPA).
- Capacidade de planejar e desenvolver seu trabalho focando os objetivos estabelecidos em conjunto.
- Se sentir confortável com arquiteturas de desenvolvimento, tais como, MVP, MVC, MVVM, MVQC (MV Qualquer Coisa).
- Vivência com desenvolvimento em ambientes e times ágeis.
- Disponibilidade para trabalho em tempo integral.
<br/>

## Benefícios
Plano de saúde, VA/VR e FIFA, [Tower Fall](http://www.towerfall-game.com/) e [Overcooked](https://www.playstation.com/en-us/games/overcooked-ps4/)
<br/>

## Como aplicar
Se você se interessou, manda seu currículo, LinkedIn e/ou GitHub para **jointheband@superplayer.fm** com o assunto **iOS Developer**.
<br/>

**Comment by reprotector** [comment]
Olá @robsondealmeida A vaga ainda está aberta?

**Comment by robsondealmeida** [comment]
@reprotector Esta não. Mas já temos uma outra para iOS Developer aberta 😄 
Manda e-mail e vamos conversar!
