### ISSUE TITLE
[SP - Morumbi] Nextel - iOS Developer Specialist

### ISSUE THREAD

**Issue by jethern** [CocoaHeadsBrasil/vagas#202]
## Empresa
 Com cobertura nacional para voz e dados e oferta de 4G nos mercados São Paulo e Rio de Janeiro, a Nextel investe continuamente em inovação e tecnologia que garantem a rede de telefonia móvel mais moderna e robusta do país. Presente no Brasil desde 1997, a operadora tem mais de 3,5 milhões de clientes com acesso a um extenso portfólio de planos e serviços. O mais recente é o Nextel Happy, uma plataforma 100% digital que dá total autonomia aos clientes para comprar e alterar os planos de internet e voz, escolher a forma de pagamento, acompanhar o consumo e mudar sempre que quiser.

# Currently we are looking for a Senior iOS developer.

## Responsibilities

- Design and create world class iOS applications;
- Lead and deliver high scale projects end to end;
- Work in cross country and cross team development projects;
- Build a team of developers and mentor junior team members;
- Participate in an Agile/SCRUM environment;
- Effectively communicate technical details and changes to team members;
- Bring the innovations to customer projects and daily live.

## Essential Skills and Experience

- 3+ years’ experience in designing and creating native iOS applications using Objective-C and/or Swift in Xcode;
- Experience interfacing with RESTful web services;
- Familiarity with git versioning system and GitHub;
- Discuss mobile UX from both a developer’s and end user’s perspectives;
- Feel ownership over everything you deliver;
- Good communication skills, both within and outside the team;
- Good written and verbal English skills.

### Desired Skills and Experience

- High interest in the field of mobile, technology and usability;
- Writing unit and UI tests for applications using TDD or BDD;
- Have examples of your own mobile applications;
- Familiarity with Xcode Server.

## Posição
Sênior

## Tipo de contratação
CLT Full

## Como aplicar
If interested, please send your CV to jether.alves@nextel.com.br with “iOS developer” in the subject line.

**Comment by reprotector** [comment]
Olá @jethern A vaga ainda está aberta?

**Comment by jethern** [comment]
@reprotector sim! manda seu CV ;)
