### ISSUE TITLE
[Belo Horizonte, MG] Desenvolvedor iOS Jr

### ISSUE THREAD

**Issue by gabrieloliva** [CocoaHeadsBrasil/vagas#203]
## AppProva
O AppProva foi criado em 2012, cresce mais de 300% ao ano e atualmente presta serviços para as principais escolas e grupos educacionais do país. Integrando o maior grupo de educação básica do Brasil, SOMOS Educação, impactamos a vida de mais de 1.500.000 alunos, professores e educadores.
 
Você fará parte do time de Soluções para a Educação Superior, em Belo Horizonte, responsável não só pelos produtos do AppProva, como também por todas as soluções educacionais da Editora Saraiva.
 
Acreditamos que o principal ativo e diferencial competitivo que existe para qualquer companhia são as pessoas e, por isso, fazemos questão de trabalhar somente com gente excelente. Se você quer gerar oportunidades para milhares de alunos e impactar a educação do Brasil, não perca a chance de juntar-se ao nosso time!

## Descrição da vaga
Estamos buscando um desenvolvedor para integrar nosso time de desenvolvimento mobile, especializado em iOS.

### Posição da Vaga
Junior

### Tipo de contratação
CLT

#### Obrigatórios:
- Swift [3~]
- MVC
- Cocoapods
- Alamofire
- Controle de versão com Git

#### Desejáveis:
- Testes unitários
- Arquitetura MVVM / VIPER
- Conhecimentos em Android
- Quick (test framework)
- RxSwift
- Firebase

#### Diferenciais:
- Projetos opensource
- React Native

## Benefícios
- Vale transporte
- Vale alimentação e refeição
- Plano de saúde

## Como aplicar
https://appprova.recruiterbox.com/jobs/fk0fhz6/

**Comment by reprotector** [comment]
@gabrieloliva, Falta descrição da posição da vaga (jr, pleno, sr) e tipo de contratação (CLT, PJ)

**Comment by gabrieloliva** [comment]
@reprotector a posição já estava implícita no título, por isso não coloquei. Mas ambas já foram atualizadas 😄

**Comment by robson-nunes** [comment]
Esta posição ainda esta em aberto?

**Comment by gabrieloliva** [comment]
@robson-nunes hey! Acabamos de fechá-la. Mas iremos abrir outras num futuro próximo! Abracos :)
