### ISSUE TITLE
[Barueri, SP] iOS Developer

### ISSUE THREAD

**Issue by otaviommendes** [CocoaHeadsBrasil/vagas#206]
## Descrição da vaga

Temos uma vaga para desenvolvedor iOS para trabalhar no projeto **Next do Bradesco**.

## Local

Barueri, SP

## Posição
Pleno ou senior.

## Tipo de contratação
CLT ou PJ. 

## Como se candidatar

Por favor envie um email para otavio.mendes@gingaone.com com seu CV anexado - enviar no assunto: Vaga iOS Next

**Comment by Viniciuscarvalho** [comment]
@otaviommendes Colocar os regimes de contratação, posição Jr. Pl, Senior de acordo com o modelo, por favor.

**Comment by otaviommendes** [comment]
@Viniciuscarvalho Feito! Obrigado!
