### ISSUE TITLE
[São Paulo, SP] Um dos maiores e-commerces de calçados e moda do Brasil

### ISSUE THREAD

**Issue by otaviommendes** [CocoaHeadsBrasil/vagas#207]
## Descrição da vaga

Temos três vagas para desenvolvedores iOS para trabalhar em **um dos maiores e-commerces de calçados e moda do Brasil**.

## Local

São Paulo, SP

## Posição
Pleno ou senior.

## Tipo de contratação
CLT ou PJ. 

## Como se candidatar

Por favor envie um email para otavio.mendes@gingaone.com com seu CV anexado - enviar no assunto: Vaga iOS ECommerce

**Comment by Viniciuscarvalho** [comment]
@otaviommendes Colocar os regimes de contratação, posição Jr. Pl, Senior de acordo com o modelo, por favor.

**Comment by otaviommendes** [comment]
@Viniciuscarvalho Feito! Obrigado!
