### ISSUE TITLE
[Franca, SP] iOS Developer PJ Júnior Remoto

### ISSUE THREAD

**Issue by rafaelvalerini** [CocoaHeadsBrasil/vagas#208]
## Empresa
 IZagro
O IZagro é um aplicativo que auxilia no controle de pragas, doenças e ervas daninhas de diversas culturas agrícolas. Nossa missão é promover ao agronegócio uma ferramenta criativa, fácil e simples para auxiliar o produtor rural a enfrentar os problemas da lavoura.

## Descrição da vaga
Precisamos de 1 desenvolvedor iOS para trabalhos pontuais, pode ser remoto, com conhecimento em ObjectiveC e Swift 2

## Posição
Júnior

## Tipo de contratação
 Remoto / PJ

## Requisitos
Conhecimentos básicos em Objective-C e Swift2

###### Diferenciais
Conhecimento em Python/Java/AngularJS

## Como aplicar
Faremos um processo de entrevistas e selecionaremos aquele que se encaixa melhor na vaga

## Contato
Para se candidatar a vaga, entre em contato pelo email rafael@brandsoftware.com.br

Obrigado

**Comment by reprotector** [comment]
Olá @rafaelvalerini . A vaga ainda está aberta?
