### ISSUE TITLE
[SP - Alphaville] BRQ Digital - Desenvolvedor iOS

### ISSUE THREAD

**Issue by cpoletti-brq** [CocoaHeadsBrasil/vagas#214]
## Empresa
Paixão por transformar negócios com tecnologia, esse é o propósito que move a BRQ há 24 anos.
Com soluções digitais próprias e customizadas, a BRQ acelera a transformação digital das maiores empresas que operam no Brasil. 
Com mais de 3000 profissionais distribuídos em oito unidades no país e uma nos EUA, a BRQ é reconhecida pelo IDC como a maior empresa de serviços no gerenciamento e desenvolvimento de aplicações para o setor financeiro, atuando também em empresas líderes em seus setores.  

www.brq.com

## Descrição da vaga
O time da BRQ  especializado na criação de produtos digitais está com oportunidades para desenvolvedores mobile iOS que gostem de programar, boas práticas e código limpo para atuarem em um ambiente de transformação e ágil ajudando um grande cliente na sua jornada de criação de novo produto digital.

## Posição
Pleno e Senior

## Tipo de contratação
Presencial em Alphaville, Contratação CLT. 

###### Obrigatórios
Swift
Git
Swagger

###### Desejáveis
Bitbucket

## Benefícios
Contratação CLT e ótima cesta de benefícios.

## Contato
Charlie - cpoletti@brq.com

**Comment by marcelofabri** [comment]
Duplicada da https://github.com/CocoaHeadsBrasil/vagas/issues/211. Por favor, atualize aquela issue caso algum requisito tenha mudado.

**Comment by cpoletti-brq** [comment]
@marcelofabri obrigado pelo retorno, mas esta é outra oportunidade da BRQ, uma dúvida as issues são por oportunidades ou empresas?

**Comment by marcelofabri** [comment]
@cpoletti-brq Em geral são por empresas, mas como é pra outra localidade acho que faz sentido deixar essa aberta também.

**Comment by cpoletti-brq** [comment]
@marcelofabri obrigado
