### ISSUE TITLE
Desenvolvimento iOS no Grubster Freela

### ISSUE THREAD

**Issue by felipetio** [CocoaHeadsBrasil/vagas#22]
## Descrição da vaga

Desenvolvimento iOS do novo aplicativo Grubster. As principais atividades são:
1. Re implementar o fluxo de autenticação com objetivo de melhorar a conversão de cadastros
2. Aprimorar fluxo de aprovação dos apps com integração contínua (utilizando fastlane e devicefarm)
3. Exibir tutorial de como funciona o desconto ao instalar e durante o uso mostrar dicas sobre como utilizar as funcionalidades (ex.: filtros)
4. Notificar usuários quando estiver próximo a um estabelecimento no horário do almoço (bechmark push foursquare)

## Local

Remoto (ou Escritório na Vila Mariana - São Paulo)

## Benefícios

- trabalho remoto com flexibilidade.
- proposta de efetivação no final do projeto

## Requisitos

Obrigatórios
- conhecimentos sólidos em swift, orientação a objeto e design patterns
- integração com apis, storyboards e autolayout
- experiência em automação de testes
- git 

Desejáveis
- experiência com objectiveC
- formação academica na área de tecnologia

Diferenciais
- experiência com desenvolvimento Android ou Ruby

## Contratação

PJ a combinar

## Nossa empresa

O Grubster foi fundado em 2011 com o intuito de criar um aplicativo para ajudar os donos de restaurantes a ocuparem as suas mesas vazias com uma proposta de benefício simples para os clientes: Desconto no final da conta, para todos na mesa, sem restrição!

Em 2015 publicamos nossos planos de assinatura e desde então nosso principal objetivo é estar presente em todos os momentos em que os clientes querem comer fora, seja em um jantar a dois ou no almoço do dia a dia. Em breve vamos publicar um app novinho em folha mas precisamos reforçar nosso time.

Somos uma equipe de alto desempenho sabemos que para lançar um projeto de sucesso precisamos estar atento aos detalhes de todas as fases do desenvolvimento por isso trabalhamos com muita organização e comprometimento para que possamos executar nossas tarefas remotamente e com muita qualidade. Venha saber mais!

## Como se candidatar

Responda as 15 perguntas desse questionário sobre você: http://goo.gl/forms/djSlQn5X4k
O questionário além de identificação tem perguntas importante sobre experiência e proposta de trabalho.

**Comment by Viniciuscarvalho** [comment]
Essa vaga já foi preenchida @felipetio ? Se sim, pode fechar a issue? 👍

**Comment by felipetio** [comment]
👍
