### ISSUE TITLE
[SP - Barueri] RADAR Profissional Consultoria de RH - Desenvolvedor iOS Pleno

### ISSUE THREAD

**Issue by RADARProfissional** [CocoaHeadsBrasil/vagas#230]
## Empresa

A Radar Profissional, Consultoria de Recrutamento & Seleção e Terceirização de mão de obra, busca profissionais para atuar em um dos nossos clientes. 

## Descrição da vaga
Profissional será responsável por desenvolvimento de aplicações mobile iOS.

## Posição
`Pleno`

## Tipo de contratação
Presencial, `PJ`.

###### Obrigatórios
•	Superior cursando / completo em Análise de Sistemas, Ciências da Computação, Tecnologia da Informação ou Engenharia da Computação;
•	Conhecimento imprescindível com Objective C, JSON e XML; 
•	iOS; Swift; Json/XML; SQL; MVC; MVP; APIs RESTful e SOAP; GIT (TFS, Jira, GitHub e/ou outros); Adaptação de layouts de smartphones e tablets; Arquitetura de Software; Testes unitários e automatizados (TDD); Provisionamento de aplicações; Push notification e Geração de certificados iOS;
###### Desejáveis

•	Desejável experiência anterior com provisionamento de aplicações e Push notification; 
•       VIPER; Xamarin e Programação Reativa.

###### Diferenciais
Profissionais que tenham participado de comunidades, grupos de discussões, eventos e afins (online ou não) relacionadas ao desenvolvimento de software;

## Benefícios
Contratação `PJ`

## Contato
Encaminhar CV com pretensão salarial para recrutadora@radarprofissional.com.br, informando o nome da vaga: Desenvolvedor iOS.

**Comment by Uragawa** [comment]
Atenção às [regras](https://github.com/CocoaHeadsBrasil/vagas#todas-as-vagas-devem-conter-o-nome-da-empresa-que-est%C3%A1-contratando) do grupo.

**Comment by reprotector** [comment]
Olá @RADARProfissional , Acredito que essa vaga fere as regras de uso de nosso canal, por isso estou fechando a vaga até que ela esteja de acordo com nossas regras

> Todas as vagas devem conter o nome da empresa que está contratando
> 
> Se você é um recrutador, você deve identificar o nome da empresa em que o candidato irá trabalhar
