### ISSUE TITLE
[São Paulo - Faria Lima] ANTLIA - Desenvolvedor Swift Sênior

### ISSUE THREAD

**Issue by fabio-tavares** [CocoaHeadsBrasil/vagas#233]
## **Empresa**

Criada em março de 2006, a Antlia é uma empresa especializada em alocação de profissionais de TI, desenvolvimento de softwares e serviços de TI.

## **Descrição da vaga**

Vaga de alocação em grande instituição financeira localizada na Faria Lima para prazo inicial de 03 (três) meses.

## **Posição**

Desenvolvedor Swift Sênior.

## **Tipo de contratação**

Presencial - PJ.

## **Requisitos**

Obrigatórios

Swift 3+
Criação de arquitetura testável
Programação reativa
Criação de Views Programáticas

Desejáveis

REST APIs

Diferenciais

RxSwift / PromiseKit
Cartography
Fastlane
SwiftLint

## **Como aplicar**

Caso tenha interesse, favor enviar CV com pretensão salarial para fabio.tavares@antlia.com.br

## **Contato**

fabio.tavares@antlia.com.br

**Comment by Lucien** [comment]
https://github.com/CocoaHeadsBrasil/vagas

**Todas as vagas devem conter o nome da empresa que está contratando.**

**Comment by reprotector** [comment]
@Lucien Foi decidido entre os admins que no caso de consultorias está OK, o que importa é qual o CNPJ que está contratando. Como o candidato vai trabalhar para a consultoria, mas numa outra empresa, está ok
