### ISSUE TITLE
Desenvolvedor iOS Pleno e Sênior - URGENTE

### ISSUE THREAD

**Issue by RADARProfissional** [CocoaHeadsBrasil/vagas#236]
[SP - Alphaville] Radar Profissional - Desenvolvedor iOS Pleno e Sênior)
 --->

## Empresa
Empresa de desenvolvimento de Software localizada em Alphaville.

## Descrição da vaga
Desenvolver aplicativos mobile iOS (iPhone e iPad);

## Posição
Pleno e Sênior

## Tipo de contratação
Presencial, CLT

## Requisitos
•	Superior cursando / completo em Análise de Sistemas, Ciências da Computação, Tecnologia da Informação ou Engenharia da Computação;
•	Conhecimento imprescindível com Objective C, JSON e XML; 
•	Necessários: iOS; Objective C; Swift; Json/XML; SQL; MVC; MVP; APIs RESTful e SOAP; GIT (TFS, Jira, GitHub e/ou outros); Adaptação de layouts de smartphones e tablets; Arquitetura de Software; Testes unitários e automatizados (TDD); Provisionamento de aplicações; Push notification e Geração de certificados iOS.

###### Desejáveis
•	Desejável experiência anterior com provisionamento de aplicações e Push notification; 
•	Desejável: VIPER; Xamarin e Programação Reativa.

###### Diferenciais
•	Será considerado como diferencial, profissionais que tenham participado de comunidades, grupos de discussões, eventos e afins (online ou não) relacionadas ao desenvolvimento de software;
## Benefícios
PJ sem benefícios

## Contato
Interessados: Enviar CV com a pretensão salarial para recrutadora@radarprofissional.com.br

**Comment by Uragawa** [comment]
Atenção às [regras](https://github.com/CocoaHeadsBrasil/vagas#todas-as-vagas-devem-conter-o-nome-da-empresa-que-est%C3%A1-contratando) do grupo.

**Comment by reprotector** [comment]
Fechando por não seguir as regras da comunidade.
