### ISSUE TITLE
[Vitória] iOS Developer | Mobile Saúde

### ISSUE THREAD

**Issue by FelipeFMMobile** [CocoaHeadsBrasil/vagas#24]
## Descrição da vaga

iOS Developer  Mobile Saúde

## Local

Presencial - Vitória Espírito Santo

## Benefícios

Refeição;
Transporte;
Plano de saúde Unimed;

## Requisitos

Obrigatórios
Ensino superior completo ou em fase de conclusão;
Experiência em linguagens Objetive-c e iOS SDK;
Web services, especialmente APIs REST;
Familiaridade com HTTP, HTML, XML e jSon;
Orientação a objetos e MVC;
Banco de dados MySql e CoreData;
Familiaridade com Git.
Inglês intermediário;

Diferenciais
Conhecimento em AWS;
Inglês avançado;
Experiência com processo de publicação na app store.

## Contratação

Salário (à combinar);

## Nossa empresa

Somos a Mobile Saúde, uma desenvolvedora de soluções inovadoras na área da saúde. Nosso escritório é em Vitória-ES, e nossa carteira de clientes abrange operadoras de saúde de todo o Brasil.

Estamos em fase de expansão e à procura de um desenvolvedor iOS para se juntar à equipe. O profissional irá atuar no levantamento, definição, especificação e desenvolvimento de aplicativos e sistemas para iOS.

## Como se candidatar

Por favor envie um email para geraldo@mobilesaude.com.br com seu CV anexado - enviar no assunto: Vaga iOS

**Comment by lucasromanomr** [comment]
@FelipeFMMobile confirma ai para fechar.
