### ISSUE TITLE
[SP - Barueri] - Desenvolvedor iOS Pleno

### ISSUE THREAD

**Issue by otaviommendes** [CocoaHeadsBrasil/vagas#240]
## Descrição da vaga
Estamos apoiando na contratação de Desenvolvedores iOS, para cliente de grande porte e projeto de grande visibilidade nacional.

## Posição
Desenvolvedor iOS Pleno.

## Tipo de contratação
 Presencial, CLT ou PJ. 

###### Obrigatórios
- Mínimo de 3 anos de experiência com desenvolvimento nativo;
- Ter desenvolvido em Swift e RxSwift;
- Experiência com animações e componentes personalizados;
- Ter trabalhado com Scrum e Kanbam;
- Vivência com ferramentas de versionamento e repositório.

###### Desejáveis
- Experiência com TDD e rotina de testes.

## Contato
viviane.domingues@gingaone.com

**Comment by unnamedd** [comment]
Vaga em não conformidade com os requerimentos dessa comunidade.

Motivo:
- Todas as vagas devem conter o nome da empresa que está contratando

**Comment by reprotector** [comment]
Olá @otaviommendes. Já havíamos alertado por Slack sobre vagas fora das regras do canal. Por conta da reincidência estamos bloqueando seu perfil de criar novas vagas. Obrigado pela compreensão.
