### ISSUE TITLE
[MG - Belo Horizonte] Samba Tech - Desenvolvimento Java 

### ISSUE THREAD

**Issue by thafreireec** [CocoaHeadsBrasil/vagas#242]
## Empresa
 Na Samba, colaborador é Rei!

Reconhecida pelo Instituto Great Place to Work® como uma das 15 melhores empresas para se trabalhar no Brasil na categoria TI & Telecom em 2017 e eleita pela FastCompany como uma das companhias mais inovadoras da América Latina em 2014, a Samba Tech ajuda centenas de empresas a se comunicarem melhor com sua audiência através dos seus vídeos online.

## Posição
 Pleno 

## Tipo de contratação
 CLT 

## Requisitos
- Nível superior completo em Ciência da Computação, Engenharia da Computação ou áreas afins;
- Experiência mínima de 2 anos em cargos similares;
- Facilidade de aprendizado;
- Pró-ativo e em busca de desafios.

###### Obrigatórios
- Domínio sobre Algoritmos e Estruturas de Dados;
- Experiência em desenvolvimento Java;
- Experiência com desenvolvimento de aplicações web, preferencialmente utilizando frameworks Java (Spring) e frameworks Javascript (NodeJS e/ou AngularJS);
- Facilidade para ler e entender código fonte, independente da linguagem de programação (utilizamos também Python, ActionScript, Shell Script);
- Experiência no desenvolvimento de sistemas com arquitetura de serviços REST;
- Experiência com controle de versão, preferencialmente Git;
- Conhecimento e/ou experiência com práticas de uma cultura DevOps é um diferencial.

###### Diferenciais
- Experiência com banco de dados relacionais. Experiência com bancos de dados não relacionais;
- Conhecimento e/ou experiência com práticas de uma cultura DevOps;
- Experiência com metodologias ágeis;
- Experiência com JS.  

## Benefícios
Informe os benefícios que a empresa oferece

## Com quem você vai trabalhar
Se desejar insira uma lista dos futuros colegas de trabalho. Você pode gerar uma com os usuários do GitHub dos funcionários em http://fpg1503.com/GithubProfileTableGenerator/

## Como aplicar
Os interessados deverão cadastrar o currículo no link abaixo
https://jobs.kenoby.com/sambatech/job/analista-de-desenvolvimento/5a0493a778b7572586c64444:

## Contato
thabata.costa@sambatech.com.br

**Comment by reprotector** [comment]
@thafreireec 

> CocoaHeadsBrasil Vagas (Somente vagas para iOS/macOS)
