### ISSUE TITLE
[ES - Vitória] Mobile Saúde - Desenvolvedor iOS

### ISSUE THREAD

**Issue by lucasromanomr** [CocoaHeadsBrasil/vagas#243]
## Empresa
Somos a Mobile Saúde, uma desenvolvedora de soluções inovadoras na área da saúde. Nosso escritório é em Vitória-ES, e nossa carteira de clientes abrange operadoras de saúde de todo o Brasil.
Estamos em fase de expansão e à procura de um desenvolvedor iOS para se juntar à equipe. O profissional irá atuar no levantamento, definição, especificação e desenvolvimento de aplicativos e sistemas para iOS.

https://www.mobilesaude.com.br

## Descrição da vaga
Programador iOS com conhecimento em Objective-C e Swift

## Posição
 Desenvolvedor iOS (Pleno / Senior)

## Tipo de contratação
 Presencial

###### Obrigatórios
- Ensino superior completo ou em fase de conclusão;
- Experiência em linguagens Objetive-c e iOS SDK;
- Web services, especialmente APIs REST;
- Familiaridade com HTTP, HTML, XML e jSon;
- Orientação a objetos e MVC;
- Banco de dados MySql e CoreData;
- Familiaride com repositorio Git.
- Inglês intermediário;

###### Diferenciais
- Conhecimento em AWS;
- Conhecimento em Swift;
- Inglês avançado;
- Experiência com processo de publicação na app store.

## Benefícios
- Salário (à combinar);
- Ticket refeição;
- Transporte;
- Plano de saúde Unimed;
- Não temos código de vestimenta. Bermuda e chinelos liberados;

## Como aplicar
https://www.mobilesaude.com.br/trabalhe-conosco/vaga/ios-developer/

## Contato
E-mail: oportunidades@mobilesaude.com.br

**Comment by lucasromanomr** [comment]
Vaga ainda está aberta

**Comment by BrunoCerberus** [comment]
@lucasromanomr Trabalho na Pag! como desenvolvedor iOS Jr no momento, mas encaixo nos parâmetros exigidos com exceção da faculdade que tive que trancar.

Meu linkedin: www.linkedin.com/in/bruno-lopes-de-mello-60b093142
Meu GitHub: https://github.com/BrunoCerberus
Meu BitBucket: https://bitbucket.org/Makubec/

Infelizmente o meu maior portfólio foi a contribuição que fiz para o desenvolvimento do App Pag! e não tenho como mostrar, pois a empresa limita a edição do código apenas dentro da própria empresa, mas o sistema de parcelamento, alteração de vencimento , correção de mais de 200 warnings devido ao código legado e a substituição do MapKit pelo Google Maps, Google Places e Google Place Picker foram desenvolvidos totalmente por mim e hoje estou desenvolvendo o app da Avista.

Caso queira me ligar meu número é (27) 9 9690-1647
