### ISSUE TITLE
[PR - Curitiba] Altran - Dev. iOS Nativo

### ISSUE THREAD

**Issue by JessicaTurra** [CocoaHeadsBrasil/vagas#247]
## Empresa
A Altran é uma empresa multinacional Francesa que atua em consultoria de inovação tecnológica e está presente em mais de vinte países. Atua no segmento financeiro, Telecom, Automotivo, Aeroespacial, energia e TI. Na Europa a Altran é Líder em inovação tecnológica. No Brasil, estamos em um crescimento exponencial e com diversos projetos em todo território nacional.

## Descrição da vaga
Desenvolvedor iOS Nativo Pl/Sr
Contratação CLT, por tempo indeterminado.

## Requisitos
- Swift
- Xcode
- Desejável: Team Service, Source Tree e Git.

## Contato
CVs para: jessica.turra@altran.com.br
Fone/Whats: (41) 99500-9429 / 3081-0953

**Comment by reprotector** [comment]
Duplicada #237
