### ISSUE TITLE
[PR - Curitiba] Boleto Bancário - Desenvolvedor Android Pleno

### ISSUE THREAD

**Issue by thamiramachado** [CocoaHeadsBrasil/vagas#252]
## Empresa
O BoletoBancário.com cria e desenvolve soluções inovadoras para o mercado de pagamento. Começamos nosso sonho com facilidades para emissão de boletos bancários por múltiplos bancos de forma automática. Hoje focamos nossos esforços em desenvolver uma plataforma completa para geração de cobranças.

Somos jovens e queremos construir algo grande! Crescemos dia após dia, cooperamos uns com os outros e buscamos um ambiente onde trabalho, amizade e resultados possam caminhar de mãos dadas. Pró-atividade e vontade de aprender fazem parte de nosso DNA.

## Descrição da vaga
• Desenvolvimento de telas fáceis com foco na usabilidade do cliente;
• Otimizar fluxos, processos e rotinas;
• Raciocínio lógico e rapidez no teclado;
• Atenção em detalhes.

## Posição
Desenvolvedor Android Pleno

## Tipo de contratação
PJ - Presencial 

## Requisitos

• Sonhar Grande!
• Ser proativo e cooperar de forma genuína;
• Acreditar que só é possível alcançar o sucesso trabalhando duro;
• Ensino superior completo em áreas relacionadas a TI;
• Já ter experiência em desenvolvimento mobile;
• Conhecer Java e meios de pagamento;
• Possuir capacidade de planejamento, desenvolvimento, testes e em aprimorar grandes projetos;
• Saber gerenciar seu tempo e prazos de entregas;
• Buscar sempre aprender coisas novas;
• Saber se comunicar de forma assertiva.

## Benefícios
Clube Gazeta do Povo
Flexibilidade de horário
Poder trabalhar de bermuda e chinelo

## Como aplicar
Envie seu currículo para rh@boletobancario.com com o assunto: Desenvolvedor Android

**Comment by marcelofabri** [comment]
@thamiramachado Vaga removida por não ser direcionada para comunidade iOS e macOS.
