### ISSUE TITLE
[CE - Aquiraz] Xamarin Developer

### ISSUE THREAD

**Issue by clmadrazo** [CocoaHeadsBrasil/vagas#254]
## Descrição da vaga

Venha fazer parte do time oowlish!
Na oowlish estamos à procura de desenvolvedores Xamarin para juntar-se a nossa equipe!

## Local

Escritório, Ceará - Aquiraz

## Benefícios

- Trabalhar na “oowlish Mansion” 😉
- Uso de SCRUM, trabalhar numa das nossas squads.
- Ambiente de trabalho internacional, descontraído e cooperativo
- Trabalhar em produtos de sucesso internacional
- Salário
- Horário flexível

## Requisitos

Obrigatórios

- Xamarin
- C# (Avançado)
- Design patterns.
- Experiência em produtos mobile.
- Inglês básico (leitura/escrito)

Diferenciais

- Conhecimentos de Python (Django)
- Inglês avançado

## Contratação

CLT

## Nossa empresa

oowlish é uma empresa de desenvolvimento dinâmico com sede no Porto Das Dunas. Nós adoramos móveis, web e excelente trabalho! Ajudamos às empresas a desenvolver e produzir seus produtos de mídia digital.

## Como se candidatar

Por favor envie um email para career@oowlish.com com seu CV anexado - enviar no assunto: Xamarin Developer

**Comment by reprotector** [comment]
Olá @clmadrazo, acredito que essa vaga não se encaixa nos requisitos do canal. 

> Somente vagas para comunidade iOS e macOS
