### ISSUE TITLE
[São Paulo] Nubank - Mobile Software Engineer

### ISSUE THREAD

**Issue by miguelbassila** [CocoaHeadsBrasil/vagas#258]
# Nubank
Leading fintech in Latin America. Using bleeding-edge technology, design and data, Nubank is committed to fighting complexity and empowering Brazilians to take control of their finances. Over 8 million people have applied for its mobile-controlled credit card since its launch on September 2014.

Located in the Pinheiros region of São Paulo, Nubank has raised USD 180 million in investment rounds led by Sequoia Capital, Founders Fund, Tiger Global, Kaszek Ventures, Goldman Sachs, QED Investors and DST Global.

With a team of over 500 of the highest-performing engineers, decision scientists, designers, and analysts, Nubank is dedicated to creating an inclusive and challenging work environment as well as the best products and customer experience.

### Why is software engineering important for Nubank?
Nubank is a technology company, and software engineers form the bulk of our team. Our software team creates new features for our cardholder customers, as well as advanced analytics and machine learning models to continuously improve decision making and streamline processes.

### What are some examples of problems a software engineer will solve?
Shipping valuable features requires close coordination between devops, database, API, frontend, and mobile workstreams; Nubank engineers commonly pair and rotate focus between these responsibilities. We consistently work with new technologies, and thus value professionals who are open to learning new things, regardless of pre-existing comfort zones. Nubank mobile software engineers might solve any of the following problems:

* Ship new features for the mobile apps using modern languages like Swift
* Take reactive architectures to the next level
* Triage bugs and exceptions reported in production

### What is it like working at Nubank?
Our teams work using agile frameworks to deliver great solutions for our customers. We emphasize pairing, controlling work-in-progress, and try to adapt our team structures and processes to suit the particular working styles of the engineers within those teams. Our working environment is open and diverse, and our offices have a broad mix of collaborative working spaces, quiet areas, leisures space, and workstations. Overall, we want our engineers to be comfortable at work: we don’t have a dress code and you can work wearing shorts and flip-flops. We also have a pet-friendly office: you may bring your furry friend to work.

* Work on a small team, being part of the project and product decisions
* Work with an app with more than 5.5 million downloads and consistently >4.7 rating across both platforms
* Have the opportunity to work with other functions, from design to decision sciences, to shape and iterate on key features
* Happy Hours every Wednesdays

*More about us*
[Our environment](https://exame.abril.com.br/negocios/por-dentro-da-sede-roxa-e-inovadora-do-nubank/)

### You must have
* 2+ years of experience with OO languages
* Passion for mobile technology and high quality engineering
* Curiosity and a desire to be responsible for all aspects of building Nubank's product in a small, highly focused, and very rapidly growing team
* Multi-threaded application development
* Proficient Swift - That's ok if you are not familiar with these languages, you will learn fast
* Understanding and curiosity in creating well thought out mobile infrastructure, SDKs, open source projects, and APIs.
* Heavy focus on testing - Unit tests, instrumental tests (KIF, Nimble, SwiftCheck)
* Knowledge on Clean Architecture concepts
* Deep knowledge of SOLID principles
* Excellent software engineering aptitude and the ability to provide technical mentorship and guidance
* Memory management and performance tuning
* Attention to detail - a pixel perfect eye
* Custom UI and animation

### You will fit well if
* You are results-oriented and enjoy shipping new features
* You enjoy writing and shipping production-quality software
* You are hungry and enjoy being constantly challenged to learn and do more
* You embrace conflict of ideas and like to question the status quo
* You learn fast and adapt easily to changing situations and priorities
* You believe in building great products and doing great work by international standards
* You want to understand the big picture, to be held accountable and to make a meaningful contribution with your work
* You have knowledge of reactive extensions (RxJava, RxSwift)

We are excited to meet **experienced coders** as well as **college seniors** with various areas of technical focus - there is no single ideal profile. We all wear multiple hats and cannot be experts in everything at once.

You will have a meaningful chance to shape architecture, process, and culture while working with bleeding edge technologies. We believe in good team chemistry, enthusiasm for building things, and the (often surprising) capacity to learn new things when we stay humble and open-minded. An engineering or computer science undergraduate degree and English language skills are helpful.

## Benefits
* Competitive compensation package
* Health, dental and life insurance
* Meal allowance (“vale refeição”)
* Flexibility to choose your own custom setup (computer, monitors, OS etc.)

## Location
São Paulo - Pinheiros

## Hiring
CLT - Full

*Meet the Nubankers: http://sou.nu/engmobile*

## Apply
https://boards.greenhouse.io/nubank/jobs/1776035?t=f35a5fb11

**Comment by miguelbassila** [comment]
Vaga ainda está aberta

**Comment by cocuroci** [comment]
@miguelbassila tem possibilidade de ser remoto?

**Comment by miguelbassila** [comment]
Vaga ainda está aberta

**Comment by pietrocaselani** [comment]
Vaga ainda está aberta

**Comment by pietrocaselani** [comment]
Vaga ainda está aberta

**Comment by pietrocaselani** [comment]
Vaga ainda está aberta

**Comment by miguelbassila** [comment]
Vaga ainda está aberta

**Comment by Bunn** [comment]
reabrindo por pedido do @miguelbassila

**Comment by miguelbassila** [comment]
Vaga ainda está aberta

**Comment by danilorequena** [comment]
Procurei por alguma vaga relacionada a iOS pra SP no link do post mas não encontrei, tem alguma outra forma de aplicar?

**Comment by carlosvreal** [comment]
Alguma possibilidade para trabalho remoto?
