### ISSUE TITLE
[SP - Pinheiros] Banco Neon - Desenvolvedor iOS Pleno

### ISSUE THREAD

**Issue by NEON-GabiMollo** [CocoaHeadsBrasil/vagas#259]
## Empresa
O banco Neon é tipo um banco, só que totalmente diferente. Queremos provar que você não precisa odiar seu banco.

## Descrição da vaga
O profissional será responsável pelo desenvolvimento e manutenção do app iOS, a expectativa é que o profissional seja capaz de entregar um produto com qualidade e requintes avançados de UX.

## Posição
Desenvolvedor iOS pleno

## Tipo de contratação
Presencial - CLT

## Requisitos
Experiência com desenvolvimento mobile nativo iOS em Swift e Objective-C.
Experiência no uso de Web Services.
Autolayout.
Conhecimentos de UX.
Design Patterns.
Cocoa pods.
Noções de arquitetura MVC e MVVM.

## Diferencial
Experiência com extensions (Apple Watch, widget, Siri).
Conhecimento em testes unitários.
Links com código no github e/ou apps publicadas.
Conhecimento em Integração Contínua.

## Benefícios
O funcionário que entra na empresa recebe uma pontuação. Com essa pontuação, ele pode compor sua cesta de benefícios podendo pegar cerca de 7 benefícios de um total de 13 opções.

## Com quem você vai trabalhar
Jean Rocha
https://www.linkedin.com/in/jeanchavesrocha/

Luciano Sugiura
https://www.linkedin.com/in/luciano-kenji-sugiura-84b40b2b/

## Como aplicar
Por favor, quem tiver interesse, se aplicar no link
https://jobs.kenoby.com/neon/job/desenvolvedor-ios-pleno/5a621eea8b928264dbd88100

**Comment by vinyguitar** [comment]
Faltou colocar o local

**Comment by NEON-GabiMollo** [comment]
SP - Bairro de PInheiros

**Comment by NEON-GabiMollo** [comment]
Vaga ainda aberta.
