### ISSUE TITLE
[Remoto] - Desenvolvedor iOS | HE:labs

### ISSUE THREAD

**Issue by marciliojrs** [CocoaHeadsBrasil/vagas#26]
## Descrição da vaga

iOS Developer

Você precisa dominar desenvolvimento iOS com Objective-C e Swift, e seus mais importantes frameworks e ferramentas (CocoaPods, CoreData, Core Location, etc), além de estar a vontade com Storyboards, Adaptive Layout e Git.

## Local

Remoto ou Escritório no Rio de Janeiro

## Requisitos

Obrigatórios
- Experiência com Swift e Objective-C

## Contratação

CLT ou PJ

## Nossa empresa

Aqui na HE:labs não existem diferentes níveis de programadores. Temos times eficientes porque prezamos por programadores de alto nível, que são capazes de se comunicar bem e trabalhar diretamente com os clientes.

Em todos os projetos trabalhamos com entregas semanais de software funcionando. Uma iteração começa com a Reunião de Planejamento com o cliente e termina com a entrega do Roteiro de Testes, de acordo com a nossa metodologia. 

Todos os membros do time, incluindo os programadores, são responsáveis pela prototipação e conceito das telas do projeto. Trabalhamos com desenhos feitos a mão, em folhas A4, como forma de comunicação sobre o trabalho que deve ser realizado. Isso quer dizer que todos são responsáveis pela Experiência do Usuário e Usabilidade das aplicações.

É necessário ter noções de inglês: leitura, escrita e oral. Falar fluentemente é um diferencial. Temos clientes em todos os cantos do mundo e a língua padrão de comunicação dentro do código é o inglês.

Temos um escritório super irado no Rio de Janeiro, mas você poderá trabalhar remotamente do seu home office, algum café na sua cidade ou mesmo mochilando pela Europa.

Cada um pode escolher as ferramentas com que prefere trabalhar. Gostamos de Macs. Fornecemos um para cada colaborador da HE.

Aqui o que importa é saber se auto-gerir, trabalhar de forma altamente colaborativa em time e criar produtos fantásticos para os clientes!

## Como se candidatar

Aplique através do link: https://helabs.recruiterbox.com/jobs/fk0ht6a/

**Comment by klevison** [comment]
Acho que a vaga não está mais aberta.

"Job not found!"
