### ISSUE TITLE
[São Paulo - Pinheiros] AppSimples - Engenharia de Software iOS (Junior/Pleno)

### ISSUE THREAD

**Issue by kyonaganawa** [CocoaHeadsBrasil/vagas#266]
## AppSimples/Outsmart
 Somos uma Startup focada em desenvolvimento de software e consultoria em inovação. Realizamos projetos para grandes empresas (como Electrolux e Suzano) e startups em destaque no mercado (como Quinto Andar e Stoodi). Além disso, ajudamos vários novos empreendedores a criar seu primeiro produto.
 Nossa empresa foi incubada e graduada no CIETEC (Centro de Inovação, Empreendedorismo e Tecnologia). Nossa especialidade é a criação de soluções utilizando aplicativos mobile (híbridos e nativos), aplicativos web e backend.
www.appsimples.com.br

## Descrição da vaga
Integrar uma das nossas equipes multidisciplinares, realizando projetos para nossos clientes e parceiros. Participar do planejamento, implementação e entrega de soluções inovadoras utilizando metodologias e tecnologias de vanguarda. Desenvolvimento de aplicações iOS (nativas e ReactNative), com possibilidade de envolvimento com outras plataformas: Android (nativo, híbrido), Web (React) e Backend (Serverless, node.js).

## Posição
 Junior ou Pleno

## Tipo de contratação
 Presencial. CLT.

###### Obrigatórios
Experiência em desenvolvimento de aplicações iOS nativas utilizando Swift.
Domínio de versionamento utilizando git.
Conhecimento dos principais patterns utilizados em projetos mobile.
Confortável em interagir com projetos e clientes de diversa natureza.
Habilidade de comunicação com colegas e clientes.

###### Desejáveis
Experiência trabalhando com metodologias ágeis e Scrum.
Conhecimento de programação reativa (RxSwift).
Conhecimento de metodologias TDD e CI.

###### Diferenciais
Desenvolvimento de aplicações Android (nativo), Web (React+Redux) e/ou híbridas com ReactNative.
Desenvolvimento ou integração com backend utilizando serviços da Amazon (Lambda, DynamoDB, SNS, S3 ... ), Google Cloud, Firebase e Node.js.

## Benefícios
Vale Transporte
Vale Refeição
Plano de Saúde

## Como aplicar
Envie um email para contato@appsimples.com.br, com CV. Coloque no título "Recrutamento iOS".

## Contato
Luciano Naganawa: luciano.naganawa@appsimples.com.br

**Comment by kyonaganawa** [comment]
Já contratamos 2 pessoas da comunidade CocoaHeads mas ainda temos vagas abertas.

**Comment by gabe351** [comment]
Enviei emails e não obtive nenhuma resposta.

**Comment by kyonaganawa** [comment]
@gabe351 Olá Gabriel, infelizmente o seu email ficou sem resposta. Pedimos desculpa pela nossa falha, já falei com a pessoa responsável pelo recrutamento para dar sequência ao seu processo. Abs!

**Comment by gabe351** [comment]
@kyonaganawa Obrigado, aguardo contato :)
