### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor iOS

### ISSUE THREAD

**Issue by MarceloAmorim** [CocoaHeadsBrasil/vagas#27]
# Descrição da vaga

Projetos MOBRJ para iOS
## Local

Escritório Rio de Janeiro - Botafogo, Centro ou Copacabana.
Possibilidade de trabalho remoto dependendo da experiência comprovada de projetos desenvolvidos pelo profissional. Não precisa ser APP de loja, desde que apresente a arquitetura/fonte e o APP rodando.
## Requisitos

Obrigatórios
- 2 anos de experiência com desenvolvimento para iOS nativo (ObjectiveC ou Swift)

Desejáveis
- experiência no uso de ferramentas com Git, BitBucket, Trello, Toggl
- sólida capacidade de entrega, comprometimento!
- clareza na comunicação
- objetividade

Diferenciais
- projetos opensource
- conhecimentos de C#, Javascript
## Contratação

PJ a combinar - início imediato!
## Nossa empresa

Visite nosso site [MOBRJ Software](www.mobrj.com.br)  
## Como se candidatar

Por favor envie um email para contato@mobrj.com.br com seu CV anexado - enviar no assunto: [Vaga iOS]

**Comment by raphaelpitang** [comment]
Opa, ainda há vaga remota?

**Comment by reprotector** [comment]
@MarceloAmorim Já fecharam a vaga? Pode fechar a issue? :)
