### ISSUE TITLE
[SP e MG] iOS Developer Pleno e Sênior - Movile, iFood, Sympla, PlayKids e outras

### ISSUE THREAD

**Issue by MovileGente** [CocoaHeadsBrasil/vagas#274]
## Empresa
A Movile é líder em marketplaces móveis, e tem como grande sonho tornar a vida de 1 bilhão de pessoas melhor através de seus aplicativos. Atualmente trabalhamos com negócios e empresas em 4 pilares, que são: Food (iFood), Tickets (Sympla), Education & Care (PlayKids, SuperPlayer e Wavy) e Rapiddo (Marketplace, Payments e Entregas). Já estamos presentes no Brasil, Estados Unidos, França, México, Colômbia, Peru e Argentina, e somamos mais de 100 milhões de usuários ativos mensalmente. Com 1600 funcionários apaixonados pelo mesmo sonho, empoderados a construir novos negócios com potencial global e motivados a tomarem riscos.

A tecnologia é o nosso core, estamos formando times que criem e desenvolvam produtos incríveis para impactar e melhorar diretamente a vida das pessoas. Nossa stack é totalmente diversificada, contamos com tecnologias e linguagens diversas para termos a liberdade de sempre aplicar o que fizer mais sentido para determinado projetos. Gostamos de inovar, de aplicar ideias diferenciadas, de mudar produtos e de criar coisas realmente grandes e escaláveis.

## Descrição da vaga
Vagas para iOS Developers que queiram nos ajudar a construir produtos globais, que impactam a vida das pessoas e estão presentes no dia a dia delas. Mas dessa vez queremos propor uma abordagem diferente. Após a inscrição, você passará por uma qualificação inicial e, sendo aprovado, você **ficará em destaque frente aos recrutadores de mais de 8 empresas do Grupo Movile, dentre elas iFood, Sympla, Rapiddo, PlayKids, MapLink e Wavy.**

**RESPONSABILIDADES E ATRIBUIÇÕES**

- Compreender problemas técnicos e desenvolver soluções;
- Ser capaz de criar soluções pragmáticas de software, onde os recursos são rapidamente entregues sem sacrificar a qualidade do código;
- Concepção e desenvolvimento de uma aplicação móvel escalável, segura e fiável;
- Concepção, desenvolvimento, implantação e manutenção de aplicações iOS;
- Colaborar com definições arquitetônicas;
- Realizar integrações com serviços de terceiros;
- Acompanhar o monitoramento de métricas do produto através do desenvolvimento de ferramentas ou integração com as existentes.

[[Vídeo] Entrevista do nosso CTO](https://youtu.be/DNfLpKNoN7c)
[[Vídeo] Tech Case de como arquitetamos um superapp usando módulos](https://www.youtube.com/watch?v=mowj7aYf1x4)

## Posição
Pleno e Sênior

## Tipo de contratação
Presencial e CLT

###### Obrigatórios

- Experiência sólida na construção de aplicações escaláveis, de alto desempenho e tolerantes a falhas;
- Experiência sólida com Swift 3.0;
- Desenvolvimento de componentes personalizados de UI.
- Vivência em realizar integrações com as APIs RESTful;

###### Diferenciais

- Familiaridade com modelos de programação reativa;
- Conhecimento em Objetive-C;

## Benefícios
- Plano de saúde
- Seguro de vida
- VR compatível com o local do escritório
- VT
- Férias
- Possibilidade de home office
- Investimento em capacitação
- E outros diversos que são específicos de algumas empresa do Grupo (ex: GymPass, Plano odontológico, vale cultura)

#### Diferenciais das empresas

- Horário flexível
- Ambiente amigável e descontraído
- Times talentosos
- Produtos e tecnologia de ponta
- Espaço para inovação e tentativas
- Oportunidade para desenvolvimento e crescimento profissional
- Snacks liberados no escritório
- Cerveja sempre à disposição
- Muito café (máquina e coador)

## Com quem você vai trabalhar
* [Guilherme Andrade](https://www.linkedin.com/in/guiaandrade/)
* [Bruno Rocha](https://www.linkedin.com/in/bruno-rocha-45786a98/)
* [Lucas Shimo](https://www.linkedin.com/in/lucas-shimo/)
* [Douglas Ferreiras](https://www.linkedin.com/in/douglassouzaferreira/)
* [Fellipe Caetano](https://www.linkedin.com/in/fellipecaetano/)

## Como aplicar
Basta [clicar nesse link ](https://movile.gupy.io/jobs/5390)e preencher a inscrição

**Comment by cocuroci** [comment]
Existe a possibilidade de contratação de pessoas de outros estado para home office?

**Comment by MovileGente** [comment]
Olá @cocuroci 

Algumas empresas já tem o home office estruturado e tenho certeza que todas aceitarão conversar e avaliar junto com os candidatos que tiverem essa necessidade.

Somos super flexíveis ;)

Abs

**Comment by peppsi** [comment]
Boa noite,

a vaga para BH ainda está aberta?

**Comment by MovileGente** [comment]
Olá @peppsi, tudo bem?

Sim, temos vagas para a BH. Além disso, se aplicando por esse link você ficará constantemente em destaque para os recrutadores de todas as empresas do grupo, para posições atuais e futuras.

Contamos com você.

Abs

**Comment by MovileGente** [comment]
Vaga ainda está aberta

**Comment by cocuroci** [comment]
@MovileGente fiz a candidatura nesse site (https://movile.gupy.io/) já faz um tempo, mas ainda não chamaram para a entrevista. Vocês dão feedback positivos e negativos?

**Comment by MovileGente** [comment]
Oi @cocuroci, eu verifiquei aqui e o feedback já foi disparado. 

Pode me enviar um e-mail <matheus.fonseca@movile.com>? Te explico tudo por lá

**Comment by alexrodrigues** [comment]
Olá @MovileGente , me candidatei para a vaga há algumas semanas e também não obtive respostas, repito a mesma pergunta do cocuroci, "Vocês dão feedback positivos ou negativos?"
