### ISSUE TITLE
[SP - Itaim Bibi] XP- Desenvolvedor iOS Júnior/Pleno/Sênior

### ISSUE THREAD

**Issue by glaucoxpi** [CocoaHeadsBrasil/vagas#275]
## Empresa
No mercado há mais de quinze anos, a XP nasceu para transformar o jeito que o brasileiro lida com investimentos. Focando no ensino simples e descomplicado, queremos que as pessoas vejam o mundo financeiro de uma forma diferente do que estão acostumadas, mais convidativo. Para ajudar nessa missão, juntamos os melhores e maiores investimentos do mercado em um só lugar, desenvolvemos material de ensino ecolocamos à disposição do investidor especialistas no assunto, tudo para que nossos clientes possam alcançar seus objetivos financeiros mais rápido. É por esses e outros motivos que a XP é atualmente uma das maiores especialistas em investimentos do Brasil, oferecendo educação, assessoria e serviços financeiros, para que seus clientes alcancem o sucesso financeiro.

## Descrição da vaga
Estamos construindo uma nova estrutura de desenvolvimento na XP e para isso precisamos de pessoas muito engajadas.
Se você gosta de compartilhar conhecimento, trabalhar em equipes multidisciplinares e está buscando crescimento constante, você é uma pessoa que nos interessa conhecer.
Trabalhamos com squads e você poderá participar de algumas delas na sua jornada dentro da empresa.
E aí, que tal vir conhecer a gente?

## Posição
Desenvolvedor iOS Júnior, Pleno e Sênior.
Estagiários são bem vindos também!

## Tipo de contratação
 CLT / Presencial

###### Obrigatórios
- Experiência em desenvolvimento de software em produção e aplicações interativas baseadas em dados
- Experiência em desenvolvimento iOS usando Swift
- Profundo conhecimento do UIKit & Foundation
- Experiência em integração com Webservices usando ou não bibliotecas de terceiros

###### Desejáveis
- Experiência trabalhando com metodologias ágeis e Scrum.

###### Diferenciais
- Experiência com armazenamento de dados (CoreData)
- Experiência com desenvolvimento de testes unitários
- Experiência com Storyboard, Auto Layout, Size Classes e Multitasking
- Experiência com gerenciadores de dependências (Ex: Cocoapods, Carthage ou SPM)
- Experiência de fluxo de CI e Fastlane

## Benefícios

- Vale Refeição
- Plano de saúde e odontológico (Bradesco)
- PLR
- Verba anual para gastar com eventos, conferências, cursos ou livros
- Salários competitivos com base na experiência e potencial
- Espaços de colaboração e convivência entre os colaboradores
- Horário flexível

## Com quem você vai trabalhar
Glauco Moraes - https://www.linkedin.com/in/glauco-moraes/
Júlio Fernandes - https://www.linkedin.com/in/julio-fernandes-7658b11b/
Felipe Trindade - https://www.linkedin.com/in/felipe-trindade-88375b9a/
Thiago Reis - https://www.linkedin.com/in/thiagoreispontes/

## Como aplicar
Envie um email para glauco.moraes@xpi.com.br, com CV. Coloque no título "iOS XP".

## Contato
Email: glauco.moraes@xpi.com.br
Slack: glaucomoraes

**Comment by BrunoCerberus** [comment]
@glaucoxpi Trabalho na Pag! como desenvolvedor iOS Jr no momento

Meu linkedin: www.linkedin.com/in/bruno-lopes-de-mello-60b093142
Meu GitHub: https://github.com/BrunoCerberus
Meu BitBucket: https://bitbucket.org/Makubec/

Infelizmente o meu maior portfólio foi a contribuição que fiz para o desenvolvimento do App Pag! e não tenho como mostrar, pois a empresa limita a edição do código apenas dentro da própria empresa, mas o sistema de parcelamento, alteração de vencimento , correção de mais de 200 warnings devido ao código legado e a substituição do MapKit pelo Google Maps, Google Places e Google Place Picker foram desenvolvidos totalmente por mim e hoje estou desenvolvendo o app da Avista.

Caso queira me ligar meu número é (27) 9 9690-1647

**Comment by reprotector** [comment]
Olá @BrunoCerberus , sugiro utilizar o "Como Aplicar" de cada vaga.

**Comment by BrunoCerberus** [comment]
Feito, grato
