### ISSUE TITLE
[SP - Jabaquara] Randstad- Analista Engenheiro de Software Pleno 

### ISSUE THREAD

**Issue by mayksalles** [CocoaHeadsBrasil/vagas#288]
## Empresa
Você quer fazer parte de um time de alto nível técnico, em uma das empresas mais inovadoras do mercado financeiro (Banco Itaú) no Brasil? 
Se sua reposta é um sonoro"SIM!"​, dá uma olhada nestas informações:

## Descrição da vaga
Experiência com o desenvolvimento e ecossistema de mobile para plataformas iOS ou Android (pelo menos 4 anos)
Lógica de Programação e Raciocínio Lógico;
Conhecer as técnicas de desenvolvimento seguro; 
Profissional vai atuar na área de inovação digital  do banco,  realizar análise, levantamento de requisitos, definir quais as melhores tecnologias serão utilizadas. 
Não ficará programando mas vai desenhar a nível de desenvolvedor, realizar desenho de solução.

## Posição
Analista Engenheiro de Software Pleno

## Tipo de contratação
Presencial.
Contratação CLT full, com um bom pacote de benefícios e um plano de carreira real, sem conto de fadas ;)

## Requisitos
 Plataformas iOS ou Android;
Lógica de Programação e Raciocínio Lógico;
Conhecer as técnicas de desenvolvimento seguro; 
Conhecimento de testes unitários, testes integrados, testes funcionais e testes automatizados; 
Trabalhar com a ferramentas Git e conhecer o funcionamento do Git Flow; 
Conhecimento de arquitetura de software MVC e MVVM; 
Conhecimento do fluxo de integração contí­nua e deploy contí­nuo; 
Restful API;  

## Como aplicar
Realizar o cadastro através do link :  http://rnstad.biz/s/w/IBRST3

## Contato
Se desejar, pode enviar o seu CV e tirar dúvidas pelo email : maycon.sales@randstad.com.br

**Comment by reprotector** [comment]
Olá @mayksalles . Reparamos que a vaga está violando as regras do canal. A vaga deve conter o nome da empresa contratante (banco)

>Todas as vagas devem conter o nome da empresa que está contratando
>se você é um recrutador, você deve identificar o nome da empresa em que o candidato irá trabalhar

**Comment by mayksalles** [comment]
Foi realizado a mudança.
