### ISSUE TITLE
[Belo Horizonte] - Desenvolvedor iOS Sênior - SambaTech

### ISSUE THREAD

**Issue by paulo-gama** [CocoaHeadsBrasil/vagas#29]
## Descrição da vaga

Estamos procurando um desenvolvedor de aplicativos IOS para integrar nosso time de desenvolvimento e ter a oportunidade de trabalhar na construção de aplicativos que irão revolucionar a forma como as empresas se comunicam usando vídeos.

Fazer parte da Equipe de Talentos da Samba Tech dará a você uma oportunidade única de participar de uma empresa em crescimento rápido e de desempenhar um papel importante na construção de produtos e serviços que prometem transformar a indústria de vídeos online e revolucionar a experiência digital!
## Local

Belo Horizonte - Av. Raja Gabaglia
## Benefícios

Horário Flexível: 8 horas diárias/ Segunda-feira à Sexta-feira - 1h de almoço.

Vale Refeição;  
Vale Transporte;
Plano de Saúde;  
Previdência Privada;  
Seguro de Vida;
GymPass;
Horario Flexível;
Sala de Jogos;
## Requisitos

Obrigatórios
Nivel superior completo em Ciência da Computação, Engenharia da Computação ou áreas afins; 
Facilidade de aprendizado; 
Experiência mínima de 2 anos em cargos similares;
Pró-ativo e em busca de desafios.

Experiência em Objective-C ou Swift, bons conhecimentos em algoritmos, análise de algoritmos e estrutura de dados;
Conhecimento das ferramentas de performance do SDK iOS e técnicas de otimização. 
## Contratação

CLT
## Nossa empresa

Na Samba, colaborador é Rei!

Reconhecida pelo Instituto Great Place to Work® como uma das 40 melhores empresas para se trabalhar no Brasil na categoria TI & Telecom em 2015 e eleita pela FastCompany como uma das companhias mais inovadoras da América Latina em 2014, a Samba Tech ajuda centenas de empresas a se comunicarem melhor com sua audiência através dos seus vídeos online.
## Como se candidatar

Por favor envie um email para thabata.costa@sambatech.com.br com seu CV anexado - enviar no assunto: Vaga iOS
ou
https://sambatech.recruiterbox.com/jobs/fk06p9n/

**Comment by reprotector** [comment]
@paulo-gama Conseguiram fechar a vaga? Se sim, pode fechar a issue?

**Comment by paulo-gama** [comment]
Vou fechar @reprotector. Obrigado.
