### ISSUE TITLE
[SP - Barra Funda] Desenvolvedor(a) iOS 

### ISSUE THREAD

**Issue by VivianeCrisogano** [CocoaHeadsBrasil/vagas#294]
## ##**Oportunidade Desenvolvedor(a) iOS - São Paulo**

**Sobre a shopper.com.br:**
Somos o supermercado 100% online que mais cresceu em 2017. 
Recebemos um prêmio de R$ 1 milhão para desenvolver tecnologias que revolucionem a forma como as pessoas fazem compras.
Acreditamos que com trabalho duro, usando tecnologias e modelos de negócio inovadores, podemos transformar a sociedade e entregar mais tempo, energia e dinheiro às pessoas. 
Levantamos da cama todos os dias com esse propósito em mente: criar soluções para que os brasileiros vivam vidas mais inteligentes. Nossa cafeína diária é a vontade de servir, e servir bem (muito bem!)
Estamos em uma fase de expansão e crescimento, e, para que isso aconteça, queremos gente do nosso lado que acredite na nossa missão e que tenha muuuita vontade de crescer e fazer um trabalho incrível!

**Descrição da vaga:**
Responsabilidades:
- Desenvolver alterações/melhorias no app da Shopper para iOS.

**Local**
Escritório - Avenida Marquês de São Vicente, 1619 - Barra Funda.

**Benefícios**
- Ambiente de startup, informal, de muito aprendizado e de possibilidade de crescimento muito rápido, nosso trabalho é focado em meritocracia, então, só depende de você!

**Requisitos:**
Conhecimentos em: Swift 3 ou 4, X Code, Itunes e Fabric
Será considerado diferencial conhecimentos em FireBase

**Contratação:**
PJ a combinar

**Como se candidatar:**
Por favor envie um email para vagas@shopper.com.br com seu CV em anexo - enviar no assunto: Desenvolvedor iOS

**Comment by Viniciuscarvalho** [comment]
Por favor @VivianeCrisogano colocar no título da vaga a localização da vaga.
