### ISSUE TITLE
[PT - Porto, PORTUGAL]  Farfetch  -  iOS Developer || Desenvolvedor iOS

### ISSUE THREAD

**Issue by sfdias** [CocoaHeadsBrasil/vagas#297]
**_We are looking for iOS Developers to work at our office at Porto, Portugal!_**

**Who we are**
Farfetch is unlike anything in the world of fashion and technology. Our mission: to revolutionize the way the world shops. To do it, we need innovators. People who challenge convention and dare to dream. We’ve gone from a start-up to a billion dollar business. But we’re not done yet. Far from it. Be bold. Be brilliant. Together, we can be extraordinary!

We have rapidly grown into a truly global company since our launch in 2008 and we’re continuing to grow. Our family now includes partner boutiques and brands across Europe, North and South America and Asia; we demonstrate our ‘Think Global’ value in everything we do.

We are a global team of over 1,500 people and have offices based in London, New York, L.A., Porto, Guimaraes, Lisbon, Sao Paulo, Shanghai, Moscow, Hong Kong & Tokyo.

We are a company with an entrepreneurial spirit and innovative culture. We are positive, passionate and live our values: Be Human, Be Brilliant, Todos Juntos, Be Revolutionary, Think Global and Amaze Customers day to day.

**The Team**
Mobile Cluster is an awesome part of the Farfetch Tech Team. We have a strong tech culture and we are leading by our values: love technology, be proud of our work and learn and teach every day.

**The Role**
You will be responsible for the end-to-end development of iOS applications driving the long-term mobile strategy planned for Farfetch. This role consists in writing top notch Objective-C/Swift code and resort to battle hardened design patterns. It isn't just about writing iOS apps, you'll also have the chance to get your hands dirty with UI Automation, fully automated build pipelines and API integration testing with node.js.

**What You’ll do**

- Build a cutting edge iOS app that will bring the joy of fashion to millions of users.
- Contribute for cross team development of common libraries.
- Help define best practices on iOS development and contribute for a share and learn driven environment.
- Unwavering commitment to Continuous Integration and Continuous Deployment.
- Work closely with other Product Development teams to improve consistency and timing of releases.
- Create prototypes of new ideas and explore new technologies on the forefront of mobile technology.

**Who You Are**

- A iOS developer with at least one released app (solo or as a team member).
- A developer with working experience in Objective-C and Swift (if you don't have experience one of them, don't worry - just be keen to learn).
- An engineer with knowledge of REST API architecture that understands client side development as well as the API backend stack.
- A person eager to get nerdy about memory management, UI layout/rendering and UI/network performance.
- A team player oriented in detail.
- An energetic, creative and fun to work human being.
- Proficient in English, both written and spoken

We love hearing from you and want you to be as ambitious as we are, but before applying please ask yourself the following…

- Is this role a good match for me and my long term goals? We want to really know why you have chosen this career.
- Do I have all the skills and experience required for this role? Be realistic. We will only consider applications that demonstrate relevant skills or the potential to match the role requirements.
- Spell Check. As simple as it sounds make sure your application is to the highest standard. You will be surprised at how many applications we receive with spelling mistakes on them.

We are committed to equality of opportunity for all staff, applications from individuals are encouraged regardless of age, disability, sex, gender reassignment, sexual orientation, pregnancy and maternity, race, religion or belief and marriage and civil partnerships

**APPLY HERE:** https://app.jobvite.com/j?aj=o1XZ4fwL&s=gitcocoabr

**Comment by sfdias** [comment]
Vaga ainda está aberta

**Comment by rafael-silva** [comment]
Vaga ainda está aberta?
