### ISSUE TITLE
[SP - Itaim Bibi] Randstad - Desenvolvedor iOS Pleno 

### ISSUE THREAD

**Issue by gondekr** [CocoaHeadsBrasil/vagas#299]
## Empresa
Randstad

## Descrição da vaga
Você vai atuar com aplicativo de game de carros

## Posição
Desenvolvedor iOS Pleno

## Tipo de contratação
Contratação: PJ - Projeto por tempo indeterminado

###### Obrigatórios
Lógica de programação, Objective-C , Swift 3.0, XCode, ObjectMapper, Realm.

###### Diferenciais
Firebase, CocoaPods , Backend Azure, Gostar de carros

## Como aplicar
Email : maycon.sales@randstad.com.br

**Comment by reprotector** [comment]
Olá @gondekr . A empresa contratante é a Randstad ou a Randstad está fazendo recrutamento para outra empresa?

**Comment by gondekr** [comment]
@reprotector Não sei cara, só recebi pelo LinkedIn, quer que tire a empresa?

**Comment by reprotector** [comment]
@gondekr O ideal, nesses casos, é que você indique o canal para a empresa que te contatou no Linkedin. Assim eles mesmos podem tirar as eventuais dúvidas das pessoas por aqui.

**Comment by gondekr** [comment]
Justo, Ok então ;D
