### ISSUE TITLE
[Rio de Janeiro - Botafogo] Desenvolvedor iOS

### ISSUE THREAD

**Issue by ruanltbg** [CocoaHeadsBrasil/vagas#3]
## Descrição da vaga

Desenvolvedor iOS no 

## Local

Rio de Janeiro (Botafogo próximo ao metro) apenas presencial. Só envie seu currículo se você já for do Rio ou esteja disposto a mudar sendo que as entrevistas e testes serão no escritório da empresa.

## Benefícios

- CLT
- VA
- Plano de saúde
- Plano dentário

## Requisitos

Obrigatórios
- 3 anos de experiência com iOS
- Domínio em Objective-C
- Domínio em desenvolvimento para iOS
- Experiência com git (github)
- Inglês avançado

Desejáveis
- Conhecimento em Swift
- Conhecimento em criação de telas
- Consumo de APIs em JSON
- Conhecimento básico em android e/ou windows phone
- Currículo em formato PDF
- Link do Linkdin (se possuir)
- Link do github (se possuir)
- Links da app store (se possuir)
- Pretensão salarial

## Contratação

CLT

## Nossa empresa

A webedia é uma empresa francesa dona dos sites e marcas Tudo Gostoso, Adoro Cinema, Paramaker, Pure Break, Pure Viagem, Pure People e licenciada IGN. 

## Como se candidatar

Por favor envie um email para thiago.verly@webedia-group.com seu CV anexado - enviar no assunto: Vaga iOS

**Comment by barbosa** [comment]
Fala @ruanltbg, tudo certo?

A vaga ainda está aberta? Só para saber se fechamos a issue ou mantemos aberta.

Obrigado!

**Comment by ruanltbg** [comment]
@barbosa pode fechar sim. Muito obrigado ;)
