### ISSUE TITLE
[PR - Curitiba] VEGA I.T. - Desenvolvedor iOS

### ISSUE THREAD

**Issue by rsalomao2** [CocoaHeadsBrasil/vagas#302]
## Empresa
O Grupo VEGA I.T., com sede em Curitiba, oferece soluções em TI, desde o ano 2000, para todo o país. O grupo é formado por três empresas que atuam com o Gerenciamento de Internet, Segurança da Informação e Suporte Técnico para Empresas, Sites e Hospedagem de Sites e com soluções em Marketing Digital.

## Descrição da vaga
Fazer parte da equipe de desenvolvimento de soluções mobile da empresa, realizando manutenção e criação de novos produtos e melhorias.

## Posição
Junior/Pleno/Senior

## Tipo de contratação
CLT

###### Obrigatórios
- Morar na cidade de Curitiba-PR ou região metropolitana;
- Experiência com desenvolvimento nativo iOS (iPhone e iPad) em linguagem Swift;
- Experiência em integrações com serviços web (APIs RESTful);
- Experiência com arquitetura MVP ou MVVM;

###### Desejáveis
- Ter uma aplicação mobile publicada na Apple Store.

###### Diferenciais
- Conhecimento em desenvolvimento Android;
- Experiência com ferramentas de controle de versão.

## Benefícios
 Assistência médica / Medicina em grupo, Assistência odontológica, Seguro de vida em grupo, Refeição fornecida no local, Vale transporte, Celular fornecido pela empresa, Remuneração fixa + variável por desempenho.

## Como aplicar
Enviar currículo com pretensão salarial para: [http://vegait.com.br/trabalhe-conosco.aspx](http://vegait.com.br/trabalhe-conosco.aspx)

## Contato
Rodrigo Salomão
rodrigos@vegait.com.br

**Comment by ezefranca** [comment]
A seção **Com quem você vai trabalhar** aparentemente está com o template.
