### ISSUE TITLE
[RJ - Remote] StoneCo. - Desenvolvedor iOS Sênior

### ISSUE THREAD

**Issue by pedrocecchetti1** [CocoaHeadsBrasil/vagas#304]
## Empresa
A Stone começou em 2012. Já fomos uma startup. Hoje, somos uma
companhia de mais de 3000 pessoas, unidas por um propósito claro: ser a
opção que o mercado de pagamentos não oferece e potencializar o
empreendedor brasileiro.
Nosso dia a dia? Ultrapassar limites, aprender muito e transformar
potencial em potência. O seu, o da Stone e o dos nossos clientes.

A Stone é uma empresa de tecnologia que desenvolve produtos para que lojistas recebam o dinheiro de vendas feitas por meio de pagamento eletrônico, cartão de crédito e débito, seja no mundo físico através da maquinha de cartão ou no e-commerce. Empresas que prestam esses serviços são chamadas de adquirentes.

Além de credenciar o estabelecimento comercial, ou seja, habilitar um estabelecimento comercial a receber pagamentos via cartão de crédito ou débito, uma adquirente é responsável por tudo que acontece por trás de uma transação realizada com cartão, desde a comunicação com os bancos e bandeiras, até a liquidação da transação, que ocorre quando o dinheiro das vendas entra na conta do lojista.
 
## Descrição da vaga

Nós estamos criando uma nova área dentro da Stone, com o objetivo de revolucionar a forma como as operações bancárias ocorrem no nível de pessoas jurídicas no Brasil.

Para isso, nós estamos buscando um Engenheiro de Software iOS que queira encarar junto conosco o desafio de estruturar uma área de mobile banking **DO ZERO**, sendo plenamente responsável pelas decisões técnicas e seus impactos no produto no médio/longo prazo.

Se você gosta de trabalhar com produtos digitais, gosta do mercado financeiro e tem vontade de trabalhar com um time altamente performático, em uma proposta **remote-first**, nós achamos que aqui é o seu lugar!

## Posição
Senior / Lead iOS Engineer

## Tipo de contratação
A contração será CLT Full, **remoto** ou **presencial** 

###### Obrigatórios

- Domínio ímpar das linguagens ObjC e Swift (só usamos essa última)
- Domínio das principais APIs do iOS Framework, dos toolkits de UI à integrações com recursos do sistema
- Domínio do ferramental oficial para iOS, bem como vivência com *toolings* alternativos (Fastlane por excelência)
- Experiência comprovada com publicação de aplicações na App Store
- Experiência comprovada com testes automatizados em seus vários sabores (unidade, integração, funcionais de aceitação, E2E)
- Experiência comprovada com **Continuous Integration** e **Continuous Delivery** para iOS
- Vivência e opinião crítica sobre mais de um padrão de arquitetura para composição das responsabilidades da aplicação no contexto de iOS (MVC, MVP, MVVM, VIPER, MVI, Redux, etc) 
- Noções sólidas de programação reativa funcional (usamos RxSwift)
- Domínio de alguns dos principais frameworks *open-source* amplamente adotados pela comunidade iOS/Swift em aplicações modernas

###### Desejáveis

- Vivência com produtos digitais financeiros ou de apps de larga escala
- Vivência e opiniões críticas sobre mais de uma metodologia de gestão de projetos em software
- Ter sido Senior em alguma experiência anterior e entender as responsabilidades associadas a essa posição
- Noções de engenharia de segurança aplicada a iOS
- Experiência com ferramentas de métricas e de marketing aplicadas à Mobile (GA, Mixpanel, Localytics, Firebase, etc, etc, etc)

###### Diferenciais

- Ter / contribuir com projetos *open-source* bacanas no Github
- Participar da comunidade de tecnologia iOS com palestras e afins

## Com quem você vai trabalhar

Nossa área de Banking é uma nova vertical dentro da Stone Co. Nós estamos com um time multidisciplinar, que tem Elixir como stack principal no backend; para além do ecossistema iOS em si, você terá a oportunidade de interagir com alguns dos principais destaques brasileiros nos ecossistemas de Elixir, Node.js e Android. 

Nosso objetivo é ajudar você e o time iOS serem destaques dentro na nossa área, e você vai trabalhar diretamente com um pequeno time de desenvolvedor@s extremamente talentos@s, engajad@s, e altamente motivad@s.

## Como aplicar
O processo seletivo consiste de algumas entrevistas e um desafio técnico. Tudo começa com você mandando seu contato de interesse através do email abaixo!

## Contato
Envie seu currículo / LinkedIn para **pedro.cecchetti@stone.com.br**

**Comment by bguidolim** [comment]
Se usa só Swift, por que precisa do domínio ímpar em ObjC? 🤔

**Comment by rafsouzap** [comment]
E estão aceitando candidatos com mais de 30 anos? Pois da última vez que participei o enfoque ficou em se relacionar com pessoas mais "novas" e não no stack tecnológico em si.

**Comment by ubiratansoares** [comment]
> Se usa só Swift, por que precisa do domínio ímpar em ObjC? 🤔

@bguidolim eventualmente nós sabemos que precisamos integrar com dependências de terceiros, e essas podem ser em Objective-C. Por isso, nós pressupomos que um Sr iOS Engineer tem conforto com essa linguagem e lida bem com esse e outros casos de uso no tocante à interoperabilidade das linguagens nativas do iOS

**Comment by lovepanda0112** [comment]
Dear Hiring Manager,

Recently I studied all the details given in your job posting. 
From your job description,  I came to understand that you need an expert iOS Developer for your project. I would be highly happy to declare my candidacy for this post. 
I would be happy to let you know that my background includes designing and delivering creative projects and also it includes services from concept through completion.
Along with my ability to collaborate effectively with clients, peers, and senior management teams, I can assure you that my talents and abilities will significantly benefit you in this particular project of yours.
I really look forward to discuss the project requirements in detail.
You can always find me on Email and Skype if you need.
I am willing to work for 60 hours per week to make your project successful if you just hire me once.
Thank you for your consideration.
Sincerely,

Alexey.

**Comment by ubiratansoares** [comment]
@lovepanda0112 

Hi Alexey

Glad to have your attention to our job offering. For this position, we are looking `exclusively` for a brazillian or portuguese fluent speakers (native or not) by now.  Because of that, this issue is intentionally written in portuguese as well.

Please, don`t get me wrong here : we have a remote-first openness, but we believe that a multi-language / multi-cultural distributed workforce is a little bit far away from our team status quo. 

A distributed team sounds like our logical next step in the mid-term, and we may get in touch with you in the future! 

Best from Brazil

**Comment by cocuroci** [comment]
Pedro, como funciona o trabalho remoto?

**Comment by willianpinho** [comment]
Olá Pedro,

Enviei um e-mail há algumas semanas e não obtive resposta ainda. Ainda está aberto processo seletivo?

Grato

**Comment by pedrocecchetti1** [comment]
@willianpinho 
Eu respondi o seu e-mail no dia 19/04, você não recebeu?

Estou enviando novamente nesse instante, por favor confirme o recebimento.

**Comment by pedrocecchetti1** [comment]
@cocuroci 
O trabalho é full remote, se quiser você pode trabalhar totalmente de casa.
Nossos times seguem a organização de squads, usamos de bench o modelo do spotify.
As cerimônias como Dailys, Sprint reviews e etc, são determinadas por cada Squad e essas reuniões são realizadas por videoconf com toda a equipe.
Caso esteja na cidade do Rio ou de São Paulo também há a disponibilidade de poder trabalhar dos nossos escritórios.

**Comment by cocuroci** [comment]
Legal @pedrocecchetti1. Enviei minha candidatura para o email informado.

Abraços.

**Comment by pedrocecchetti1** [comment]
Vaga Fechada!
