### ISSUE TITLE
[São Paulo] Dev. iOS Pleno/Sênior

### ISSUE THREAD

**Issue by igor9silva** [CocoaHeadsBrasil/vagas#306]
### EvolutionIT Services

Somos uma consultoria de TI jovem, porém madura, que combina em seu time profissionais com larga vivência em projetos de TI de elevada complexidade a uma equipe de desenvolvedores e especialistas nas mais recentes tecnologias para as áreas de Business Intelligence e Mobilidade Corporativa.

## Local

São Paulo - Barra Funda (1 quadra do metrô)

#### Diferenciais

- Participar do desenvolvimento de soluções de mobilidade corporativa para diversos clientes
- Oportunidade de trabalhar em empresa 100% nacional com tecnologias de ponta
- Liberdade para propor novas atividades, processos e metodologias
- Horário flexível, ambiente descontraído, escritório a menos de 5 minutos do metrô Barra Funda

## Requisitos

**Obrigatórios:**
- Objective-C e Swift + CocoaTouch
- Versionamento com GIT
- Inglês avançado
- Boas práticas
- CocoaPods
- Design patterns, MVC, MVVM, MVP...
- Capacidade para assumir responsabilidades – ser pragmático e ter foco no resultado
- Capacidade interpretativa e facilidade para traduzir requisitos em soluções

**Desejáveis:**
- Experiência com plataformas SAP (SMP)
- SQL
- REST
- CoreData
- RxSwift
- Abordagens ágeis
- Carthage, SPM

## Contratação

PJ, a combinar

## Como se candidatar

Por favor envie um email para igor.silva@evolutionit.com.br com seu CV anexado - enviar no assunto: Vaga iOS

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by Viniciuscarvalho** [comment]
Igor, seria bom colocar o nome da empresa na descrição da vaga ou no título.

**Comment by igor9silva** [comment]
@Viniciuscarvalho opa, falha minha. Atualizado, obrigado!
