### ISSUE TITLE
[SP - Barueri - Alphaville] Iteris Consultoria e Software - Desenvolvedor(a) iOS Pleno 

### ISSUE THREAD

**Issue by Ruthlene** [CocoaHeadsBrasil/vagas#309]
## Empresa
A Iteris é parceira das maiores fornecedoras de tecnologia do mundo e líder em soluções de Colaboração, Integração na plataforma Microsoft e BI.
Somos comprometidos com os desafios da TI dos nossos clientes e nossa missão é prestar serviços de TI com excelência na qualidade e atendimento diferenciado, buscando construir laços reais e duradouros com nossos clientes, colaboradores e parceiros.
Procuramos pessoas que gostem de desafios, se interessem verdadeiramente em transformar a TI em diferencial para os negócios das empresas e sejam apaixonadas por tecnologia.

## Descrição da vaga
Missão do Cargo:
Compreender o negócio e a necessidade do cliente, de forma a desenvolver a aplicação que melhor atenda aos seus desafios, dentro do prazo estipulado.

O que você precisa fazer?
Experiência nas etapas de análise conceitual e desenvolvimento de aplicações de negócio utilizando:
Swift;
Orientação à Objetos;
Integração com APIs Restful e/ou Webservices;
Design Patterns;
Experiência em adaptação de layouts entre iPhone/iPad;
Guidelines de design e de desenvolvimento da Apple;
Metodologias ágeis (Scrum e XP);
GIT;

## Posição
 Júnior e Pleno

## Tipo de contratação
Trabalho presencial, CLT ou PJ

## Requisitos
Que tipo de habilidades buscamos?
Ser criativo e cheio de ideias;
Ser comunicativo e curtir trocar experiências;
Gostar de compartilhar e absorver conhecimento;
Ser questionador naquilo que faça sentido;
Se preocupar com o cliente que está utilizando aquilo o que desenvolvemos;
Mantem-se atualizado e sempre está por dentro de novas tecnologias;
Sentimento de dono no que atua;
Procura ser organizado e opinar em soluções;
Técnicas e práticas ágeis para os ciclos de desenvolvimento tornam suas entregas mais efetivas e fica motivado com o resultado agregado a cada sprint;

## Benefícios
O que oferecemos?
Pacote atraente de remuneração;
Time altamente capacitado, focado em meritocracia, colaboração e constante atualização tecnológica;
Ambiente descontraído e horário flexível;
Uma das melhores assistências médicas do Brasil, assistência odontológica opcional e seguro de vida;
Cesta de benefícios flexível para distribuir livremente entre VR, VA e VT.

## Como aplicar
https://jobs.kenoby.com/iteris/job/desenvolvedor-ios-juniorpleno/5ad0bd106425dc0dadb76e1a

## Contato
https://www.iteris.com.br/

**Comment by jefersonalvarenga** [comment]
No link aparece a mensagem abaixo:

Obrigado pelo seu interesse!
Infelizmente esta posição já foi encerrada, mas fique a vontade para procurar outras oportunidades na nossa página de carreiras.

**Comment by marcelofabri** [comment]
Fechando a vaga. @Ruthlene se a vaga ainda existir, por favor atualize o link e mande um comentário que a reabriremos.
