### ISSUE TITLE
[São Paulo - Paulista] Projeto Maior - Dev IOS com React Native

### ISSUE THREAD

**Issue by Tnunciaroni** [CocoaHeadsBrasil/vagas#315]
## Empresa
Empresa Americana, profissional ficará alocado em SP

Dev IOS com conhecimentos em React Native
Inglês Avançado/Fluente

## Tipo de contratação
PJ

## Como aplicar
enviar currículo para vagas@projetomaior.com.br

**Comment by reprotector** [comment]
@Tnunciaroni Vaga está totalmente fora dos padrões e das regras. Favor ler as regras antes de publicar: https://github.com/CocoaHeadsBrasil/vagas
