### ISSUE TITLE
(SP- Paulista- Desenvolvedor JAVA Sr)

### ISSUE THREAD

**Issue by DHAccesstage** [CocoaHeadsBrasil/vagas#318]
## Empresa
Accesstage somos uma empresa de tecnologia com foco em Conectividade Financeira, estamos no mercado há 17 anos.

## Descrição da vaga
Desenvolver soluções para a cadeia financeira com comunicação por webservices.

## Posição
Posição Pl/ Sr

## Tipo de contratação
Contratação CLT

## Requisitos
- Desenvolvimento orientado a serviços. 
- Experiencia em Frameworks de front-end (ANGULAR, JSF, Prime Faces ou  Rich Faces). 
- Desejável conhecimento em Maven, GitLab e Jenkins.
- Desejável experiência em Back-End Java/Docker 
- Banco de dados Relacional Oracle e/ou Postgree

###### Desejáveis
Certificação em linguagem de programação
experiência em ambiente EDI, conhecimento em tecnologias mobile e/ou integração contínua (Hudson, Sonar).

## Benefícios
VR, VA, VT, AM, AO, SEGURO DE VIDA

## Como aplicar
Terá um teste técnico e entrevistas.

## Contato
Interessados, favor encaminhar o currículo para: suellen.almeida@accesstage.com.br

**Comment by Viniciuscarvalho** [comment]
Olá @DHAccesstage , esse espaço são para vagas de iOS, essa vaga não está de acordo com o repositório, por isso irei fechar a issue.
