### ISSUE TITLE
[São Paulo - Vila Olímpia] Desenvolvedor iOS  [Junior] (Swift | Objective-C) | WebMotors 

### ISSUE THREAD

**Issue by ezefranca** [CocoaHeadsBrasil/vagas#32]
## Descrição da vaga

Vaga de Desenvolvedor iOS Junior no aplicativo Webmotors
[AppStore](https://itunes.apple.com/br/app/webmotors-comprar-e-vender/id496509047?mt=8)

## Local

Escritório São Paulo - Vila Olímpia (1 minuto da estação Vila Olimpia a pé)

## Requisitos

Obrigatórios

- Algum conhecimento/interesse em Objective-C (para dar manutenção num primeiro momento)
- Conhecimentos de Swift
- Alguma experiencia com Git (pull request, merge, resolução de conflitos)

Desejáveis

- Conhecimento em gerenciador de dependências (CocoaPods)
- Conhecer o processo de publicação na AppStore

## Contratação

PJ a combinar

## Nossa empresa

Maior portal automotivo da internet brasileira. Líder em audiência, com 8,5 milhões de usuários únicos. Atua no segmento de classificados de veículos e conta com mais de 200 mil anúncios de todo o Brasil. Atualmente, a WebMotors reúne o maior conteúdo editorial e diversos serviços e iniciativas que contribuem para a manutenção preventiva e melhoria da qualidade do trânsito dos grandes centros urbanos.

## Como se candidatar

Por favor envie um email para rodrigo.nunes@webmotors.com.br e/ou bsantos@webmotors.com.br com seu CV anexado - enviar no assunto: Vaga iOS - Junior

**Comment by Viniciuscarvalho** [comment]
O Rodrigo está de férias @ezefranca , sabe com quem entrar em contato lá?
