### ISSUE TITLE
[MG - Uberlândia] Desenvolvedor iOS Sênior

### ISSUE THREAD

**Issue by chsqrodrigues** [CocoaHeadsBrasil/vagas#322]
## Empresa
TQI - Technology and Quality on Innovation

## Posição
Sênior

## Tipo de contratação
Presencial, CLT ou PJ (a negociar)

###### Obrigatórios
-Swift
-GIT
-JSON
-Testes unitários
-MVVM

###### Desejáveis

- Arquitetura de Software
- Conhecimentos de Design Patterns;
- Carthage
- Continuous Integration / Fastlane

###### Diferenciais

- Pró-atividade
- Resolver problemas
- Criativo e Inovador

## Benefícios

- Horário Flexível;
- Ambiente de trabalho;
- Mesa de pebolim;
- Playstation 4
- Hockey
- Happy Hours

## Como aplicar
Enviar CV para tqi_crodrigues@uolinc.com

**Comment by Viniciuscarvalho** [comment]
Por favor @chsqrodrigues , depois colocar o nome da empresa contratante.
