### ISSUE TITLE
[SP e BH] Avenue Code - Desenvolvedor iOS 

### ISSUE THREAD

**Issue by TalentAcquisiton** [CocoaHeadsBrasil/vagas#333]
## Empresa
 A Avenue Code é a principal consultoria de software focada na entrega de soluções de desenvolvimento ponta a ponta para a transformação digital em todas as vertentes. Com sede em São Francisco e três escritórios adicionais (Nova Iorque, Belo Horizonte e São Paulo) a Avenue Code é uma empresa 100% financiada com capital privado, rentável, e apresenta uma sólida trajetória de crescimento desde o primeiro dia. Nós nos preocupamos profundamente com nossos clientes, nossos parceiros e nossos consultores. Preferimos a palavra "parceiro" a "fornecedor" e nossos investimentos nos relacionamentos profissionais são um reflexo dessa filosofia. Temos muito orgulho da nossa perspicácia técnica, da nossa capacidade colaborativa de resolução de problemas e do calor e profissionalismo dos nossos consultores.

## Posição
 Pleno e Sênior

## Tipo de contratação
CLT - Presencial

## Requisitos
Analisar, projetar, programar, depurar e modificar software;
Escrever códigos realizar testes e depurar aplicações;
Interagir com os usuários para definir os requisitos de sistema e/ou modificações necessárias, bem como interagir com os interessados para entender os requisitos para o desenvolvimento de aplicações.

###### Obrigatórios
Experiência com desenvolvimento de software;
Experiência com iOS SDK;
Experiência com metodologias Ágeis;
Experiência com tecnologias relacionadas a desenvolvimento móvel, tais como iOS SDK, Objective C, Cocoa, xcode IDE e REST/JSON;
Conhecimento em MVC, MVP e/ou MVVM;
Conhecimento em Testes Unitários
Inglês avançado.

###### Desejáveis
Conhecimento em novas técnologias como SWIFT
Conhecimento em UI Tests

## Benefícios
VR ou VA + Plano de Saúde (Bradesco) + Plano Odontológico (Odontoprev) + Aulas de Inglês 2 vezes por semana (no horário de trabalho) + PLR + Bônus por Performance + Reembolso de Certificações Técnicas (lista pré determinada) + Horário Flexível.

## Como aplicar
Candidate-se através do link: https://www.avenuecode.com/careers/belo-horizonte-mg/desenvolvedor-a-mobile-ios/

**Comment by cocuroci** [comment]
Existe possibilidade Remoto?

**Comment by TalentAcquisiton** [comment]
Olá @cocuroci!
Na Avenue Code nós trabalhamos apenas com a modalidade presencial :)

**Comment by cocuroci** [comment]
Obrigado pelo retorno @TalentAcquisiton
