### ISSUE TITLE
[São Paulo] Nubank - Mobile Continuous Deployment Engineer

### ISSUE THREAD

**Issue by miguelbassila** [CocoaHeadsBrasil/vagas#339]
# Nubank
Leading fintech in Latin America. Using bleeding-edge technology, design and data, Nubank is committed to fighting complexity and empowering Brazilians to take control of their finances. Over 8 million people have applied for its mobile-controlled credit card since its launch on September 2014.

Located in the Pinheiros region of São Paulo, Nubank has raised USD 180 million in investment rounds led by Sequoia Capital, Founders Fund, Tiger Global, Kaszek Ventures, Goldman Sachs, QED Investors and DST Global.

With a team of over 500 of the highest-performing engineers, decision scientists, designers, and analysts, Nubank is dedicated to creating an inclusive and challenging work environment as well as the best products and customer experience.

Why is Mobile Systems Engineering important for Nubank?
Nubank is a technology company, and software engineers form the bulk of our team. Also, our mobile infrastructure is growing in sophistication, complexity, robustness and observability. We are looking for engineers that can help with the challenges around provisioning and operating such architectures.

### What are some examples of problems a Mobile Systems Engineer will solve?
Here at Nubank we treat infrastructure and operations as Software Engineering problems. It's expected of a Mobile Systems Engineer to have solid programming skills coupled with background on modularized projects and operating systems. We consistently work with new technologies and thus value professionals who are open to learning new things, regardless of pre-existing comfort zones.

Some of the problems you'll encounter:
* Identify bottlenecks on building and testing performance and work on improving them;
* Scale systems efficiently through configuration tuning and/or major architectural changes;
* Troubleshoot/debug performance issues and architectural bottlenecks on mobile CI pipelines;
* Cultivate a culture of observability and monitoring;
* Provide a friendly API to other Engineers for working on the monorepo structure;
* Contribute to (and/or create) open-source projects to improve our tooling and automation.

*More about us*
[Our environment](https://exame.abril.com.br/negocios/por-dentro-da-sede-roxa-e-inovadora-do-nubank/)

### You will fit well
* You aren't afraid of crossing abstraction boundaries to go deep into the root cause of an issue;
* You enjoy operating a dynamic, large scale, complex environment;
* You want to understand the big picture, to be held accountable and make a meaningful contribution with your work

### Relevant experiences
* You write high quality code in a programming language (high-level scripting and functional paradigm)
* Android and/or iOS platform knowledge
* Automated Android and/or iOS applications process of building, testing and deployment
* Modularized Android/iOS applications
* Build tools (gradle, buck)
* Infrastructure as code (e.g. CloudFormation, Ansible, Terraform)
* Containerized environment and container orchestration (Docker)
* Cloud environment (AWS, GCE, private cloud)
* Monitoring and Culture of Observability (Riemann, InfluxDB, Grafana, Prometheus)
* An engineering or computer science undergraduate degree and English language skills are helpful, but we have people with all kind of backgrounds here.

## Benefits
* Casual and international environment - you can wear shorts and havaianas in the office and work with people from different places in the world
* Cool office with a great location - we're accessible by bus and subway, situated in * Pinheiros/Jardins and therefore close to many fun bars and restaurants
* Competitive compensation package and access to the company's Stock Option * * Plan based on performance
* Health, dental and life insurance
* Flexibility to choose your own custom setup (computer, monitors, OS, etc.)

## Location
São Paulo - Pinheiros

## Hiring
CLT - Full

*Meet the Nubankers: http://sou.nu/engmobile*

## Apply
https://boards.greenhouse.io/nubank/jobs/1776032?t=f35a5fb11

**Comment by cocuroci** [comment]
Existe chances de trabalho remoto?

**Comment by ronanrodrigo** [comment]
@cocuroci não temos nenhuma política sobre trabalho remoto. Mas, podemos trabalhar remoto esporadicamente.

**Comment by miguelbassila** [comment]
Vaga ainda está aberta

**Comment by ronanrodrigo** [comment]
Vaga ainda está aberta

**Comment by pietrocaselani** [comment]
Vaga ainda está aberta

**Comment by miguelbassila** [comment]
Vaga ainda está aberta

**Comment by Bunn** [comment]
reabrindo por pedido do @miguelbassila

**Comment by miguelbassila** [comment]
Vaga ainda está aberta
