### ISSUE TITLE
[São Paulo] Desenvolvedor Android - Sênior  - Contratação CLT 5A Attiva - Presencial 

### ISSUE THREAD

**Issue by HeloisaMoraes** [CocoaHeadsBrasil/vagas#342]
## Empresa
A 5A Attiva é especialista em identificar profissionais de alta performance em Tecnologia da Informação, especialmente na área de desenvolvimento de software

## Descrição da vaga
Desenhar sistemas de informação apropriados às necessidades dos usuários e consistentes com a arquitetura de software da organização,

## Posição
 Sênior 

## Tipo de contratação
 Presencial CLT + Benefícios 

###### Obrigatórios
Experiência de mais de 5 anos em análise e desenvolvimento de sistemas:
Experiência em desenvolvimento Mobile para IOS
Consumo de serviços rest via aplicação Mobile
Conhecimento no sistema operacional IOS
Linguagem S wift
Plataforma Java ( JSE, JEE, APIS e Bibliotecas ).
Repositório de código (git, svn)
Bibliotecas, frameworks e ferramentas (obrigatórios: Spring, Hibernate)
## Benefícios
Vale Transporte; Vale Alimentação de R$ 900,00/mês; Vale Refeição R$ 31,50/dia;  + Assistência medica
(Sul América ) plano padrão + Assistência Odontológica + Seguro de Vida + PLR

## Com quem você vai trabalhar
Se desejar insira uma lista dos futuros colegas de trabalho. Você pode gerar uma com os usuários do GitHub dos funcionários em http://fpg1503.com/GithubProfileTableGenerator/

## Como aplicar
Informe como é feito o processo para aplicar a vaga

## Contato
Interessados enviar CV para heloisa.moraes@5aattiva.com.br

**Comment by Viniciuscarvalho** [comment]
Olá @HeloisaMoraes , aqui as vagas são somente para desenvolvedores iOS, existe um repositório exclusivo para Android - https://github.com/androiddevbr/vagas.

Vou fechar a vaga ok?
Obrigado.
