### ISSUE TITLE
[DF - Brasília] AGSOFT - Desenvolvedor iOS

### ISSUE THREAD

**Issue by joaogabriel** [CocoaHeadsBrasil/vagas#344]
## Empresa

A AG Soft foi fundada em 2004, com sede em Brasília-DF e atuação em todo o território nacional. Cresceu com grande potencial em consultoria e prestação de serviços em Tecnologia da Informação no segmento de Gestão e Segurança da Informação.

No ano 2012 a AG Soft ampliou seus negócios em Gestão Documental, efetuando serviços de bureau de digitalização de acervos documentais para diversos órgãos públicos federais, estaduais e municipais em todo o Brasil.

## Descrição da vaga

Venha para o nosso time de desenvolvimento!
 
Estamos buscando um programador com experiência em desenvolvimento nativo iOS (linguagem Swift) para desenvolver e auxiliar no projeto de aplicativos mobile iOS (iPhone e iPad) com integração a sistemas, serviços e banco de dados.
 
O candidato ideal precisa ter vontade de aprender, trabalhar em equipe, ser dinâmico, responsável, pró-ativo e comprometido. Se tiver domínio em desenvolvimento em Android melhor ainda.

## Posição
Desenvolvedor iOS - Pleno ou Sênior

## Tipo de contratação
PJ ou Freelancer. Informar pretensão.

###### Obrigatórios

- Já ter publicado aplicativos na App Store
- Linguagem Swift
- XCode
- JSON/XML
- Integração com outras APIs/Webservices
- Conhecimento dos mecanismos de autenticação (Google, Facebook e Twitter)
- Push Notifications
- Git
- Firebase

###### Desejáveis

- Objective-C
- Conhecimentos em Machine Learning
- Conhecimentos  para  reconhecimento facial e de imagens
- Conhecimento em desenvolvimento Android
- Boas noções de UX & UI
- Adaptação de layouts de smartphones e tablets
- Experiência em trabalhar com times ágeis utilizando ferramentas de controle de versão e - atividades como GIT/TFS/Jira entre outros
- Testes unitários e automatizados (TDD);  
- Provisionamento de aplicações
- Conhecer como trabalhar com bibliotecas open source e entender todo o ecossistema iOS
- Habilidade para se comunicar bem e recomendar melhores práticas de desenvolvimento
- Arquitetura de Software
- Geração de certificados iOS

## Como aplicar
Envie um email com o título "iOS Developer" fornecendo CV / Portfolio / Github + Pretensão Salarial para: guilherme.armani@agsoft.com.br

## Contato
AGSOFT - www.agsoft.com.br ou +55 61 3225-8000

**Comment by thiagodelmotte** [comment]
@reprotector vaga já foi finalizada segundo a empresa
