### ISSUE TITLE
[Campinas/SP] Desenvolvedor iOS - Buildbox IT Solution

### ISSUE THREAD

**Issue by Marianashare** [CocoaHeadsBrasil/vagas#346]
Empresa de tecnologia localizada em Campinas, S.P., com foco em inovação no desenvolvimento de aplicativos nativos e sistemas web.
A empresa possui uma forte cultura e procura profissionais que estejam engajados com ela. É uma companhia que utiliza e aprende sobre tecnologia de ponta, oferece aos funcionários o envolvimento com grandes projetos e ganho rápido de responsabilidades, crescimento contínuo na função e ambiente jovem e descontraído.

Para pessoas cursando ou formadas em áreas correlatas.

Experiências desejáveis da vaga:
· Conhecimento de Swift, Objective-C;
· Experiência em uso de Autolayout;
· Conhecimento de ferramentas como GIT, Xcode, Fastlane;
· Conceitos de programação reativa;
· Criação de códigos de boa qualidade a partir de designs de wireframes;
· Criação e manutenção da arquitetura, identificação e manutenção de bugs e gargalos de performance em alguns dos aplicativos do grupo.

OBS: A vaga é efetiva - Profissional PJ

Por favor, encaminhar o seu currículo atualizado para o e-mail ct@sharerh.com com o assunto iOS - Campinas.

**Comment by bguidolim** [comment]
E qual a empresa?

**Comment by Marianashare** [comment]
Ola, poderia nos passar seu contato para falarmos melhor à respeito da vaga?



2018-07-03 18:07 GMT-03:00 Bruno Guidolim <notifications@github.com>:

**Comment by bguidolim** [comment]
Na verdade não estou interessado na vaga, digo isso por que são as regras para anunciar vagas neste repositório.

Todas as regras de uso podem ser encontradas aqui: https://github.com/CocoaHeadsBrasil/vagas#regras-de-uso

A regra em questão é essa aqui:
```
Todas as vagas devem conter o nome da empresa que está contratando

Se você é um recrutador, você deve identificar o nome da empresa em que o candidato irá trabalhar
```

Por ora vou invalidar a vaga, se topar seguir as regras de uso é só editar esta vaga ou abrir uma nova.

Obrigado.

**Comment by Marianashare** [comment]
Oi Bruno,
Eu sou de uma consultoria de Recrutamento e Seleção. E fomos contratados
para conseguir candidatos para nosso cliente, que focasse esse contato aqui
consco, por isso deixamos o nome da empresa como confidencial. E realmente
não sabia das regras, desculpe. Vocês vão divulgar as vagas com o nome da
empresa? Ou pode ser colocado o nome da nossa, Share RH?

Aguardo retorno.
Obrigada.



2018-07-04 9:29 GMT-03:00 Bruno Guidolim <notifications@github.com>:

**Comment by bguidolim** [comment]
Como a vaga em questão é PJ, se no contrato de prestação de serviço a empresa contratante for a Share RH, então poderemos divulgar normalmente. Caso contrário, será mantida como inválida.

**Comment by Marianashare** [comment]
Então esta bem.
Pode colocar o nome da empresa

Buildbox

Confirme se será anunciada, por favor.
Obrigada.



Em 4 de julho de 2018 15:54, Bruno Guidolim <notifications@github.com>
escreveu:

**Comment by bguidolim** [comment]
Perfeito, já vou habilitar.
Ajuda pro pessoal que está procurando a vaga citar qual o nível do desenvolvedor que procuram.

Obrigado por colaborar :)

**Comment by Marianashare** [comment]
Obrigada pela parceria.
Fico à disposição.



2018-07-04 16:18 GMT-03:00 Bruno Guidolim <notifications@github.com>:
