### ISSUE TITLE
[Campinas] Desenvolvedor iOS

### ISSUE THREAD

**Issue by talentreplacement** [CocoaHeadsBrasil/vagas#352]
Exigências:
Experiência comprovada em desenvolvimento de software, aplicativos iOS em Swift;
Ao menos um aplicativo publicado na Google Play Store;
Experiência em APIs, Apple e Google;
Experiência em trabalhos com dados remotos via REST e JSON;
Experiência em implementação de bibliotecas de terceiros (Facebook/Twitter/Google/etc);
Sólido conhecimento da arquitetura de aplicações move e seu ciclo de vida

Responsabilidades:
Criar e desenvolver aplicativos avançados na plataforma iOS
Colaborar com o time multifuncional para definir, desenhar e entregar novas funcionalidades
Trabalhar com APIs e serviços externos de dados
Criar códigos robusto, testável e reutilizável
Trabalhar em correções de bugs e aperfeiçoamento da performance de aplicações
Continuamente descobrir, testar e implementar novas tecnologias para maximar a eficiência do produto e do desenvolvimento.

Enviar cv com pretensao salarial para: recrutamento@talentreplacement.com.br

**Comment by reprotector** [comment]
Olá @talentreplacement , Estou desativando a vaga temporariamente pois está fora das nossas regras de uso. 

> Todas as vagas devem conter o nome da empresa que está contratando
>Se você é um recrutador, você deve identificar o nome da empresa em que o candidato irá trabalhar

**Comment by moquiutijunio** [comment]
Bom dia, não seria um aplicativo publicado na App Store?

**Comment by pmnascimento** [comment]
@moquiutijunio nada, acho que para o  cara concorrer a vaga,  ele tem que ter feito um app iOS mas publicado na Google Play isso para provar que ele é bom mesmo.

AHAHAHHAH,
