### ISSUE TITLE
[Campinas] Dextra Digital - iOS Developer Pleno/Sênior

### ISSUE THREAD

**Issue by Lilicaan** [CocoaHeadsBrasil/vagas#356]
## Empresa
A Dextra é um estúdio de inovação digital e de desenvolvimento de software ágil para clientes que buscam criar produtos disruptivos. Combinamos processos de inovação, design de UX, novas tecnologia e visão de negócios para criar software que reposicione os nossos clientes no mundo dos negócios digitais.

## Descrição da vaga
Se você é ávido por tecnologias de ponta e gosta de novos desafios...Aqui é o seu lugar!
Na Dextra os desenvolvedores são responsáveis pela expertise e conhecimento das tecnologias e propõem as melhores soluções técnicas durante todo o processo de desenvolvimento garantindo o sucesso da entrega para o cliente.

O que você precisa saber para ocupar esta vaga?
Programar.. Mas com paixão!  
Ser fera no desenvolvimento de aplicativos na plataforma iOS usando Objective-C e principalmente Swift; 
Desenvolver novas funcionalidades para os produtos digitais de nossos clientes  e ter conhecimento em desenvolvimento de telas para iOS (Storyboard, Auto Layout, componentes nativos, Views, criação de componentes customizados).

## Tipo de contratação
CLT

## Como aplicar
Curtiu? Mande seu cv ou linkedIn para recurtamento@dextra.com.br - Assunto: iOSCPS

**Comment by barrault01** [comment]
Vaga ainda está aberta

Le mar. 16 oct. 2018 à 22:27, stale[bot] <notifications@github.com> a
écrit :
