### ISSUE TITLE
[SP-Vila Leopoldina] - Toodoo Desenvolvedor iOS Pleno/Senior

### ISSUE THREAD

**Issue by leresche** [CocoaHeadsBrasil/vagas#366]
## Empresa
Você pode conhecer mais sobre a toodoo em http://toodoo.com.br/, mas o melhor jeito e dar um pulo aqui e conversar com o pessoal!

## Descrição da vaga
Precisamos de um Dev iOs para nosso time interno.

## Posição
Desejamos que a pessoa tenha experiência entre pleno e sênior, tanto faz se é recém pleno ou recém sênior.

## Tipo de contratação
Contratação presencial PJ.

###### Obrigatórios
Conhecimento em Objective-C e Swift
X-Code
Interface Builder

###### Desejáveis
Experiência em Objective-C
Cocoa Pods

## Benefícios
Trabalhar com um time triple A
Flexibilidade de horário
Home-Office 1 vez por semana

## Como aplicar
Visita na toodoo, conversa com time (técnico e os bosses)

## Contato
Igor +55 11 99105-4940
Thiago +55 11 96400-3854

**Comment by danilorequena** [comment]
Como posso me candidatar?
