### ISSUE TITLE
[São Paulo - Paulista] Spring Professional - Desenvolvedor iOS Pleno e Senior

### ISSUE THREAD

**Issue by giovannaghetti** [CocoaHeadsBrasil/vagas#369]
[São Paulo - Paulista] Spring Professional - Multinacional de Tecnologia - Desenvolvedor iOS Pleno e Senior

Spring Professional, consultoria de Recrutamento e Seleção para média e alta gerência contrata para multinacional de tecnologia um Desenvolvedor iOS Sr e um Desenvolvedor iOS Pl.

Desenvolvedores iOS Pleno e Senior
CLT Full
Requisitos:
- Ter trabalhado com migração ObjectiveC para Swift 4;
- Ter trabalhado com geração de SDK;
- Possuir aplicativos publicados;
- Ter participado de tomada de decisões para o melhor andamento do aplicativo;
- Ter trabalhado com integrações e consumo de apis de terceiros;
- Ter conhecimento com SourceTree, Bitbucket, SqlPro For Sqlite;
- Conhecer o ciclo de vida e processos do app desde a definição e levantamento de requisitos até a loja;
-  Inglês intermediário.

Diferenciais: 
- Conhecimento em Android;
- Plataformas Cross;

Benefícios: 
VA, VT, VT, AM, AO, Seguro de Vida, Auxílio Creche. 

Interessados enviar e-mail com CV + pretensão salarial para: giovanna.ghetti@spring.com

Para mais informações:
Giovanna Crem Ghetti (Linkedin)
giovanna.ghetti@spring.com (e-mail)

**Comment by Uragawa** [comment]
Favor incluir o nome da empresa contratante de acordo com as [regras do canal](https://github.com/CocoaHeadsBrasil/vagas#todas-as-vagas-devem-conter-o-nome-da-empresa-que-est%C3%A1-contratando).

**Comment by unnamedd** [comment]
@giovannaghetti de acordo a violação da regra

> **Todas as vagas devem conter o nome da empresa que está contratando**
> Se você é um recrutador, você deve identificar o nome da empresa em que o candidato irá trabalhar
> 

sua issue foi fechada e o conteúdo removido.
