### ISSUE TITLE
[SP - Campinas] Dextra - Pessoa desenvolvedora iOS

### ISSUE THREAD

**Issue by biancanalien** [CocoaHeadsBrasil/vagas#374]
## Empresa

Somos um estúdio de inovação digital e de desenvolvimento de software ágil.
Projetamos e desenvolvemos soluções digitais que criam oportunidades para clientes como Google, Globosat, Livelo, Nextel, Marisa, Confidence/Travelex, entre muitos outros.

Nossa cultura é nosso diferencial. Nossos valores são baseados na cooperação, transparência e na confiança mútua entre as pessoas, além do orgulho pelo próprio trabalho que vem da liberdade para inovar em suas atividades.

A Dextra enfatiza a diversidade e trata com equidade e respeito todos seus colaboradores independente de gênero, orientação sexual, raça, idade, nível sócio econômico, PCD´s ou qualquer outra característica individual. Fazemos questão de ter diferentes perfis em nosso quadro e temos oportunidades iguais para todos colaboradores. Aqui você pode ser você mesmo!

## Descrição da vaga

Se você curte tecnologias de ponta e gosta de novos desafios...Aqui é o seu lugar!
Estamos procurando pessoas desenvolvedoras iOS!

As pessoas da Dextra são responsáveis pela expertise e conhecimento das tecnologias e propõem as melhores soluções técnicas durante todo o processo de desenvolvimento de software, garantindo o sucesso da entrega para o cliente. Venha conhecer a gente e fazer parte desse time!

## Posição
 Pleno e Senior

## Tipo de contratação
Presencial CLT

###### Obrigatórios
- Ser fera no desenvolvimento de aplicativos na plataforma iOS usando Swift; 
- Ter conhecimento em desenvolvimento de telas para iOS (Auto Layout, componentes nativos, Views, criação de componentes customizados)
 - Experiência com Xcode, Fastlane e Storyboards

###### Diferenciais
 - Implementar testes unitários e de tela
 - Experiência com ferramentas de CI (Ex: Fastlane e Circle CI)
 - Ser ativo na comunidade
 - Escrever em blogs, palestrar etc. 

## Benefícios
- Plano de saúde
- Plano Odontológico
- Seguro de vida
- Vale Refeição, alimentação e combustível
- Auxílio creche

## Diferenciais
- Equipe autônomas
- Mentoria
- Horário flexível / Home office
- Vídeo games e jogos
- Ambiente descontraído
- Plano de carreira
- Eventos internos de compartilhamento de conhecimento
- Snacks
- Cerveja de sexta-feira

## Como aplicar
Por favor envie um email para liliane.silva@dextra-sw.com com seu CV anexado - enviar no assunto: Vaga iOS

## Contato

liliane.silva@dextra-sw.com
juliana.pessoto@dextra-sw.com

## Labels
CLT
Presencial
Pleno
Senior

**Comment by cocuroci** [comment]
Aceita totalmente remoto?

**Comment by biancanalien** [comment]
@cocuroci acredito que essa seja só presencial, mas você pode tirar essa dúvida melhor mandando email para a Lili (Liliane.Silva@dextra-sw.com)

**Comment by biancanalien** [comment]
Vaga ainda está aberta

**Comment by barrault01** [comment]
Vaga ainda está aberta

**Comment by barrault01** [comment]
Vaga ainda está aberta
