### ISSUE TITLE
[SP Vila Olimpia] iOS Developer (JR /PL) @ Docway

### ISSUE THREAD

**Issue by jefferson-docway** [CocoaHeadsBrasil/vagas#376]
## Empresa
 Docway - Startup Healthcare

## Descrição da vaga
Procuramos um developer pró-ativo, autônomo e criativo. Onde o mesmo fará parte de todo o  planejamento e desenvolvimento de nosso aplicativo.
Se você deseja criar, inovar, trabalhar com novas tecnologias e fazer a diferença para a saúde. Esperamos você!

## Posição
Júnior ou Pleno

## Tipo de contratação
 CLT 

###### Obrigatórios
- Desenvolvimento de aplicativos na plataforma iOS usando Swift;
- De 1 a 3 anos de experiência
- Inglês básico
- Xcode, 

###### Desejáveis
- Testflight
- Zeplin
- Git
- Firebase

## Como aplicar
Por favor enviar o seu CV para vagas@docway.co com o titulo da vaga.
#

**Comment by danilorequena** [comment]
Estou tentando enviar o currículo no e-mail citado, mas o e-mail está voltando com falha.

**Comment by jefferson-docway** [comment]
@danilorequena Olá Danilo, tudo bom? Por favor, você poderia renviar esse e-mail para: jessica.maiumi@docway.co ?

Peço também que confirme o sufixo do e-mail, pois tem que ser ".co", certo?

Obrigado
