### ISSUE TITLE
[ Belo Horizonte ] Desenvolvedor iOS Sênior

### ISSUE THREAD

**Issue by lukascaraujo** [CocoaHeadsBrasil/vagas#38]
## Descrição da vaga

Empresa que atua com desenvolvimento de aplicativos móveis e sistemas distribuídos, procura desenvolvedor iOS sênior que tenha excelente raciocínio lógico e goste bastante de programar. O desenvolvedor irá participar de projetos onde são envolvidos empresas de alto nível nacional e internacional.
## Local

Alocado na sede da empresa, localizado na região da Savassi em Belo Horizonte - MG
## Benefícios
- VT
- VR(450,00/mês)
- Plano de saúde
- Plano odontológico
- Reembolso de estacionamento
## Requisitos

Obrigatórios
- 5 anos trabalhando com aplicações móveis 
- Ter desenvolvido aplicações mobile relevantes (os apps serão avaliados) 
- Exímio conhecedor sobre a arquitetura de aplicações iOS
- Excelente raciocínio lógico
- Conhecimento aprofundado em Objective C/ Swift 
- Experiência em programação cliente servidor 
- Boas práticas de desenvolvimento 
- Conhecimento sobre Padrões de Projeto 

Desejáveis
- Inglês fluente
- Conhecimento em UX/UI
- Ter participado de comunidades, grupos de discussões, eventos e afins (online ou não) relacionadas ao desenvolvimento de software

Comportamental
- Facilidade de comunicação
- Capacidade analítica
- Excelente background técnico
- Capacidade de pensar e resolver problemas de forma criativa
- Apaixonado por mobile
## Contratação

CLT
## Como se candidatar

Por favor envie um email para vagas.ti@pontomobi.com.br com seu CV anexado - enviar no assunto: Vaga iOS Sênior

**Comment by reprotector** [comment]
@lukascaraujo Já fecharam a vaga? Pode fechar a issue?
