### ISSUE TITLE
[São Paulo] Desenvolvedor iOS - GetNinjas

### ISSUE THREAD

**Issue by lucaspedrazoli** [CocoaHeadsBrasil/vagas#380]
## Empresa GetNinjas
 A maior plataforma de contratação de serviços do Brasil, com mais de 400 mil profissionais 
 cadastrados em mais de 200 tipos de serviço – desde eletricistas até professores de inglês.

## Descrição da vaga
Buscamos uma pessoa que esteja em busca de aumentar sua experiência em um projeto consistente, com cultura de testes, arquitetura bem definida e que queira aumentar suas skills técnicas em iOS.

## Posição
Júnior ou Pleno

## Tipo de contratação
CLT presencial

## Requisitos
* Git
* Swift 4
* Testes unitários (TDD/BDD)
* Ter experiência com desenvolvimento Mobile e com desenvolvimento de software;
* Grande habilidade e facilidade com comunicação. Prezamos muito esse aspecto, além de claro, as tech skills.
* Aprendizado contínuo e disseminação do conhecimento adquirido;

###### Obrigatórios
* Git
* Swift 

###### Desejáveis
* Testes unitários (TDD/BDD)

###### Diferenciais
* Swift Generics
* Testes com QuickSpec/Nimble
* Conhecimento em Ruby

## Benefícios
* GymPass
* Vale transporte / Alimentação
* Plano de saúde
* Plano odontológico

## Como aplicar
https://jobs.kenoby.com/getninjas/job/desenvolvedora-ios-junior/5b7c174d7f4bdf698f4f1beb

## Contato
https://www.linkedin.com/in/lucaspedrazoli/

**Comment by Viniciuscarvalho** [comment]
Depois colocar no título da vaga ou na descrição a empresa ta @lucaspedrazoli ?
