### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor iOS - Stone Pagamentos

### ISSUE THREAD

**Issue by jaisonv** [CocoaHeadsBrasil/vagas#39]
## Descrição da vaga

A Stone é uma Adquirente de meios de pagamento, autorizada pela Visa e Mastercard a credenciar lojistas, processar e autorizar transações de cartão de crédito com essas bandeiras e outras.

Nossa Companhia nasceu com o propósito de fazer diferente, servir nossos comerciantes com excelência e prover as melhores tecnologias e inovações do mercado.

A Stone evolui a cada dia e, apesar de nova, possui uma tecnologia própria, robusta, capaz de suportar 10.000 transações por segundo.

Se você tem energia para aprender, sem medo de desenvolver novas soluções **e/ou** é um desenvolvedor mobile experiente e procura crescer com a empresa, candidate-se para a vaga!
## Local

Escritório, Centro - Rio de Janeiro
## Benefícios
- Horário flexível
- Video games
- Trabalhe de bermuda e chinelo
- Vale transporte
- Vale refeição/alimentação
- Plano de saúde
## Requisitos

**Obrigatórios:**
- Pelo menos com 1 ano de experiência com desenvolvimento Objective-C e/ou Swift
- Experiências com aplicações RESTful (JSON e XML)
- Bons conhecimentos na plataforma iOS
- Boas noções de Orientação a Objetos
- Controle de verão com Git

**Desejáveis:**
- Testes de UI
- Testes unitários
- Layout Universal (iPhone e iPad)
- Persistência de dados (Core Data, Realm)

**Diferenciais:**
- Projetos opensource
## Como se candidatar

Se interessou pela empresa? Quer ver o nosso escritório? Acha que está de acordo com o que buscamos? Mande um email com o assunto `#DEV_iOS @"SEU_NOME"` para o email devmobile@stone.com.br 

Quer saber mais sobre a empresa? Acesse o nosso [site](http://www.stone.com.br/)

**Comment by reprotector** [comment]
@jaisonv Já fecharam a vaga? Pode fechar a issue?

**Comment by jaisonv** [comment]
Oi, @reprotector. As vagas ainda estão abertas.

**Comment by reprotector** [comment]
@jaisonv A vaga ainda está aberta ou posso fechar a issue?

**Comment by jaisonv** [comment]
Ta aberta ainda. Ainda tem uma vaga.
