### ISSUE TITLE
[Remoto]  Programador iOS 

### ISSUE THREAD

**Issue by Anndressa** [CocoaHeadsBrasil/vagas#4]
## Descrição da vaga

O nosso time da engenharia está a procura de um novo membro para a equipe de desenvolvimento IOS.

O QUE ESSA PESSOA FARÁ?

- Trabalhar no app para iPhone do enjoei, aplicativo desenvolvido em Swift e na versão 2.0, com suporte a iOS 7.1 em diante
- Implementação de novas features no roadmap, melhorias, e correções em todas as áreas do aplicativo.
- Interações frequentes com as equipes de produto, backend e design.
- Fazer testes e code reviews, focando na atenção a detalhes e senso de ownership do produto.

## Local

Remoto

## Benefícios

- CLT
- Vale Alimentação/Refeição
- Plano de Saúde
- Plano Odontológico

## Requisitos

QUAIS EXPERIÊNCIAS SÃO ESSENCIAIS?
- Swift 2.0+
- Testes unitários usando XCTestCase  (nativo xcode 7)
- Testes de UI automatizados usando XCTestCase (nativo xcode 7)
- Integração Contínua (CI) no iOS
- Consumo de APIs REST
- Storyboards e Xibs
- Autolayout
- Performance Profiling e Debug com Instruments e lldb
- Certificados e Provision Profiles
- Conceitos da Human Interface Guidelines
- Git/GitHub

O QUE É DESEJÁVEL QUE ELE(A) TENHA?
- Conhecimento de operações via terminal para compilação e diagnóstico
- Conhecimento sobre automatização de testes e geração de builds (ex.: fastlane, xctool, etc)
- Contato com a comunidade de desenvolvedores iOS
- Skills de liderança

## Contratação

CLT a combinar

## Nossa empresa

O Enjoei é a maior plataforma para compra e venda de produtos de moda usados no Brasil. Fundado em 2012, mais de 1 milhão de usuários e 4 milhões de produtos passaram pelo marketplace. Nossa missão é ressignificar a relação das pessoas com as coisas, oferecendo o melhor destino para se consumir moda a preços acessíveis. Nossos investidores incluem os fundos Bessemer Venture Partners e Monashees Capital, líderes em Venture Capital no Vale do Silício e Brasil.

## Como se candidatar

https://jobs.lever.co/enjoei/51fd8278-e2e2-42bb-8260-73e678ca7b5e

**Comment by barbosa** [comment]
Olá @Anndressa, tudo bem?

A vaga ainda está aberta? Só para saber se fechamos a issue ou mantemos aberta.

Obrigado!

**Comment by Viniciuscarvalho** [comment]
@Anndressa a vaga ainda está aberta? Se for o caso de ter sido preenchida, pode fechar a issue 👍

**Comment by Anndressa** [comment]
Sim, está aberta!

**Comment by brunogama** [comment]
Link da vaga não existe mais, fechou?
