### ISSUE TITLE
[CAMPINAS- SP] APPITO - DESENVOLVEDOR iOS PLENO

### ISSUE THREAD

**Issue by talentreplacement** [CocoaHeadsBrasil/vagas#401]
## Empresa
 Nós vamos revolucionar o esporte amador no mundo. Para isso, contamos com um elenco apaixonado por fazer parte dessa revolução e que é movido por cada partida e amizade gerada através do aplicativo.

## Descrição da vaga
Criar e desenvolver aplicativos avançados na plataforma iOS
Colaborar com o time multifuncional para definir, desenhar e entregar novas funcionalidades
Trabalhar com APIs e serviços externos de dados
Criar códigos robusto, testável e reutilizável
Trabalhar em correções de bugs e aperfeiçoamento da performance de aplicações
Continuamente descobrir, testar e implementar novas tecnologias para maximar a eficiência do produto e do desenvolvimento.

## Posição
  pleno

## Tipo de contratação
cooperado

## Requisitos
Experiência comprovada em desenvolvimento de software, aplicativos iOS em Swift;
Ao menos um aplicativo publicado.
Experiência em APIs, Apple e Google;
Experiência em trabalhos com dados remotos via REST e JSON;
Experiência em implementação de bibliotecas de terceiros (Facebook/Twitter/Google/etc);
Sólido conhecimento da arquitetura de aplicações move e seu ciclo de vida

## Benefícios
VT, VR, convenio medico

## Como aplicar
Enviar cv com pretensao salarial para recrutamento@talentreplacement.com.br

## Contato
recrutamento@talentreplacement.com.br

**Comment by reprotector** [comment]
Olá @talentreplacement , em menos de 1 hora foram criadas 3 vagas. 1 fora das regras e as outras 2 duplicadas. Favor seguir as regras do canal.
