### ISSUE TITLE
[SC - Florianópolis] Desenvolvedor iOS Sênior

### ISSUE THREAD

**Issue by sahjarussi** [CocoaHeadsBrasil/vagas#403]
Vaga removida

**Comment by reprotector** [comment]
Olá @sahjarussi, A vaga postada está fora das regras dos canais, mais precisamente em:

> Todas as vagas devem conter o nome da empresa que está contratando
>Se você é um recrutador, você deve identificar o nome da empresa em que o candidato irá trabalhar

Favor adicionar a vaga com o nome da empresa em que o candidato irá trabalhar.
