### ISSUE TITLE
[REMOTO] Swift dev na Rocketlab

### ISSUE THREAD

**Issue by nativedone** [CocoaHeadsBrasil/vagas#407]
![image](https://user-images.githubusercontent.com/20998754/46239281-21abe380-c3da-11e8-9ad3-dcc2278c5a13.png)

## Empresa
https://www.rocketlab.com.au/  - mobile and web apps

## Descrição da vaga

Oi pessoal,

Tem uma vaga do meu time aqui de Sydney/AU:

Swift, Clean code, aplicativo publicado na loja.

Ingles: tem que falar pelo menos o suficiente pra se comunicar. Pode falar cometendo erros de gramatica, etc... mas tem que falar.

## Posição
 iOS Senior

## Tipo de contratação
 100%  remoto, CLT, PJ ou Freelancer. 

###### Obrigatórios
- Swift
- Clean code
-  Aplicativo publicado na loja
- Falar ingles (Nao precisa muita fluencia. O foco total eh comunicacao! Somos uma empresa de software. Pode falar ingles com erros? Pode! Mas, tem que falar. Tem que comunicar a sua idea e o seu trabalho.)

## Benefícios

- Flexibilidade de horarios
- Pagamento em $AUD
- Contrato: `full-time`, `part-time` ou `freelance`

## Como aplicar
- Compatilhar links de aplicativos na loja e codigos
- Call curta de 15 min
- Teste agendado de 50 min
- Contratacao ou feedback em ate 2 dias

## Contato
- Me envie uma messagem privada em https://twitter.com/nativedone

**Comment by thiagodelmotte** [comment]
@nativedone ainda aberta?

**Comment by luizfelipeairesoares** [comment]
Ainda há vagas?

**Comment by nativedone** [comment]
Obrigado aqueles que aplicaram. Essa fechou!
