### ISSUE TITLE
[São Paulo] Desenvolvedor iOS Sênior (Swift | Objective-c) - Kiddo Labs

### ISSUE THREAD

**Issue by CavalcanteLeo** [CocoaHeadsBrasil/vagas#41]
## Descrição da vaga

Temos duas vagas aberta para entrar no time de desenvolvimento iOS no qual irá contiunuar projetos existentes assim como novos projetos.
## Local

Jardins, São Paulo.
## Requisitos

**Obrigatórios**
- 1+ ano de experiência com Swift
- 3+ anos de experiência com Objective-C
- Sólidos conhecimentos nos design patterns (MVVC, MVC, VIPER, protocols, blocks, singleton, Abstract Factory, Servant, Builder, Observer, Dependency Injection etc..)
- Bom raciocínio lógico
- Fortes conhecimentos com Git
- Boa proficiência em inglês

**Desejáveis**
- Continuous Integration com Jenkins
- Conhecer e saber configurar ferramentas de automação, como Fastlane.
- Conhecimento em manipulação de imagens (raw bitmap)
- Conhecimentos em Socket
- Conhecimentos em algum banco de dado como Core Data ou Realm
- Experiência com automatização de testes unidade, integração e funcional
- Experiência com TDD / BDD;

**Diferenciais**
- projetos opensource
## Contratação

A combinar
## Nossa empresa

Somos uma empresa de design de produtos digitais. Atendemos grandes empresas desenvolvendo produtos inovadores que agregam valor real à cadeia de negócio. Precisamos de desenvolvedores iOS sênior e pleno para trabalhar em diversos projetos **nacionais** e **internacionais**.

[www.kiddolabs.com](www.kiddolabs.com)
## Como se candidatar

Por favor envie um email para **vagas@kiddolabs.com** com seu linkedin - enviar no assunto: Vaga iOS

**Comment by marcelofabri** [comment]
@CavalcanteLeo você pode atualizar a lista de benefícios para não ser a do template? Ou realmente esses são os benefícios? 😅

**Comment by CavalcanteLeo** [comment]
mudei hehe, esqueci de tirar

**Comment by reprotector** [comment]
@CavalcanteLeo Já fecharam a vaga? Pode fechar a issue?

**Comment by CavalcanteLeo** [comment]
fechado!! já fechamos a vaga sim, obrigado @reprotector
