### ISSUE TITLE
[São Paulo] Desenvolvedor iOS - Concrete - São Paulo

### ISSUE THREAD

**Issue by 060526** [CocoaHeadsBrasil/vagas#414]
## Concrete Desenvolvimento de Sistemas
Somos a Concrete, uma empresa da Accenture especializada em produtos digitais, e estamos em constante movimento. Trabalhamos junto às maiores companhias do Brasil para garantir a transformação digital. Para isso, usamos design, desenvolvimento ágil e nossa cultura de inovação. Trabalhamos com tendências, mas não seguimos passos: criamos os nossos caminhos, que viram referência. 

## Descrição da vaga
Aqui, não seguimos passos. 
Criamos nossos caminhos, que viram referência.
No capítulo de iOS temos uma oportunidade ímpar de viver em uma comunidade prática com dezenas de desenvolvedores iOS, trocando conhecimento e compartilhando informações técnicas e práticas de uma forma única. Além de desafiadores, os projetos têm acompanhamento próximo dos gerentes, que estão sempre buscando entender o momento de cada mebro do capítulo, considerando seus próximos desafios e oportunidades de crescimento e visando a melhoria contínua e evolução de todos. Práticas ágeis, lean, visão de produto e engenharia sólida são pilares que serão incorporados desde o primeiro dia até se tornarem quase que uma segunda natureza. 

Vem mover o mundo com o capítulo de iOS!

#SomosConcrete #TrabalheComOsMelhores 

Esta oportunidade é extensiva a todas as pessoas com deficiência. Pedimos que o tipo de deficiência seja mencionado no currículo, bem como se existe a necessidade de algum recurso especial para desenvolver seu trabalho. A Accenture é um empregador que acolhe candidaturas de todos os setores da sociedade e não discrimina com base na raça, religião ou crença, etnia ou origem nacional, deficiência, idade, nacionalidade, estado civil, orientação sexual ou identidade de gênero ou qualquer outra base, que é protegida pela lei aplicável.

## Posição
A combinar

## Tipo de contratação
CLT - Presencial

## Requisitos
Buscamos pessoas que:
- Tenham sólido conhecimento em:
- controle de versão distribuído (Git);
- ObjC/Swift, orientação a objeto e design patterns;
- guidelines de design e de desenvolvimento da Apple;
- Tenham conhecimento em:
- integração com APIs Restful e/ou Webservices;
- familiaridade com Storyboards, Xibs, Autolayout;
- metodologias ágeis (Scrum e XP);
- Saibam alguma coisa sobre:
- controle de versão distribuído (Git)
- gerenciamento de dependências de projeto (CocoaPods, Carthage)
- adaptação de layouts entre iPhone/iPad com testes em iOS (com uso ou não de frameworks)

## Benefícios
 VR, VT, AM (gratuita para titular e dependentes), AO (gratuita para titular e dependentes), Gympass entre outros.

## Como aplicar
https://github.com/concretesolutions/ios-recruiting-brazil/blob/master/README.md

## Contato
trabalheconosco@concrete.com.br ou pode entrar em contato @Viniciuscarvalho

**Comment by CocoaHeadsBR** [comment]
Vaga ainda está aberta
