### ISSUE TITLE
[São Paulo-SP] Keycar - Desenvolvedor JAVA para Android e C

### ISSUE THREAD

**Issue by dhaytaboada** [CocoaHeadsBrasil/vagas#416]
## Empresa
 Breve descrição da empresa

## Descrição da vaga
Desenvolvimento de firmware de dispositivo embarcado com interface microcontrolada utilizando linguagens Java para Android e C. 

## Posição
Pleno

## Tipo de contratação
PJ

## Requisitos
- Linguagem Java SE (avançado);
- Particularidades da linguagem Java para Android (intermediário);
- Boas noções de gerenciamento de memória e tráfego de dados.
- Boa noção de lógica binária; 
- Linguagem C para microcontroladores PIC da Microchip (XC8) (básico/intermediário);
- Linguagem C para microcontroladores Atmel/Arduino(desejável);
- Conhecimentos básicos de eletrônica;
- Conhecimento de módulos GSM, GNSS, BLE e WIFI. 

## Contato
rh@keycar.com.br

**Comment by Viniciuscarvalho** [comment]
Essa vaga não atende as especificações do grupo de iOS. 
Por favor ler as informações do Readme.
Vou fechar a vaga até atender a uma vaga de iOS ta?

Obrigado.
