### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor iOS Pleno / Sênior (Swift | Objective-c)

### ISSUE THREAD

**Issue by hmagico** [CocoaHeadsBrasil/vagas#42]
## Descrição da vaga

Buscamos um profissional de nível pleno/sênior que seja apaixonado(a) por desenvolvimento de software, com vontade de crescer, encarar novos desafios e que tenha o perfil "Hands on".

Você será o nosso "Ninja" técnico responsável pela programação iOS! Participará de debates técnicos de produto e será responsável junto com a equipe para propor a melhor solução técnica para as funcionalidades do app. Você vai trabalhar com o desenvolvimento de aplicações e ferramentas para melhoria do processo de desenvolvimento, sempre buscando a alta disponibilidade e qualidade.  Será responsável pelo desenvolvimento e otimização de app nativo iOS. 
## Local

Escritório Rio de Janeiro - Ipanema
## Requisitos

**Tão essenciais quanto respirar - "Sem isso não rola"**
- Programação nativa (+3 anos com Objective-C e 1 ano Swift)
- Experiência com GIT 

**Obrigatórios - "O nome já diz tudo"**
- Experiência em projetos utilizando Cocoapods, GIT, JSON, XML e integração com API RESTful de terceiros;
- Experiência com Adaptive Layout e elementos de layout;
- Experiência com design patterns(MVVC, MVC, MVVM e etc..); 
- Experiência com persistência de dados (Core Data, Realm ou SQLite);
- Experiência com arquitetura de Sistemas e levantamento de requisitos;  

**Desejáveis - "Se souber isso aqui, já está agregando valor"**
- Vivência em projetos com processos ágil (Scrum);
- Experiência em projetos utilizando API Google Maps;
- Experiência com UX e UI;

**Diferenciais - "Chegou até aqui? Tá tranquilo, tá favorável"**
- Projetos Open Source
- Experiência em projetos utilizando libs para manipulação de imagens e vídeos. 
- Ter atuado em projetos aplicando práticas de XP (TDD, refactoring, continuous integration, etc);
## Contratação

PJ à combinar 
## Nossa empresa

O Yummie é a rede para os apaixonados por gastronomia! Resultado da união de grandes executivos do mercado corporativo, somos uma startup totalmente focada em integrar o crescente universo gastronômico. Se você está em busca de crescimento, reconhecimento e novos desafios, o Yummie é o lugar certo para você.  Venha tomar um café conosco e aproveite para conhecer nosso escritório com vista para belíssima praia de Ipanema :)! Estamos ansiosos para saber mais sobre você.
## Benefícios
- Ambiente de Startup (+ liberdade para fazer , -  burocracia, + reconhecimento)
- Máquina de café grátis \0/
## Como se candidatar

Por favor envie um email para helder@yummie.com.br com seu CV anexado - enviar no assunto:  Vaga iOS

**Comment by reprotector** [comment]
@hmagico Já fecharam a vaga? Pode fechar a issue?
