### ISSUE TITLE
[SP - Berrini] SKY Brasil - Desenvolvedor iOS Sênior

### ISSUE THREAD

**Issue by rafael-augusto-souza** [CocoaHeadsBrasil/vagas#424]
## Empresa
A SKY é a maior empresa de TV por Satélite do Brasil, com mais de 5MM de assinantes.
A área de atuação será no departamento de DIGITAL, com o projeto do Aplicativo Minha SKY, este APP alcançou a marca de 5MM de downloads em 1,4 anos e possui as melhores marcas de usuários mensais, nota de usuários e crescimento do mercado de TV por Assinatura.
Além de termos sido reconhecidos internacionalmente pelo uso de Inteligencia Artificial, Machine Learning e algumas técnicas de computação em nuvem (Step Functions).

## Descrição da vaga
Atuar no desenvolvimento e manutenção de aplicativos nativos com Swift, com foco na qualidade, no usuário e com grande interação com os demais membros da equipe.

## Posição
Sênior

## Tipo de contratação
CLT, PJ ou cooperado.

###### Obrigatórios
- 3+ anos de experiência com desenvolvimento iOS
- Sólidos conhecimentos em Swift
- MVVM
- Orientação a objetos e design patterns. 

###### Desejáveis
- Gitflow
- Familiaridade com processo de desenvolvimento de software ágil (como XP, Scrum e Kanban)

## Contato
Enviar currículo via e-mail para [rafael.diasdesouza@terceiro-sky.com.br] com o assunto: "Vaga GitHub - Dev iOS". No corpo do e-mail descrever a pretensão salarial e tipo de contratação desejado.

**Comment by reprotector** [comment]
@rafael-augusto-souza Qual o nome da empresa contratante? De acordo com nossas regras, todas as vagas devem conter o nome da empresa contratante.

**Comment by rafael-augusto-souza** [comment]
Vaga ainda está aberta
