### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor iOS Pleno / Sênior (Swift)

### ISSUE THREAD

**Issue by jaisonerick** [CocoaHeadsBrasil/vagas#43]
## Nossa empresa

A [SumOne](http://bonuz.me) é uma empresa jovem de alto crescimento. Com o propósito de conectar  marcas com seus clientes, atendemos mais de [1.300 lojas em todo o Brasil](http://clientes.bonuz.me/mapa.html), com marcas nacionais como Spoleto, Koni, Subway, Pizza Hut entre outros. Nossos principais produtos são o Bonuz, app mobile de fidelidade e ofertas com mais de 300.000 usuários e o Companion, um app mobile de marketing digital local usado por centenas de donos de loja.
## Descrição da vaga

Estamos em busca de alguém com paixão por trabalhar em equipe, sede de aprendizado e desenvolvimento e que acredite em nosso propósito: criar relações ganha-ganha entre marcas e seus clientes.

Você vai ser responsável por desenvolver, arquitetar e dar manutenção na versão iOS do aplicativo [Bonuz](https://itunes.apple.com/br/app/bonuz/id649405785?mt=8). Nosso processo criativo é participativo e focado no cliente. Aqui você terá a oportunidade de participar das decisões referentes ao produto e a empresa.
## Local

Escritório em Florianópolis, SC

![image](https://cloud.githubusercontent.com/assets/332253/17591010/7f54d606-5fb2-11e6-96f6-91759d55e37b.png)
## Benefícios
- VR / VA + VT
- Convênios com empresas da região
- Ambiente de trabalho descontraído e divertido
- Trabalhar de pantufas
## Requisitos

**Obrigatórios**
- Experiência em desenvolvimento iOS (+3 anos)
- Experiência no controle de versionamento GIT
- Experiência com design patterns (MVVC, MVC, MVVM e etc..)
- Experiência em Core Data

**Desejáveis**
- Experiência com Cocoapods
- Ter trabalhado com Lean / Ágil
## Contratação

CLT
## Como se candidatar

Inscreva-se no linkedin: https://www.linkedin.com/jobs2/view/177377785?trk=biz-overview-job-post

**Comment by reprotector** [comment]
@jaisonerick Já fecharam a vaga? Pode fechar a issue?

**Comment by jaisonerick** [comment]
@reprotector Fechada.. Desculpe pela demora.
