### ISSUE TITLE
[São Paulo, SP] Desenvolvedor iOS <-> Junior | Itaú Unibanco

### ISSUE THREAD

**Issue by defaultbr** [CocoaHeadsBrasil/vagas#432]
Eai, está afim de trabalhar no maior banco do Brasil? 

## Sobre a vaga

Atuar no desenvolvimento de novas features, manutenção de aplicativos existentes com Objective-C e Swift com aplicação de boas práticas e foco na qualidade, propor melhorias, participar de outros projetos e também terá oportunidade de aprender outras linguagens.

## Local

Itaú Unibanco Centro Empresarial - Parque Jabaquara, São Paulo

## Benefícios

- VA
- VR
- VT
- Plano de saúde
- Plano odontológico
- Seguro de vida
- PLR 
- Plano de carreira

- Café no andar free
- Área de jogos com pebolim e videogame

## Requisitos

- Desenvolvimento Switf ou Objective-C
- Saber fazer um teste unitário
- Saber sobre Git (git pull, git push, git commit e outros comandos básicos)
- Trabalhar em equipe
- Boas práticas

Desejáveis
- Conhecimento em testes instrumentados
- Conhecimento em Injeção de Dependências

## Contratação

CLT - Junior

## Como se candidatar

Deve se cadidatar por intermédio de um link: http://bit.ly/ItauIOSJr

obs: sou funcionário do Itau e não recrutador

**Comment by mbrufatto** [comment]
A vaga já foi fechada. Pelo menos é o que diz o link.
