### ISSUE TITLE
Analista de Desenvolvimento Mobile (IOS) 

### ISSUE THREAD

**Issue by thafreireec** [CocoaHeadsBrasil/vagas#44]
**Empresa:** 
Na Samba, colaborador é Rei!

Reconhecida pelo Instituto Great Place to Work® como uma das 40 melhores empresas para se trabalhar no Brasil na categoria TI & Telecom em 2015 e eleita pela FastCompany como uma das companhias mais inovadoras da América Latina em 2014, a Samba Tech ajuda centenas de empresas a se comunicarem melhor com sua audiência através dos seus vídeos online.

**Como Desenvolvedor de aplicativos mobile suas atividades serão:**
- Participar do desenho e implementação de novas funcionalidades dos produtos mobile iOS da Samba, colaborando com o Gerente de Produto e UX Designers para garantir a entrega de códigos escaláveis e de qualidade;  
- Otimizar aplicativos mobile iOS; 
- Desenvolver protótipos rapidamente.

**Qualificações:**
- Nível superior completo em Ciência da Computação, Engenharia da Computação ou áreas afins; 
- Facilidade de aprendizado; 
- Experiência mínima de 2 anos em cargos similares;
- Pró-ativo e em busca de desafios.  

**Conhecimentos necessários:**                   
- Experiência em Objective-C ou Swift, bons conhecimentos em algoritmos, análise de algoritmos e estrutura de dados;
- Conhecimento das ferramentas de performance do SDK iOS e técnicas de otimização. 

**O que oferecemos:** 
- Vale Refeição;  
- Vale Transporte;
- Plano de Saúde;  
- Previdência Privada;  
- Seguro de Vida;
- GymPass;
- Horário Flexível.  

**Nivel esperado:** 
- Pleno/ sênior.

**Forma de contratação:** 
- CLT (Presencial).

**Endereço:** Rua Turim, 99 - Santa Lúcia. 
Belo Horizonte - MG.

_Os interessados deverão cadastrar o currículo no link abaixo:_ 
https://sambatech.recruiterbox.com/jobs/fk06p9n/

**Comment by marcelofabri** [comment]
@thafreireec Você pode adicionar mais detalhes conforme o template tinha? Onde é a vaga? Qual o nível esperado? Aceita remoto? Qual a forma de contratação, CLT ou PJ?

**Comment by margem** [comment]
A vaga já foi preenchida?

**Comment by thafreireec** [comment]
Bom dia,

À vaga ainda está em aberto.


Abraços.

<http://t.sidekickopen28.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8q5JFgVQBdTP7gs83nW64QWwH56dwNYf68PCfl02?t=http%3A%2F%2Fsambatech.com%2F&si=5741188443799552&pi=5c8ad520-928a-40c7-d091-f7d45356ef5a>

*Thabata Costa *| In House Recruiter
+55 (31) 3225-8658 | +55 (31) 97358-0006
*R. Turim, 99 - 2*º andar - Santa Lucia | CEP: 30360-552 | BH - MG - Brasil

<http://t.sidekickopen28.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8q5JFgVQBdTP7gs83nW64QWwH56dwNYf68PCfl02?t=http%3A%2F%2Fsambatech.com%2F&si=5741188443799552&pi=5c8ad520-928a-40c7-d091-f7d45356ef5a>
*O conteúdo deste e-mail deve ser tratado como confidencial.*
*The information in this email should be treated as confidential.*

2016-09-05 15:54 GMT-03:00 Margem <notifications@github.com>:

**Comment by reprotector** [comment]
Duplicate #29
