### ISSUE TITLE
[São Paulo] - Vaga desenvolvedor iOS Sr - Family 24h

### ISSUE THREAD

**Issue by aloisiovmello** [CocoaHeadsBrasil/vagas#443]
## Empresa
O Family 24h é uma startup voltada pra segurança familiar,
Se você está afim de trabalhar numa empresa jovem e ambiciosa, este é o seu lugar!

## Descrição da vaga
Estamos buscando um desenvolvedor de aplicativos iOS e que queira ver seu trabalho
reconhecido no mundo inteiro e o principal, que curta novos desafios.

## Posição
iOS Developer Sr

## Tipo de contratação
Presencial

###### Obrigatórios
Requisitos básicos:
* Fluência em Objective-C e Swift
* Core Location
* Core Data
* Google Maps framework
* Experiência com integração de API REST
* Controle de Versão - GIT
* Autolayout
###### Diferenciais
*Experiência com core Bluetooth

## Como aplicar
Enviar curriculos para: contact@family24h.com com o título: iOS Developer

**Comment by mauriciomaniglia** [comment]
O endereço de e-mail está correto ?

**Comment by aloisiovmello** [comment]
Sim, você enviou e deu problema?

**Comment by mauriciomaniglia** [comment]
> Sim, você enviou e deu problema?

Sim, está retornando.

**Comment by aloisiovmello** [comment]
Envie diretamente pra mim, por favor: aloisio@eokoe.com
