### ISSUE TITLE
[PR - Curitiba] TCS Tata - Desenvolvedor iOS Jr/Pl/Sr

### ISSUE THREAD

**Issue by rsalomao2** [CocoaHeadsBrasil/vagas#444]
## Empresa
 TCS Tata

## Descrição da vaga
 Desenvolvedor iOS - Swift

## Posição
 Jr/Pl/Sr - Estamos buscando qualquer nível de desenvolvedor, que tenha pelo menos 1 ano de experiência

## Tipo de contratação
 CLT

## Requisitos
 Swift na ponta dos dedos, Realm e GIT. É necessário saber criar as views por código e não somente pelo dashboard.

###### Obrigatórios
Swift

###### Desejáveis
RxSwift e MVVM

###### Diferenciais
N/A

## Benefícios
 - Plano Saúde
 - VR
 - VT
 - PL
 - Certificações
 - Descontos em diversos setores de educação

## Com quem você vai trabalhar
Será alocado em cliente da área financeira, localizada da cidade de Curitiba. Projeto de grande porte com muito trabalho e coisas para aprender.

## Como aplicar
Enviar CV para:
rodrigo.salomao@tcs.com

## Contato
Rodrigo Salomão

**Comment by willianpinho** [comment]
Presencial ou remoto?
