### ISSUE TITLE
[RS - Porto Alegre / São Leopoldo] - CWI Software - Mobile IONIC

### ISSUE THREAD

**Issue by CWI-RH** [CocoaHeadsBrasil/vagas#445]
## Empresa
Aqui na CWI Software desenvolvemos soluções e sistemas de TI com base nas necessidades específicas de empresas de médio a grande porte em âmbito global, desde 1991.
O ambiente da CWI é pensado nos mínimos detalhes para que projetos e sonhos de vida sejam colocados em prática, com liberdade criativa e incentivo à inovação.
Na CWI, todos têm liberdade para transmitir seus conhecimentos e competências entre todas as áreas, para que juntos sejam construídos projetos de qualidade superior.
Os projetos da CWI motivam as equipes a darem o seu melhor, pois o crescimento pessoal e profissional se reflete no resultado final para as marcas que atendemos.

## Descrição da vaga
Este (a) profissional é responsável por todo o projeto de desenvolvimento, desde a análise das necessidades do cliente, planejamento dos recursos do aplicativo, desenvolvimento, implantação de arquitetura, ferramentas e recursos, até a realização e configuração de testes.

## Posição
Pleno e Sênior

## Tipo de contratação
 Contratação CLT + Benefícios

## Requisitos
Experiência com desenvolvimento de aplicativos usando Ionic (incluindo push e processos de publicação iOS e Android)

###### Obrigatórios
Excelência no desenvolvimento de soluções para Front-End
Fluência com HTML, CSS, SaaS, Javascript, Jquery, etc
Experiência com Angular (typescript)
Experiência com desenvolvimento de aplicativos usando Ionic (incluindo push e processos de publicação iOS e Android)
Experiência na construção de soluções que envolvam chamada de serviços (REST ou não)

###### Desejáveis
Desejável conhecimento de .NET para camada de backend

## Benefícios
•	Vale Refeição
•	Vale Transporte
•	Plano de Saúde
•	Plano Odontológico
•	Seguro de Vida
•	Incentivo a Educação e Certificação
•	Parceria com diversas fornecedores: Instituição de Ensino, Restaurantes, Saúde e Lazer, Viagens
•	Ambiente Colaborativo

## Com quem você vai trabalhar
Possibilidade de trabalhar com as mais diversas tecnologias atendendo clientes dos mais variados segmentos;
Nossos times são compostos por profissionais de alta performance, referência na área.

## Como aplicar
Por favor envie um e-mail para work@cwi.com.br com seu CV anexado - enviar no assunto: Mobile - Ionic. 

## Contato
work@cwi.com.br

**Comment by Viniciuscarvalho** [comment]
Olá, creio que essa vaga de desenvolvedor IONIC não esteja de acordo com o grupo visto que aqui temos vagas para desenvolvedores iOS.

Vocês já tem uma vaga descrita para iOS - https://github.com/CocoaHeadsBrasil/vagas/issues/433

Vou fechar essa vaga, tudo bem?

Obrigado.
