### ISSUE TITLE
[MG - Belo Horizonte] Veek - Desenvolvedor iOS Pleno/Sênior

### ISSUE THREAD

**Issue by bernardoassis** [CocoaHeadsBrasil/vagas#451]
## Veek
A Veek é uma MVNO (Mobile Virtual Network Operator) que, traduzido pra Português é "Operadora Móvel com Rede Virtual". No idioma das pessoas comuns é “operadora de celular que contrata a rede física de outras empresas pra oferecer um serviço melhor”.

E como a gente faz isso? Proporcionando aos nossos clientes que eles resolvam tudo (mesmo) pelo app: pede chip, faz recarga, resolve tretas…

Vou te explicar: o grande problema das outras operadoras nem é sinal e sim o atendimento zoado e pacotes confusos que te fazem pagar por coisas que você não usa.

Então, a gente aluga essa estrutura física de antenas pra te oferecer atendimento com uma galera bacana e recargas que você usa como bem entender, com preço justo. Simples assim.

Nosso time é baseado em São Paulo, SP. Mas somente a equipe de desenvolvimento de aplicativos trabalha em Belo Horizonte. Tente entender o porquê no motivo 5 do post: https://blog.veek.com.br/tudo-sobre-a-veek/a-veek-e-confiavel/

## Descrição da vaga
A Veek é uma startup na área de telecomunicações em que os seus produtos se baseam nos seus apps Android e iOS. Buscamos desenvolvedores que tenham sangue no olho e desejo de participar da (r)evolução de um produto de nível internacional, com alto grau de inovação, referência no segmento de telecomunicações e elogiado por todos (inclusive por nossos concorrentes 😁).

## Posição
Pleno/Sênior

## Tipo de contratação
PJ a combinar - Belo Horizonte (Co-working no Funcionários)

###### Obrigatórios
Mínimo de 2 anos de experiência com Desenvolvimento iOS em Swift e/ou Objective-C no Xcode;
Conhecimento da ferramenta de controle de versão de código-fonte Git;
Conhecimento sólido em programação orientada a objetos;
Conhecimento sólido em um ou mais padrões de arquiteturais: MVC, MVP, MVVM, VIPER;
Conhecimento sólido em APIs RestFul;
Conhecimento em testes unitários.

###### Desejáveis
Experiência com XCTest;
Conhecimento em Cocoapods, Alamofire, Firebase, Jenkins, RxSwift, Swagger;
Conhecimento em ferramentas de analytics e Crash Reporting;
Algum aplicativo publicado na App Store.

###### Diferenciais
Noções de UX e UI;
Experiência de trabalho em equipes de desenvolvimento ágil;
Habilidade de trabalho com independência e supervisão mínima;
Disposição em compartilhar o seu conhecimento com as pessoas da área de tecnologia da empresa;
Boa habilidade de comunicação escrita e verbal;
Disposição para aprender novas tecnologias e aplicá-las em um curto espaço de tempo;
Espírito de equipe em um time multi-disciplinar;
Capacidade de analisar situações e informações, realizando avaliação crítica e conclusiva, apontando direcionamentos para subsidiar as tomadas de decisões.

## Benefícios
- Remuneração compatível com o seu nível de conhecimento;
- Horário flexível;
- Excelente ambiente de trabalho;
- Possibilidade de trabalho remoto.

## Com quem você vai trabalhar
| ![](https://github.com/bernardoassis.png?size=117) | ![](https://github.com/diogochbittencourt.png?size=117) | ![](https://github.com/eduardoleal.png?size=117) | ![](https://github.com/Fepame.png?size=117) | ![](https://github.com/jpalacio1988.png?size=117) | ![](https://github.com/leonardorutz.png?size=117) |
| --- | --- | --- | --- | --- | --- |
|[bernardoassis](https://github.com/bernardoassis) |[diogochbittencourt](https://github.com/diogochbittencourt) |[eduardoleal](https://github.com/eduardoleal) |[Fepame](https://github.com/Fepame) |[jpalacio1988](https://github.com/jpalacio1988) |[leonardorutz](https://github.com/leonardorutz) |

| ![](https://github.com/lraphas.png?size=117) | ![](https://github.com/leonardosilvarib.png?size=117) | ![](https://github.com/RenanNeitzel.png?size=117) | ![](https://github.com/rodolfoconde.png?size=117) |
| --- | --- | --- | --- |
|[lraphas](https://github.com/lraphas) |[leonardosilvarib](https://github.com/leonardosilvarib) |[RenanNeitzel](https://github.com/RenanNeitzel) |[rodolfoconde](https://github.com/rodolfoconde) |

## Como aplicar
Por favor envie um email para bernardo.assis@veek.com.br com seu CV anexado ou LinkedIn - enviar no assunto: Vaga Dev iOS

## Contato
Bernardo de Assis Carvalho - bernardo.assis@veek.com.br

**Comment by moquiutijunio** [comment]
@bernardoassis eu enviei um email e não tive nenhum retorno, poderia verificar?
