### ISSUE TITLE
[São Paulo - Pinheiros] Guiabolso - Desenvolvedor iOS

### ISSUE THREAD

**Issue by agvieira** [CocoaHeadsBrasil/vagas#452]
## Empresa
Trabalhamos incessantemente para entender melhor o comportamento humano que está por trás de cada um de nossos usuários de forma a criar uma experiência incrível de uso. Nós fazemos isso, porque acreditamos que podemos contribuir muito para melhorar a vida financeira das pessoas.
Agora, criar algo extraordinário não é nada fácil. As melhores ideias surgem quando as pessoas estão se divertindo e trabalhando para um propósito maior. Você será desafiado, aprenderá e se divertirá. Queremos que todas pessoas que usem o GuiaBolso façam boas escolhas financeiras.

#### O que fazem? Como vivem? O que comem os guias?

A gente busca fazer tudo com coragem e excelência, porque curtimos ver o resultado de um trabalho bem feito, mas não é um resultado a qualquer custo: o caminho importa muito no Guiabolso, e o melhor deles é colaborarmos uns com os outros. Puxamos várias iniciativas pra que todas as áreas saibam o que cada uma tá fazendo e possam se ajudar.

Nosso ambiente é diverso e gostamos de construir nossas relações com base na transparência. Temos até o GbTalks, um encontro com nosso CEO para falarmos de resultados e abordar vários assuntos, desde os mais estratégicos até tirar dúvidas do dia a dia dos Guias.

O dia a dia do Guiabolso é bem desafiador e por isso todos os Guias aqui atuam como donos do negócio. É, a gente trabalha duro, mas também se diverte. Toda sexta a gente tem a Green Friday, um momento pra gente contar as novidades da semana e celebrarmos cada conquista! 

## Descrição da vaga
- Elaborar novas funcionalidades que brilhem os olhos dos nossos usuários
- Propor melhorias de processo e desenvolvimento e distribuição de nossos produtos
- Colaborar com a área de produto, design e com os desenvolvedores das outras plataformas com o objetivo de ter um produto final com uma visão unificada
- Executar e acompanhar resolução de bugs e exceptions reportados
- Medir e otimizar a performance e uso de dados

## Posição
- desenvolvedor iOS - Sênior

## Tipo de contratação
- CLT

###### Obrigatórios
- Excelente conhecimento nas linguagens Swift e Objective-C
- Conhecimento com tecnologias como fastlane, cocoapods, push notifications, core data, etc
- Experiência com o processo de distribuição da App Store
- Estar confortável com a aplicação dos guidelines da Apple
- Experiência com AutoLayout
- Tenha paixão por tecnologia e por melhorar a vida financeira do brasileiro

###### Diferenciais
- Conhecimento em testes unitários
- Experiência com ferramentas de CI/CD
- Experiência com extensions (Apple Watch, widget, Siri).

## Benefícios
- Vale-refeição ou Alimentação
- Vale-transporte
- Plano de saúde
- Gympass
- Seguro de Vida

## Como aplicar
Basta se cadastrar no nosso site através do link: [Cadastre-se aqui](https://jobs.kenoby.com/guiabolso/job/desenvolvedor-ios/5bd9eff267eef749512f5c69)

## Contato
Caso tenha qualquer dúvida e só me mandar um email (andre.vieira@guiabolso.com.br)

**Comment by bernardold** [comment]
Vaga ainda está aberta

**Comment by bernardold** [comment]
Vaga ainda está aberta
