### ISSUE TITLE
[RS - Porto Alegre] WK Recursos Humanos - iOS Developer

### ISSUE THREAD

**Issue by aaamenezes** [CocoaHeadsBrasil/vagas#463]
## Empresa
Empresa de desenvolvimento mobile

## Posição
Jr

## Tipo de contratação
CLT ou PJ

###### Obrigatórios
- Graduação em andamento
- Objective-C
- Swift
- Pods
- Storyboard
- Chamadas SOAP
- Json
- Versionamento do código Git

## Benefícios
- VT
- VR
- Plano de saúde

## Como aplicar
Inscreva-se agora em https://www.wkrh.com.br/job/programador-ios-a0f1i000004x2qwua0/

## Contato
Ou envie um e-mail para marianna.braga@wkrh.com.br

**Comment by guilhermeoa07** [comment]
Vaga ainda em aberto? Entrevista pode ser remota?

**Comment by reprotector** [comment]
@aaamenezes Olá! Estou removendo a vaga por estar fora das nossas regras:

> Todas as vagas devem conter o nome da empresa que está contratando
> Se você é um recrutador, você deve identificar o nome da empresa em que o candidato irá trabalhar

**Comment by aaamenezes** [comment]
Entendo, @reprotector. Obrigado.
