### ISSUE TITLE
[SC - Florianópolis] Desenvolvedor iOS Sênior no Peixe Urbano / Groupon LATAM

### ISSUE THREAD

**Issue by insidegui** [CocoaHeadsBrasil/vagas#467]
Se você gosta de trabalhar em um ambiente dinâmico, inovador e com projetos que desafiam, seu lugar é no Peixe Urbano! 

Estamos em busca de um Engenheiro de Software iOS para somar forças ao time e dar conta da missão que é fazer com nossos mais de 30 milhões de usuários, tenham uma experiência cada vez mais positiva em nosso app.

## No seu dia a dia aqui no PU você vai: 

- Participar do desenvolvimento de apps relacionados ao negócio do Peixe Urbano, Groupon e Groupon LATAM, na plataforma iOS;
- Identificar, diagnosticar e corrigir bugs;
- Contribuir no desenvolvimento e adoção de melhores práticas no time.

## O que a gente precisa de você: 

- 3 anos ou mais de experiência criando apps para iOS
- Domínio de Swift e Objective-C
- Conhecimento sobre os frameworks da Apple, especialmente UIKit
- Experiência com APIs REST e parsing de JSON
- Experiência em multi-threading com GCD
- Experiência de uso do LLDB, view debugger e outras ferramentas de debug
- Conhecimento avançado de UITableView, UICollectionView e desenvolvimento de componentes de UI customizados
- Experiência com ferramentas de tracking (Firebase, Fabric, Localytics, etc.)
- Inglês técnico
- Experiência em versionamento usando Git

## Será seu diferencial se você também tiver: 

- Experiência com view code (desenvolvimento sem Interface Builder)
- Experiência com código legado
- Experiência com app extensions, push notifications e uso de múltiplos targets no Xcode
- Experiência com Apple Watch, CoreLocation, PassKit
- Noção das regras de negócio da Apple para a plataforma( incluindo Design Guidelines e App Store Review Guidelines) 
- Conhecimento de UX e ferramentas de design (Sketch e Zeplin)
- Experiência no uso de ferramentas auxiliares de dessenvolvimento (proxy, debbugers, etc.)
- Contribuições para projetos open-source

## O que o PU oferece: 

- VR e/ou VA
- Assistência médica
- Assistência odontológica
- Seguro de vida
- PLR
- Gympass
- Jornada flexível 

### Nível de experiência
Pleno-sênior

### Setor
Internet Marketing e publicidade Mídia online

### Tipo de emprego
Tempo integral

## Entre em contato

[Vaga no Linkedin](
https://www.linkedin.com/jobs/cap/view/1052843944)
[E-mail](mailto:bruna.rosa@peixeurbano.com)

**Comment by dbonates** [comment]
@Viniciuscarvalho, não é `CLT`, é `PJ`! 😉

**Comment by insidegui** [comment]
Vaga ainda está aberta

**Comment by dbonates** [comment]
e pode ser remota tb ;)

**Comment by insidegui** [comment]
Vaga preenchida.
