### ISSUE TITLE
[Remoto] Desenvolvedor(a) iOS Pleno/Sênior | Tabmedia

### ISSUE THREAD

**Issue by danielCarlosCE** [CocoaHeadsBrasil/vagas#468]
## Sobre a empresa
A Tabmedia é uma plataforma de gestão de conteúdos de Marketing e Treinamento capaz de gerenciar, segmentar, distribuir e mensurar conteúdos estáticos e interativos em tempo real.
Atualmente, a solução é utilizada por 50 empresas, em 7 países somando mais de 15.000 usuários ativos.

## Posição
Pleno/Sênior 

## Tipo de contratação
Remoto, CLT ou PJ 

###### Obrigatórios
- Proficiência com Objective-C e Swift
- Core Data
- Experiência com APIs para consumo de dados
- Testes automatizados (XCTest, Quick, Nimble, etc)
- GIT
- Entendimento sobre os guidelines de interface
- Arquitetura MVP, MVVM e afins
- Reactive programming - RxSwift
- Clean Code
- Inglês técnico (leitura)

###### Diferenciais
- Scrum
- Integração Contínua
- Testes automatizados de UI
- React Native

###### Experiência
2+ anos de experiência com iOS

## Como aplicar
Interessados devem se cadastrar na vaga no Linkedin: https://www.linkedin.com/jobs/view/1056302750

**Comment by mbrufatto** [comment]
Boa tarde! 
Já me candidatei, mas ainda não obtive nenhum retorno.

**Comment by danielCarlosCE** [comment]
Bom dia!

Nós da Tabmedia, agradecemos imensamente o seu interesse em trabalhar conosco, no entanto, fechamos a contratação de uma outra pessoa esta semana.

Vamos trabalhar duro para continuar crescendo e gerando novas oportunidades num futuro breve.

Não desista. Ficaremos na torcida para que consiga uma oportunidade ainda melhor do que esta.

Até a próxima,
