### ISSUE TITLE
[Jaguariúna-SP] Ab-Inbev - Desenvolvedor(a) iOS Junior/Pleno/Senior

### ISSUE THREAD

**Issue by mazevedofs** [CocoaHeadsBrasil/vagas#476]
## Empresa
A AB-Inbev, com operações em todos os continentes do mundo e com um portfólio de "estrelas" como Budweiser, Stella Artois, Skol, Brahma, Corona, entre outras e reconhecida como uma das melhores empresas para se trabalhar. 

## Descrição da vaga
temos mais de uma vaga!
Na Ab-InBev procuramos pessoas de todos os backgrounds para nos ajudar no nosso sonho de juntar as pessoas por um mundo melhor!

Suas responsabilidades serão:
* Desenvolver aplicações e features usadas no mundo todo;
* Colaborar com times multidisciplinares de vários países;
* Garantir o desempenho, escalabilidade e segurança das aplicações em produção, para garantir a melhor experiência dos nossos usuários;
* Resolver problemas complexos que impactam o negócio;
* Ser parte da transformação digital de uma das maiores companhias do mundo!

## Posição
 iOS Developer (Júnior/Pleno/Sênior)

## Tipo de contratação
CLT presencial em Jaguariúna

###### Obrigatórios
* Bacharelado completo
* Experiência com desenvolvimento de aplicações nativas usando Swift and Objective-C, auto-layout, Carthage e CocoaPods
* Experiência com Git
* Conhecimento sobre os principais padrões de desenvolvimento mobile
* Inglês intermediário

###### Desejáveis
* Conhecer programação reativa - RxSwift
* Ter trabalhado com metodologias ágeis
* Conhecimento de testes unitários e de interface

## Benefícios
14º Salário, Bônus anual variável, Plano médico e odontológico, fretado para região metropolitana de Campinas.

## Com quem você vai trabalhar
@mazevedofs pode falar comigo :)

## Como aplicar
Envie email para recrutamento@ab-inbev.com

## Contato
recrutamento@ab-inbev.com

**Comment by guilhermeoa07** [comment]
Processo seletivo pode ser remoto?

**Comment by mazevedofs** [comment]
O processo pode ser remoto sim

**Comment by mazevedofs** [comment]
Continua aberta!

**Comment by liuvasconcelos** [comment]
Alguma chance do trabalho em si ser remoto, pelo menos por um tempo?

**Comment by mazevedofs** [comment]
Oi Lívia, infelizmente não :/
Mas podemos conversar sobre detalhes específicos, me manda email se quiser

**Comment by mazevedofs** [comment]
Vagas ainda abertas

**Comment by tfmart** [comment]
Bom dia, ainda há vagas para Jr?

**Comment by guilhermeoa07** [comment]
Entrevista pode ser remota?

**Comment by guilhermeoa07** [comment]
@mazevedofs enviei o currículo a algum tempo, mas não recebi nenhum retorno, nem positivo ou negativo, ainda está em processo de avaliação?

**Comment by mazevedofs** [comment]
@guilhermeoa07 ainda estamos no processo
@tfmart temos sim
