### ISSUE TITLE
[Curitiba-PR, REMOTO] Consulta Remedios. iOS Pleno

### ISSUE THREAD

**Issue by trancosowiliam** [CocoaHeadsBrasil/vagas#486]
## Empresa
Consulta Remedios

Somos a maior e melhor plataforma de medicamentos do Brasil e a mais relevante com informações sobre saúde e bem-estar. Com mais de 20 milhões de usuários únicos por mês, fazemos da tecnologia um meio transformador para a vida de todas as pessoas.

## Descrição da vaga
Você irá atuar na criação de toda a estrutura da aplicação iOS, do zero, transformar o protótipo em interface ricas e funcionais, na criação de novas features e manutenção do código escrito, tudo baseado em um código legível e reutilizável. Desenvolverá nosso aplicativo iOS em diferentes campos e aumentará os limites da tecnologia móvel. 

###### Principais atividades
- Trabalhar no desenvolvimento do ciclo de vida completo de projetos sensíveis ao tempo;
- Recomendar tecnologias apropriadas para implementar novos recursos;
- Desenvolver bibliotecas de código que podem ser reutilizadas em várias partes do projeto ou, até mesmo, em outros projetos;
- Reproduzir de maneira fiel a UI dos protótipos, incluindo animações;
- Realizar o levamento de requisitos para o desenvolvimento das novas features e componentes;
- Ajudar a fazer o Code Review (tanto iOS quanto Android) das aplicações detectando possíveis problemas, contribuindo para o bem-estar do projeto e da equipe mobile de um modo geral;
- Criar novos métodos para melhorar a eficiência dos processos e produtos.
- Projetar, codificar, analisar e testar sistemas para aplicativos iOS.
- Lidar com atualizações de software, patches e correções de bugs.
- Comunicação constante com a equipe de desenvolvedores, designers e gerente do projeto a fim de discutir melhorias e novos recursos.
- Manter os arquivos, códigos e scripts de uma maneira organizada que permita que outros membros da equipe façam edições, sugestões e alterações.

## Posição
 Pleno

## Tipo de contratação
CLT ou PJ

###### Obrigatórios
- 2 anos ou mais de experiência com desenvolvimento para aplicações mobile;
- Vivência com integração da aplicação consumindo APIs RESTful;
- Domínio dos conceitos do GitHub como branching, pull-requests, etc;
- Mindset de melhorias continuas, focando em entregar valor para o projeto;
- Ser formado, ou não, em Sistemas de Informação, Ciência/Engenharia da Computação, Análise e Desenvolvimento de Sistemas ou cursos similares;
- Se você não é formado mas possuí uma boa experiência na área, ficaremos felizes em avaliar seu portfólio!
- Swift
- CocoaPods
- Git
- Firebase toolkit

###### Desejáveis
- Custom Views e XIBs
- Arquitetura MVVM-C
- Testes Unitários
- Testes de UI
- SwiftLint
- Fastlane
- Pivotal / JIRA / Trello / Asana
- Gitflow

###### Diferenciais
- Conhecimento em kotlin, para ajudar nos code review da aplicação Android;

## Benefícios
- Ambiente de muita autonomia, aprendizado e desafios;
- Escritório informal, descontraído e cheio de pessoas incríveis;
- Horário Semi-Flexível (8 horas/dia de segunda à sexta);
- Vale Refeição e/ou Vale Alimentação;
- Vale Transporte.

## Como aplicar
https://carreiras.consultaremedios.com.br/o/ios-developer-pl

## Contato
rafael.goncalves@consultaremedios.com.br
wiliam.trancoso@consultaremedios.com.br

**Comment by KelvinEC** [comment]
Vaga ainda aberta? 
Não consta no Link fornecido.

**Comment by trancosowiliam** [comment]
closed!
