### ISSUE TITLE
[SP - Campinas] iOS Developer Pleno - CI&T

### ISSUE THREAD

**Issue by psilvadias** [CocoaHeadsBrasil/vagas#49]
### Sobre a CI&T

A CI&T é a especialista global em soluções digitais escolhida por líderes como Coca-Cola, Netshoes, Motorola e Alelo para conduzir suas iniciativas mais inovadoras. Aliando domínio tecnológico, liderança em metodologias Lean e Agile, e expertise na sua indústria, resolvemos problemas de negócio, construindo o caminho entre o legado e o futuro. Fundada em 1995, com sede em Campinas e escritórios em locais estratégicos da América Latina, América do Norte, Europa e Ásia, a CI&T foi escolhida parceira do ano para serviços em nuvem pelo Google, nominada “Cool Vendor” pelo Gartner e eleita Great Place to Work por dez anos consecutivos. Saiba mais em: www.ciandt.com.
### Descrição da oportunidade

Atualmente a CI&T tem uma oportunidade para Developer Mobile iOS em sua base de Campinas.  
### Posição

Pleno
### Tipo de contratação

Presencial, escritório em Campinas - Pólis de Tecnologia. 
### Requisitos

Conhecimento em implementação de aplicativos iOS (Nativo), englobando:
- Experiência com desenvolvimento iOS (objective-C) 
- Experiência com desenvolvimento iOS (Swift) 
- concepção da UI e UX utilizando os guidelines Google sempre que necessário;
- preocupação com a segurança das informações dentro da app;
- será diferencial caso conhecer também Objective C (para iOS)
### Benefícios

Melhor empresa! Melhores pessoas! Estamos na lista das Melhores Empresas para Trabalhar no Brasil (GPTW 2016) pela décima vez consecutiva, única empresa de TI com esse feito.
# ciandtgptw10 #ilovethisplace #ciandtpride
### Como aplicar

Por favor envie um email para psilva@ciandt.com com o link do LinkdIn ou seu CV anexado - enviar no assunto: Vaga iOS GitHub
### Contato

Quer saber mais?
ciandt.com
@ciandt_br
fb.com/ciandt
linkedin.com/company/ciandt

Fique de olho em nossas outras oportunidades: ciandt.com/carreiras

**Comment by reprotector** [comment]
@psilvadias Já fecharam a vaga? Pode fechar a issue?
