### ISSUE TITLE
 [SP - Moema] Looke - Desenvolvedor iOS Pleno

### ISSUE THREAD

**Issue by thaishbrasil** [CocoaHeadsBrasil/vagas#491]
## Sobre o Looke
Somos a mais completa  plataforma de Streaming do mercado Brasileiro 
Trabalhamos com opções de assinatura, locação e compra de conteúdos em Vídeo.
Oferecendo mais de 20.000 vídeos, incluindo filmes recém-saídos dos cinemas, clássicos, shows, documentários, séries exclusivas e os mais queridos conteúdos infantis,  levando diversão para todos os targets.
O Looke tem parcerias com grandes empresas  de diversos segmentos, levando sempre as melhores experiências para seus usuários

## Com o que você vai trabalhar: 
Desenvolver aplicativos para Streaming de Videos para iOS> Iphone, Ipad e Apple TV

## Tipo de contratação
CLT ou PJ 

## Requisitos para se Candidatar
Ter pelo menos 3 anos de experiência com desenvolvimento de softwares 
Ter pelo menos 1 ano de experiência com desenvolvimento iOS.
Ter experiência com desenvolvimento de apps nativo 
Sólidos conhecimentos em Swift e ter conhecimentos em Objective-C
Conhecimento das guidelines de design e de desenvolvimento da Apple

###### Atividades
Construir aplicações para iOS utilizando Objective C / Swift 4.2;
Dominar o git flow 
Implementar mockups do time de design, com atenção aos detalhes visuais e compatibilidade entre devices;
Dominar o processo de deploy (AppStore Connect, TestFlight, AppStore).
Priorizar e tratar bugs e exceções reportados em produção;
Contribuir em decisões de arquitetura sobre novas partes do projeto.
Experiência em integração com banco de dados, integrações com APIs RESTful

###### Desejáveis (não obrigatório)
Conhecimentos em Android com o objetivo de potencializar a curva de aprendizado dentro do nosso ambiente.
Testes automatizados 
XCode Server 
Continuous Integration 
RxSwift 
Cocoa Pods
Familiaridade com processo de desenvolvimento de software ágil (como XP, Scrum e Kanban)
Desenvolvimento multiplataforma (Android e Xamarim). 

## Benefícios
Seguro Saúde, Odontológico e de Vida de Primeira linha
VT/VR 
Bônus Salarial por Performance pago 1x no ano
Escola de Inglês e Espanhol na empresa
“no dress code” o que for mais confortável (mais ou menos informal)
Ser saudável – Frutas, Snacks, Ginástica Laboral e programas de incentivo e suporte de Qualidade de vida
Integração Gostamos de comemorar com festas 1x ao mês no nosso Ambiente de trabalho

## Como aplicar
enviar CV para: vagas@looke.com.br
https://www.looke.com.br

## Contato
Thais Fernandes

Nossa Cultura:
Somos uma empresa jovem inspirada em tecnologias disruptivas. Oferecemos um ambiente de trabalho que Incentiva a inovação e a produtividade, garantido liberdade com responsabilidade.
O Looke é uma Plataforma brasileira. Multiplataforma.
Temos aplicativos de iOS, Android, TV conectada, Playstation, PC, Safari, Apple TV, Android TV.
Tudo isso a gente faz aqui. A gente faz a plataforma inteira.
Fazemos toda a parte de Encriptação, Decriptação, Encoding de vídeo.
100% dessa tecnologia, é nacional, proprietária da empresa e, é feita toda aqui com a gente.
Você, se vir a ser contratado, virá para trabalhar numa área específica de Android para atender essa plataforma.
O Streaming de Vídeo é o futuro da distribuição de Vídeo pela internet. O que a gente conhece hoje de distribuição linear de TV, aqueles canais que a gente contrata, isso vai acabar. 100% está se tornando internet. Está se tornando no mundo inteiro. Como a Netflix fez isso, a Amazon Prime, o próprio Itunes, o Google Play...
É com isso que a gente quer que você venha trabalhar.
Distribuição de Vídeo por internet.

![looke para vagas](https://user-images.githubusercontent.com/47364879/52731870-f3542c80-2fa5-11e9-9cd6-92d25555d419.png)

**Comment by reprotector** [comment]
Duplicada #487
