### ISSUE TITLE
[São Paulo - Berrini] Desenvolvedor iOS Pleno e Senior

### ISSUE THREAD

**Issue by Vivianematos** [CocoaHeadsBrasil/vagas#5]
## Local

Zona Sul - Berrini

## Benefícios

- frigobar sempre cheio :P
- sala de jogos

## Requisitos

Obrigatórios
- Experiência em programação iOS.
- Vivência na utilização de Git.
- Ser pró ativo e gostar de trabalhar como time.
- Gostar de participar de discussões estratégicas e não somente técnica.
- Possuir e enviar portfólio com apps desenvolvidos para iPhone e/ou iPad.  

Desejáveis
- Experiência com projetos utilizando Scrum.
- Ter trabalhado com TDD.
- Conhecimento em programação Swift.

## Contratação

PJ e/ou CLT a combinar

## Nossa empresa

Aqui na GingaOne somos um grupo de profissionais extremamente qualificados, dedicados e apaixonados pelo que fazem, que acreditam no poder transformador da tecnologia e que querem deixar sua marca neste admirável mundo novo. 

## Como se candidatar

Por favor envie um email para viviane.matos@gingaone.com com seu CV anexado e Pretensão PJ e CLT. - enviar no assunto: Vaga iOS

**Comment by barbosa** [comment]
Olá @Vivianematos, tudo bem?

A vaga ainda está aberta? Só para saber se fechamos a issue ou mantemos aberta.

Obrigado!

**Comment by Vivianematos** [comment]
Oi Gustavo,

Essa vaga está em stand by por enquanto, pode fechar por favor.

Obrigada.



*Viviane Matos Bonifacio*
Recursos Humanos

+ 55 11 5505 2923
+ 55 11 97653-6975

Skype: viviane.bonifacio2
www.gingaone.com


2016-03-31 12:06 GMT-03:00 Gustavo Barbosa <notifications@github.com>:
