### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) iOS Jr - tech.fit

### ISSUE THREAD

**Issue by rodolfofadino** [CocoaHeadsBrasil/vagas#505]
## Descrição da vaga

E se você pudesse ajudar a transformar a vida de centenas de milhares de brasileiros através da tecnologia? Conheça a tech.fit, hoje temos 3 aplicativos:

O Dieta e Saúde é o maior programa de emagrecimento online do Brasil. Mais de 1.600.000 de pessoas já fizeram o Dieta e Saúde (ou "DS" para os íntimos).

O Tecnonutri (TN) é uma plataforma de alimentação saudável, através de um app, escolhido pelo Google no Brasil e no México como um dos melhores apps do ano em 2016.

E o Numi, novo aplicativo voltado para fitness e exercícios.

## Local

Presencial São Paulo, SP (200 metros do metro Conceição)

## Como Desenvolvedor(a) iOS você irá:

- Desenvolver e evoluir nossos aplicativos na plataforma iOS
- Criar features que facilitem o emagrecimento das pessoas
- Integrações com plataformas como Firebase, AppsFlyer e Facebook Analytics
- Inovar, criando soluções mobile que tragam engajamento nos nossos aplicativos

## Pré-requisitos

- Formação superior em Ciência da Computação, Análise de Sistemas, Engenharia da Computação e afins
- Vontade de aprender
- Paixão por tecnologia
- Entusiasmo em fazer acontecer
- Desenvolver em Swift e/ou Objective-C
- Padrões de desenvolvimento MVP, MVVM e MVC
- Caso não tenha esses requisitos e conheça outra tecnologia e tenha vontade aprender coisas novas, nos procure também!
- Inglês técnico

## Será um diferencial:

- Experiência com metodologias ágeis
- Ter algum aplicativo próprio
- Ter participado de grupos estudantis (Empresa Júnior, Liga de Empreendedores, Atléticas e similares).

## Contratação

- CLT

## Nossa empresa

Cuidar de si mesmo é uma jornada diária e fundamental para uma geração de pessoas conectadas.
Essa é a jornada da tech.fit, uma das 4 melhores empresas PME para se trabalhar no Brasil segundo o love mondays.
Somos líderes em aplicativos de saúde e self-care no Brasil.

## Como se candidatar

Por favor envie um email para rodolfo@tech.fit com seu CV anexado - enviar no assunto: Vaga iOS

**Comment by guilhermeoa07** [comment]
Entrevista pode ser remota?

**Comment by rodolfofadino** [comment]
Poderia sim @guilhermeoa07 obrigado pelo feedback, no momento conseguimos trazer uma pessoa para nosso time, valeu mesmo o/
