### ISSUE TITLE
[SP - Osasco] - Desenvolvedor iOS Sênior - Foursys

### ISSUE THREAD

**Issue by marceloreis13** [CocoaHeadsBrasil/vagas#52]
[SP - Osasco] Foursys - Desenvolvedor iOS Sênior
## Empresa

Somos uma empresa de serviços de TI com 15 anos de atuação no mercado, focada no desenvolvimento de soluções customizadas, consultoria de TI, Outsourcing, Body Shop e treinamento, para atender as demandas de seus clientes.

Provedora de soluções, consolida sua marca entregando projetos com qualidade e respeitando os prazos acordados com seus clientes.

Utilizamos as melhores práticas de mercado para desenvolvimento de software, atuando em todo ciclo de vida do projeto com profissionais capacitados, que utilizam seus processos baseados na metodologiaRUP (Rational Unified Process) e a gestão dos projetos baseados no PMI (Project Management Institute), o que garante alto grau de satisfação de seus clientes.
## Descrição da vaga

Você será responsável por desenvolver e dar manutenção em versões iOS de aplicativos novos e legados, tanto em **Swift** quanto **Objective-C**.
## Posição

Sênior.
## Tipo de contratação

Presencial
###### Obrigatórios
- 1 ano de experiência com Swift
- 3 anos de experiência com Objective-C
- Experiência em desenvolvimento (+5 anos)
- APIs RESTful e/ou Webservices
- Familiaridade com Storyboards e Autolayout para iPhone/iPad
- Conhecimento das guidelines de design e de desenvolvimento da Apple
###### Desejáveis
- Conhecimento de metodologias ágeis
- Experiência com Cocoapods
- Ter participado de comunidades, grupos de discussões, eventos e afins (online ou não) relacionadas ao desenvolvimento de software
## Benefícios
- Salário 7~10 (negociável)
- VR
- Plano de Saúde
## Como aplicar

Por favor envie um email para marcelo.reis@foursys.com.br com seu CV anexado - enviar no assunto: Vaga Dev iOS Sênior

**Comment by reprotector** [comment]
@marceloreis13 Já fecharam a vaga? Pode fechar a issue?
