### ISSUE TITLE
[SP - Moema] Empresa medio porte e-commerce - Desenvolvedor iOS Jr

### ISSUE THREAD

**Issue by andreabrandao** [CocoaHeadsBrasil/vagas#521]
## Empresa
Empresa de médio porte de e-commerce

## Posição
Jr

## Tipo de contratação
PJ

## Benefícios
contratação PJ 

## Com quem você vai trabalhar
Se desejar insira uma lista dos futuros colegas de trabalho. Você pode gerar uma com os usuários do GitHub dos funcionários em http://fpg1503.com/GithubProfileTableGenerator/

## Como aplicar
Entrevista Skype + Entrevista Presencial

## Contato
andrea@mootit.com.br

**Comment by reprotector** [comment]
Olá, @andreabrandao. Favor atenção nas regras do canal, todas as vagas devem conter o nome da empresa.

**Comment by andreabrandao** [comment]
Olá,

Infelizmente o cliente nos pediu sigilo no nome da empresa , nesse caso
como posso proceder?

Abs

*Andréa Brandão.*
*Skype: dea_brandao*
(11) 99143-5600 ou 98151-4646


Renan Protector <notifications@github.com> escreveu no dia sexta,
15/03/2019 à(s) 16:06:
