### ISSUE TITLE
[Florianópolis-SC] Engenheiro de Software Mobile iOS na Peixe Urbano

### ISSUE THREAD

**Issue by penelopevitoria** [CocoaHeadsBrasil/vagas#524]
**Esta é uma vaga de um cliente da GeekHunter, candidate-se para ter acesso as informações completas sobre a empresa.**

### **Empresa**

Se você gosta de trabalhar em um ambiente dinâmico, inovador e com projetos que desafiam, esse é o seu lugar! Estamos em busca de um Engenheiro de Software iOS para somar forças ao time e dar conta da missão que é fazer com nossos mais de 30 milhões de usuários, tenham uma experiência cada vez mais positiva em nosso app. 

### **Descrição da vaga**

- Participar do desenvolvimento de apps relacionados ao negócio, na plataforma iOS;
- Identificar, diagnosticar e corrigir de bugs;
- Contribuir no desenvolvimento e adoção de melhores práticas no time;

**Será seu diferencial se você também tiver:** 

- Experiência com view code (desenvolvimento sem Interface Builder)
- Experiência com código legado
- Experiência com app extensions, push notifications e uso de múltiplos targets no Xcode
- Experiência com Apple Watch, CoreLocation, PassKit
- Noção das regras de negócio da Apple para a plataforma( incluindo Design Guidelines e App Store Review Guidelines) 
- Conhecimento de UX e ferramentas de design (Sketch e Zeplin)
- Experiência no uso de ferramentas auxiliares de dessenvolvimento (proxy, debbugers, etc.)
- Contribuições para projetos open-source

### **Posição**
Pleno ou Sênior

### **Tipo de contratação**
Regime PJ // Salário: R$ 10 000,00

### **Requisitos Obrigatórios**

- 3 anos ou mais de experiência criando apps para iOS
- Domínio de Swift e Objective-C
- Conhecimento sobre os frameworks da Apple, especialmente UIKit
- Experiência com APIs REST e parsing de JSON
- Experiência em multi-threading com GCD
- Experiência de uso do LLDB, view debugger e outras ferramentas de debug
- Conhecimento avançado de UITableView, UICollectionView e desenvolvimento de componentes de UI customizados
- Experiência com ferramentas de tracking (Firebase, Fabric, Localytics, etc.)
- Inglês técnico
- Experiência em versionamento usando Git

### **Requisitos Desejáveis**

- Experiência com view code (desenvolvimento sem Interface Builder)
- Experiência com código legado
- Experiência com app extensions, push notifications e uso de múltiplos targets no Xcode
- Experiência com Apple Watch, CoreLocation, PassKit
- Noção das regras de negócio da Apple para a plataforma( incluindo Design Guidelines e App Store Review Guidelines) 
- Conhecimento de UX e ferramentas de design (Sketch e Zeplin)
- Experiência no uso de ferramentas auxiliares de dessenvolvimento (proxy, debbugers, etc.)

### **## Benefícios**
Vale refeição, Vale alimentação, Plano de saúde, Plano odontológico, Outros

### **Como aplicar**

Cadastre-se na GeekHunter e concorra à vaga: http://bit.ly/2Y7lfDj

**Comment by Viniciuscarvalho** [comment]
Olá @penelopevitoria , tudo bem? Esta vaga já havia sido criada, anteriormente https://github.com/CocoaHeadsBrasil/vagas/issues/467

Vou fechar essa issue, tudo bem?

Abraços.
