### ISSUE TITLE
[SP - São Caetano] - Desenvolvedor iOS

### ISSUE THREAD

**Issue by recruitermaaaa** [CocoaHeadsBrasil/vagas#525]
A Taking Consutoria está contratando  para o cliente VIA VAREJO.

Necessário experiência em desenvolvimento. 

 Nível Sr e Pleno

Contratação PJ por tempo indeterminado. 

Requisitos: Swift 4, Alamofire, CocoaPods, Carthage, ViewCode-Design Pattern, XIB IOS, Push Notification (Firebase, APNS), REST, IOS.

Desejáveis: APPs Publicados na Loja, SOLID, DDD, Cultura DevOps.

Para participar do processo, favor enviar currículo para cida.araujo@taking.com.br

Contato: celular corporativo (11)95320-8898

**Comment by Uragawa** [comment]
Olá, este espaço é apenas para vagas do ecossistema Apple. Tente o https://github.com/androiddevbr/vagas, mas atente para o fato de que lá, como aqui, as vagas devem conter o nome da empresa que está contratando.

**Comment by recruitermaaaa** [comment]
Publiquei a vaga errada...vou editar para as vagas de iOS.
