### ISSUE TITLE
[São Paulo] Senior iOS Developer | Elo7

### ISSUE THREAD

**Issue by rsicarelli** [CocoaHeadsBrasil/vagas#53]
## Empresa

Elo7 é o maior site da América Latina de compra e venda de produtos criativos e autorais. Aqui você compra diretamente de milhares de pessoas que transformam ideias criativas em produtos únicos e diferenciados. Além de comprar ou vender, você pode também apreciar o trabalho criativo de artesãos, artistas, designers e todos aqueles que criam manualmente produtos diferenciados e de qualidade.
## Descrição da vaga

Estamos buscando profissionais apaixonados por desenvolvimento de software e que tenham grandes aspirações em se tornar cada vez melhores no que fazem, e melhor que isso, que não apenas queiram, mas que estejam dispostos a se manter em constante estado de aprendizado, inspeção e adaptação. 

Além disso, este profissional, deverá estar confortável com a ideia de aprender, ensinar e trabalhar em equipe. Todos os nossos profissionais estão sempre estudando e ensinando aos outros. O profissional que buscamos precisa ser compromissado! Se você é um daqueles consultores PJ que gosta de pular de galho em galho, por favor, não perca nosso tempo, e nem o seu. Buscamos relacionamentos de longo prazo.
## Posição

Sênior
## Tipo de contratação

Nosso escritório fica na Vila Olímpia, [exatamente na rua da estação](https://goo.gl/maps/rPoN3kFYQ8N2) 
Horário flexível e não batemos ponto 🙌 
###### Você precisa conhecer bem:
- Orientação a objetos e boas práticas de programação 
- Swift 2
- Consumo de APIs REST  
- Objective - C
- Testes automatizados
###### Diferenciais
- Java
- Conhecimentos de back-end _(por aqui você vai ter liberdade de programar de tudo)_
## Benefícios

Conheça a nossa engenharia: http://carreira.elo7.com.br/engenharia/
- CLT full (saúde + odonto + VT 29/dia); 🍚 
- Frutas diferentes todos os dias; 🍎 
- Hackday a cada duas semanas; 👾 
- Tech Talk semanal _(todos os engenheiros podem apresentar)_; 🎤 
- Craft day a cada duas semanas; 👌 
- Grupos de estudos diversos; 📚 
- Gym Pass; 💪 
- Massagem 2x por semana; ☺️ 
- Manicure e pedicure 2x por semana; 💅 
- Ginástica laboral 2x por semana; 🏃 
- Corte de cabelo e barba 1x por semana; 👨 
- [Colaboradores](http://www.colaboradores.com.br/); 👊 
- Descontos em diversos restaurantes da região; 🍂 
- Vários happy hours 🍻 
## Como aplicar

https://www.linkedin.com/comm/jobs2/view/196488486
## Contato

Se tiver alguma dúvida sobre a empresa, produto ou o time, sinta-se a vontade de entrar em contato comigo 👊;

**Comment by reprotector** [comment]
@rsicarelli Já fecharam a vaga? Pode fechar a issue?
