### ISSUE TITLE
[Amsterdam - Holanda] Booking.com - iOS Developer

### ISSUE THREAD

**Issue by mauriciomeirelles** [CocoaHeadsBrasil/vagas#54]
## Booking.com

Booking.com BV (the company behind Booking.com™, the market leading online hotel reservation service in the world) and/or its various support companies throughout the world are looking for people to support the business in the fast-growing hotel markets. We are looking for engineers with strong experience developing native applications on the iPhone or iPad.
## Descrição da vaga

Our guiding principle is that by helping our users we help our business, so we listen to our customers and give them features they want to use.  As a developer in our mobile team you’ll be a key part of the idea generation process, working in a small start up-like group which takes full ownership of its part of our platform. You’ll be working on the iterative improvements we make as part of our high-speed release cycles, as well as looking ahead and implementing broader changes to our mobile app.

As iOS developer you will:
- Develop new features to our iOS products
- Optimize UI for performance
- Monitor and understand customer behavior
- Build native iOS components
- Solve issues prioritizing based on customer impact
- Collaborate with back end developers, designers, product owners to constantly improve customer experience within iOS platform
## Posição

iOS Developer
## Tipo de contratação

Presencial
###### Obrigatórios
- 5+ years of experience as a developer
- 3+ years iOS application development using iOS SDK
- Knowledge of Cocoa, Objective-C and Xcode
- Knowledge of Object Oriented concepts and a strong passion for software development
- Self-motivated to explore new technologies, applications and environments
- Excellent attention to detail
- Self-starter, highly motivated, team-player
- Fully comfortable working in English, both in writing and spoken
###### Diferenciais
- Experience with Apple Approval & Distribution Process, Ad Hoc & Enterprise Distribution
- Have built an approved store App
- Experience working with A/B testing
- You are passionate about open source and contribute
- You’re not afraid to solve deep technical challenges of a whole new level at a huge scale
- You have an intrinsic curiosity in technological innovations and you are always on top of the latest trends
## Benefícios

We are a performance-based company that offers career advancement and lucrative compensation, including bonuses and stock potential.  We also offer what we call the “Booking Deal” with other competitive perks and benefits.  The Technology department has monthly hackathons, training and attends/speaks at global conferences.

This position is open to worldwide candidates and in the case of relocation, we will assist you with a generous relocation package, ensuring a smooth transition to working and living in Amsterdam.  We have successfully relocated 300+ Technology professionals to Amsterdam in the last year!

The hiring company Booking.com BV is the company behind Booking.com™, the market leading online accommodation reservation service in the world. Booking.com BV is looking for a iOS Developer in Amsterdam, the Netherlands. All references to “Booking.com" refer to Booking.com BV.
## Como aplicar

http://grnh.se/ujghd8

De preferência falar comigo se aplicar!
## Contato

mauricio.meirelles@booking.com

**Comment by reprotector** [comment]
@mauriciomeirelles Já fecharam a vaga? Pode fechar a issue?

**Comment by mauriciomeirelles** [comment]
Não fechou não!
Pelo que eu saiba o objetivo era contratar uns 20 esse ano ainda, só conseguiram contratar 5... Então tem muitas vagas ainda, se for bom e quiser morar em Amsterdam só avisar :)

**Comment by narlei** [comment]
@mauriciomeirelles mandei email.

**Comment by fnazarios** [comment]
@mauriciomeirelles a vaga Ainda está aberta?

**Comment by mauriciomeirelles** [comment]
Yep, sempre hahaha 
Ouvi falar que o ritmo de contratação diminuiu um pouco mais ainda precisam de mais gente do que conseguimos achar :)

**Comment by damboscolo** [comment]
Olá Maurício, gostaria de saber sobre o processo seletivo. É muito difícil? Obrigada.

**Comment by mauriciomeirelles** [comment]
Então, não acho que seja difícil se você esiver preparada. As entrevistas fora do BR normalmente pedem um pouco mais de general programming e conceitos, nessa parte que normalmente as pessoas se complicam um pouco... também é legal estudar mais a fundo como o iOS / Objective-c realmente funcionam. 
Se tiver alguma dúvida específica me chama no slack :)

**Comment by phenemann** [comment]
opa, ainda estão contratando pra essa vaga?

**Comment by jethern** [comment]
@mauriciomeirelles opa, ainda estão contratando pra essa vaga? x2
