### ISSUE TITLE
[Amsterdam - Holanda] Booking.com - Graduate iOS Developer

### ISSUE THREAD

**Issue by mauriciomeirelles** [CocoaHeadsBrasil/vagas#55]
## Booking.com

Booking.com is looking for new Graduate iOS Developers who are passionate about mobile development, eager to learn, thrive on challenge, and who believe in success through collaboration – people who will become our next generation of iOS developers!

We offer an international, result-driven, fun and dynamic environment. If scale and complexity excite you, Booking is the place to B!
## Descrição da vaga

At Booking.com we care about our users, and our guiding principle is that by helping our users we help our business. We listen to our customers and give them features they want to use, using continuous experimentation and A/B testing to understand their behaviour. As a developer in the iOS team you’ll be a key part of the idea generation process, working in a small startup-like team which takes full ownership of its part of our platform. You’ll be working on the iterative improvements we make as part of our high-speed release cycles, as well as looking ahead and implementing broader changes to our iOS app.

As a Graduate iOS Developer you will rotate through three different teams over a 12-month period. Your focus will be on learning as much as there is to learn about our tech stack, app environment and way of working. You’ll spend time working in existing teams on the iOS platform, but also collaborate with your fellow Grad Developers to work on new and innovative products. We are very data-driven and do extensive A/B testing.
## Posição

Graduate iOS Developer
## Tipo de contratação

Presencial
## Requisitos

Obrigatórios
- Strong passion for hacking and programming, with experience in Objective-C or Swift
- Practical experience in developing iOS applications, either through internships, work experience or personal projects
- Ability to work independently in small teams
- Excellent English communication skills, both spoken and written
- Enthusiasm for working in a large, fast-paced e-commerce environment
- Highly ambitious with a keen business sense
- Recent (or soon-to-be) university graduate in Mathematics, Software Engineering, or related field
- Available to start a full time job on 1st of November 2016
## Como aplicar

http://grnh.se/25n7cj

De preferência falar comigo se aplicar!
## Contato

mauricio.meirelles@booking.com

**Comment by reprotector** [comment]
@mauriciomeirelles Já fecharam a vaga? Pode fechar a issue?

**Comment by mauriciomeirelles** [comment]
Não fechou não! Pode deixar! :)

**Comment by reprotector** [comment]
@mauriciomeirelles A vaga ainda está aberta ou posso fechar a issue?

**Comment by mauriciomeirelles** [comment]
Esta acredito estar fechada por enquanto. Então pode fechar!
Valeu!
