### ISSUE TITLE
[remoto] Devs Mobile Sênior - Xamarin e C# | Impulso

### ISSUE THREAD

**Issue by ThaysdaCosta** [CocoaHeadsBrasil/vagas#555]
## Descrição da vaga
Buscamos Dev Mobile (Sênior) para atuar remotamente num projeto.

## Local
Onde você quiser. 100% REMOTO!

###### Obrigatórios
Xamarin
C#

###### Necessário conhecimentos de:
Microsoft Visual 
Git
Microsoft Azure

## Remuneração
Até R$65/h (~R$10.400/mês).💰 A própria pessoa define quanto julga ser adequado receber.

## Sobre nós
A Impulso é um ecossistema - um ambiente colaborativo tecnológico - que engloba a execução de projetos de software, consultoria, treinamento e formação para empresas e profissionais de tecnologia.
Nutrimos uma comunidade, a Impulso Network, que já conta com mais de 8.800 pessoas!

## Como se candidatar
Acesse o link 👉🏻 https://impulser.me/thays-impulso (após registrar-se, você receberá por email as credenciais para acessar o chat da nossa comunidade, no RocketChat).

Assim que entrar, por favor, me chame pelo chat da Impulso e mencione o assunto (OP382 - Mobile Xamarin e C#). Lá eu sou `@thays` 😉

Aguardo vocês! 🚀

**Comment by mbrufatto** [comment]
Essa vaga não é para iOS?
