### ISSUE TITLE
[São Paulo - Ana Rosa] ChefsClub - Desenvolvedor iOS Junior

### ISSUE THREAD

**Issue by PauloLeite022** [CocoaHeadsBrasil/vagas#558]
## ChefsClub
ChefsClub é o maior Clube de gastronomia do Brasil e garante aos usuários benefícios variados em seus restaurantes parceiros através de reservas e também de checkins no aplicativo ChefsClub. Não entendeu? [Veja como funciona](https://www.chefsclub.com.br/como-funciona)

## Posição
Desenvolvedor iOS Junior

## Tipo de contratação
Presencial CLT ou PJ

## Salário
A combinar - [Referência](https://www.lovemondays.com.br/salarios/cargo/salario-desenvolvedor-ios-junior)

## Benefícios
VR de R$440,00
VT caso o desconto faça sentido
Assinatura gratuita do ChefsClub
Outros benefícios que ocorrem durante o ano como cursos, eventos, viagens, etc

## Descrição da vaga
Nosso aplicativo foi construído usando a linguagem Swift, seguindo padrões amplamente difundidos no desenvolvimento iOS: Um projeto que segue a arquitetura MVVM, orientado à componentização de Views, bibliotecas gerenciadas pelo CocoaPods, testes instrumentados e Fastlane para liberação de aplicativos e gerenciamento de certificados.
[Você pode ver mais sobre as tecnologias que usamos aqui](https://stackshare.io/felipetio2/chefsclub). 
Porém muito mais importante do que ser experiente com tecnologias que usamos, é se comportar como uma mente curiosa, gostar de aprender coisas novas rapidamente e entender os principais conceitos por trás das bibliotecas e dos frameworks que você já domina.
Entendemos que o tempo gasto no escritório não equivale à produtividade. Por isso, nossa equipe está livre para trabalhar remotamente e toda a comunicação é feita rigorosamente no Slack.

## Como aplicar
https://podio.com/webforms/15229618/1020915

## Contato
CTO: felipe@chefsclub.com.br
Desenvolvedor iOS Senior: paulo.leite@chefsclub.com.br

**Comment by Paulo-http** [comment]
Contratado!
