### ISSUE TITLE
SP - São Paulo - Startup - Desenvolvedor iOS Senior

### ISSUE THREAD

**Issue by LindaRojasG4** [CocoaHeadsBrasil/vagas#56]
Startup de tecnologia disruptiva com alto crescimento num determinado mercado brasileiro. 
Ano passado contavam com uma base de 50 funcionários e hoje contam com 150 e um planejamento para maior abrangência nos próximos 2 anos. Constantemente na mídia, por sua estrutura, faturamento, tecnologia e por seus fundadores, dois profissionais visionários. 

Nossa empresa tem como objetivo...
Aplicativo construído para simplificar os passos do usuário final, desconstruindo um processo a principio muito burocrático num determinado mercado brasileiro.

Descrição da vaga
Precisamos de alguém que acompanhe toda esta inovação e gire bem dentro da empresa.
Que ajude a desenvolver e manter o app 
Precisamos alguém com um perfil mais sênior, que conte com experiência em outras startups ou empresas que utilizem tecnologia de ponta.

Desenvolvedor iOS Sênior

Sênior 

Presencial

Escritório em São Paulo, próximo ao metrô da Paulista
## Requisitos

Inglês avançado
Background teórico 
Acima de 6 anos de experiência em desenvolvimento / programação

Caso seu perfil se aplique a vaga, me envie seu CV e se tiver o link do LinkedIn no corpo do email
Se seu CV for aprovado por nossa equipe, faremos um contato telefônico alinhando alguns pontos.
Em seguida, abrimos o nome do cliente e o processo de fato começa!! Let's go! 

Por favor envie um email para linda.solis@g4globalpartners.com com seu CV anexado - enviar no assunto: Vaga iOS

**Comment by reprotector** [comment]
@LindaRojasG4 Já fecharam a vaga? Pode fechar a issue?

**Comment by G4Juliana** [comment]
Já fechamos a vaga sim, pode fechar. Obrigada!
