### ISSUE TITLE
[SP - Jaguariuna] - AMBEV - Desenvolvedor iOS Pl/Sr

### ISSUE THREAD

**Issue by recruitermaaaa** [CocoaHeadsBrasil/vagas#560]
Descrição da vaga: 
• Projetar e criar aplicativos e recursos para dispositivos móveis usados em todo o mundo;
• Colaborar com equipes multidisciplinares em vários países
• Garantir que nossos aplicativos móveis tenham desempenho e escala na produção, proporcionando a melhor experiência para nossos clientes
• Resolva problemas complexos que afetam diretamente o negócio
• Faça parte da transformação digital de uma das maiores empresas do mundo

Responsabilidades:
 
- Experiência no desenvolvimento de aplicativos nativos usando Swift e Objective-C, layout automático e gerenciamento de decência com Carthage e CocoaPods
• Bem versado em git
• Conhecimento dos principais padrões de desenvolvimento usados em aplicativos para dispositivos móveis
• Inglês intermediário

Desejável: 
• Experiência em trabalhar em projetos ágeis (scrum / kanban)
• Algum conhecimento de programação reativa (RxSwift)
• Conhecimento de testes unitários, de interface do usuário e funcionais com o Xcode
• Algum conhecimento de linguagens como python e C ++

Local: Jaguariúna - cidade próxima a Campinas 

Escritório - TI  - Jaguariúna

A empresa é uma Multinacional, atua possui escritório global de gerência funcional em Nova York, e sedes regionais em Londres, Cidade do México, Joanesburgo, St. 
O profissional terá a oportunidade de interagir com as equipes de fora do Brasil. 
Grande oportunidade de crescimento profissional!

Contratação: 

PJ -  valor a combinar - após 3/4 meses grande possibilidade de efetivação.

Por favor envie um email cida.araujo@taking.com.br com seu CV anexado - enviar no assunto: Vaga Dev iOS

**Comment by reprotector** [comment]
Duplicada #527
