### ISSUE TITLE
[RJ - Botafogo] Moki - Desenvolvedor iOS Senior/Pleno

### ISSUE THREAD

**Issue by gwerneck** [CocoaHeadsBrasil/vagas#565]
## Empresa
Moki é a pioneira e mais inovadora solução focada em ganhos de eficiência nas rotinas de levantamentos de campo. Atende as maiores empresas do varejo brasileiro, além diversas outras empresas de serviço, da indústria e do agronegócio. Tendo usuários em mais de 38 países e clientes em diversas operações na América Latina, tem um ambicioso projeto de expansão nacional e internacional.

## Descrição da vaga
A Moki está buscando desenvolvedores de apps para iPhone e iPad, para integrar o time de desenvolvimento e manutenção da aplicação Moki Checklist & Trade Marketing. Buscamos talentos capazes de codificar as nossas ideias e a experiência de usuário criada pela equipe de design.

## Posição
Pleno ou Senior

## Tipo de contratação
Presencial, CLT Full (Salário compatível com o mercado)

## Requisitos
.Domínio em front-end (criação de views e telas) para diferentes resoluções de tela;
.Conhecimento em Apple Design Guide Lines;
.Compreenda a importância da UX e tenha compromisso com o produto final;
.Concilie demandas e prazos comerciais com qualidade de código;
.Escreva um código limpo, padronizado e comentado;
.Seja proativo trazendo sempre ideias para resolvermos nossos desafios;
.Siga as tendências do mercado e que seja capaz de se adaptar rapidamente a novas tecnologias;
.Tenha boa comunicação, trabalho em equipe, senso de organização, atenção a detalhes e foco.

###### Obrigatórios
.Sólidos conhecimentos em Swift e Objective;
.Experiência com Git;
.Experiência com integração com APIs RESTful;
.Conhecimentos de push notification, persistências;
.Conhecimentos de publicação na loja Apple e processos de revisão

###### Desejáveis
.Conhecimentos de inglês suficiente para leitura técnica e para treinamentos em vídeos no idioma
.Conhecimento de Espanhol

###### Diferenciais
.Conhecimento de Xamarim

## Benefícios
.Opções de horário: 08h/17h, 09h/18h ou 10h/19h
.Vale transporte
.Ticket Refeição
.Ticket Alimentação
.Plano de saúde
.Seguro de vida
.Dress code flexível

## Como aplicar
Enviar currículo com descrição da experiência, trabalhos realizados e pretensão salarial para guilherme@moki.com.br

## Contato
Guilherme Werneck - guilherme@moki.com.br

**Comment by gwerneck** [comment]
Vaga ainda está aberta

**Comment by victorvieiraveiga** [comment]
Teria vaga para Jr?

**Comment by gwerneck** [comment]
Oi Victor, depende de quão junior você é. Teira algum portfolio para
compartilhar comigo?

De qualquer forma vamos falar na semana que vem. Me mande um numero de
contato?

Grato,
GW

Em qui, 24 de out de 2019 17:07, Victor Vieira Veiga <
notifications@github.com> escreveu:

**Comment by victorvieiraveiga** [comment]
tem meu GitHub https://github.com/victorvieiraveiga

**Comment by MarcosiOSdev** [comment]
A vaga ta aberta ou inativa ?

**Comment by gwerneck** [comment]
A vaga está aberta.

Em sex, 25 de out de 2019 03:55, Marcos Felipe Souza <
notifications@github.com> escreveu:
