### ISSUE TITLE
[São Paulo - Vila Olímpia] Easynvest - Desenvolvedor iOS 

### ISSUE THREAD

**Issue by lucasbim** [CocoaHeadsBrasil/vagas#57]
## Empresa

Somos essencialmente uma empresa de tecnologia, que quer construir a melhor experiência de investimento que existe. 

## Descrição da vaga

Estamos montando um novo time de desenvolvimento, com pessoas brilhantes para pensar em todos os aspectos da nossa estrutura. Buscamos desenvolvedores iOS que nos ajude a trabalhar o nosso app do zero, desde a arquitetura até os testes. Você vai trabalhar com designers, PM´s e outros desenvolvedores. 

💥0 código legado! 
💯% Swift 3! 

## Tipo de contratação

CLT

## Requisitos

- Conhecimento e experiência em desenvolvendo aplicativos iOS; 
- Experiência em novos desenvolvimentos, planejando a arquitetura de soluções do zero; 
- Capacidade de desenvolvimento estruturada; 
- Raciocínio analítico extremamente desenvolvido; 
- Capacidade de trabalhar em times multidisciplinares e se comunicar de forma clara com o time de desenvolvimento;  
- Ter ownership e ser pró-ativo. 
## Benefícios

🍎 Você vai trabalhar com um iMac Retina, i7, 16gb e SSD! 🍎
- VA
- VR
- PLR
- Plano de Saúde e Odonto
## Como aplicar

Aplique aqui: https://www.easynvest.com.br/carreiras?gh_jid=547529

e boa sorte!

## Contato

Se interessou e está com algumas dúvidas antes de aplicar? Me procure no slack iOSDevBR, sou o  @lucascypriano lá.

**Comment by reprotector** [comment]
@lucasbim Já fecharam a vaga? Pode fechar a issue?

**Comment by lucasbim** [comment]
@reprotector ainda não.

**Comment by reprotector** [comment]
@lucasbim E agora? :)

**Comment by lucasbim** [comment]
@reprotector ainda não, estamos com 2 vagas iOS ainda. Tem como atualizar as labels pra ser somente pra pleno e sênior?
