### ISSUE TITLE
[SP - Moema] Looke- Desenvolvedor iOS Senior

### ISSUE THREAD

**Issue by thaishbrasil** [CocoaHeadsBrasil/vagas#572]
## Looke
Somos a mais completa  plataforma de Streaming do mercado Brasileiro 
Trabalhamos com opções de assinatura, locação e compra de conteúdos em Vídeo.
Assim como Netflix, Google Play, Itunes, Amazon Prime, incluímos em nossa Plataforma filmes recém-saídos dos cinemas, clássicos, shows, documentários, séries exclusivas e os mais queridos conteúdos infantis,  levando diversão para todos os targets.
O Looke tem parcerias com grandes empresas  de diversos segmentos, levando sempre as melhores experiências em Vídeos para seus usuários.

## Descrição da vaga
Construir aplicações para iOS utilizando Objective C  e  Swift 4.2
Dominar o git flow 
Implementar mockups do time de design, com atenção aos detalhes visuais e compatibilidade entre devices
Dominar o processo de deploy (AppStore Connect, TestFlight, AppStore)
Priorizar e tratar bugs e exceções reportados em produção
Contribuir em decisões de arquitetura sobre novas partes do projeto.
Experiência em integração com banco de dados, integrações com APIs RESTful

## Posição
 Pleno/Senior

## Tipo de contratação
CLT ou PJ

## Requisitos
Pelo menos 3 anos de experiência com desenvolvimento de softwares 
Ter pelo menos 3 anos de experiência com desenvolvimento iOS
Experiência com desenvolvimento de apps nativo 
Sólidos conhecimentos em Swift e ter conhecimentos em Objective-C
Conhecimento das guidelines de design e de desenvolvimento da Apple

###### Desejáveis
Cocoa Pods
Testes automatizados 
XCode Server 
Continuous Integration 
RxSwift 
Familiaridade com processo de desenvolvimento de software ágil (como XP, Scrum e Kanban)
Desenvolvimento multiplataforma (Android e Xamarim - tecnologias que também utilizamos). 

## Como aplicar
enviar CV para: vagas@looke.com.br ou thais.fernandes@looke.com.br

## Contato
Thais Fernandes
Recursos Humanos
T +55 11 5053 5033 
Alameda dos Maracatins, 780 – 7º Andar – Moema

![ios_2](https://user-images.githubusercontent.com/47364879/58187069-77483f80-7c8c-11e9-9dec-e9c54621d7ac.png)

**Comment by reprotector** [comment]
Duplicada #567
