### ISSUE TITLE
[MG - Belo Horizonte] Banco Inter - Desenvolvedor Mobile Pleno e Sênior 

### ISSUE THREAD

**Issue by ThiagoMiranda** [CocoaHeadsBrasil/vagas#574]
## Empresa
O Banco Inter é o primeiro banco 100% digital do Brasil e o único a oferecer uma conta completa e totalmente isenta de tarifas. Acreditamos que a relação das pessoas com seu banco pode ser muito mais simples, transparente e justa. E estamos fazendo essa transformação acontecer. 
 
Hoje somos um Banco múltiplo, com ações listadas na B3 e todos os serviços financeiros que você precisa.

## Descrição da vaga

- Desenvolvimento e manutenção de aplicações nativas, com integração com serviços back-end
- Participará da definição padrões, garantir a qualidade, responsividade e estabilidade dos Apps
- Desenvolvimento de um APP totalmente modularizado usando as melhores práticas do mercado
- Ajudar e definir a trilha de CI/CD do aplicativo até seu lançamento

## Posição
 Pleno e Sênior

## Tipo de contratação
CLT

## Requisitos
- Profissional graduado em TI (Ciência da Computação, Sistemas da Informação e afins)
- Experiência em desenvolvimento de Apps IOS
- Experiência com processos de integração contínua
- Experiência em testes unitários
- Domínio em publicações na App Store
- Para IOS: Excelente conhecimento das linguagens Swift e Objective-C, Cocoa Pods ou - Carthage, familiaridade com as aplicações dos guidelines da Apple

###### Obrigatórios
- 2+ anos de experiência em desenvolvimento IOS
- Conhecimentos em arquiteturas MVC, MVVM
- Conhecimentos em ferramentas de testes como XCTest e XCUITest
- Conhecimentos em práticas como Clean Architecture e Domain-Driven Design

###### Desejáveis
- Experiências com integração de serviços REST/SOAP
- Noções de engenharia de segurança aplicada a iOS
- Conhecimentos em programação reativa utilizando RxSwift

###### Diferenciais
- Experiência com React Native e integração com o nativo

## Benefícios
- Salário competitivo
- Assistência médica e odontológica
- Auxílio creche
- Participação nos Lucros e Resultados
- Seguro de vida
- Vale Alimentação
- Vale Refeição
- Vale Transporte
- Espaço Bem Estar (Corte de Cabelo, manicure, Quick massage, Pebolim...)
- Meetup’s com temas diversos do universo de tecnologia e finanças

## Como aplicar
https://portal.kenoby.com/bancointer/cadastrar/5cd0a17ac0c1992ea684c7d3?1=1

## Contato
daniel.lamas@bancointer.com.br

**Comment by rogerioc** [comment]
"Vaga ainda está aberta" continuamos precisando de devs iOS também podem entrar em contato com
rogerio.celestino@bancointer.com.br.

**Comment by rogerioc** [comment]
Pessoal, o banco vem crescendo bastante tem muitos desafios e muita coisa para se fazer. Estamos precisando de pessoas boas e animadas. A cultura vem mudando tb saindo muito do formalismo. #sanguelaranja #revolucaobancaria
