### ISSUE TITLE
[São Paulo] Desenvolvedor(a) iOS

### ISSUE THREAD

**Issue by aline-navarro** [CocoaHeadsBrasil/vagas#586]
## Tipo de contratação
presencial, PJ 

## Requisitos
- Profissionais com domínio técnico de linguagens para o sistema SWIFT;
- Necessário ter conhecimentos em Push Notifications;
- Autentificação (login e logout);
- Integração de APIs e publicação de aplicativos Apple Store);
- Multitasking;

## Contato
Por favor encaminhe um CV para aline.navarro@keepsimple.com.br

**Comment by marcelofabri** [comment]
Olá, @aline-navarro. Favor atenção nas regras do canal, todas as vagas devem conter o nome da empresa.
