### ISSUE TITLE
[SP - Pinheiros] Banco Neon - Desenvolvedor iOS Sênior

### ISSUE THREAD

**Issue by luanamentlik** [CocoaHeadsBrasil/vagas#59]
## Empresa

[SP - Pinheiros] Banco Neon - Desenvolvedor iOS Sênior
## Descrição da vaga

Desenvolvedor Sênior para atuar com desenvolvimento nativo em fintech brasileira.
## Posição

Sênior.
## Tipo de contratação

CLT
###### Obrigatórios

Programação e desenvolvimento de em linguagem nativa, Objective C e/ou Swift;
Programar e desenvolver mecanismos de software realizando suas respectivas validações e avaliações;
Contribuir e participar de todas as fases do ciclo de vida do desenvolvimento.
## Como aplicar

Por favor envie um email para luana.mentlik@hubtalent.com.br com seu CV anexado - enviar no assunto: Vaga iOS
## Contato

luana.mentlik@hubtalent.com.br

**Comment by reprotector** [comment]
@luanamentlik Já fecharam a vaga? Pode fechar a issue?
