### ISSUE TITLE
[Porto Alegre - TecnoPuc] - Desenvolvedor iOS | Globo.com

### ISSUE THREAD

**Issue by diegomarcon** [CocoaHeadsBrasil/vagas#6]
## Local

TecnoPuc - Porto Alegre.
## Benefícios
- CLT
- VR
- Plano de Saúde
- Xbox One
- Frutas 
- E mais.. :)
## Requisitos

Obrigatórios
- Ser apaixonada(o) por desenvolvimento de software e tecnologia
- Ter facilidade para trabalhar dentro de times multi-disciplinares;
- Ter experiência com Objective C ou Swift;
- Ter experiência ou vontade de aprender Android (Java/Kotlin).
- Possuir conhecimentos de integração utilizando API RESTful;
- Conhecer e ter experiência com testes unitários, de aceitação, mocks, etc;

Diferenciais
- Projetos Opensource
## Contratação

CLT
## Nossa empresa

A globo.com é o braço de Internet do Grupo Globo, o maior grupo de mídia da América Latina. A globo.com agrega os maiores portais do Brasil, e é líder de audiência de Notícias com o portal G1, Esportes com o GloboEsporte.com, Entretenimento com o portal GShow, Celebridades com o portal Ego, e Vídeos com o Globo.tv.

Além disso, a globo.com atua como provedor de serviços de internet (ISP), consultoria e presta apoio estratégico e tecnológico para outras empresas do Grupo Globo. Possui uma das maiores infra-estruturas de distribuição de conteúdo da América Latina, e é detentora do recorde de maior audiência em vídeo streaming do Brasil.
## Como se candidatar

https://talentos.globo.com/#/oportunidades/desenvolvedor-mobile/mp0hdea

**Comment by barbosa** [comment]
Olá @diegomarcon, tudo bem?

A vaga ainda está aberta? Só para saber se fechamos a issue ou mantemos aberta.

Obrigado!

**Comment by diegomarcon** [comment]
@barbosa, desculpa a demora. 

Ainda está aberta sim.

**Comment by Viniciuscarvalho** [comment]
A vaga já foi preenchida @diegomarcon ? Se sim, pode fechar a issue? 👍

**Comment by diegomarcon** [comment]
@Viniciuscarvalho Uma das vagas já foi preenchida, porém abrimos outra com a mesma especificação :)

**Comment by Viniciuscarvalho** [comment]
Tudo certo @diegomarcon 👍

**Comment by reprotector** [comment]
@diegomarcon A vaga já foi preenchida? Pode fechar a issue?
