### ISSUE TITLE
[RJ - Barra da Tijuca] Homer - Desenvolvedor(a) iOS

### ISSUE THREAD

**Issue by Romulomga** [CocoaHeadsBrasil/vagas#601]
## Empresa
O Homer é a maior e mais segura rede de parcerias para corretores de imóveis. Milhares de corretores em todo o Brasil já estão melhorando a sua forma de trabalhar com o Homer. Startup de 3 anos com uma equipe robusta e unida que busca transformar o mercado imobiliário.
Quer entrar pra esse time?
Estamos buscando pessoas incríveis para fazer parte do nosso time e melhorar ainda mais nosso produto.

## Posição
Temos vagas para desenvolvedor iOS Júnior, Pleno e Sênior.

## Local
Atualmente estamos localizados em um escritório na Barra da Tijuca, RJ. Lugar de fácil acesso via BRT, com integração ao Metrô e tudo mais.

## Tipo de contratação
PJ a combinar, presencial, com horário flexível e possibilidade de dia remoto quando necessário.

###### Obrigatórios
* Desenvolver iOS nativo em linguagem Swift e Objective-C.
* Apple Guidelines.
* Utilização de serviços REST.
* Git.
* CocoaPods.

###### Desejáveis
* Familiaridade com processo de desenvolvimento de software ágil(Scrum).
* Experiência em publicação e gestão de aplicativos na Apple Store
* Realm ou CoreData
* Conhecimento na arquitetura MVVM

###### Diferenciais
* Fastlane
* Conhecimentos em testes unitários
* Ter algum aplicativo publicado

## Como se candidatar
Por favor envie um email para vagas@homer.com.br com seu CV anexado - enviar no assunto: Vaga iOS

**Comment by Romulomga** [comment]
Vaga ainda aberta.

**Comment by victorvieiraveiga** [comment]
A vaga ainda esta aberta?

**Comment by Romulomga** [comment]
Sim

**Comment by Romulomga** [comment]
Vaga ainda está aberta
