### ISSUE TITLE
[SP - Butantã] MYB - Desenvolvedor iOS/Android

### ISSUE THREAD

**Issue by myochem** [CocoaHeadsBrasil/vagas#61]
## MYB

Somos uma empresa prestadora de serviços na área de telecomunicações / tecnologia, especializada em medições de parâmetros e testes de redes móveis. Servir nossos clientes com excelência maximizando valor é o nosso objetivo. 
## Descrição da vaga

Desenvolvedor Android e iOS
•         Desenvolvimento de aplicativos para controle / gerenciamento de dispositivos IoT para plataformas Android / iOS. Colaboração com todos os times envolvidos para definir,desenhar e criar novos recursos. Trabalhar com dados e APIs externos. Testes de usabilidade, funcionalidade, confiabilidade e robustez. Solução de bugs e melhoramento contínuo de performance. Avaliação e implementação contínua de novas tecnologias para maximizar a eficiência. 
## Tipo de Contratação

Presencial - São Paulo (Butantã)
## Requisitos

Conhecimento de MQTT. Conhecimento de AWS IoT - Amazon Services. Domínio das linguagens de programação Swift e Java. Experiência com iOS SDK. Experiência com Android SDK. Tenha participado do desenvolvimento de pelo menos um app Android / iOS. Experiência com REST e JSON. Experiência com bibliotecas e APIs de terceiros. Conhecimentos gerais da área de desenvolvimento de aplicativos mobile, arquiteturas, tendências e tecnologias emergentes. Entendimento sólido sobre o ciclo completo de desenvolvimento de aplicativos mobile. 
## Benefícios:

Assistência Médica / Medicina em grupo, 
Tíquete-refeição, 
Vale-transporte
## Como aplicar

Favor enviar curriculum com a pretensão salarial para recursos.humanos@myb.com.br, no assunto escrever Desenvolvedor iOS/Android 
## Contato

recursos.humanos@myb.com.br

**Comment by reprotector** [comment]
@myochem Já fecharam a vaga? Pode fechar a issue?
