### ISSUE TITLE
[SP ou Full Remote] PicPay - Pessoal desenvolvedora iOS Jr/Pleno/Senior

### ISSUE THREAD

**Issue by fnazarios** [CocoaHeadsBrasil/vagas#616]
##  Empresa
O PicPay é uma plataforma de pagamento criada para quebrar barreiras e eliminar burocracias. Nós existimos para melhorar a vida das pessoas e só conseguimos fazer isso porque temos pessoas fantásticas aqui dentro.

## Descrição da vaga
Buscamos pessoas que sejam apaixonadas por construir aplicações distribuídas e de alta performance, escaláveis para milhões de novos usuários em todo o mundo e que suportem a melhor experiência de pagamentos.

## Posição
Junior, Pleno ou Senior (Pode ser full-remote)

## Tipo de contratação
CLT Full

## Requisitos
Trabalhamos em equipes pequenas e multidisciplinares utilizando Metodologia Agile.
Para essa vaga é essencial que o dev tenha experiência ou noção:

•  Swift;
•  REST APIs;
•  Autolayout com xib, storyboard e/ou ViewCode;
•  Noções de arquitetura (MVVM, Viper, e etc);
•  Testes automatizados;
•  Ferramentas de controle de versão (Git);
•  Gerenciamento de dependências. 

###### Manja dessas coisas? Tá avançando 10 casas.
•  Experiência com Objective-C

## Benefícios
O que temos de legal por aqui?

•  Assistências médica (você e +1 dependente ficam por nossa conta!);
•  Assistência odontológica;
•  Seguro de vida;
•  Vale Transporte e/ou Auxílio combustível;
•  Vale Refeição e/ou Vale Alimentação;
•  Vale Cultura;
•  PicPay Acolhe - Programa que cuida da gente e dos nossos familiares, oferecendo apoio jurídico, social, psicológico e financeiro;
•  Frutas, snacks, chás e café à vontade no escritório o dia todo (é sério, o dia todo mesmo!);
•  Horário flexível e possibilidade de home office;
•  No dress code;
•  Sorteio para shows nacionais e internacionais.

## Como aplicar
Nossos times de desenvolvimento estão localizados nos escritórios de SP e Vitória, ES e você pode escolher a vaga para a cidade que curte mais.

Só aplicar para a vaga aqui: https://www.linkedin.com/jobs/view/1499340799/

##### Sabe de alguém que curtiria essa oportunidade?
Compartilhe com seu amigx que tem a cara para essa vaga, vai ser incrível ter elx por aqui :)

## Contato
No Slack iOSDevBr, você pode falar com a gente: **@fnazarios**

**Comment by fnazarios** [comment]
Pode adicionar a label de junior? Valeu!

**Comment by danilorequena** [comment]
Não estou conseguindo me candidatar na vaga pelo LinkedIn

**Comment by fnazarios** [comment]
@danilorequena pode mandar o linkedin pra mim (fernando.sousa@picpay.com ou iosdevbr @fnazarios)
