### ISSUE TITLE
[Bangkok - Tailândia] Leading eCommerce business - iOS Engineer)

### ISSUE THREAD

**Issue by tjshannon** [CocoaHeadsBrasil/vagas#63]
# **[Bangkok - Tailândia] Leading eCommerce business - iOS Engineer**
## Empresa

Working with one of the world's leading travel company on an app with millions of active users. They focus on code quality, innovation and maximising the user experience. They have a hugely multicultural team with around 64 different nationalities represented in Bangkok and will help you with the relocation process through flights, visas and accommodation 

Build the world's best iOS app and have fun whilst doing it...
## Descrição da vaga

Working in a hugely talented, highly experienced Mobile team you will play a major part in writing major new features on an app used by millions of people worldwide. Although the app is large scale the company are constantly innovating to ensure they stay ahead of the technological curve. You should have:
- An enormous passion for iOS
- Experience with Objective-C and ideally Swift
- Great knowledge of iOS Architecture (Viper)
- Experience writing Unit Tests
- Value clean code and software craftsmanship
- A desire to create the best possible iOS app
- Comfortable working in an English speaking team
- A passion for Open Source is encouraged

## Tipo de contratação

Permanent 

Office - Bangkok

## Contato

If you would like to apply or have any questions please email tom.shannon@knowit.co.uk

**Comment by reprotector** [comment]
@tjshannon Já fecharam a vaga? Pode fechar a issue?
