### ISSUE TITLE
[PR - CURITIBA] EBANX - iOS Specialist Developer

### ISSUE THREAD

**Issue by fernandocruz** [CocoaHeadsBrasil/vagas#639]
## Empresa
 O EBANX é uma fintech global que surgiu em 2012 com a missão de conectar empresas a America Latina, facilitando pagamentos em sites internacionais como Aliexpress, Airbnb, Sony, Spotify e muitos outros.

Enquanto crescemos, nosso portifólio também se expandiu e fomos alem dos métodos de pagamentos. Hoje oferecemos soluções em processamentos locais para empresas brasileiras e diferentes produtos e serviços para nossos consumidores finais.

Nos chamamos ebankers e estamos mudando o jeito que as pessoas compram, se conectam e vivem globalmente. Quer se juntar ao nosso Sonho Grande e fazer parte desse time?

## Descrição da vaga
Buscamos um desenvolvedor especialista em iOS para nos ajudar no desenvolvimento de produtos para os nossos mais de 40 milhões de usuários.

Você vai trabalhar com um time talentoso que vai te inspirar, com um produto que democratiza o acesso às compras internacionais para milhões de latino-americanos e em um ambiente altamente favorável a experimentos e inovação.

Se você é muito bom e quer trabalhar em um ambiente multicultural e inovador com a cara do Vale do Silício, vem conversar com a gente.

## Posição
 Especialista

## Tipo de contratação
 Presencial, CLT. 

## Requisitos
Inglês avançado para leitura e conversação;
Curso superior completo em área relacionada (Ciência da Computação, Sistemas de Informação, etc);
Agile na veia;
Git guruness;
Bom tino negocial;
Experiência sólida com TDD e pair-programming;
Um verdadeiro Clean Coder;
Um DDD Practitioner;
Experiência comprovada com múltiplas arquiteturas (MVC, MVP, MVVM, VIPER, etc);
Experiência prévia no mercado de pagamentos;
Um bom espanhol. Estamos expandindo rápido por toda América Latina.

###### Obrigatórios
Mais de 5 anos de experiência como desenvolvedor de software;
Pelo menos 4 anos de experiência com desenvolvimento iOS;
Experiência com pelo menos 2 linguagens de programação tais como Swift, Objective-C, Kotlin, Java, Scala, Groovy, Clojure, Javascript, Ruby, Python, etc;
Integrar com APIs RESTful de olhos fechados;
Ter trabalhado em pelo menos 2 aplicativos já publicados na Apple Store;
Saber utilizar bem conceitos do GitHub como branching, pull-requests, etc;
Mindset de Continuous Delivery, focado em entregar valor de negócio e ao usuário final;
Experiência dando mentoria para outros desenvolvedores;
Conhecimento sobre boas práticas de segurança para desenvolvimento de aplicativos;
Inglês intermediário (lê e escreve bem, fala razoável);

## Benefícios
Ambiente de muita autonomia, aprendizado e desafios;
Escritório informal, descontraído e cheio de pessoas incríveis;
Horário Semi-Flexível (8 horas/dia de segunda à sexta);
Plano de Saúde e Odontológico (Bradesco Top Nacional);
Vale Refeição e/ou Vale Alimentação (R$30,00/dia);
Vale Transporte;
Language Center: idiomas dentro do EBANX;
EBANX Education: bolsa de até R$400,00/mês;
EBANX Skills: bolsa de até R$150,00/mês;
Hello Ebanker (é um programa com especializado e com orientação de profissionais das áreas: psicologia, finanças e jurídico);
Programa de performance WAVES;
EBANX Play: Incentivo ao esporte e bem estar (gympass, SESC, corridas de rua);
Espaço Zen para massagem 2x por mês;
Blue Club: Clube de desconto exclusivo para ebankers. Nele você encontra desconto em padarias, restaurantes, cursos, loja de eletrônicos e muito mais! 

## Como aplicar
https://carreiras.ebanx.com/#/job/fk0j3zn
## Contato
debora.kretzer@ebanx.com / luis.santos@ebanx.com

**Comment by ezefranca** [comment]
@fernandocruz na falta de uma tag Especialista usei a Sênior.
