### ISSUE TITLE
[RJ - Barra da Tijuca] Ubook - Desenvolver iOS Pleno

### ISSUE THREAD

**Issue by rafsouzap** [CocoaHeadsBrasil/vagas#651]
## Empresa
Somos uma empresa brasileira de streaming de audiobooks, ebooks, podcasts, jornais e revistas, com uma base de 6 milhões de usuários registrados e mais de 15 mil títulos no catálogo, estamos crescendo em um ritmo forte e acelerado, assumindo desafios cada vez maiores, expandindo nossos serviços para mais países da América Latina e Europa.

## Descrição da vaga
Estamos em busca de desenvolvedor iOS para se juntar ao nosso time de mobile e nos ajudar a construir apps incríveis, que tenha vontade de fazer parte de uma empresa que está mudando o mundo com suas novas tecnologias.

## Posição
Pleno

## Tipo de contratação
CLT - Presencial

###### Obrigatórios
* Conhecimento pleno da plataforma iOS e suas APIs
* Conhecimento pleno da linguagem Swift
* Conhecimento pleno da IDE Xcode
* Conhecimento sobre SQLite e JSON
* Conhecimento sobre Git
* Elaborar código limpo e com estrutura legível (clean code)

## Benefícios
* Salário e benefícios compatíveis com o mercado

## Como aplicar
Para se candidatar, envie seu currículo para o e-mail [vagas.ti@ubook.com](mailto:vagas.ti@ubook.com), mencionando no assunto o nome da vaga: Vaga - Dev iOS.

**Comment by thallesmarchetti** [comment]
Aceitam para Jr??

**Comment by FoxPB** [comment]
Faço a mesma pergunta aceitam Jr?

**Comment by rafsouzap** [comment]
@thallesmarchetti @FoxPB no momento a vaga é para Pleno, entretanto, fiquem à vontade para enviar o CV, que o time certamente pode avaliar.
