### ISSUE TITLE
[RJ - Centro] Radix Engenharia e Software - Programador iOS

### ISSUE THREAD

**Issue by thacilima** [CocoaHeadsBrasil/vagas#66]
## Empresa

A Radix é uma empresa de engenharia e desenvolvimento de software, 100% nacional, que oferece serviços e soluções de tecnologia, altamente qualificados e com independência tecnológica, para atender as principais indústrias de processo do Brasil e do mundo. Seu nome vem do latim e significa raíz, origem.
A empresa chegou ao mercado em abril de 2010 e tem sua essência enraizada na firme convicção de que é possível desenvolver tecnologia no Brasil, confiando e investindo no enorme potencial técnico e humano desenvolvido em universidades e centros tecnológicos presentes em todo o país.
A Radix acredita ser multiplicadora de um processo de transformação do Brasil. Um processo de construção de um país com mais tecnologia, resultados, universidades e empresas fortes, e com mais fornecedores desenvolvidos e capacitados. Para isso, a Radix conta com um time de gerentes e consultores multidisciplinares, com mais de 25 anos de experiência em projetos de Engenharia, Automação & TI Industrial e Desenvolvimento de Software.
## Descrição da vaga

Para esta vaga candidato irá participar da construção de aplicativos mobile para diversos clientes. A participação nos projetos é ativa, com liberdade para participar da identificação de problemas e da proposição das suas soluções. Se você procura um ambiente desafiador, seu lugar é aqui!
## Posição

Programador iOS.
## Tipo de contratação

CLT - Presencial Rio de Janeiro (Centro).
###### Obrigatórios
- Conhecimentos em Swift, Xib/Storyboards, Auto Layout e integração com webservices.
###### Diferenciais

- Aplicativos publicados na lojas.
- Conhecimentos em:
  - Android
  - GIT
  - SVN
  - Framework Realm
## Benefícios

Plano de Saúde e Odontológico Amil; Vale Transporte; Vale Refeição (R$30 por dia trabalhado) e outros.
## Como aplicar

Envie o seu currículo para rh@radixeng.com.br.
## Contato

 rh@radixeng.com.br.

**Comment by reprotector** [comment]
@thacilima Já fecharam a vaga? Podemos fechar a issue?

**Comment by thacilima** [comment]
Está em aberto sim.

**Comment by reprotector** [comment]
@thacilima A vaga ainda está aberta ou posso fechar a issue?
