### ISSUE TITLE
[PR - Curitiba] Deal - Desenvolvedor C++

### ISSUE THREAD

**Issue by Ednaalves** [CocoaHeadsBrasil/vagas#666]
## Deal
Fundada em 2004, somos uma empresa multinacional brasileira especializada em Transformação Digital, Consultoria e Desenvolvimento de Projetos e Esteiras Ágeis, com Lean, DevOps e arquitetura escalável em microserviços, Kubernets, ElasticSearch. Soluções em BI e BigData. E Laboratórios de Tecnologia em IoT, Machine Learning e Inteligência Artificial. Presente nos principais mercados da economia brasileira e no mercado internacional, operamos no modelo de empresa de consultoria focada no crescimento dos negócios dos nossos clientes.

## Descrição da vaga
Buscamos um Desenvolvedor C++ para nos ajudar no desenvolvimento de sistemas e produtos.

## Posição
Pleno

## Tipo de contratação
Contratação CLT

## Requisitos
Possuir experiência com Testes funcionais e unitários   
Experiência com desenvolvimento de componentes de software embarcado para Set-Top-Box 
Integração com plataformas de IPTV   
Identificação de bugs em software embarcado para Set-Top-Box          
Identificar e desenvolver novas funcionalidades visando facilitar a manutenção e melhorar a qualidade do produto;" 

## Skill        
Possuir experiência com C/C++ em ambiente GNU/Linux            
Experiência com Versionamento de código com Git       
Experiência com Redes TCP/IP 
Experiência com Linguagens de script (python, shell, perl)          
Conhecimento em ferramentas de Debug e otimização             

## Requisitos Desejáveis: 
Conhecimento em TV digital, IPTV e DVB
Biblioteca QT
Programação em ambiente web (HTML, CSS, JavaScript)
Metodologias ágeis"

## Benefícios
Salário a combinar + plano de saúde, plano odontológico, vale refeição e/ou alimentação (R$422,00).

## Como aplicar
Para se candidatar envie seu currículo para edna.alves@deal.com.br

## Contato
41 99238-7805(whatsapp)

**Comment by marcelofabri** [comment]
@Ednaalves esse espaço é para vagas relacionadas ao ecossistema Apple.

**Comment by iurichiba** [comment]
C++ no grupo de iOS/MacOS. Justo ser #666.
