### ISSUE TITLE
[SP - Berrini] Empresa Infosys - Desenvolvedor Mobile iOS (Swift) e Android - Sênior 

### ISSUE THREAD

**Issue by ilkinha** [CocoaHeadsBrasil/vagas#69]
## Empresa

Infosys Technologies Limited é uma empresa em expansão do segmento de TI e Outsourcing, com sede em Bangalore, na Índia. A Infosys é uma empresa multicultural, com mais de 180.000 colaboradores de 88 nacionalidades. Operações em 76 cidades de 33 países em todo o mundo.
Em outubro de 2009, a Infosys iniciou suas operações no Brasil, com sua sede localizada em Nova Lima/MG e operações em São Paulo, Araraquara e Rio de Janeiro. 
## Descrição da vaga

Vaga para um dos maiores projetos da companhia
## Posição

Sênior
## Tipo de contratação

Presencial 
Escritório São Paulo - Vila Olímpia/Berrini
## Requisitos

Obrigatório possuir Graduação completa, inglês avançado e experiência com desenvolvimento iOS (Swift) e Android
## Contato

Por favor, envie um email para ilka.nakazawa@infosys.com com seu CV anexado 
 E-mail: ilka.nakazawa@infosys.com e telefone (11) 3198-4408

**Comment by reprotector** [comment]
@ilkinha Já fecharam a vaga? Podemos fechar a issue?

**Comment by ilkinha** [comment]
Oi Renan,

Fechamos sim, podem fechar.

Obrigada!
Ilka
