### ISSUE TITLE
[São Paulo - SP] Especialista em Sistemas na Foco em Você

### ISSUE THREAD

**Issue by GabrielyLopesG** [CocoaHeadsBrasil/vagas#694]
## Empresa
 A Foco em Você é uma consultoria voltada para área da tecnologia. Atuando no mercado há 7 anos com clientes de grande porte.

## Descrição da vaga
Experiência com desenvolvimento em Python, APIs REST, métricas de infraestrutura, administração de logs, sistema operacional Linux, AWS, Jenkins e GIT 21.

# Local
Pinheiros - Sp

## Posição
Pleno/Sênior

## Tipo de contratação
Presencial, PJ

## Como se candidatar 
Enviar currículo atualizado com o assunto "Especialista de Sistemas - GitHub" rh@focoemvoce.com.br ou gabriely@focoemvoce.com.br.

# Labels
- PJ
- Presencial
- Pleno
- Sênior
- Alocado

**Comment by marcelofabri** [comment]
@GabrielyLopesG esse espaço é para vagas relacionadas ao ecossistema Apple
