### ISSUE TITLE
[SP - Consolação] Evino - Desenvolvedor iOS

### ISSUE THREAD

**Issue by vbrittes** [CocoaHeadsBrasil/vagas#697]
## Evino
Somos uma empresa que nasceu na safra de 2013, ano em que um pequeno time resolveu realizar um grande sonho: compartilhar a paixão por vinho com o maior número possível de pessoas e inserir a bebida no dia a dia dos brasileiros.

Em 6 anos de evolução, o time ficou mais encorpado e hoje somos mais de 200 Eviners divididos entre a matriz, que fica em São Paulo, e nosso centro de distribuição, no Espírito Santo.

Além de amantes do vinho, somos apaixonados por qualidade de vida e, por isso, prezamos por uma empresa feita por todos, em um ambiente leve, divertido e de hierarquia horizontal - afinal, autonomia e senso de dono são premissas das quais não abrimos mão.

O que nos ajuda a levar o melhor do mundo do vinho para a vida das pessoas? Sermos a maior importadora de França e Itália, termos o melhor app de vinhos da atualidade e, é claro, um portfólio que faz qualquer pessoa querer brindar #SemDemora.

Se você curte descobertas, inovação, desafios, mix de culturas e o principal, vinho, a Evino é o lugar certo para você.

Estamos aqui para quebrar barreiras e levar o vinho para o dia a dia de todos os brasileiros, #SemTabus. 

Eaí, topa ir nessa missão com a gente?

## Descrição da vaga
Como Desenvolvedor iOS, você vai:

- Trabalhar em uma empresa que tem uma visão Mobile First;
- Ter a oportunidade de propor ideias e inovar em um time colaborativo e participativo tanto nas decisões do negócio quanto de tecnologia;
- Cuidar do App que já existe mas pensando sempre no próximo passo, focado em melhorar e inovar sempre;
- Solucionar problemas aliado a um pensamento estruturado em processos; 
- Desenvolver aplicações nativas iOS, valorizando a excelência na experiência do usuário, sempre;

## Posição
Jr/Pl/Sr

## Tipo de contratação
 Presencial CLT

###### Obrigatórios
- Compartilhe paixão por tecnologia e desenvolvimento de software, com atenção a um código limpo, conciso e saudável;
- Abrace a mudança e inovação;
- Tenha experiência em publicação de apps na AppStore;
- Tenha conhecimento em Swift;
- Reconheça especificações de UI/UX nativo;
- Tenha experiência no uso de Web Services;
- Entenda estrutura de dados e quando aplicá-las;
- Conheça boas práticas de desenvolvimento;
- Tenha vivência com no mínimo uma metodologia ágil (Scrum, Kanban, XP);
- Use ferramentas analíticas para acompanhar o comportamento do App.

###### Desejáveis
- Familiarizado com boas práticas de teste;
- Utilizado ferramentas de depuração do XCode;
- Trabalhado com apps de e-commerce/varejoo;
- Publicado um ou mais Apps na AppStore;
- Trabalhado com Apps com alto volume de acessos.

## Benefícios
- Espaço para criar e colaborar com a área, imprimindo o seu jeito de ser e conhecimentos que deram certo em outros lugares;
- Cultura de crescimento e muita aprendizagem;
- Benefícios como Vale-transporte, Vale-refeição/Alimentação, Assistência Médica e Odontológica, GymPass, Sesc, Convênio Farmácia, Alimand, Cupons de desconto eviners, Clube de descontos em diversos itens, frutas no escritório;
- Flexibilidade de horários;
- No dress code! Aqui você pode ser quem você é, e vir trabalhar como se sentir à vontade;
- Ambiente descontraído e divertido;
- E sim! Você pode tomar vinho enquanto trabalha!

## Como aplicar
https://evino.gupy.io/jobs/81344

## Contato
victor.brittes@evino.com.br

**Comment by AdautoP** [comment]
Possibilidade de remoto ou apenas presencial?

**Comment by vbrittes** [comment]
@AdautoP apenas presencial. Mas somos bem flexíveis com relação a Home Office (:
