### ISSUE TITLE
Desenvolvedor IOS 

### ISSUE THREAD

**Issue by 1657** [CocoaHeadsBrasil/vagas#698]
Share RH
Somos uma consultoria especializada em recrutamento e seleção, e trabalhamos com posições para diversos clientes.

Descrição da vaga
Atuar com desenvolvimento IOS, alocado em uma grande banco, atuando como referência técnica prezando pela qualidade da entrega. O cliente fica em Campinas.

Pleno.

Posição Presencial, CLT.

Requisitos

Obrigatórios:
Formação em Ciências da Computação, Análise de Sistemas, Tecnologia da Informação e afins;
Experiência com MVVM, MVP ou MVC;
Experiência com Swift.

Desejáveis:
Experiência com Teste Unitário;
Experiência com CI/CD.

Diferenciais:
Objective-C;
Experiência com metodologia ágil (Scrum e Kanban).

Benefícios:
Vale refeição;
Vale alimentação;
Assistência médica Sulamérica;
Gympass;
Reembolso de 100% para certificações;
PLR podendo chegar a dois salários.

Como aplicar:
Primeiro temos uma entrevista com o Dennis da Sharerh, e depois uma entrevista direta com o cliente.

Contato:
Interessados por gentileza encaminhar CV para: ts@sharerh.com

**Comment by marcelofabri** [comment]
@1657 É necessário divulgar o nome da empresa: https://github.com/CocoaHeadsBrasil/vagas#todas-as-vagas-devem-conter-o-nome-da-empresa-que-está-contratando.

**Comment by 1657** [comment]
Entendi me desculpe acabei esquecendo, posso repostar com o nome da empresa?

**Comment by 1657** [comment]
E uma dúvida, você conhece algum grupo aqui no GitHub, de vagas de Java?

**Comment by marcelofabri** [comment]
> Entendi me desculpe acabei esquecendo, posso repostar com o nome da empresa?

Sim
