### ISSUE TITLE
[Campinas - SP] Oportunidade iOS

### ISSUE THREAD

**Issue by Anatalent** [CocoaHeadsBrasil/vagas#7]
Responsabilidades
• Design e criação de aplicações para iOS
• Garantir a performance, qualidade e responsividade das aplicações
• Colaborar com o time para definir, desenvolver e entregar novas funcionalidades
• Identificar e corrigir gargalos e bugs nas aplicações
• Ajuda para manter organização e qualidade do código

Skills
• Proficiência em Swift e um bom conhecimento de seus ecossistemas
• Sólidos conhecimentos de programação orientada a objetos
• Conhecimento de gerenciamento de memória e multi-threading
• Conhecimento de bancos de dados embarcados e outros sistemas de armazenamento de dados
• Familiaridade com API’s RESTfull e conexão com serviços no back-end
• Conhecimento dos princípios Apple de design e guidelines de interface

Campinas-SP
Interessados enviar cvs com pretensão salarial para: recrutamento@talentreplacement.com.br

**Comment by barbosa** [comment]
Olá @Anatalent, tudo bem?

A vaga ainda está aberta? Só para saber se fechamos a issue ou mantemos aberta.

Obrigado!

**Comment by Anatalent** [comment]
Olá,

 

Já foi concluída a vaga.

 

De: Gustavo Barbosa [mailto:notifications@github.com] 
Enviada em: quinta-feira, 31 de março de 2016 12:07
Para: CocoaHeadsBrasil/vagas
Cc: Anatalent
Assunto: Re: [CocoaHeadsBrasil/vagas] [Campinas - SP] Oportunidade iOS (#7)

 

Olá @Anatalent <https://github.com/Anatalent> , tudo bem?

A vaga ainda está aberta? Só para saber se fechamos a issue ou mantemos aberta.

Obrigado!

—
You are receiving this because you were mentioned.
Reply to this email directly or  <https://github.com/CocoaHeadsBrasil/vagas/issues/7#issuecomment-203979069> view it on GitHub  <https://github.com/notifications/beacon/AQ4rDgw9BLdfyLy2W72-thoDi73g4n2bks5py-MhgaJpZM4Hq2pD.gif> 

Nenhum vírus encontrado nessa mensagem.
Verificado por AVG - www.avgbrasil.com.br
Versão: 2016.0.7497 / Banco de dados de vírus: 4545/11926 - Data de Lançamento: 03/31/16
