### ISSUE TITLE
Desenvolvedor Android - Rio de Janeiro

### ISSUE THREAD

**Issue by ubook-dev** [CocoaHeadsBrasil/vagas#716]
## Empresa
A maior plataforma de audiotainment da América Latina, acelerando sua expansão internacional, está à procura de um profissional para atuar no time de DESENVOLVIMENTO da UBOOK, que tenha vontade de fazer parte da empresa que está mudando o mundo com suas novas tecnologias.

## Descrição da vaga
Desenvolvimento mobile Android. 

## Posição
Pleno, Sênior, Ninja, Samurai, Espadachim ou Paladino

## Tipo de contratação
Presencial / CLT ou PJ.

## Requisitos
Precisamos que você conheça sobre Java, Kotlin, Android Studio, SQLite, JSON, Git e que desenvolva um código limpo e saudável.

## Benefícios
Oferecemos salário compatível com o mercado e benefícios super bacanas como, Plano de Saúde Sul América (quarto particular) pago pela empresa, VR, VA, frutas todos os dias, parcerias com desconto.

## Como aplicar
Se você possui estas características, entre em contato conosco enviando seu CV para rh@ubook.com e nos ajude a mudar o mundo também.

**Comment by Bunn** [comment]
@ubook-dev esse espaço é para vagas relacionadas ao ecossistema Apple
