### ISSUE TITLE
[SP - Vila Olimpia] Easynvest - Pessoa Desenvolvedora iOS

### ISSUE THREAD

**Issue by Lcsmarcal** [CocoaHeadsBrasil/vagas#717]
Nós da Easynvest estamos despertando o poder de investir no Brasil inteiro, revolucionando o mercado financeiro e promovendo a educação financeira para os quatro cantos do país. Tudo isso através de uma experiência online e que inova a cada dia!

O que nós, Easylovers, acreditamos?
• Sermos autênticos por onde passarmos; 
• Errar rápido e aprender rápido, de forma descomplicada e independente para trazer maior valor para o cliente; 
• Encarar os desafios com coragem e embasamento;

 Ah! Uma curiosidade sobre a gente: nossa credibilidade vem sendo construída há mais de 5 décadas. Em toda a nossa história a transformação digital e cultural está presente e isso é motivo de muito orgulho para nós.

Na Easynvest, somos acessíveis e inclusivos em tudo que fazemos. Isso se traduz em oportunidades iguais e diversidade de gênero, de etnia, de religião, de orientação sexual, de identidade de gênero, de origem, de idade e de pessoas com deficiência na hora de contratar. Se você quer contribuir para um ambiente com pluralidade e respeito, #JunteSeANós

Se você se identifica com o nosso jeito de ser e quer ajudar a despertar a cultura de investimentos no Brasil, queremos te conhecer!

O Desenvolvedor iOS 
• Buscamos alguém que seja apaixonado por desafios e tecnologia para integrar nossa equipe de desenvolvedores.Responsabilidades
• Você será responsável pelo desenvolvimento de um aplicativo nativo da Easynvest, tomando decisões sobre a arquitetura do mesmo. 
• É muito importante o monitoramento de métricas e da qualidade de todo projeto, bem como o auxílio dos demais membros da equipe.Qualificações 
• Swift 
• Padrões de projetos (MVVM) 
• Padrões de arquitetura 
• Desenvolvimento de testes (XCTest e OHHTTPStubs) 
• Integração ContínuaPara apoiar os Easylovers nessa jornada, temos:

• Salário compatível com mercado, com revisões feitas anualmente 
• Sem Dress Code: venha como se sente bem! 
• Ambiente descontraído, diverso e inclusivo 
• Day off no mês de aniversário 
• Flexibilidade de horário 
• Gympass 
• Plano de saúde e odontológico do Bradesco (sem coparticipação) 
• Auxílio creche (R$ 300,00 - para filhos até 5 anos) 
• Vale refeição (R$ 682,00) e Vale alimentação (R$ 460,00) 
• Vale transporte 
• Subsídio para pós-graduação e cursos/treinamentos (de acordo com política interna) 
• PPR – participação por resultados 
• Frutas frescas todos os dias

Candidate-se no:
[Linkedin](https://www.linkedin.com/jobs/view/pessoa-desenvolvedora-ios-at-easynvest-1545124073/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic&originalSubdomain=br)
[Glassdoor](https://www.glassdoor.com.br/job-listing/pessoa-desenvolvedora-ios-easynvest-JV_IC2479061_KO0,25_KE26,35.htm?jl=3316924413&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic)

**Comment by danilorequena** [comment]
Bom dia, em ambos os links, está como a vaga não aceita mais inscrições
