### ISSUE TITLE
[Belo Horizonte/MG] Sympla - Desenvolvedor iOS Sênior/Pleno

### ISSUE THREAD

**Issue by naroga** [CocoaHeadsBrasil/vagas#72]
## Sympla

A Sympla é uma startup sediada em Belo Horizonte que, em menos de três anos de existência, se tornou a plataforma de eventos mais utilizada no Brasil e possui o site com o maior número de eventos à venda no país. 

Com o objetivo de simplificar e otimizar a criação e gestão de eventos para produtores e melhorar a experiência da compra de ingressos online pelos participantes, oferecemos diversas ferramentas eficazes e soluções inteligentes para todas as etapas de um evento. Aqui, você poderá participar da expansão de uma startup jovem e que já é referência no mercado online ticketing no país. 

Encara o desafio?
## Descrição da vaga

Funções desta posição:
- Desenvolver novos aplicativos e novas funcionalidades para os aplicativos iOS da Sympla;
- Garantir a melhor experiência de usuário em todas as funcionalidades desenvolvidas;
- Atuar para resolver problemas complexos de desempenho e desafios de arquitetura;
- Identificar e resolver potenciais gargalos de desempenho do sistema.
## Posição

Desenvolvedor iOS Pleno/**Sênior**
## Tipo de contratação

Presencial, Belo Horizonte, CLT.
## Requisitos
- A partir de 3 anos de experiência com desenvolvimento mobile especificamente para a plataforma iOS;
- Compreender os princípios fundamentais de design para uma aplicação escalável;
- Ter familiaridade com os desafios de desenvolvimento mobile e suas soluções;
- Ter familiaridade com bancos de dados SQL / NoSQL;
- Capacidade de priorizar o seu próprio trabalho a partir das linhas gerais definidas pela equipe e a partir de feedbacks recebidos dos usuários finais;
- Ser flexível, independente e responsável;
- Ser curioso, com muita vontade de experimentar e aprender coisas novas;
- Ter senso de organização, atenção a detalhes e foco;
- Conhecer os conceitos de startup;
- Must rock!
## Benefícios
- Horário Flexível
- Ambiente criativo, inovador e estimulante;
- Regime de contratação CLT;
- Salário compatível com o mercado, VT e VR;
- No dress code (pode trabalhar de bermuda, chinelo, etc);
- Clima descontraído;
- Café, bebidas variadas e snacks.
## Como aplicar

Basta preencher as informações no [nosso site](http://www.sympla.com.br/trabalhe-conosco#job-9499)!

![Our team](http://d1gkntzr8mxq7s.cloudfront.net/57b5d36738797.png)

**Comment by reprotector** [comment]
@naroga Já fecharam a vaga? Podemos fechar a issue?

**Comment by naroga** [comment]
@reprotector A vaga é perene, não estamos procurando um número específico de DEVs, vamos contratar quantos bons devs apareçam que sejam aprovados na seleção. Pode deixar aberto. Se mudarmos a estratégia e fecharmos a vaga, eu comunico aqui.

**Comment by reprotector** [comment]
@naroga A vaga ainda está aberta ou posso fechar a issue?

**Comment by naroga** [comment]
@reprotector Ainda está aberta.

**Comment by Viniciuscarvalho** [comment]
A vaga ainda está aberta @naroga ?

**Comment by naroga** [comment]
@Viniciuscarvalho: rapaz, não sei informar. Não estou mais na equipe. Pode fechar o issue que eu comunico o pessoal lá pra reabrir, caso seja relevante.

Valeu.

**Comment by Viniciuscarvalho** [comment]
Show!
