### ISSUE TITLE
[SP-Pinheiros] Desenvolvedor IOS 

### ISSUE THREAD

**Issue by gabrielylopes** [CocoaHeadsBrasil/vagas#722]
## Descrição da vaga
A foco em você está buscando por Desenvolvedor IOS:
Experiência com aplicativos em IOS nativo (Objective C), GIT, atuar com diferentes dimensões de dispositivos (Tablet, celular e afins), testes, code-review, integração continua, Bluetooth API, Scrum/Kanban.

## Posição
 Pleno e Sênior.

## Tipo de contratação
Presencial - PJ

## Como aplicar
Triagem de currículo => aprovação => entrevista na empresa. 

## Contato
Envie seu cv atualizado para gabriely@focoemvoce.com.br com o assunto "Desenvolvedor IOS - GitHub".

## Labels 
-PJ
-Presencial
-Pleno
-Sênior

**Comment by ezefranca** [comment]
@gabrielylopes  Poderia adicionar o nome da empresa no título e descrição.
