### ISSUE TITLE
[Curitiba, PR] Desenvolvedor iOS Pleno/Sênior - TCS

### ISSUE THREAD

**Issue by AutomTech** [CocoaHeadsBrasil/vagas#725]
## Empresa
Segmento bancário.

## Descrição da vaga
Desenvolvimento de aplicativos mobile para banco digital.

## Posição
iOS Pleno/Sênior 

## Tipo de contratação
CLT

###### Obrigatórios
Experiência em desenvolvimento swift.

###### Desejáveis
Conhecimento em ViewCode.

###### Diferenciais
Conhecimento em RxSwift.

## Benefícios
Seguro Saúde e odontológico com co-participação, extensível aos familiares
PLR do sindicato do Paraná
Seguro de vida
Vale alientação ou refeição no valor de R$ 484,00
Auxilio creche
Conveio com o SESC

## Como aplicar
Enviar CV para o e-mail trabalheconosco@automtech.com.br

## Contato
(41) 988078687.

**Comment by cocuroci** [comment]
Qual o banco?

**Comment by Bunn** [comment]
@AutomTech Qual o nome da empresa? Conforme as regras, todas as as vagas devem ter o nome da empresa contratante.
Se você é um recrutador, você deve identificar o nome da empresa em que o candidato irá trabalhar

**Comment by AutomTech** [comment]
Para TCS pessoal
