### ISSUE TITLE
[Florianópolis] Socialbase - iOS Developer

### ISSUE THREAD

**Issue by ostanik** [CocoaHeadsBrasil/vagas#73]
## A Socialbase

SocialBase é uma empresa jovem, com espírito cooperativo e nossa plataforma destina-se a mudar a forma como as empresas se comunicam, criando conexões positivas entre os colaboradores internos. Nosso produto contribui para construção de uma Cultura mais Colaborativa, armazenamos arquivos, mensagem e conversas entre colaboradores em uma única ferramenta. Nossa meta é proporcionar a melhor experiência em comunicação interna para as empresas !
## Descrição da vaga

Você fará parte do time de soluções mobile da plataforma SocialBase, participando das definições arquiteturais, manutenção e criação novos aplicativos com características de alta disponibilidade, confiabilidade e comunicação em tempo real.
###### Atividades
- Análise,
- Arquitetura e desenvolvimento de sistemas mobile iOS;
- Integração com outros produtos e plataformas;
- Pesquisa e desenvolvimento de novas tecnologias.
## Posição

Pleno
## Tipo de contratação

Presencial - CLT
###### Obrigatórios
- Conhecimento em Objective-C e Swift;
- Conhecimento com Core Data e AFNetwork;
- Gerenciamento de dependências com o Cocoa Pods;
- Conhecimento com Auto Layout e Story Board;
- Experiência na Apple Store em publicação de aplicativos;
- Experiência com push notifications;
###### Desejáveis
- No mínimo 3 anos de experiência com desenvolvimento iOS;
- Experiência com Build Automatizado (Fastlane);
- Conhecimento com teste unitário é um plus;
- Ter algum projeto ou contribuição no Github;
- Formação completa ou cursando (Ciência da computação, Sistemas de informação e áreas afins)
###### Você precisa ser
- Criativo, ágil, disciplinado e organizado;
- Curioso;
- Crítico em relação a ferramentas utilizadas, com o objetivo de melhorar o desenvolvimento;
- Pesquisador nas horas vagas, trazendo novidades que podem ser realmente aplicadas nos  projetos;
- Ser engajado e ter bom relacionamento com a equipe;
## Benefícios
- Oportunidade para experimentar novos desafios;
- Vale-refeição expressivo;
- Horário flexível;
- Plano de saúde sem coparticipação;
- Café, capuccino e mocaccino pra manter níveis adequados de cafeína;
- Frutas, lanches e laboral pra manter a mente sã;
- Happy Hour toda semana;
  Muito teamwork!
## Como aplicar

[workable
](https://socialbase.workable.com/jobs/175272)
## Contato

[Site](http://www.socialbase.com.br/carreiras#inicio)

**Comment by reprotector** [comment]
@ostanik Já fecharam a vaga? Podemos fechar a issue?

**Comment by ostanik** [comment]
@reprotector acho que já pode fechar 👍
