### ISSUE TITLE
[Freelancer | Remoto | SP] - Desenvolvedor iOS

### ISSUE THREAD

**Issue by rapholivera** [CocoaHeadsBrasil/vagas#731]
![Platform][ios-platform] ![Language][lang-image] ![remote-image]

## Empresa
**Videvince Ventures**

## Descrição da vaga
Olá, trabalho em uma Venture Building, temos um app já em produção com target no exterior e passaremos por um processo de migração de api;

Não envolvem atividades muito complexas, porém precisamos de mão de obra, de uma pessoa ágil e com conhecimento em `Swift` e `NSCoding`.

**IMPORTANTE** dizer também que a migração tem grande chance de se estender durante as festas de finais de ano. Não quer dizer que vá precisar de esforço no dia 24/25 e dia 31/01, Mas se você for viajar e tiver dias indisponíveis nesses período, por favor, comunique no email também para podermos avaliar a contratação de mais pessoas.

## Posição
Desenvolvedor Junior/Pleno - Freelancer

## Como aplicar
Preciso que você mande um e-mail com:
* Valor/hora;
* Disponibilidade de horas semanais;
* Disponibilidade de início;
* Dias indisponíveis até o começo de 2020;
* Apps que já trabalhou;
**Mande p/** Raphael Oliveira rso@videvince.com

[ios-platform]: https://img.shields.io/badge/platform-iOS-informational.svg
[lang-image]: https://img.shields.io/badge/language-swift-success.svg
[remote-image]:https://img.shields.io/static/v1?label=remote&message=Freelancer&color=orange

**Comment by frankdiogo** [comment]
não estou conseguindo enviar as informações para o e-mail informado: rso@videvince.com

**Comment by xReee** [comment]
@frankdiogo  `rso@videvince.com`
