### ISSUE TITLE
[Florianópolis - SC] Cheesecake Labs - iOS Developer

### ISSUE THREAD

**Issue by gracietti** [CocoaHeadsBrasil/vagas#74]
## Opening Description

We are looking for an iOS Developer in Florianópolis/SC area who is interested in working with our projects in partnership with **Silicon Valley**, joining international and multidisciplinary teams.

## Location

Very cool office / Florianopolis - SC
![office](https://www.ckl.io/wp-content/themes/cheesecake_labs/images/ckl/career7@2x.jpg)
## Benefits
- stock options
- above average salary
- flexible working time
- geek culture
- video games
- 24/7 snacks (really great stuff!!)
- yoga classes
- english classes
- beers and a unique work environment
  ![benefits](https://s3.amazonaws.com/ckl-website-static/wp-content/uploads/2016/10/we-offer.png)
## Requirements

**Required Skills:**
- Fluent English (+ knowledge of technical terms);
- Proficiency in iOS (native development);
- Proficiency in git;

**Differentials:**
- Experience with CoreData;
- Experience with CocoaPods;
- Acquaintance with open-source libraries;
- Advanced knowledge of iOS' Interface Guidelines;
- Open-source contributions (GitHub libraries);
- Development of personal projects;
- Published apps at App Store;
## Contract Type

CLT

## How to Apply

 [APPLY HERE](https://www.ckl.io/careers/)

## About Us

Cheesecake Labs is a full-stack mobile app development company headquartered in Florianópolis - Brazil, but with a **solid integration with the Silicon Valley**, in the US. We make partnership with startups with great disruption potential - and we develop mobile solutions for them.

![home](https://s3.amazonaws.com/ckl-website-static/wp-content/uploads/2016/10/ckl-home.png)

**Comment by reprotector** [comment]
@gracietti Já fecharam a vaga? Podemos fechar a issue?

**Comment by gracietti** [comment]
Opa! Ainda não @reprotector . A vaga continua em aberto.

**Comment by gracietti** [comment]
@marcelofabri , poderias por favor remover a Label de Senior?

**Comment by reprotector** [comment]
@gracietti A vaga ainda está aberta ou posso fechar a issue?

**Comment by gracietti** [comment]
Opa @reprotector . A vaga continua em aberto.
