### ISSUE TITLE
[ SP - Brooklyn / Vila Cordeiro ] Work & Co - Desenvolvedor iOS - todos os níveis

### ISSUE THREAD

**Issue by marceloatwork** [CocoaHeadsBrasil/vagas#75]
## Empresa

[Work & Co](http://work.co) : Empresa dos Estados Unidos começando sua presença em São Paulo. Estamos no nosso terceiro ano de vida e já contamos com 176 pessoas em 3 países. 
Nossa cultura é pautada na meritocracia, respeito e principalmente na mão na massa. 

Nosso foco é a criação  e o  desenvolvemos produtos digitais para as maiores empresas do mundo. Não trabalhamos como produto de Agências. Somos independentes. Não somos uma Agência, não fazemos nenhum tipo de Marketing ou Social Media, apenas produtos.

Estamos organizados em somente 3 áreas: Estratégia, Design e Tecnologia, com pesos iguais.

Clientes Globais: Virgin America, Google, Facebook, Apple, Epic Games, Nike, Youtube...
Clientes no Brasil: Vivo, Santander, Descomplica, Oi

Case da Virgin America: [VA Case](https://work.co/virgin-america/)
Nossa perspective em desenvolvimento de apps: [The Next Web: the app that makes flying fun again/](http://thenextweb.com/insider/2016/09/29/the-app-that-makes-flying-fun-again/)
## Descrição da vaga

Buscamos desenvolvedores iOS ( E Android, caso queira indicar conhecidos ) de todos os níveis de experiência para projeto de larga escala com a Vivo no Brasil. 
## Posição

Todos os níveis, com vagas para : Leads, Seniors, Mid e Juniors
## Tipo de contratação

CLT Presencial
## Requisitos

Proporcionais e realistas de acordo com o nível que se encaixa:
Procuramos Desenvolvedores interessados em trabalhar em produtos usados por milhares de pessoas; Que possuam facilidade de trabalhar em equipes multidisciplinares : Designers, QAs, PMs. 
### Conhecimento Técnico:

Não ligamos para anos de experiência, ligamos para tipos de problemas que você já resolveu. Com ou sem ajuda, no prazo ou fora dele pois você buscava a melhor solução  possível. 

Isso em mente, excelente fundamentos de iOS e seus principais Frameworks e APIs.
Como temos um foco em experiência do usuário, conhecimentos que são relevantes para a interface de usuário  são um grandes plus.
###### Obrigatórios

Vontade de fazer o melhor trabalho possível
Excelente familiaridade com Objective-C,  Swift
(projeto é primeiramente em Obj-C )
###### Desejáveis

AutoLayout
Cocoapods
Carthage
Git
Apps Publicados
Experiência em otimização ( performance ) 
Inglês Técnico ( leitura ) 
###### Diferenciais

RxSwift
Experiência "Cross-Plataforma" com Android.
Inglês (intermediário ou avançado) não será necessário para o dia a dia, mas abre muitas portas na empresa.
## Benefícios

Plano de Saúde  e Dental
VR
## Como aplicar

Entre em contato, compartilhe o máximo de código que puder. É muito mais importante que CV. Mesmo que seja de um pequeno projeto pessoal. Estamos interessados em como você aborda um problema, como organiza suas idéias e sua implementação. 

Caso não possua projetos públicos, 3 alternativas, avise no email de apresentação:
1. Envie classes ou componentes separados do contexto que resolvam um problema e mostrem seu conhecimento na plataforma.
2. Mostre snippets sem contexto dos códigos que possui via screenshare
3. Escolha uma API publica simples como a do [youtube V3](https://developers.google.com/youtube/v3/) e crie um app que liste os videos trending no Brasil, em uma tableview com alguma animação assim que o item entra na parte visível da tela. 

Utilize AutoLayout (requerido) e outros frameworks que achar relevante. Busque demonstrar os conhecimentos que diferenciam ou pelo menos definem claramente seu nível de experiência.

Plus: O video mais proximo do centro da tela começa a tocar caso o usuário não interaja por <x> segundos ( ao seu critério ).
## Contato

Mande email com CV básico + Código ( Github handle ou similar ) para:
eduardo@work.co

**Comment by fernandudouglas** [comment]
Enviei um e-mail em 11/01/2017 para tirar uma dúvida e até o momento não obtive retorno...

**Comment by reprotector** [comment]
@marceloatwork A vaga ainda está aberta?
