### ISSUE TITLE
[PR - Curitiba] AutomTech - Dev. iOS 

### ISSUE THREAD

**Issue by AutomTech** [CocoaHeadsBrasil/vagas#758]
#555  Empresa
Seguimento bancário.

## Descrição da vaga
Desenvolvimento em esteira ágil de aplicativos em iOS utilizando Swift. 

## Posição
 Pleno & Sênior.

## Tipo de contratação
CLT.

###### Obrigatórios
- Experiência em Desenvolvimento Swift;
- Ensino Superior Completo.

###### Desejáveis
- Conhecimento em View Code.

###### Diferenciais
Conhecimento em RxSwift.

## Benefícios
Seguro Saúde e odontológico com co-participação, extensível aos familiares
PLR do sindicato do Paraná
Seguro de vida
Vale alimentação ou refeição no valor de R$ 484,00
Auxilio creche
Conveio com o SESC

## Como aplicar
Enviar CV para trabalheconosco@automtech.com.br ou (41) 988078687.

## Contato
(41) 988078687.

![iOS](https://user-images.githubusercontent.com/57018306/73366351-958b2400-428c-11ea-85c3-fea2fed37c9a.jpg)

**Comment by mbrufatto** [comment]
Pode ser remoto?

**Comment by AutomTech** [comment]
@mbrufatto Essa posição é apenas presencial. Recebemos seu CV no e-mail e já te retornamos. Obrigada!
