### ISSUE TITLE
[RJ - Barra da Tijuca] Homer - Desenvolvedor iOS

### ISSUE THREAD

**Issue by breferrari** [CocoaHeadsBrasil/vagas#77]
## Empresa

Somos uma startup no segmento imobiliário com aplicativo já publicado para [Android](https://play.google.com/store/apps/details?id=com.corretorvip.app.br) e atualmente finalizando a versão iOS para lançamento.

[<img src="http://www.homer.com.br/img/logo_homer_lg.png">](Homer)
## Posição

Estagiário ou CLT.
## Localização

Atualmente estamos localizados em um escritório dentro do Città América, na Barra da Tijuca. Lugar de fácil acesso via BRT, com integração ao Metrô e tudo mais.
## Tipo de contratação

Presencial com horário flexível e possibilidade de trabalho remoto quando necessário.
###### Obrigatórios
- Proficiência em iOS
- Objective-C
###### Desejáveis
- Cocoapods
- Utilização de serviços REST
- Git
###### Diferenciais
- Swift
- Ruby
- Fastlane
- Proficiência em Android
- Ter algum aplicativo publicado
## Como aplicar

Enviar CV ou LinkedIn atualizado para **marcelo@ipanema.ventures** ou para **brenno.ferrari@kroonar.com**.
## Links

[Homer](http://www.homer.com.br/)
[Facebook](https://www.facebook.com/useHomer/)

**Comment by reprotector** [comment]
@breferrari A vaga ainda está aberta? Podemos fechar a issue?

**Comment by breferrari** [comment]
Sim
