### ISSUE TITLE
[Brasil Remoto] X-Team procura por dev iOS com conhecimentos de AWS (e inglês)

### ISSUE THREAD

**Issue by jeanlucaslima** [CocoaHeadsBrasil/vagas#770]
## Empresa
X-Team é uma software house, mas nasceu da vontade e experiência de criar uma comunidade e espaço para programadores se sentirem motivados trabalhando de qualquer lugar do mundo. Não só o bullshit de sempre de que é um lugar bonitinho, mas trazendo coisas na prática como hackerhouses ao redor do mundo e até um grupo de benefícios chamado [Unleash+](https://x-team.com/unleash/) para você gastar com o que te motiva, seja um headphone da hora ou até pagar um jantar pra sua família. 

Respeitamos os programadores porque todos da empresa foram programadores já. E sabemos que a melhor forma de trabalhar é poder trabalhar do seu jeito, de onde você quiser, seja de casa ou seja de um coworking. 

Atendemos hoje empresas como FOX, Sony, Riot Games, Dell, Twitter. Em várias stacks, não só Android :^) 

Alguns YouTubers falando sobre nós: [Filipe Deschamps](https://www.youtube.com/watch?v=0C-_6H4P20E&t=), [Diolinux](https://www.youtube.com/watch?v=1EsQDpynCGE)

## Descrição da vaga
Esta vaga especificamente é para trabalhar em um projeto que utiliza Swift, mas algumas partes do app estão em Obj-C. Também precisa entender e ter prática com AWS, especificamente: S3, Cognito e DynamoDB. 

## Posição
A vaga é para um dev com essa experiência, mas não necessariamente um senior, se você se considera pleno, sinta-se convidado a se inscrever. 

## Tipo de contratação

PJ a combinar, pagamento remoto (via transferwise, transferência bancária ou outros serviços).

###### Obrigatórios

* Obj-C e Swift
* AWS (S3, Cognito, DynamoDB)

## Benefícios
- Salário competitivo
- [Benefícios e reembolsos para te manter motivado, ](https://x-team.com/unleash/) como academia, café, alimentos orgânicos e até jogos.
- Uma comunidade saudável de programadores que se apoiam, comunicam e até viajam juntos

## Como aplicar
Para se inscrever na vaga, basta criar seu perfil [por este link](https://x-team.com/brasil).

## Contato
Em caso de dúvidas pode falar comigo pelo meu [telegram](https://t.me/jeanlima), [twitter](https://twitter.com/aleattorium) ou [linkedin](https://www.linkedin.com/in/jeanlucaslima/).

Ah, no Slack sou iOS Dev BR sou @jean

PS: se você se identifica com uma minoria em programação e acha que talvez não tenha todos os requisitos da vaga, mas tem interesse na X-Team, me manda uma mensagem!

**Comment by silvanando** [comment]
Eu não recomendaria essa empresa. Comecei a fazer o processo com uma pessoa chamada Leonardo Jardim, numa conversa no hangouts. Apesar da má vontade totalmente visivel na hora de conduzir a entrevista (parecia que estava ali obrigado), a conversa foi ok, abrangendo o básico apresentando a empresa e foi apenas isso. O termino da conversa foi ele falando que o próximo passo era conversar com um gestor técnico. Passou 2 semanas e nada, então resolvo mandar uma mensagem no linkedin perguntando se aconteceu algo. Mensagens essas que foram lidas e completamente ignoradas. Também mandei mensagens pra o senhor Jean Lima, que também foram lidas e ignoradas.

Por fim, desisti de participar, entendendo que se uma empresa leva o processo de entrevista desse jeito, não esperaria coisa boa dela.

Fica o feedback público.

**Comment by jeanlucaslima** [comment]
Fechando porque a vaga não está mais aberta, @silvanando onde falou comigo? Não vejo uma mensagem sua no Slack, mas posso estar errado, fora muitas notificações. De qualquer forma quero entrar em contato para entender melhor a situação, entrevistamos várias pessoas no Brasil e mantemos contato com vários brasileiros. Me diz qual a melhor forma de entrar em contato, por favor.

**Comment by jeanlucaslima** [comment]
@ezefranca não sei como lidar com a situação, procurei no Slack e não encontrei uma conversa com "Nando" no histórico e o recrutador também está disponível para explicar algo pessoalmente. É algo que me importo.

**Comment by unnamedd** [comment]
@jeanlucaslima pelo que podemos entender, ele diz ter tido essas conversas através do LinkedIn.

**Comment by jeanlucaslima** [comment]
Se foi Linkedin, não tem ninguém com esse nome no meu histórico dos últimos desde março. E todas as (poucas) conversas foram respondidas. :-/ 

Todas as entrevistas quando chega no estágio de ser chamado pro hangouts é registrado... A pessoa com nome "Nando" aí acima também não tem um registro com a gente, a não ser que tenha criado o perfil com nome falso só para fazer essa "denúncia".
