### ISSUE TITLE
[Campinas - SP] Desenvolvedoras iOS Junior - Anheuser-Busch InBev

### ISSUE THREAD

**Issue by ricardobrg** [CocoaHeadsBrasil/vagas#777]
## Empresa
A Anheuser-Busch InBev é uma empresa multinacional de bebidas e cervejas formada em 2004 pela fusão da belga Interbrew e da brasileira Ambev. Está sediada em Leuven, na Bélgica, e possui escritório global de gerência funcional em Nova York, e sedes regionais em Londres, Cidade do México, Joanesburgo, St.

A Anheuser-Busch InBev (ABInBev) tem uma galera apaixonada por cerveja que são especialistas nas tecnologias mais inovadoras utilizadas no mercado. São mais de 200 fanáticos que formam o Beertech, célula de tecnologia da companhia, localizada atualmente no Escritório Global de Jaguariúna/SP e em nosso headquarter em Nova York.

O intuito desta estrutura é oferecer serviços e soluções digitais para as empresas que pertencem ao Grupo Anheuser-Busch InBev, como por exemplo: Ambev, Labatt Brewing, Cervejaria Modelo, Cervejaria Hondurenha, South African Breweries (SAB) e muitas outras, que juntas formam o maior grupo cervejeiro do mundo.

A junção de profissionais técnicos, estratégicos e com senso de dono trabalhando lado a lado para a entrega de produtos globais auxilia fortemente no impulsionamento e crescimento de negócios locais que vendem um dos produtos mais consumidos e apreciados de todo o mundo, a cerveja.

## Descrição da vaga

A AB-InBev está realizando um programa de capacitação remunerada com execução da ProWay. A contratação será com salário e benefícios desde o início do curso. Os candidatos selecionados serão contratado como CLT já no primeiro dia de curso que terá 3 meses de duração. A capacitação ocorrerá em Campinas e o local de trabalho após o curso será em Jaguariúna (região metropolitana de Campinas).

A primeira turma será de Android e iOS e tem início previsto para abril. As inscrições serão válidas também para as demais turmas que devem ser logo anunciadas.

## Posição
 Programador Júnior

## Tipo de contratação
 CLT

###### Obrigatórios
Trabalho em equipe

###### Desejáveis
Conhecimento básico em programação (qualquer linguagem)

###### Diferenciais
Inglês

## Benefícios
Salário R$ 2.458.62

VR, Gympass, Convênio médico e odontológico, fretado, 14º salário, auxílio material escolar para
dependentes, convênio farmácia

## Maiores informações e inscrições 
http://beertech.proway.com.br

**Comment by leticiafaleia** [comment]
Aceita remoto?
