### ISSUE TITLE
[REMOTO] Invillia - Dev. iOS Sênior 

### ISSUE THREAD

**Issue by GabriellyLeonel** [CocoaHeadsBrasil/vagas#788]
## Empresa
 Nós somos a Invillia,
Somos mais de 400 Invillianos atuando dentro e fora do Brasil, gerando oportunidades todos os dias para clientes potenciais em diversos segmentos e tecnologias. 
Faça uma imersão aqui https://invillia.com/ 

## Descrição da vaga
 Desenvolvimento e manutenção de aplicativos Mobile com foco em ferramentas de 2FA (Segundo Fator de Autenticação). Colaborar com times de desenvolvimento utilizando metodologias agéis. Desenvolver código através da documentação e histórias de usuário. Corrigir defeitos. Executar testes.

## Posição
SÊNIOR

## Tipo de contratação
CLT, REMOTO.

## Requisitos
Swift 4.0+
Basico de objective c
Arquitetura mvvm-c
Coordinator.
Testes unitarios XCTest
Teste UI com KIF
Git
GitFlow
Auto Layout
Trabalhar com .xib
Conhecer criação de componentes
Bitbucket
Metodos Ageis (Scrum/Kanban)
Clean Code.
Integração Rest
Fabric
Pull Request e code review
 
## Benefícios
• Plano de Saúde: Coletivo – Desconto de contribuição mensal de R$21,89 (por pessoa); 
• Plano Odontológico: Desconto de contribuição mensal R$ 16,77 (Titular) R$ 33,54 (dependente); 
• Seguro de vida: Apólice no valor de R$ 100.000,00 (Sem Descontos); 
• Cartão Farmácia: Valor limite de crédito R$ 200,00 (Descontado em folha após 45 dias); 
• Vale alimentação/refeição: R$ 409,64 (Sem Descontos); 
• Auxilio Creche: Filhos de 0 a 24 meses R$ 481,98 / 24 a 60 meses R$ 421,00;
• Participação de Lucros atrelado a metas;
• Convênio com escola de idiomas e universidades; 
• Apoio a certificações; 
• Educação corporativa; 
• Auxílio Teletrabalho - R$ 250,00.

## Como aplicar
Envie seu currículo com pretensão salarial, no título iOS SÊNIOR, para o e-mail: gabrielly.leonel@invillia.com

## Contato
gabrielly.leonel@invillia.com

**Comment by IslasGiga** [comment]
Acho que os requisitos não estão corretos.

**Comment by GabriellyLeonel** [comment]
> Acho que os requisitos não estão corretos.

Olá, já arrumei. Agora estão certos :)
