### ISSUE TITLE
[São Paulo - Vila Mariana] iOS Developer Pleno || Senior - IBM

### ISSUE THREAD

**Issue by lucastorquato** [CocoaHeadsBrasil/vagas#79]
## Empresa
A IBM atua há mais de 100 anos no mercado de soluções, tem hoje a marca de tecnologia mais valiosa do mundo e conta com mais de 400 mil funcionários ao redor do mundo. Na IBM você pode aplicar seu conhecimento, usando-o de forma mais profunda ou mesmo se reinventando ao trabalhar com temas desafiadores, de forma globalizada. 

## Descrição da vaga
A IBM tem uma oportunidade para iOS Developer em São Paulo.

## Posição
Pleno || Senior

## Tipo de contratação
CLT - Presencial - São Paulo (Tutóia @ Vila Mariana)

## Requisitos
- 3+ anos de experiência com desenvolvimento utilizando a plataforma iOS
- Swift & Objective-C
- Testes, testes e testes 
- Clean code & Refactoring
- GIT
- Inglês (Full professional proficiency)
- Metodologias ágeis 
- Team worker

## Benefícios
- Plano Médico, Odontológico e Psicoterápico
- Plano de Medicamentos Vidalink 
- Ticket Alimentação
- Ticket Refeição
- Plano de Aposentadoria de Contribuição Definida (Fundação Previdenciária IBM) 
- Plano Creche Aplicado para Mulheres 
- Plano Creche Aplicado para Homens que tenham a Guarda Legal e em caso de Falecimento do 
cônjuge 
- Bônus de participação nos resultados (GDP)
- PLR (Participação nos Lucros e Resultados)

## Como aplicar
Por favor, enviar um email para antoniot@br.ibm.com com o assunto "iOS Dev - Oportunidade" e seu CV anexado.

## Contato
antoniot@br.ibm.com ou @torquato no slack iOS Dev BR

**Comment by reprotector** [comment]
@lucastorquato Conseguiram contratar? Foi alguém daqui? :)

**Comment by lucastorquato** [comment]
@reprotector 
yeah =) 
...daqui comunidade "iOS Dev BR? Sim também \o/
