### ISSUE TITLE
[Porto Alegre] SouthSystem - iOS Developer Pleno/ Sênior

### ISSUE THREAD

**Issue by AlineLarruscaim** [CocoaHeadsBrasil/vagas#792]
## SOUTHSYSTEM
 Somos uma empresa focada nos desafios e resultados de nossos clientes. Alinhamos as nossas estratégias as de nossos parceiros, garantindo assim maior sinergia na busca dos objetivos planejados

## Descrição da vaga

Nessa oportunidade, o(a) profissional trabalhará com:

Desenvolvimento iOS;
Desenvolvimento nativo em Swift;
Programação Orientada a Objetos;
Programação com reativo (RxSwift);
MVVM (Model View View Model);
Desenvolvimento de testes;
Desenvolvimento com frameworks;
Conceitos de UX e UI.

Será bacana se você tiver:

Experiência com desenvolvimento utilizando APIs e Mock;
Experiência com trabalho com times que utilizam métodos ágeis para desenvolvimento;
Concepção colaborativa de produtos;
Habilidade de exploração e proposição de soluções e conexão com o negócio;
Experiência em eventos como Meetups, hackathon, grupos de tecnologias ou envolvimento com algum tipo de comunidade;
Vontade de aprender novas tecnologias e abertura para temas ligados a engajamento de usuário e gamificação.

## Posição
Pleno/ Sênior

## Tipo de contratação
 Inicialmente, por estarmos em uma pandemia, será remoto. Porém, precisamos que o profissional tenha disponibilidade para trabalho presencial. 
** PJ OU COOPERADO 

## Contato
Encaminhar o currículo para o e-mail: aline.larruscaim@southsystem.com.br

**Comment by unnamedd** [comment]
Vaga duplicada.
