### ISSUE TITLE
[SC - Florianópolis] SOUTH SYSTEM - Dev iOS

### ISSUE THREAD

**Issue by cmazoni** [CocoaHeadsBrasil/vagas#793]
## Empresa
 
A SOUTH SYSTEM atua hoje principalmente no setor financeiro, desenvolvendo as melhores soluções para atender às demandas de seus clientes. Focamos muito no desenvolvimento de nossos profissionais, oferecendo cursos e treinamentos para impulsionar seu desenvolvimento, com uma cultura horizontal e tecnologias de ponta, incentivando desafios!

## Descrição da vaga

A SOUTH SYSTEM está em busca de uma pessoa denvolvedora iOS que queira fazer parte do nosso propósito de impulsionar o desenvolvimento das pessoas para inovar o mundo. Para fazer parte do time, há algumas skills que valorizamos muito, e não estamos falando apenas de tecnologia, nós valorizamos profissionais que respeitem o próximo e suas diferenças, que sejam leais e responsáveis com as entregas e com as pessoas, que sejam proativos e saibam trabalhar em grupo, além de ter sede de aprendizado para trabalhar com inovação contínua.. A colaboração e engajamento devem fazer parte do dia a dia para que o resultado seja eficaz.

## Posição
 Dev iOS pleno ou sênior

## Tipo de contratação
 Presencial, PJ ou cooperado

###### Obrigatórios

- Swift 4.2;
- Storyboards;
- MVVM;
- Core Animation;
- Core Graphics.

###### Desejáveis

- Subclassing / Custom Elements;
- Keychain;
- Biometry;
- Auto Layout.

## Benefícios

- Salários compatíveis com o mercado;
- Macbook;
- Oferta de cursos e treinamentos para impulsionar o seu desenvolvimento.

## Como aplicar

Envie um e-mail com o teu currículo para claudia.mazoni@southsystem.com.br com a vaga no assunto e vamos marcar uma conversa!

**Comment by ezefranca** [comment]
Duplicada #794
