### ISSUE TITLE
[São Paulo - JK] - Desenvolvedor iOS Senior

### ISSUE THREAD

**Issue by bguidolim** [CocoaHeadsBrasil/vagas#8]
## Descrição da vaga

 - Desenvolver aplicações mobile iOS;
 - Realizar manutenções e customizações de aplicações mobile iOS;
 - Realizar integrações com webservices e APIs;
 - Atuar na manutenção e melhoria de design e arquitetura da aplicação iOS;
 - Aplicar boas práticas de codificação e versionamento de código;
 - Executar e documentar testes unitários, funcionais, de interface garantindo que os requisitos do negócio sejam atendidos;
 - Analisar regras de negócio da aplicação;
 - Manter-se atualizado com as novas soluções de tecnologia que sejam aplicáveis ao desenvolvimento, por meio de pesquisas, cursos, fóruns, networking, etc;
 - Posicionar a equipe sobre o andamento de suas atividades;
 - Relatar à equipe problemas que venham impactar a produtividade e/ou qualidade dos projetos em que estiver atuando, sempre focando em ajudar a solucioná-los;

## Local

Presencial - São Paulo/SP - Av. JK

## Requisitos

Experiência mínima de 6 anos na área de desenvolvimento de software e 4 anos em iOS.
Ensino Superior completo na área de TI
Curso de desenvolvimento mobile iOS

 - Objective-C
 - Integração com serviços utilizando REST/JSON
 - Google APIs
 - GIT
 - Push notification
 - Conhecimento avançado de UI e UX (guidelines do iOS)
 - Geração de certificados iOS
 - Inglês (nível suficiente para pesquisas e leitura técnica).

Desejáveis
 - Swift
 - TFS
 - Banco de dados relacionais (Sqlite, SQL Server, MySQL, Oracle)
 - Conhecimentos em linguagem de programação orientada a objeto (Java, C++, C#)
 - OAuth2

## Contratação

PJ/CLT a combinar

## Como se candidatar

Por favor envie um email para telma.nunciaroni@livegroup.com.br com seu CV anexado e links de apps desenvolvidos - enviar no assunto: Vaga - Desenvolvedor iOS

**Comment by barbosa** [comment]
Olá @bguidolim, tudo bem?

A vaga ainda está aberta? Só para saber se fechamos a issue ou mantemos aberta.

Obrigado!

**Comment by bguidolim** [comment]
Pode fechar :)
Nosso amigo Jhonathan Wyterlin do Slack já preencheu a vaga :)

Bruno Guidolim - via iPhone




On Thu, Mar 31, 2016 at 8:07 AM -0700, "Gustavo Barbosa" <notifications@github.com> wrote:












Olá @bguidolim, tudo bem?



A vaga ainda está aberta? Só para saber se fechamos a issue ou mantemos aberta.



Obrigado!

**Comment by barbosa** [comment]
@bguidolim beleza!
