### ISSUE TITLE
[São Paulo - Rebouças] GetNinjas - Estágio Desenvolvimento iOS

### ISSUE THREAD

**Issue by thiagodelmotte** [CocoaHeadsBrasil/vagas#80]
## Empresa

VOCÊ! Quer contribuir para todos os aspectos da definição, construção e manutenção da nossa plataforma Mobile iOS?

Você se joga pra encarar desafios, tem atitude e trabalha bem em time? Então queremos que você seja um NINJA!

GetNinjas. www.getninjas.com.br

## Descrição da vaga

A vida de um NINJA é repleta de desafios e aqui não será diferente, listamos algumas qualidades essenciais e outras consideradas diferenciais:

- Cursando Ciência da Computação, Sistemas de Informação ou similar
- Bons conhecimentos de programação e padrões de projeto
- Vontade de aprender
- Apaixonado por programação
- Facilidade de trabalhar em equipe
- Familiaridade com ambiente OSX
- Desejável: Conhecer iOS, Objective-c, Swift, CocoaPods, ter feito ou participado de algum app
- Plus: GIT, API/REST, TDD, Testes

## Posição
Estágio

## Tipo de contratação
Presencial, contrato de estágio

## Benefícios

- Remuneração competitiva
- Vale-Transporte e Vale-Refeição
- Possibilidade de ter um enorme impacto positivo e mudar a maneira como as pessoas usam a internet.

Os NINJAS amam:
- Lanches, chocolates, frutas gratuitas no escritório
- Ambiente de trabalho divertido e descolado
- NERFS 
- Chinelo e bermuda 
- Sinuca
- Cesta de Basquete
- Rede no jardim

## Como aplicar
candidate-se a vaga em: https://getninjas.workable.com/jobs/382842

**Comment by reprotector** [comment]
@thiagodelmotte A vaga ainda está aberta? Podemos fechar a issue?

**Comment by thiagodelmotte** [comment]
Está aberta!


Att,
Thiago Delmotte
Cel.: (11) 99471-8172

**Comment by Junior-iOS** [comment]
@thiagodelmotte, currículo enviado. 
Desde já, agradeço!
