### ISSUE TITLE
[São Paulo - SP] 5A Attiva - iOS Developer

### ISSUE THREAD

**Issue by helenmatos** [CocoaHeadsBrasil/vagas#801]
## 5A Attiva
Olá, estamos buscando Desenvolvedor IOS Jr
Buscamos um profissional que queira evoluir profissionalmente e que goste de trabalhar com modelo de Squads.

## Posição
Desenvolvedor IOS Junior e Pleno 

## Tipo de contratação
Inicialmente irá trabalhar de forma remota /  contratação PJ

###### Obrigatórios
Swift
- XCode 
- Fastlane - automação de builds
- Constraints e StackView
- Protocolo HTTP
- Domínio de API Rest/RestFUL
- Experiência com o armazenamento offline, threading, gerenciamento de memória  e otimização de desempenho;
- Ter experiência em Apple Design Guide Lines
- Bibliotecas comuns ao desenvolvimento iOS (RXSwift, Alamo Fire etc).
- Implementar mockups do time de design, com atenção aos detalhes visuais e compatibilidade entre devices;

###### Desejáveis
- Websocket/SSE
- Gitflow
- Kanban/Jira
- Vivência em Times Multidisciplinares/Squads
- Boas práticas de desenvolvimento (SOLID, KISS, DRY)
- Ter projetos publicados na App Store

## Com quem você vai trabalhar
Interessados, por favor, enviar CV para Ingrid.prudencio@5aattiva.com

## Como aplicar
Nos envie o seu CV, em breve retornaremos com maiores detalhes da oportunidade. 

## Contato
Para maiores informações, entrar em contato com Ingrid Prudencio 
E-mail: Ingrid.prudencio@5aattiva.com

**Comment by DouglasHennrich** [comment]
Vaga ativa ainda ?

**Comment by DouglasHennrich** [comment]
Tentei enviar um email, mas diz que o destinatario nao existe
