### ISSUE TITLE
[Remoto/Orlando, FL] Stormbreaker Studios - Junior iOS Developer

### ISSUE THREAD

**Issue by mediumhotcoffee** [CocoaHeadsBrasil/vagas#814]
## Empresa
Stormbreaker Studios is a fast-growing mobile application development agency based in Orlando, FL, with clients throughout the United States, Europe, and Asia. We specialize in native iOS and Android development for entrepreneurs and small businesses in a variety of industry sectors, including: Health & Wellness, Hospitality, Education, Utilities, and Entertainment. We take a consultative approach with our clients, helping them find ways to further their core business goals through mobile apps.

## Descrição da vaga
We are looking for a native iOS developer with knowledge of Swift (Objective-C a plus). The candidate must be organized, detail-oriented and able to effectively communicate with their fellow developers, project managers, and leadership.

You may be a great fit if you:
- Have created an app (for yourself or for someone else) from scratch, that has been
 published on the App Store
- Have demonstrated experience with and/or are committed to continuous learning about: Xcode, Swift, Objective-C, RESTful APIs, JSON, Auto Layout, frameworks, and APIs including Foundation, UIKit, and CocoaTouch, Firebase, and Apple Human Interface Guidelines
- Communicate regularly and write clean code
- Have at least 6 working hours that overlap the U.S. Eastern time zone
- Have experience working on a distributed team and/or telecommuting

## Posição
Junior iOS engineer

## Tipo de contratação
- Freelancer

###### Obrigatórios
- Swift 5
- Xcode
- CocoaPods
- Git (at least working knowledge of basic operations and branching)
- Auto Layout

###### Desejáveis
- Objective-C
- Jira
- Hubstaff
- GitHub
- Slack
- Discord
- Firebase Auth, Realtime Database, and Firebase Storage
- Understanding of how to work with a XD and/or Sketch prototype
- Knowledge of common mobile development design patterns (e.g. MVC, MVVM, etc.)

###### Diferenciais
- Knowledge of Android development (Java and Kotlin)
- Knowledge of Swift Package Manager
- Knowledge of CoreData and CloudKit

## Benefícios
- N/A (freelancer)

## Com quem você vai trabalhar
- [Gary Chisholm](https://www.linkedin.com/in/gary-chisholm-6348453/)
- [Charlyn Keating](https://www.linkedin.com/in/charlynkeating/)
- [Marcos Silva](https://www.linkedin.com/in/marcossilva7/)

## Como aplicar
1. Send a copy of your résumé and GitHub repo (if you have one that you can share) to marcos@stormbreakerstudios.com or gary@stormbreakerstudios.com, or send it on a DM to Marcos Silva on the iOS Dev BR Slack — however you prefer
2. If selected, we'll contact you for a phone interview
3. After the phone interview, selected candidates have to pass an iOS layout test

## Contato
If you have any questions, please reach out to us:
- Email: marcos@stormbreakerstudios.com (Marcos Silva, Project Manager)
- Slack: Marcos Silva (iOS Dev BR)

**Comment by unnamedd** [comment]
@mediumhotcoffee 

Por favor, siga o padrão adotado nas outras issues, que geralmente é: 

[Cidade - UF] Empresa - Posição

> **Cadastrando uma vaga**
> 
> Adicione uma issue utilizando o template oferecido na descrição. No título, coloque o nome da cidade entre colchetes, seguida do nome da vaga.

https://github.com/CocoaHeadsBrasil/vagas/blob/master/README.md

**Comment by mediumhotcoffee** [comment]
Title updated.

**Comment by unnamedd** [comment]
Adicione também o nome da empresa, por favor, uma vez que ela consta na descrição da vaga.

**Comment by mediumhotcoffee** [comment]
Done.

**Comment by mediumhotcoffee** [comment]
Hello,

we're closing this issue as we have chosen a candidate. To those who applied, we appreciate you taking the time to do so. We'll send the updates by EOD today.

Quick reminder: your information will not be shared outside of our company and was only used to reach a conclusion about your application. If you have any questions or concerns, feel free to contact me at marcos@stormbreakerstudios.com

Marcos Silva
