### ISSUE TITLE
[REMOTO] Dev. iOS Sênior - Invillia 

### ISSUE THREAD

**Issue by GabriellyLeonel** [CocoaHeadsBrasil/vagas#816]
## Empresa
Somos mais de 500 Invillianos atuando dentro e fora do Brasil, gerando oportunidades todos os dias para clientes potenciais em diversos segmentos e tecnologias.
Estamos com posições para atuar em alguns dos nossos clientes veja em nosso site alguns deles
Faça uma imersão aqui https://invillia.com/

## Posição
Sênior

## Tipo de contratação
 Informe se é remoto/presencial, CLT, PJ ou Freelancer. 

## Requisitos
Swift 4.0+; Basico de objective c; Arquitetura mvvm-c; Coordinator; Testes unitarios; XCTest; Teste UI com KIF; Git; GitFlow; Auto Layout; Trabalhar com .xib; Conhecer criação de componentes; Bitbucket;
Metodos Ageis (Scrum/Kanban); Clean Code; Integração Rest; Fabric; Pull Request e code review. 

## Benefícios
VR, VA, AM, AO, SV, Ajuda de custo. 

## Como aplicar
Envie seu currículo com pretensão salarial para: gabrielly.leonel@invillia.com com o assunto: iOS.

**Comment by unnamedd** [comment]
Vaga duplicada.
https://github.com/CocoaHeadsBrasil/vagas/issues/804

**Comment by GabriellyLeonel** [comment]
é outra vaga....

**Comment by unnamedd** [comment]
Não é o que parece. Tudo descrito na vaga #804, também se aplica a essa vaga aqui. Mas fique a vontade para copiar as diferenças daqui e editar lá.
