### ISSUE TITLE
[Amsterdam] Siilo - iOS Developer

### ISSUE THREAD

**Issue by brunokoga** [CocoaHeadsBrasil/vagas#822]
## Empresa
Here at Siilo, we’re on a mission to create a future where patients and professionals are practicing medicine together. Even though we’re young and ambitious (founded only in 2015), we’re already the fastest growing secure messenger for doctors and nurses, and we’re on track to solve the biggest communication challenges faced by health professionals on a global scale.

On top of that, the impacts on reduced spend on healthcare (we estimate billions!), alongside patient experience / quality of life, will be profound. Because of this, we are finalists in the TechCrunch Europas Awards for Hottest Health Tech startups and were mentioned as one of Amsterdam’s hottest startups to watch in 2019!

## Descrição da vaga
We’re seeking an iOS Developer to join us on our mission to change the way that the healthcare industry works. Engineering sits at the heart of our business, and within this role, you’ll be responsible for helping us drive our platform forward and stand apart from our competition. You’ll be joining a small but extremely talented & experienced engineering team, to work on the truly transformational, as well as to push yourself to the next level.

## Posição
Somos um time de 2 desenvolvedores iOS e estamos procurando por mais uma pessoa pra se juntar ao time. A vaga requer um certo nível de experiência com desenvolvimento iOS. Para mais detalhes, [aqui está o link oficial da vaga](https://jobs.lever.co/siilo/5c8973f1-0bcc-418e-ab34-97cf2650b856).

## Tipo de contratação
Originalmente era uma vaga presencial: a Siilo é Visa Sponsor e relocação pra Amsterdam é possível. Mas temos gente trabalhando na Austrália, em Fortaleza... se trabalhar remoto é melhor pra você, a gente conversa.

## Requisitos
- 3+ years of experience with iOS development; Our codebase is mostly written in Swift. Being comfortable with Objective-C code is a plus
- Experience delivering universal apps
- You're passionate about writing clean and well-documented code
- You are willing to always discuss new ideas and approaches to solve problems.
- You understand that the technologies surrounding iOS development are always evolving and you are eager to learn, code and share new solutions with your colleagues
- You love to work collaboratively. You understand that the whole is greater than the sum of the parts
- You're comfortable with using 3rd-party libraries and dependency managers (we currently use CocoaPods). Bonus points if you have contributed to open-source projects
- Nices-to-have: experience with reactive programming, cryptography, secure storage of data (keychain, encrypted database, data protection)
- Fluent in English; Dutch is not necessary

## Benefícios
- Flexible working hours – we believe in having a great work/​life balance
- A great office in the middle of the Amsterdam Canals
- The freedom to work how you work best – we have a relaxed but very ambitious company culture
- Training and conference budget – if you’re not learning, we’re not developing as a company
24 days of annual leave per year
- Daily, delicious team lunches – it’s important to us that we take time out at midday to enjoy lunch together
- Competitive company benefits & salary

## Com quem você vai trabalhar
- Working on our end-to-end encrypted chat app where security and privacy are at the center of everything you do
- Working with cutting edge technologies, building and maintaining an extremely reliable app that our users can trust on
- Being involved with not only engineering, but also with product-related and design discussions and decisions
- Working on a small, but very talented (and friendly!) team
- Being at the center of an industry that needs change. You can make a difference that really matters!

## Como aplicar
[aqui](https://jobs.lever.co/siilo/5c8973f1-0bcc-418e-ab34-97cf2650b856)

## Contato
[Aqui no site da vaga](https://jobs.lever.co/siilo/5c8973f1-0bcc-418e-ab34-97cf2650b856) ou pode entrar em contato comigo: bkoga [at] siilo [dot] com

**Comment by carlosvreal** [comment]
@brunokoga essa vaga ainda está aberta?

**Comment by brunokoga** [comment]
@carlosvreal super aberta!

**Comment by brunokoga** [comment]
Vaga preenchida! Obrigado a todos!
