### ISSUE TITLE
[REMOTO] Desenvolvedor(a) Mobile iOS

### ISSUE THREAD

**Issue by marjorybraga** [CocoaHeadsBrasil/vagas#824]
## Empresa

Somos uma empresa de desenvolvimento de software atendendo desde Startup's até pequenas e médias empresas, estamos criando nossa cultura de trabalho remoto para poder crescer de forma sustentável.
Procuramos talentos para poder crescer junto com a empresa e se tornar o diferencial no mercado brasileiro.

## Descrição da vaga

Com o que você vai trabalhar:
Desenvolvimento de aplicativos para iOS, caso queira e demonstre no processo seletivo poderá atuar em outras de desenvolvimento.

Cultura de trabalho remoto
Regime: PJ;
Período: Integral;
Contratação imediata;

## Posição

Desenvolvedor Júnior/Pleno

## Tipo de contratação

Cultura Trabalho remoto
Regime: PJ

## Requisitos

Com o que você vai trabalhar:
Desenvolvimento de aplicativos para iOS, caso queira e demonstre no processo seletivo poderá atuar em outras de desenvolvimento.

Construir aplicações para iOS utilizando Objective C / Swift 5.0;
Conhecer o processo de deploy (AppStore Connect, TestFlight, AppStore);
Priorizar e tratar bugs e exceções reportados em produção;
Contribuir em decisões de arquitetura sobre novas partes do projeto.
Experiência em integração com banco de dados, integrações com APIs RESTful.

## Como aplicar

Responda o formulário abaixo:  
[Link formulário de contratação](https://forms.gle/wLrFpUaVUQP7f2VUA)

## Contato

vagas@soluevo.us

**Comment by DouglasHennrich** [comment]
Vaga ainda está aberta?
