### ISSUE TITLE
[Remoto] Guru - Desenvolvedor@ iOS Pleno/Senior - PJ

### ISSUE THREAD

**Issue by barrault01** [CocoaHeadsBrasil/vagas#825]
## Empresa
A cada dia estamos crescendo 🙌 Mais usuários, mais sugestões, mais feedbacks, e por isto estamos crescendo o time.
Acreditamos que o investimento em ações deveria ser para todos e fazemos isso com um produto simples, intuitivo e que cabe no bolso de todo mundo!?

#Nossacultura
O que você vai encontrar aqui?
- Ambiente de startup de rápido crescimento;
- Rapidez e agilidade na tomada de decisões e construção do produto;
- Total liberdade para se envolver em decisões estratégicas;
- Foco nas métricas e na experiência do usuário;
- Desafios multidisciplinares, trabalhando de forma muito próxima com toda a equipe.

## Posição
Procuramos um@ dev iOS Pleno/Senior 

## Tipo de contratação
Remoto - PJ 

## Requisitos

- Experiência com Desenvolvimento iOS (Swift);
- Experiência com testes automatizados e unitários;
- Conhecimento da arquitetura MVVM;
- Experiência com ferramentas de CI.

## Com quem você vai trabalhar
https://www.linkedin.com/in/ant1/ 

## Como aplicar
Manda um email com cv ou linkedin para guru@guru.com.vc ou me procura aqui no slack @ant_one

**Comment by danilorequena** [comment]
A vaga ainda está aberta?
