### ISSUE TITLE
[Copenhagen] Shape A/S - iOS Developer

### ISSUE THREAD

**Issue by filipegn** [CocoaHeadsBrasil/vagas#829]
## Empresa
 Shape is known for building high quality mobile apps that tackle real problems and push businesses forward. At Shape you will be working closely together with talented designers and developers to build awesome mobile apps. You will put your existing skills to good use, and learn new ones by working together with other skilled people.

We hope that you also want to share your knowledge with co-workers and assume you are as eager to follow the newest technology trends as the rest of us.

## Posição
Pleno / Senior

## Tipo de contratação
Copenhagen, DK. The company offers visa sponsorship and relocation package.

## Requisitos

- Experience with developing native iOS apps using Swift or Objective-C and the iOS SDK.
- Motivation to become a part of and learn from a team of experienced and passionate developers for iOS, Android and the web.
- Interest in design patterns and well structured code and workflows.

## Benefícios

Our office is located in a lovely old warehouse on Islands Brygge, where we host social events, keynotes, Fifa tournaments, morning runs (and swims), friday bars, board game nights, family LEGO days and much more.

We are organized with a very flat hierarchy without unnecessary project managers, but with team leads who also have technical backgrounds. Our team is very international and so far includes people from 14 different countries. Our company language is English.

A couple of times each year we press pause on our daily projects and retrieve to a remote location. We get together for socialising and hacking on side projects - we call this Shape Weekend. It is a lot of fun.

## Como aplicar
https://www.shape.dk/careers/ios-developer

## Contato
(at)filipe.nobrega or (at)tales on slack

**Comment by talesp** [comment]
Vaga ainda está aberta

**Comment by talesp** [comment]
A vaga ainda está aberta :)

**Comment by talesp** [comment]
pingando porque a vaga ainda está aberta :)
