### ISSUE TITLE
[SP - Boituva] Desenvolvedor IOS Pleno / Sênior

### ISSUE THREAD

**Issue by MarinaEvolutionIT** [CocoaHeadsBrasil/vagas#83]
## Empresa
Evolution IT

## Descrição da vaga
Vaga com reembolso de despesa, prazo: 2017 
Local de trabalho: cliente em Boituva SP

## Posição
Desenvolvedor IOS Pleno / Sênior

## Tipo de contratação
Presencial, PJ

## Requisitos
Experiência mínima de 3 anos com IOS

## Contato
Enviar CV para marina.duarte@evolutionit.com.br
Informando pretensão para PJ

**Comment by klevison** [comment]
Entrei em contato e a vaga não está mais aberta.
