### ISSUE TITLE
[Belo Horizonte/MG - Santa Lúcia] eMotion Digital - Desenvolvedor iOS

### ISSUE THREAD

**Issue by bernardoassis** [CocoaHeadsBrasil/vagas#84]
## Empresa
A eMotion Digital é uma empresa de tecnologia focada em produção, distribuição de conteúdo e desenvolvimento de projetos incríveis (apps iOS/Android/HTML5) para o mercado de SVA (Serviços de Valor Agregado) para operadoras no mundo inteiro!

## Descrição da vaga
Pra galera que está aprendendo a desenvolver iOS (ou estagiando na área) em BH e Região, estamos buscando analistas de sistemas para trabalhar com desenvolvimento iOS (Obj-C e Swift) na eMotion Digital. É uma grande oportunidade para aprender bastante trabalhando com projetos de apps não só para iPhone e iPad, mas também para a Apple TV e o Apple Watch!

## Posição
Analista de Sistemas Junior

## Tipo de contratação
CLT (Presencial)

###### Obrigatórios
Experiência com programação em Swift e/ou Objective-C no Xcode;
Conhecimento de controle de versão de código-fonte Git;
Conhecimento sólido em programação orientada a objetos;
Conhecimento sólido de padrões de projeto de software;
Estar no final do curso (ou ser formado) alguma faculdade na área de ciências exatas (de preferência em TI).

###### Desejáveis
Experiência com programação em front-end web (HTML/CSS/Javascript);
Experiência com programação back-end (qualquer linguagem);
Experiência em banco de dados SQL;
Algum aplicativo publicado na App Store.

###### Diferenciais
Experiência de trabalho em equipes de desenvolvimento ágil;
Habilidade de trabalho com independência e supervisão mínima;
Disposição em compartilhar o seu conhecimento com as pessoas da área de tecnologia da empresa;
Boa habilidade de comunicação escrita e verbal;
Disposição para aprender novas tecnologias e aplicá-las em um curto espaço de tempo;
Espírito de equipe em um time multi-disciplinar;
Capacidade de analisar situações e informações, realizando avaliação crítica e conclusiva, apontando direcionamentos para subsidiar as tomadas de decisões.

## Benefícios
Almoço fornecido pela empresa;
Flexibilidade de horário;
Possibilidade de home office (em ocasiões excepcionais);
Lanche oferecido no final da tarde;
Vale Transporte.

## Como aplicar
Por favor envie um email para bernardo@emotiondigital.com.br com seu CV anexado - com o assunto: Vaga Desenvolvedor iOS

## Contato
@bernardoassis no grupo iOS Dev BR no Slack
bernardoassis no Skype
E-mail: bernardo@emotiondigital.com.br

**Comment by reprotector** [comment]
@bernardoassis A vaga ainda está aberta? Podemos fechar a issue?

**Comment by bernardoassis** [comment]
@reprotector Ainda aberta. Interessados ainda podem enviar currículo!
