### ISSUE TITLE
[SÃO PAULO - SP] IOS Developer na Ayfa 

### ISSUE THREAD

**Issue by gasineoamanda** [CocoaHeadsBrasil/vagas#847]
A Afya está revolucionando o mercado de educação médica no Brasil e você pode entrar nesse movimento!
Nascemos oficialmente em 2019, com o objetivo de sermos a principal parceira dos médicos em suas jornadas de formação, nós já formamos mais de 100 mil médicos pelo Brasil e contamos com um time de 4.000 pessoas para garantir que os nossos alunos possam transformar seus sonhos em realidade!
Em plena pandemia pudemos ter maior noção de quão importante é o nosso papel, e por isso nesse estamos focados em expandir o nosso time de tecnologia para atender a todas as nossas unidades espalhadas pelo país.
Trabalhamos com desenvolvimento nativo, focado em Swift, e buscamos pessoas comunicativas, com espírito empreendedor e dispostas a crescer exponencialmente com a Afya. Serão bem-vindos conhecimentos em API Rest e UX.
E aí? Topa o desafio? 🙂

https://byintera.in/rw

**Comment by ezefranca** [comment]
Oi @gasineoamanda  tudo bem?

Você poderia editar sua vaga seguindo o padrão de postagem, estou enviando ele abaixo.

Obrigado.

```

<!--- Regras do canal: https://github.com/CocoaHeadsBrasil/vagas/   --->

<!--- Atenção! Verifique as regras do canal antes de postar sua vaga. Vagas fora das regras serão excluídas e a reincidência pode causar o banimento do usuário no canal. Obrigado!  --->

<!---
    Se a vaga for presencial, adicione ao início da issue o código do Estado.
    exemplo: [SP - Morumbi] EmpresaFictícia - Desenvolvedor iOS Pleno
 --->
 
 <!--- Por favor, siga o fluxo abaixo --->

## Empresa
 Breve descrição da empresa

## Descrição da vaga

## Posição
 Informe qual a posição da vaga (ex.: pleno)

## Tipo de contratação
 Informe se é remoto/presencial, CLT, PJ ou Freelancer. 

## Requisitos

###### Obrigatórios

###### Desejáveis

###### Diferenciais

## Benefícios
Informe os benefícios que a empresa oferece

## Com quem você vai trabalhar
Se desejar insira uma lista dos futuros colegas de trabalho. Você pode gerar uma com os usuários do GitHub dos funcionários em http://fpg1503.com/GithubProfileTableGenerator/

## Como aplicar
Informe como é feito o processo para aplicar a vaga

## Contato
Informe aqui os contatos para mais informações
```
