### ISSUE TITLE
[São Paulo] Banco Neon - DESENVOLVEDOR iOS

### ISSUE THREAD

**Issue by CamilaNeon** [CocoaHeadsBrasil/vagas#86]
## Empresa
O Neon é um banco novo e totalmente diferente.
Ele nasceu do desejo de transformar, de revolucionar uma área que quase não se reinventa. E também nasce por cansaço. Estamos cansados de pagar uma fortuna em taxas e não receber um atendimento de qualidade, de ter que apelar pra uma lupa pra saber de verdade com que tipo de instituição estamos lidando. Inovar é ter coragem para mudar.
Nosso aplicativo foi construído para facilitar a vida financeira e valorizar a experiência dos clientes. Tudo sem enrolação, sem blá blá blá. Somos transparentes e queremos continuar assim.
Um banco acessível e aberto a conversas, opiniões e novas ideias.

## Descrição da vaga

O profissional será responsável pelo desenvolvimento e manutenção do app iOS, consumindo e alimentando dados a partir de uma api remota. A expectativa é que o profissional seja capaz de entregar um produto com requintes avançados de UX.

## Posição
2 vagas - Pleno e Sênior

## Tipo de contratação
Presencial, CLT. 

###### Obrigatórios
- Experiência de no mínimo 3 anos em desenvolvimento e manutenção de aplicativos mobile nativos iOS (Objective-C / Swift)
- SQLite/ Core Data
- Experiência no uso de Web Services(REST, JSON/XML).
- Storyboard autolayout
- Conhecimentos de UX.
- Core Animation.
- Design Patterns .
- Cocoa pods.
- Conhecimento em testes integrados.

###### Diferenciais
- Experiência com apple watch
- Links com código no github e ou apps publicadas
- Conhecimentos avançados em SpritKit
- Ter trabalhado com jogos
- Integração contínua

## Benefícios
Horário Flexível
No dress code
happy hour semanal por conta da empresa
sala de descanso/ videogame
Subsidio para academia (Gym Pass)
Subsidio Plano de Saúde
Estacionamento ou Vale Transporte (sem desconto)
Vale Cultura

## Como aplicar
Por favor envie um email para seja@banconeon.com.br com seu CV anexado - enviar no assunto: Vaga iOS

## Contato
www.banconeon.com.br
camila.monteiro@timeneon.com.br

**Comment by reprotector** [comment]
Olá @CamilaNeon, já existe uma vaga aberta para o Neon (https://github.com/CocoaHeadsBrasil/vagas/issues/59) Podemos fechá-la?
