### ISSUE TITLE
[SC - Blumenau] PremierSoft - Desenvolvedor iOS (Swift)

### ISSUE THREAD

**Issue by hulsenbeck** [CocoaHeadsBrasil/vagas#860]
## Empresa
No mercado há 9 anos, e com mais de 100 aplicativos publicados, a PremierSoft é referência quando o assunto é desenvolvimento de aplicativos personalizados para iOS e Android.
Atendemos desde empresas de pequeno porte, até grandes nomes como Faber Castell, Philips, Ailos e PagueVeloz.

## Descrição da vaga

A PremierSoft está em busca de um(a) desenvolvedor(a) iOS.

Pré-requisitos:

– Não ter problema com cachorros (temos duas Goldens que nos fazem companhia)

– Comprometimento e vontade de aprender

– Inglês técnico

– Conhecimento em Swift

Diferenciais:

– Conhecimento em ObjC

– Experiência em projetos de bancos/instituições financeiras

## Posição
 Estamos contratando desde Desenvolvedor Júnior até Sênior

## Tipo de contratação
Presencial PJ

###### Obrigatórios

– Não ter problema com cachorros (temos duas Goldens que nos fazem companhia)

– Comprometimento e vontade de aprender

– Inglês técnico

– Conhecimento em Swift

###### Desejáveis

– Conhecimento em ObjC

## Como aplicar
Envie seu CV para rh@premiersoft.net 

## Contato
Se quiser saber mais detalhes sobre a empresa/vaga, pode me dar um alô no Slack do iOS DevBR - usuário @hulsenbeck

**Comment by didisouzacosta** [comment]
Existe a chance de ser remoto?

**Comment by hulsenbeck** [comment]
@didisouzacosta infelizmente para essa vaga em questão, não...Trabalhamos com modelo híbrido, mas realizamos encontros presenciais.

**Comment by didisouzacosta** [comment]
@hulsenbeck Muito obrigado, caso ela se torne remota avise aqui por favor.
