### ISSUE TITLE
[Florianópolis-SC] ArcTouch - iOS Developer

### ISSUE THREAD

**Issue by NatCarneiro** [CocoaHeadsBrasil/vagas#87]
## Empresa
ArcTouch helps brands to connect more deeply with customers through custom experiences for phones, tablets and smart things. We transform app ideas into experiences for a wide range of connected devices you hold in your hand, wear on your wrist, and use in your home and car. Our world-class clients range from Fortune 500 businesses to well-known brands and influential startups, including NBC, Honeywell, Yahoo, CBS, Guess, Salesforce, Skyjet, Audi, and many more. ArcTouch is part of Grey, a WPP company.

## Descrição da vaga
ArcTouch is hiring skilled, creative, and adaptable iOS Developers/Engineers to create awesome products for big international companies.

## Posição
 Middle or Senior

## Tipo de contratação
Presencial - Florianópolis -SC
CLT

## Requisitos

- Objective-C and/or Swift
- Experience with Agile, Test Driven or Behavior Driven Development
- Solid understanding of iOS SDK on frameworks such as: UIKit, CoreFoundation, GCD, Auto Layout, Storyboards etc.
- Advanced object-oriented programming and knowledge of design patterns
- Familiarity integrating apps to RESTful APIs
- BS degree in Computer Science or equivalent
- English - Fluent
- 

## Benefícios
Flextime, Cross Cultural Daily Experience, Tech Talks, No dress code, 1 weekly lunch (for free <3), Subsidy Academy, English Classes, Happy Hours.

## Como aplicar
Send us your resumé or (Linkedin + contacts) for: work@arctouch.com

## Contato
natalia.carneiro@arctouch.com
https://arctouch.com/

**Comment by reprotector** [comment]
@NatCarneiro Já existe uma vaga aberta para ArcTouch - https://github.com/CocoaHeadsBrasil/vagas/issues/67 - Podemos fechá-la?
