### ISSUE TITLE
[SP - Vila Olímpia] Boom Financial - Desenvolvedor iOS

### ISSUE THREAD

**Issue by Luckcheese** [CocoaHeadsBrasil/vagas#88]
## The Company
PagueMob is a subsidiary of an US based international money-remittance company headquartered in the US, with offices in Miami, San Francisco and São Paulo. Our company’s mission is to be the most socially responsible financial services company servicing the complete needs of the underserved and unbanked consumer. We make it safe, easy and inexpensive to share funds with family in the US and “back home.” 

## Job Description
We're looking for iOS developers willing to building iOS applications in a small team environment. Those applications can range from consumer facing iOS applications to business-critical partner applications. You will be part of a lean, multicultural team based in São Paulo and San Francisco.
You will have the chance to work in an agile environment with cutting-edge technology all over the software stack. The technologies we use include Scala, Akka, Play, AngularJS, Docker, AWS, Bootstrap, Redis, Elasticsearch, Mobile (iOS and Android), among others.

## Position level
Middle or Senior

## Procurement regime
CLT - In place

###### Responsibilities
- Prototype and build iOS (iPhone & iPad) apps
- Rapidly fix bugs and solve problems
- Pro-actively look for ways to improve product

###### Must Have
- Passion for delivering great user experience and usability
- Building iOS applications in Objective-C or Swift
- Solid understanding of the full web technology stack
- Experience building web integrated software and applications
- Disciplined approach to test-first and quality assurance
- Advanced English
- Object-oriented programming
- Clean code and Git expertise
- Willing to learn new technologies
- Ready to work in a fast-paced, ever-changing environment
- Team work
- Education: BS or M.S. in Computer Engineering/Science or equivalent

###### Nice to Have
- Contributes to open source and has sample links
- Visual design skills
- Great written communication and documentation abilities
- Data-informed product development: analytics, A/B testing, etc.

## Benefits
- Meal allowance (VR)
- Public transportation allowance (VT)
- Health and Dental Insurance
- Life insurance
- Fun environment (with video games)

## How to apply
https://goo.gl/forms/ShCHp8h4RojtOMOV2

## Contact
https://www.linkedin.com/jobs/view/240760173

**Comment by reprotector** [comment]
@Luckcheese A vaga ainda está aberta ou podemos fechar a issue?
