### ISSUE TITLE
[São Paulo - Vila Olímpia] 99Taxis - Desenvolvedor iOS Pleno e Sênior

### ISSUE THREAD

**Issue by rafaortiz** [CocoaHeadsBrasil/vagas#9]
## Descrição da vaga

Aqui na 99 estamos constantemente evoluindo nossa cultura de desenvolvimento. Abordamos o desenvolvimento mobile com precisão e rigor de engenharia, trabalhamos com testes e ferramentas que garantem a qualidade e o impacto positivo nos nossos usuários.

Pequenos detalhes são vitais, focamos na experiência do usuário. Se você é um dev focado em produto, que não hesita em lutar por aquilo que acredita, e se nos seus aplicativos você emprega valores como usabilidade e velocidade, nós adoraríamos lhe conhecer.

## Aqui você irá

- Garantir o envio de software com qualidade, através de integração contínua, automação de testes e profundos code-reviews.
- Construir plataformas sustentáveis e estáveis para novas ideias de produto.
- Trabalhar com time multidisciplinar.
- Encontrar soluções simples e elegantes para problemas difíceis.

## Requisitos

Obrigatórios
- Graduação na área de computação ou experiência prática equivalente.
- Experiência com GIT.
- Capacidade de priorizar tarefas efetivamente.
- Experiência com as melhores práticas de engenharia de software (testes, code-review, continuous integration …).
- Conhecimento e vivência com RESTful
- Vários anos de experiência em Objective-C e desenvolvimento iOS.
- Conhecimentos avançados nos frameworks Cocoa Touch(Foundation, UIKIT, MapKit).
- Familiaridade com o processo de distribuição da App Store.

Diferenciais
- Experiência com MVVM
- Experiência com Reactive Cocoa
- Experiência Viper

## Contratação

CLT

## Local

Escritório São Paulo - Vila Olímpia

## O que os devs amam na 99? \o/

- os patinetes
- café
- bolo na sexta
- cerveja na sexta
- game night na quinta
- bermuda e chinelo
- badminton
- basquete
- violão

## Como se candidatar

http://goo.gl/forms/d9i7tK399E

**Comment by barbosa** [comment]
Olá @rafaortiz, tudo bem?

A vaga ainda está aberta? Só para saber se fechamos a issue ou mantemos aberta.

Obrigado!

**Comment by rafaortiz** [comment]
Opa @barbosa, tudo bom.

A vaga ainda está aberta sim, se puder mantenha a issue aberta por favor.

Quando for fechada aviso por aqui.

Abs!

**Comment by barbosa** [comment]
@rafaortiz sem problemas!

**Comment by Viniciuscarvalho** [comment]
@rafaortiz a vaga já foi preenchida? Se sim, poderia fechar a issue? 👍

**Comment by rafaortiz** [comment]
Cara não foi preenchida não, se quiser pode mandar um e-mail para
philipe.steiff@99taxis.com que ele te dá uma atenção melhor ;)

Abs!

2016-07-12 20:08 GMT-03:00 Vinicius Carvalho Marques <
notifications@github.com>:

**Comment by Viniciuscarvalho** [comment]
Beleza @rafaortiz, estava dando uma geral nas vagas para fechar as issues, mas bom saber :)
