### ISSUE TITLE
[SP - Itaim] Multinacional Bens de Consumo - Desenvolvedor Mobile Jr

### ISSUE THREAD

**Issue by FelipereisFollow** [CocoaHeadsBrasil/vagas#90]
[SP - Itaim] Multinacional Bens de Consumo - Desenvolvedor Mobile Jr

 Venture de uma grande multinacional de bebidas, focados em desenvolvimento de eCommerce, novas tecnologias e inovação. 

Desenvolvedor Mobile

Buscamos também:
Desenvolvedor back end
Desenvolvedor front end
Desenvolvedor fullstack

Júnior (recém formado)

CLT - Presencial
Bônus salarial agressivo

CVs ou dúvidas:

felipe.reis@followrecruitment.com

**Comment by reprotector** [comment]
Olá @FelipereisFollow, todas as vagas devem conter o nome da empresa que está contratando. Pode modificar a vaga, por favor?

**Comment by rafaelnicolett** [comment]
Vaga somente para júnior?

**Comment by FelipereisFollow** [comment]
Olá @rafaelnicolett com exceção de Dev Fullstack, as demais são nível Jr

@reprotector infelizmente nosso cliente não permite divulgarmos seu nome publicamente, em um bate-papo com os interessados poderemos abrir detalhes. Por gentileza, me informe se podemos manter o anúncio dessa forma ou removê-lo

**Comment by DougFischer** [comment]
@FelipereisFollow Nossos termos de uso desse espaço, que você deveria ter lido, não permitem recrutadores* e vagas sem o nome da empresa. Sua vaga será removida.

* Consideramos recrutador qualquer pessoa que estiver em busca de um candidato para outra empresa que não a sua própria.
