### ISSUE TITLE
[São Paulo/SP - Zona Sul] - DogHero - Desenvolvedor IOS Senior 

### ISSUE THREAD

**Issue by gabimollo** [CocoaHeadsBrasil/vagas#91]
**_Recruto para Startup com produto fantástico e extremamente inovador: acabaram de ser selecionados pelo Google para programa global de aceleração._**

**Responsibilities**
Develop and maintain our native mobile apps (IOS)
Consume RESTful APIs to implement new functionalities that enhance the quality of our product
Bring pixel perfect UI/UX into life

**Requirements**
Senior experience coding in relevant startups and/or personal projects
Relevant Startup experience
Advanced knowledge of IOS 

**Local de trabalho:**
Vila Mariana

**Contratação:**
CLT Full

**Benefícios:**
Salário competitivo
Oportunidade de ganhar Stock Options
Assistência médica
Gym Pass
Bonus para upgrade deconfiguração de notebook
Cozinha com chefe de cozinha
Ambiente fun

Interessados enviar cv para gaby_mollo@hotmail.com

**Comment by DougFischer** [comment]
@gabimollo Uma das regras desse espaço é que todas as vagas devem conter o nome da empresa. Você pode atualizar a descrição com essa informação?

**Comment by reprotector** [comment]
@gabimollo A vaga ainda está aberta ou podemos fechar a issue?

**Comment by gabimollo** [comment]
@reprotector A gt ainda nao fechou, mas como nao rolou sucesso nas aplicações, pode fechar  a issue.
Tks =)
