### ISSUE TITLE
[ VAGA REMOTO ] Cliente Revelo - Front-End Sênior 

### ISSUE THREAD

**Issue by CapassoLevinia** [CocoaHeadsBrasil/vagas#919]
Empresas Target: Work&Co - start-up em tecnologia, média empresa + 500 colaboradores 

Descrição da vaga
Posição PJ
Buscando profissionais que tenham aptidões em qualquer uma das stacks: React Native, Angular, Node.js e Javascript
De preferência mais de uma das linguagens
Experiência consolidada como front end.

- Dominar boas práticas de código limpo e atingir a maestria em arquitetura de software.
- Surfar com facilidade nas tecnologias web, mas está sempre buscando novas abordagens, principalmente sabendo que as dispositivos móveis estão em ascensão.
- Experiência prévia em consultoria de Design System & Ops e sabe lidar bem com as demandas dos clientes.

Principais Funções:
Acompanhar o desenvolvimento e entrega de projetos de consultoria em Design System & Ops para grandes clientes. Presença nas rotinas diárias com o cliente, negociação das melhores estratégias de tecnologia visando melhorar os processos de design.
## Posição

Posição Sênior 

## Tipo de contratação
Remoto | PJ 

## Benefícios
Férias Remuneradas, 13º, Sociedade na entrada, Período sabático remunerado após 3 anos de empresa.

Envio de resposta por e-mail: lilactechrh@gmail.com ou Linkedin linkedin.com/in/levinia-capasso-gente

**Comment by diogot** [comment]
> Esse repositório é específico para a postagem de vagas de iOS e MacOS
