### ISSUE TITLE
[SP - V. Mariana] - Confidencial - Desenvolvedor iOS (Pleno e Senior)

### ISSUE THREAD

**Issue by thiagonetorh** [CocoaHeadsBrasil/vagas#92]

**Comment by unnamedd** [comment]
@thiagonetorh leia as regras no README do [repositório](https://github.com/CocoaHeadsBrasil/vagas), é necessário que você informe o local, nome da empresa e posição no título da issue.

**Comment by thiagonetorh** [comment]
Prontinho
