### ISSUE TITLE
[ Campinas, SP ] Cliente Revelo - Software Developer Android (Pleno) e (Sênior)

### ISSUE THREAD

**Issue by CapassoLevinia** [CocoaHeadsBrasil/vagas#920]
## Empresa
Especialistas em solucionar problemas.
Com mais de 16 anos de história e um portfólio que ultrapassa 1000 projetos, somos um dos maiores institutos de ciência e tecnologia do Brasil.
## Descrição da vaga
- Experiência em desenvolvimento de software;
- Experiência em desenvolvimento Android;
- Experiência com linguagem Java.
IDIOMA: Inglês avançado (obrigatório)

## Posição
Pleno

## Tipo de contratação
 Presencial, CLT

###### Diferenciais
DIFERENCIAL:
- Conhecimentos em C#, C/C++, /C#
## Benefícios
Horário Flexível
Plano Médico e Odontológico
VA e/ou VR
Fretado e/ou Estacionamento Gratuito
Quick Massage
Gympass para desconto em academias

## Como aplicar
Envio de resposta e-mail: lilactechrh@gmail.com ou Linkedin https://www.linkedin.com/in/levinia-capasso-gente

**Comment by diogot** [comment]
> Esse repositório é específico para a postagem de vagas de iOS e MacOS
