### ISSUE TITLE
[ São Paulo, SP] Cliente Revelo -  Dev Back-end Sênior (C#, .NET)

### ISSUE THREAD

**Issue by CapassoLevinia** [CocoaHeadsBrasil/vagas#921]
## Empresa
Empresa de Software/Implementação, multinacional com sede na Suécia.
A vaga atenderá toda América Latina, em empresas do segmento de Telecom e Utilities (provedores de energia).

## Descrição da vaga
Requisitos obrigatórios (não serão aprovados candidatos com requisitos faltantes):
Inglês Intermediário (entendimento de leitura);
Espanhol Avançado (boa conversação, pois atenderá diversos clientes com esse idioma);
Experiência profunda com desenvolvimento C# e .NET;
Experiência com bancos de dados relacionais (ideal que seja Oracle);
Formação superior completa;
Experiência com soluções/estratégias.

## Posição
Sênior

## Tipo de contratação
 Presencial, CLT

###### Diferenciais
DIFERENCIAL:
Conhecimento em Soluções GIS para empresas de energia e telecom.
## Benefícios
Modelo Híbrido (2 a 3x por semana home office)
Contratação CLT - Remuneração + Plano de saúde + VR

## Como aplicar
Envio de resposta e-mail: lilactechrh@gmail.com ou Linkedin https://www.linkedin.com/in/levinia-capasso-gente

**Comment by diogot** [comment]
> Esse repositório é específico para a postagem de vagas de iOS e MacOS
