### ISSUE TITLE
[ São Paulo, com possibilidade remoto ] Cliente Revelo -  Head Mobile

### ISSUE THREAD

**Issue by CapassoLevinia** [CocoaHeadsBrasil/vagas#922]
## Empresa
 Empresa no segmento da música. Plataforma de música brasileira, com artistas independentes, tendo como principal funcionalidade: streamings e downloads.

## Descrição da vaga
Requisitos obrigatórios (não serão considerados candidatos com falta de qualquer requisito desse campo):
Experiência com gestão de pessoas (apenas liderança técnica não é considerável);
Conhecimento com Flutter;
Experiência em desenvolvimento mobile nativo (Android e iOS);
Experiência em versionamento usando Git;
Profundo conhecimento com metodologias ágeis.
## Posição
 Sênior

## Tipo de contratação
Contratação CLT 

## Benefícios
Benefícios: Plano de Saúde, VT, VR E Auxílio em cursos e eventos.

## Como aplicar
Envio de reposta por e-mail: lilactechrh@gmail.com ou Linkedin linkedin.com/in/levinia-capasso-gente

**Comment by diogot** [comment]
> [Se você é um recrutador, você deve identificar o nome da empresa em que o candidato irá trabalhar](https://github.com/CocoaHeadsBrasil/vagas#todas-as-vagas-devem-conter-o-nome-da-empresa-que-está-contratando)

**Comment by CapassoLevinia** [comment]
Olá desculpe-me não me apresentei. Meu nome é Levinia Capasso, sou Tech Recruiter, parceiro da Startup Revelo. 

São mais de 03 mil clientes, infelizmente eles não mencionam o nome na vaga.

**Comment by diogot** [comment]
Entendo, mas as vagas que não atendem ao requisitos não devem ser postadas aqui.

**Comment by CapassoLevinia** [comment]
Esta certo, obrigada!
