### ISSUE TITLE
[São Paulo/SP - Zona Sul] - DogHero - IOS Engineer

### ISSUE THREAD

**Issue by gabimollo** [CocoaHeadsBrasil/vagas#95]
**A DogHero está crescendo bastante e buscando os melhores profissionais do mercado. Com produto fantástico e extremamente inovado, acabamos de ser selecionados pelo Google para programa global de aceleração. Além de já termos investimento de 2 das maiores investidoras: Kaszek e Monashees+.**

**Responsabilidades**
Develop and maintain our native mobile apps (IOS)
Consume RESTful APIs to implement new functionalities that enhance the quality of our product
Bring pixel perfect UI/UX into life

**Requisitos**
Senior experience coding in relevant startups and/or personal projects
Relevant Startup experience
Advanced knowledge of IOS

**Local de trabalho**
Vila Mariana

**Contratação**
CLT Full

**Benefícios**
Salário competitivo
Oportunidade de ganhar Stock Options
Assistência médica
Gym Pass
Bonus para upgrade deconfiguração de notebook
Cozinha com chefe de cozinha
Ambiente fun

Interessados enviar cv para gaby_mollo@hotmail.com

**Comment by marcelofabri** [comment]
Fechando por ser duplicada da #91. Por favor, poste apenas uma vez a vaga.
