### ISSUE TITLE
[PR - Curitiba] EBANX - Senior Mobile Developer (iOS and/or Android)

### ISSUE THREAD

**Issue by cocuroci** [CocoaHeadsBrasil/vagas#96]
## Empresa
O EBANX é um grupo financeiro global com atitude do Vale do Silício. A gente acredita que todas as pessoas devem ter poder de escolher e de chegar mais longe. Por isso, colocamos meios de pagamento locais e seguros (boleto bancário, transferências, cartões de crédito nacionais) nos principais sites do mundo. Somos líderes no Brasil e estamos conquistando a América Latina. Tudo para que as pessoas tenham acesso ao que desejam sem burocracia, sem preocupação e sem sair de casa.

Já alcançamos mais de 16.000.000 de consumidores e só em 2015 processamos mais de 1 bilhão de reais. Empresas como AirBnB, Spotify, AliExpress, PlayStation já trabalham com a gente.

**Queremos alguém que queira impactar a vida dos nossos 1+ milhões de usuários brasileiros e latino-americanos que tem conta com a gente.**

## Descrição da vaga
**Buscamos um Desenvolvedor Mobile Sênior para fazer parte do nosso Squad de End User. Estamos criando um produto novo cuja peça central é um app novo, escrito do zero.**

O EBANX trabalha com Squads, isto é, equipes pequenas (8-14 pessoas) horizontais disciplinares em que devs, designers, pessoas de produto, negócio e marketing trabalham juntos para criar produtos incríveis.

## Posição
Senior Mobile Developer (iOS and/or Android)

## Tipo de contratação
Presencial - CLT

## Requisitos

- Desenvolver aplicativos em iOS e Android (e/ou: você não precisa saber ambos).
-- Para iOS: utilizamos Swift (Alamofire, Unbox, SwiftyJSON, etc.)
-- Para Android: utilizamos Kotlin (Retrofit 2, RxKotlin, etc.)
- Tomar posse de projetos e fazer as coisas acontecerem. Queremos criar um aplicativo novo, do zero e manter um ciclo de releases rápido, dinâmicos e sempre cheio de novidades.
- Você precisar comunicar-se tão bem (no mínimo) quanto você desenvolve. Desenvolver um app no EBANX envolve outros desenvolvedores, web designers, pessoas de UX, product manager, etc. Manter todos na mesma página e todas dependências resolvidas é essencial para o sucesso e para manter o ciclo ágil.
- Escrever e testar códigos de modo eficiente, ágil e bem-documentado.
- Participar ativamente do levantamento de requisitos e brainstorms para novas funcionalidades dos nossos aplicativos.
- Você vai mais que desenvolver. Um aplicativo é mais que código e ele nunca tem um fim :)

Para saber mais: [https://blog.ebanx.com/behind-the-scenes/conheca-area-de-tecnologia-e-desenvolvimento-do-ebanx](https://blog.ebanx.com/behind-the-scenes/conheca-area-de-tecnologia-e-desenvolvimento-do-ebanx)

###### Obrigatórios

- Conhecimento em um stack (iOS ou Android), utilizando linguagens de programação como Swift, Java, ObjectiveC, etc;
- Habilidade para escolher a ferramenta correta para o projeto e fazer o mesmo acontecer;
- Integrar com APIs RESTful de olhos fechados;
- Conhecimento em bancos de dados relacionais e não relacionais;
- Saber utilizar bem conceitos do Git(Hub) como branching, pull-requests, etc;
- Inglês intermediário (lê e escreve bem, fala razoável).

###### Diferenciais

- Poliglota de stack: iOS e Android.
- Inglês avançado (conversação). Ele é o idioma oficial do EBANX.
- Um bom espanhol. Estamos expandindo rápido por toda América Latina.

###### Tecnologias de Dev e Ops que usamos (calma, você não precisa saber tudo)

- PHP (in-house MVC, Laravel);
- Ruby (Ruby On Rails);
- Java Spring e Android;
- iOS (Swift);
- MySQL, PostgreSQL, Redis, RabbitMQ, Memcached (outros em breve);
- Testes (Codeception, RSpec);
- Git;
- Travis CI;
- New Relic;
- JIRA.
- AWS (OpsWorks, EC2, ELB, SQS, S3, RedShift, RDS, ElastiCache, SES, CloudWatch, etc.);
- Vagrant e Docker para ambiente de desenvolvimento;
- Entre várias outras coisas. Temos uma equipe de Ops dedicada 24x7.

## Benefícios

- Aulas de Inglês e Espanhol dentro do EBANX.
- Bolsa para cursos e atualização de até R$ 300 / mês.
- Horário Semi-Flexível (8 horas de segunda à sexta).
- Ambiente informal e descontraído - Frutas e snack saudáveis, chuveiros no escritório, uma Pug que adora carinho, patinete, nerf, drones, Nespressos e festas.
- Programa de Remuneração Variável.
- Contrato CLT, Vale Refeição, Plano de Saúde e Odontológico.

Para saber um pouco mais veja a nossa [Career Page](http://www.ebanx.com/br/carreiras) e procure as fotos tiradas pelos ebankers no nosso [Instagram](https://www.instagram.com/ebanxlife/).

## Como aplicar
No link [https://ebanx.recruiterbox.com/jobs/fk0mwhq/](https://ebanx.recruiterbox.com/jobs/fk0mwhq/)

**Comment by reprotector** [comment]
@cocuroci A vaga ainda está aberta ou posso fechar a issue?
