### ISSUE TITLE
[PR - Curitiba] EBANX - Tech Lead Mobile (iOS and Android)

### ISSUE THREAD

**Issue by cocuroci** [CocoaHeadsBrasil/vagas#97]
## Empresa
O EBANX é um grupo financeiro global com atitude do Vale do Silício. A gente acredita que todas as pessoas devem ter poder de escolher e de chegar mais longe. Por isso, colocamos meios de pagamento locais e seguros (boleto bancário, transferências, cartões de crédito nacionais) nos principais sites do mundo. Somos líderes no Brasil e estamos conquistando a América Latina. Tudo para que as pessoas tenham acesso ao que desejam sem burocracia, sem preocupação e sem sair de casa.

Já alcançamos mais de 16.000.000 de consumidores e só em 2015 processamos mais de 1 bilhão de reais. Empresas como AirBnB, Spotify, AliExpress, PlayStation já trabalham com a gente.

**Queremos alguém que queira impactar a vida dos nossos 1+ milhões de usuários brasileiros e latino-americanos que tem conta com a gente.**

## Descrição da vaga
**Buscamos um Líder Técnico Mobile experiente, hands-on para liderar o desenvolvimento de um produto novo cuja peça central é um app, escrito do zero.**

O EBANX trabalha com Squads, isto é, equipes pequenas (8-14 pessoas) horizontais multi-discliplinares em que devs, designers, pessoas de produto, negócio e marketing trabalham juntos para criar produtos incríveis.

O líder técnico trabalhará como o mentor em todo o processo de desenvolvimento mobile e também como um desenvolvedor sênior, colocando a mão na massa e fazendo acontecer.

## Posição
Tech Lead Mobile (iOS and Android)

## Tipo de contratação
Presencial - CLT

## Requisitos

Trabalhar em um ambiente diversificado e dinâmico que desenvolve aplicativos em iOS e Android.

- iOS: utilizamos Swift (Alamofire, Unbox, SwiftyJSON, etc...)
- Android: utilizamos Kotlin (Retrofit 2, RxKotlin, etc

Ser dono do backlog de atividades e do processo de desenvolvimento priorizando com o gerente de produto e com a equipe nas sprints.

Tomar posse de projetos e fazer as coisas acontecerem. Queremos um ciclo de releases rápido, dinâmicos e sempre cheio de novidades.

Escrever e testar códigos de modo eficiente, ágil e bem-documentado.

###### Obrigatórios

- Conhecimento em uma ou mais linguagens de programação como Swift, Java, ObjectiveC, etc;
- Habilidade para escolher a ferramenta correta para o projeto e fazer o mesmo acontecer;
- Integrar com APIs RESTful de olhos fechados;
- Conhecimento em bancos de dados relacionais e não relacionais;
- Saber utilizar bem conceitos do Git(Hub) como branching, pull-requests, etc;

###### Diferenciais

- Experiência em desenvolvimento web full stack e APIs além de mobile.
- Inglês avançado (conversação). Ele é o idioma oficial do EBANX.
- Um bom espanhol. Estamos expandindo rápido por toda América Latina e iremos levar o aplicativo para esses mercados também.

## Benefícios

- Aulas de Inglês e Espanhol dentro do EBANX.
- Bolsa para cursos e atualização de até R$ 300 / mês.
- Horário Semi-Flexível (8 horas de segunda à sexta).
- Ambiente informal e descontraído - Frutas e snack saudáveis, chuveiros no escritório, uma Pug que adora carinho, patinete, nerf, drones, Nespressos e festas.
- Programa de Remuneração Variável.
- Contrato CLT, Vale Refeição, Plano de Saúde e Odontológico.

Para saber um pouco mais veja a nossa [Career Page](http://www.ebanx.com/br/carreiras) e procure as fotos tiradas pelos ebankers no nosso [Instagram](https://www.instagram.com/ebanxlife/).

## Como aplicar
No link [https://ebanx.recruiterbox.com/jobs/fk0mwyo/](https://ebanx.recruiterbox.com/jobs/fk0mwyo/)

**Comment by reprotector** [comment]
@cocuroci A vaga ainda está aberta ou posso fechar a issue?
