### ISSUE TITLE
[100% REMOTO] Desenvolvedor iOS @ Instituição Financeira

### ISSUE THREAD

**Issue by lucasherodoto** [CocoaHeadsBrasil/vagas#977]
## Empresa
Instituição financeira atuante nas áreas de cartões de crédito

## Descrição da vaga

Requisitos:

• Familiaridade com RestFul APIs para conectar as aplicações IOS com os serviços de back-end;
• Conhecimento dos conceitos SOLID e arquitetura Clean Swift;
• Conhecimento de boas práticas no desenvolvimento de aplicações para iOS;
• Teste unitário;
• Familiaridade com APIs de messageria em cloud;
• Push notifications, crashlytics e ferramentas de Analytics; (plus)
• Familiaridade com integração contínua;
• Habilidade para fazer benchmarking e otimização de aplicações;
• Arquitetura Clean;
• Generics;
• Componentização
• Programação Funcional;
• Injeção de dependências;
• Build configurations;
• Retain Cycle;
• Manejo de Threads;
• ViewCode e Xib;
• CocoaPods;
• GitFlow;

Diferencial:
• iOS com Swift 5
• Design pattern de Coordinator e como transformá-lo em Clean; Cuckoo;
• Nimble;
• Habilidade para trabalhar com libs externas;
• Conhecimento de frameworks de segurança;
• Familiaridade com soluções de criptografia;

## Posição
Sênior 

## Tipo de contratação

Vaga remota em Regime PJ (salário equiparado ao mercado)

## Como aplicar

Envie um email para lucas.martins@cq1.com.br com seu CV anexado e pretensão salarial.
Enviar no Assunto: Desenvolvedor iOS

**Comment by unnamedd** [comment]
Por favor, informe a empresa.

Quando a issue for alterada, só reabrir. Até lá, ela está fechada.
