### ISSUE TITLE
[REMOTO] Desenvolvedor iOS @ Empresa de Meios de Pagamentos Eletrônicos

### ISSUE THREAD

**Issue by lucasherodoto** [CocoaHeadsBrasil/vagas#978]
## Empresa

Empresa atuante no setor de serviços financeiros, sobretudo como adquirente multi-bandeira

## Requisitos

Experiência com aplicativos em IOS nativo (ObjectiveC)
Trabalhar com diferentes dimensões de dispositivos (Tablet, celular e afins);
Experiência com GIT;
Trabalhar realizando testes, code review e integração contínua
Superior completo em Ciências da Computação, Engenharia, Sistemas da Informação ou áreas afins;

Principais atividades: #BDD e TDD;
Promover um code review constante;
Lidar com times são multidisciplinares (PO, UX, UI e Desenvolvedores);

## Posição

Pleno

## Tipo de contratação
PJ 

## Como aplicar

Caso possua interesse, enviar um e-mail para lucas.martins@cq1.com.br com seu CV anexado e pretensão salarial.
Enviar no assunto: Vaga Desenvolvedor iOS

**Comment by unnamedd** [comment]
Por favor, informe a empresa.

Quando a issue for alterada, só reabrir. Até lá, ela está fechada.
