### ISSUE TITLE
[Remoto] - InEvent - iOS Hero

### ISSUE THREAD

**Issue by arturgaleno** [CocoaHeadsBrasil/vagas#99]
## Empresa
 A InEvent é uma startup B2B que desenvolve um aplicativo inteligente para organizadores de eventos possibilitarem interação, negócios e networking dentro deles, facilitando toda a troca de informações entre os principais stakeholders. Nós ajudamos a construir grandes histórias dentro dos eventos através de um SaaS web e mobile.

## Descrição da vaga

A InEvent está a procura de um(a) profissional com abições de crescer junto com uma equipe de jovens empreendedores em uma startup no mercado de eventos. Se você acha que é capaz de inovar na forma como desenvolvemos e criamos nossas plataformas, introduzir novos conceitos e formas de nossos sistemas mais robustos e poderosos, você está no lugar certo. Venha conosco fazer parte da construção desta empresa consciente que vai mudar o mercado de eventos no Brasil e mundo à fora!

## Posição

Buscamos profissionais com vontade de aprender, que gostam de acompanhar inovações e novas formas de resolver problemas. Dentro da InEvent, você poderá:

- Aprender modelos de desenvolvimento usados nas nossas plataformas;

- Inovar e reestruturar parte dos nossos sistemas (estrutura + design);
 
- Aprender sobre automatização de processos para a produção e entrega de aplicativos em larga escala.
 
- Trabalhar com uma equipe capacitada e pronta para aprender e ensinar todo tipo de experiência e conhecimento;
 
- Otimizar a performance do aplicativo mobile para diferentes versões do iOS.
 
- Implementar as funcionalidades recém-lançadas pela Apple em versões mais novas do aplicativo, conforme liberado em betas na WWDC.
 
- Ter flexibilidade de horário e de local de trabalho!
 
- Participar de eventos de empreendedorismo e tecnologia.

## Tipo de contratação
Júnior - Remoto - PJ

###### Obrigatórios

- Capacidade de aprendizado rápido e percepção na resolução de problemas;

- Conhecimento e experiência em desenvolvimento com Objective-C e/ou Swift.

###### Desejáveis

- Conhecer os truques e manias da suíte de desenvolvimento Xcode.

- Ter prática utilizando ferramentas como Cocoapods e repositórios opensorces mantidos pela InEvent (https://github.com/ineventapp).

- Estar preparado para trabalhar em um ambiente remoto e confortável com um ambiente UNIX e plataformas de versionamento de código (GIT).

- Criatividade e curiosidade para aprender e aplicar novos conceitos em nossas plataformas;

- Gostar de hackathons, ter o espírito de um hacker - quando requisitado, resolver o problema com paixão e vontade;

- Colaborar ativamente com a geração de valor da InEvent, tendo coragem para ser desafiado e disposição para propor melhorias necessárias.

## Benefícios

**Carga horária:** de 20 horas semanais com a possibilidade de tornar-se Full Time. Horários flexíveis (o que importa são os resultados).

**Benefícios:** Benefícios: Salário (a partir de R$ 2.200,00) + bônus por metas.

## Como aplicar
Basta enviar seus dados usando o formulário abaixo. Este é um processo seletivo contínuo, com data de término indeterminada.

https://ineventapp.recruiterbox.com/jobs/fk0hn76/

**Início:** Fevereiro de 2017.

## Contato
Informe aqui os contatos para mais informações

**Comment by raphaelpitang** [comment]
"Este é um processo seletivo contínuo"
Poderiam explicar isso?

**Comment by raphaelpitang** [comment]
Essa remuneração é negociável para remoto?

**Comment by atsneves** [comment]
Link inválido.

**Comment by miguelarauj1o** [comment]
@arturgaleno, olá tenho interesse.
linkedin: https://br.linkedin.com/in/miguelarauj1o
github: https://github.com/miguelarauj1o

Ademais, como @atsneves informou, o link para o formulário está inválido.
Abraços!

**Comment by mbrufatto** [comment]
Tenho interesse.
Como mando currículo?

**Comment by joelbanzatto** [comment]
Eu tenho interesse: joel.banzatto@gmail.com

Consertem o formulário, por favor...

**Comment by kweles** [comment]
Olá Tenho interesse!
Segue meu linkedin: https://br.linkedin.com/in/weles-saggiorato-siqueira-a7005757
Como faço para enviar currículo?
Obrigado!

**Comment by rogerluan** [comment]
Olá, tenho interesse na vaga. Resume: roger.ml/resume

Obrigado

**Comment by Viniciato** [comment]
Ola, tenho interesse!!
email: vininadin@gmail.com
Obrigado!

**Comment by arturgaleno** [comment]
Pessoal, a vaga foi encerrada. Muito obrigado a todos!
